facebook/create-react-app

packages/create-react-app/createReactApp.js

Closes #3573 
Added a minor change to allow `.tar.gz` extension for the `--scripts-version` CLI.
I didn't enable the `.tar` extension, It's supported by the package([tar-pack](https://github.com/ForbesLindesay/tar-pack)) but it seems not to be supported by Yarn.
Thanks!

Extend --scripts-version to include .tar.gz format

---

CONTRIBUTING.md

This PR is in follow up to the discussion in issue #2828 
This introduces a new section in contributing.md for developers using windows machine to help them contribute to this project without relying on workarounds. 
**Tests**: 
Below are the screenshot that shows that the steps followed enable devs to use the scripts in the repo as is: 
_Running Prettier_
This shows that windows bash is able to understand unix based paths and patterns without any changes.
_Running .sh scripts in tasks folder_
This shows that windows bash is able to run the scripts out of the box.

Documentation to help windows contributors

---

packages/react-dev-utils/printHostingInstructions.js

There are no functional or text changes with this PR. I'm just cleaning up the logic for printHostingInstructions to make it more readable and remove some duplication. The only minor logic change is that I replaced a couple hard-coded literals (`'build'`) with variables (`buildFolder`).
The main `printHostingInstructions` method is now purely logic. It calls three other functions `printBaseMessage`, `printDeployInstructions`, and `printStaticServerInstructions`; which contain the console statements with minimal logic.

Cleaning up printHostingInstructions a bit

---

README.md

Just a little README change to note Neutrino supports react components as well. 😺

Update README.md to note Neutrino's support of react components

---

packages/eslint-config-react-app/index.js
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

As this (https://github.com/facebookincubator/create-react-app/issues/2176) issue has been closed, seems like this code was meant to be brought back.

Redisable require.ensure()

---

packages/react-dev-utils/WebpackDevServerUtils.js

I created a new app and verified that all the requests that do not have `GET` method get proxied.
Fixes #3311

Use proxy for all request methods other than GET

---

packages/react-scripts/template/README.md

Tricky issue, if you not aware on how service-workers work. Related to #2440

docs: add info about service-worker and HTTP caching headers into Firebase section

---

tasks/e2e-simple.sh

Just so we don't accidentally introduce them again with an old PR.
Based on a similar check in React repo.

Lint against files with old license

---

tasks/e2e-installs.sh
tasks/e2e-kitchensink.sh
tasks/e2e-simple.sh

Use latest npm in e2e tests

---

.travis.yml
tasks/e2e-installs.sh
tasks/e2e-kitchensink.sh
tasks/e2e-simple.sh
tasks/local-test.sh

Our E2E tests are in a very messy state right now. Due to a pile of hacks that accumulated over months, it's very hard to understand what's happening to the packages.
I want to simplify this. As a first step I want to get rid of this variable.
It looks like it's not actually being used. (The branch is always false.) And since Yarn now ships with CI images, we actually *do* use Yarn on CI already.
With this change, we're just eliminating already dead code. Next, I'll try to simplify the actual CI script, but for now I just want the code to reflect what it actually does because it wasn't obvious.

Always use Yarn on CI

---

tasks/e2e-installs.sh
tasks/e2e-kitchensink.sh
tasks/e2e-simple.sh

Don't know if this will work but worth a try. Maybe some of these hacks can go with recent Yarn versions?

Try to use Yarn in more E2E scripts

---

.travis.yml
tasks/e2e-old-node.sh
tasks/e2e-simple.sh

It does a completely separate thing. Doesn't make sense to me to keep it with the rest.

Separate old Node E2E test

---

packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/package.json

as quoted by the readme https://github.com/webpack-contrib/uglifyjs-webpack-plugin:
>webpack =< v3.0.0 currently contains v0.4.6 of this plugin under webpack.optimize.UglifyJsPlugin as an alias. For usage of the latest version (v1.0.0), please follow the instructions below. Aliasing v1.0.0 as webpack.optimize.UglifyJsPlugin is scheduled for webpack v4.0.0
The v1 is released on [October](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v1.0.0), so I think it's mature enough to switch to v1 in CRA? or do we want to wait for webpack 4?
This allows us to use uglify-es and access to parallel and cache options. Hence improving our build speed.
I haven't test it yet, but maybe this will break our parsing of uglify error …

use uglifyjs-webpack-plugin v1

---

packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/package.json

Since this now uses `uglify-es` under the hood, we want to restrict language support to ES5.
This is in line with the **current behavior**.
Given we've recently merged browserlist support, we should probably set this option based on specific browsers (in a follow up PR).

Specify JavaScript version for Uglify

---

tasks/e2e-simple.sh

This removes a lot of the painful trickery we do via setting up a local registry and actually **publishes** the modules.
We can now test as if we're an end-user. This means our tests actually mean something now. 😄
`verdaccio` is used to spin up a lightweight local registry. It allows you to publish packages and uses npm as its fallback.
`verdaccio` supports an anonymous publishing mode, but I'd rather not ship a config file with this.
Since we use `verdaccio`'s defaults, you must login to publish a package.
Due to long standing [npm crap](https://github.com/npm/npm/issues/7042), we have to use `npm-cli-login` to login (over standard `npm adduser`).
Packages are released using our `release.sh` script.
The `create_react_app` function, our `install_package` npm link workaround, and `npm …

Use private registry

---

tasks/e2e-installs.sh
tasks/e2e-kitchensink.sh

This PR removes `install_package` and emulates true end-user use via publishing for the installs and kitchensink tests.
Follow up to #3744.

Follow-up: use private registry

---

tasks/e2e-installs.sh
tasks/e2e-kitchensink.sh
tasks/e2e-simple.sh

This removes some workarounds which really aren't needed anymore. Should speed up tests a bit. 😄

Remove redundant steps in e2e tests

---

packages/create-react-app/createReactApp.js

These fairly common project config files shouldn't ever conflict with create-react-app generated files.
**.npmignore**: [Files that should not be published by npm](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)
**mkdocs.yml**: [Project config for MkDocs utility](http://www.mkdocs.org/user-guide/configuration/)
**docs**: [Default docs dir for MkDocs](http://www.mkdocs.org/user-guide/configuration/#docs_dir)
**.travis.yml**: [Project config for Travis CI](https://docs.travis-ci.com/user/customizing-the-build/)
**.gitlab-ci.yml**: [Project config for GitLab CI](https://docs.gitlab.com/ce/ci/yaml/README.html)
**.gitattributes**: [Path specific git attribute config](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes)

Adding some more non-conflicting config files to validFiles

---

tasks/e2e-installs.sh
tasks/e2e-kitchensink.sh
tasks/e2e-simple.sh

tried running `yarn e2e` locally and it messes up my registry config 😅  need to do something about `npm install npm@latest` though, maybe use nvm?

[e2e] clean up changes to npm and yarn registry

---

.yarnrc

Adds ~2-3 seconds to install time, but can save some headaches.
Pretty important when multiple users start fiddling with package.json files and we start using more advanced package manager settings.
Also will help recover your tree after you use `npm` by accident without wiping out all `node_modules`.

Enable Yarn check files

---

packages/babel-preset-react-app/index.js
packages/react-scripts/scripts/init.js
tasks/e2e-kitchensink.sh

This removes the `ie 9` target and `forceAllTransforms` since we're dropping IE9 support by default.
We want to allow target browsers to be configurable via the `browserslist` key in `package.json`.
This also enables `useBuiltIns` for smaller bundles.
I've also adjusted the defaults we generate for a more ergonomic development experience.
----
There's still no story for users upgrading from * -> 2.x (it'd use browserlist defaults currently).

Loosen Babel preset to use browserslist

---

packages/babel-preset-react-app/dependencies.js
packages/babel-preset-react-app/package.json
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

Proof of concept for https://github.com/facebookincubator/create-react-app/issues/1125.
This currently runs *all* `node_modules` through `babel-preset-env`.
(Which was unsafe in Babel 6, but should—maybe—be safe in Babel 7.)
I don't know the impact on the build time. It'll definitely make the cold start slower but hopefully repeated builds will be okay. We need some measurements with larger projects here: https://mobile.twitter.com/dan_abramov/status/952248179478745089.
I intentionally only did this for webpack. I don’t think we need to do this for tests because you control the Node version on which you run the tests, unlike the user’s browser. And it’s never required to compile because we intentionally don’t allow any custom transforms (like JSX). Only “real” JS gets compiled.
TODO:

Compile dependencies with babel-preset-env

---

CODE_OF_CONDUCT.md

All FB open source projects including this one enforce [our code of conduct](https://code.facebook.com/pages/876921332402685/open-source-code-of-conduct), but I just realized we haven't explicitly linked to it from a Markdown file. So I'm doing just that.

Add an explicit link to our Code of Conduct

---

packages/react-dev-utils/package.json

This should include some error handling that would work around https://github.com/facebookincubator/create-react-app/issues/3690.
I haven't verified it works yet, but the last time I tried to do similar edits locally, and then inserted a `throw` in the same place the error was reported, `detect-port` said the ports were taken and jumped to a high port. I'm not sure why it didn't give me an error instead but this seems edge casey enough that I don't care strongly how it works as long as it doesn't crash.

Bump detect-port-alt

---

packages/babel-preset-react-app/index.js
packages/babel-preset-react-app/package.json
packages/react-scripts/fixtures/kitchensink/src/features/syntax/ObjectDestructuring.js

This works around https://github.com/facebookincubator/create-react-app/issues/3694 and hardens the integration test for it.
The underlying issue is https://github.com/babel/babel/issues/7215#issuecomment-357515580.

Always include destructuring transform

---

packages/react-dev-utils/browsersHelper.js
packages/react-dev-utils/package.json
packages/react-scripts/config/paths.js
packages/react-scripts/package.json
packages/react-scripts/scripts/build.js
packages/react-scripts/scripts/start.js

This PR warns about specifying browsers with a method other than `package.json` after build.
This PR also prevents `build`/`start` when no browsers are specified.
TODO:
Fixes #3779

Tell user what browser support their application was built with

---

packages/react-scripts/scripts/start.js

To see the new warning message run `HOST=8.8.8.8 npm run start`.
Closes #3719

Add warning when HOST environment variable is set (#3719)

---

CHANGELOG.md

* [#3387](https://github.com/facebookincubator/create-react-app/pull/3387) Add support for variable expansion in `.env` files. ([@moos](https://github.com/moos))
* `react-error-overlay`
* [#3474](https://github.com/facebookincubator/create-react-app/pull/3474) Allow the error overlay to be unregistered. ([@Timer](https://github.com/Timer))
* [#3408](https://github.com/facebookincubator/create-react-app/pull/3408) Add `--info` flag to help gather bug reports. ([@tabrindle](https://github.com/tabrindle))
* [#3409](https://github.com/facebookincubator/create-react-app/pull/3409) Add `--use-npm` flag to bypass Yarn even on systems that have it. ([@tabrindle](https://github.com/tabrindle))
* [#3725](https://github.com/facebookincubator/create-react-app/pul …

Changelog for 1.1.0

---

packages/react-scripts/scripts/test.js

Fixes https://github.com/facebookincubator/create-react-app/issues/3801.
To use, run `yarn test --watchAll` or `npm test -- --watchAll` or add `--watchAll` to the test command in your `scripts` section of `package.json`.

Support Jest --watchAll flag

---

package.json
tasks/screencast-start.js
tasks/screencast.js
tasks/screencast.sh

This is a spinoff motivated by manual work done for #3810. 
This PR automates said work completely but introduces a non-trivial ammount of additional scripting and depedencies.
* **screencast.js**: Automate screencast.sh, asciinema, svg-term-cli. Removes progress-bar, npm tree data from cast
* **screencast.sh**: Simulate user input, trigger demoed commands
* **screencast-start.js**: Start a shell command and end the process log patterns have been observed

Automate screencast recordings

---

packages/eslint-config-react-app/index.js

Build crashes whenever JSX is not returned as proposed here: #2303. 
The build crashes whenever JSX isn't returned, as opposed to just giving a warning.
Create a stateless component without a return clause.
For example:
` import React from 'react';`
`export default function Logo(){`
`    <div className="App-header">`
`        <img src="./logo.svg" className="App-logo" alt="logo" />`
`        <h2>Welcome to React</h2>`
`    </div>`
`}`

Changes no-unused-expressions lint from warning to error

---

packages/react-scripts/scripts/utils/createJestConfig.js

I wasn't aware of the fact that users of c-r-a could just define
`src/setupTests.js` and it would be configured with Jest - I nearly
ejected before I found a GitHub issue that confirmed this functionality.
I thought it might be a nice idea to add it to the error about Jest
config overrides to stop others ejecting when they don't need to.

Enhance Jest config error for `setupTestFrameworkScriptFile`

---

packages/react-scripts/template/README.md

Improved documentation in packages/react-scripts/template/README.md to clarify instructions for hosting React-app on GitHub Pages while connected to a custom domain name.

Updated react-scripts Readme.md to better document GitHub Pages

---

packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
packages/react-scripts/fixtures/kitchensink/src/App.js
packages/react-scripts/fixtures/kitchensink/src/features/webpack/CssModulesInclusion.js
packages/react-scripts/fixtures/kitchensink/src/features/webpack/CssModulesInclusion.test.js
packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/style.module.css
packages/react-scripts/package.json
packages/react-scripts/scripts/utils/createJestConfig.js
packages/react-scripts/template/README.md

This adds support for CSS Modules using the explicit file naming convention `[name].module.css`
When using css modules, class names follow a deterministic convention rather than the standard random hash with the covention `[directory]__[filename]___[classname]`.
Given `src/components/Button/Button.module.css` with a class `.primary {}`, the generated classname will be `src-components-Button__Button-module___primary`. 
This is done to allow targeting off elements via classname, causes minimal overhead with gzip-enabled, and allows a developer to find component location in the devtools.
See issue #2278 for more details.
We are currently waiting on version 2 of Create-React-App to add css module support as it is a breaking change. The current release timeframe is unknown.
You may use …

Add support for CSS Modules with explicit filename - [name].module.css

---

packages/react-dev-utils/launchEditor.js

- `powershell -Command "Get-Process | Select-Object Path"`: ~1300ms (current implementation)
- `Get-Process | Select-Object Path` on already running PowerShell daemon/agent: ~300ms (implementation in #2711)
- `wmic process where "executablepath is not null" get executablepath`: ~110ms (this implementation)
_Tested on Windows 10 with an i5-4690_
For comparison on other platforms:
- `ps x` on macOS: ~60ms

Use wmic to get process list on Windows

---

packages/babel-preset-react-app/index.js
packages/babel-preset-react-app/package.json
packages/eslint-config-react-app/index.js

Apply `babel-plugin-transform-react-remove-prop-types` when building for production.
Closes #209

Remove PropTypes from production build (#209)

---

packages/react-dev-utils/printBuildError.js
packages/react-dev-utils/printHostingInstructions.js
packages/react-scripts/scripts/start.js

I verified the old links and the new links redirect to the same endpoint.

Use custom bit.ly links

---

packages/react-scripts/template/src/index.js
packages/react-scripts/template/src/registerServiceWorker.js
packages/react-scripts/template/src/serviceWorker.js

Addresses disabling service worker by default from #2554.

Disable service worker by default

---

packages/babel-preset-react-app/README.md
packages/babel-preset-react-app/index.js

related to #3863,
now you can make `babel-preset-react-app@next` work nicely with `@babel/preset-typescript`:
```
{
"presets": [
["react-app", {
"flow": false 
}],
"@babel/typescript"
]
}
```

feat: add opt-out for prestet-flow to work with @babel/preset-typescript

---

packages/react-scripts/template/src/serviceWorker.js

This is PR version of #3375 for `next` branch.
Adding two callbacks in `serviceWorker.js` file:
- `onUpdate` - executed when service worker has been updated in the background
(console logs _New content is available; please refresh._)
- `onSuccess` - executed after service worker has been installed for the first time
(console logs _Content is cached for offline use._)
To use it inside application to show notification (toast/ icon etc) register service worker inside App.js file:
```js
// App.js
import { register as registerServiceWorker } from './serviceWorker.js'
export default class App {
constructor() {
// Register service worker and add onUpdate callback
registerServiceWorker({
onUpdate: this.handleServiceWorkerUpdate
})
}
// Simplest notification implementation example. …
```

Provide callbacks in serviceWorker (next)

---

tasks/e2e-installs.sh

https://github.com/facebookincubator/create-react-app/pull/2705 fixed project deletion logic to leave the log. So we don't expect folder to be deleted now.

Fix integration test

---

packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

This behavior was originally introduced in #1359 as we thought it would fix the `npm link` development workflow issues.
However, we have since found several problems with it:
* It doesn’t match the Node resolution mechanism (which reverted a similar change in https://github.com/nodejs/node/pull/6537 and kept it behind a flag)
* It still leads to the “duplicate React” problem (#675)
* It is inconsistent with Jest (as described in https://github.com/facebookincubator/create-react-app/issues/3883, past versions of Jest had this behavior but it led to issues like https://github.com/facebook/jest/issues/3830 and https://github.com/facebook/jest/pull/4761#issuecomment-339419335 so I fixed it in https://github.com/facebook/jest/pull/4761 to match the Node resolution mechanism)
There are also …

Don't use app node_modules folder as a resolve fallback

---

packages/react-scripts/scripts/init.js
tasks/e2e-kitchensink.sh

It needed this commit because our git integration had a race condition. I fixed it in https://github.com/facebookincubator/create-react-app/pull/3877 so now the commit ends up empty and fails. We can remove this now.

Fix the E2E script

---

README.md

Rails Webpacker is the "official" Rails way to use modern JavaScript (ES6, modules, etc.) *within* a Rails app, totally bypassing and even replacing the traditional asset pipeline. For uses of React in Rails without the intention to build a SPA, this is a very straightforward approach.

Add Rails Webpacker as alternative to CRA in Rails

---

packages/react-scripts/template/README.md

Update User Guide's README.md to include `json` and `css`
files in the command to format the entire project for the first time
with prettier, that it's consistent with the `lint-staged` command.
----
As simple as that, don't think any more explanation is needed. Does it make sense to you guys?
Feel free to edit the PR or commit message if needed.

Include `{json,css}` files in prettier command

---

CHANGELOG.md

Add ```<noscript>``` to ```<body>``` as part of migration instructions from 0.9.5 to 1.0.0 in order to provide fallback content when JavaScript is not available and improve [Lighthouse ](https://developers.google.com/web/tools/lighthouse/)score.

Update changelog to add noscript when migrating to 1.0.0

---

lerna.json
packages/babel-preset-react-app/package.json
packages/confusing-browser-globals/package.json
packages/create-react-app/package.json
packages/eslint-config-react-app/package.json
packages/react-dev-utils/package.json
packages/react-error-overlay/package.json
packages/react-scripts/package.json
packages/react-scripts/template/README.md

Fix package repository name

---

packages/react-scripts/template/README.md

This adds instructions needed when configuring Netlify for continuous delivery of a GitHub repository.
This is what [the form](https://app.netlify.com/start) currently looks like:

Update instructions for continuous delivery with Netlify

---

packages/react-dev-utils/launchEditor.js

Adds support for the error overlay to detect and open the file with the error in JetBrains GoLand IDE.
Relates to #2636.

Autodetect GoLand editor

---

packages/react-scripts/config/paths.js

without this, the latest alpha broke on start
```
/Users/adeviankakrisnafadlil/Projects/eurecah/node_modules/react-scripts/config/paths.js:130
.reduce(
^
TypeError: Cannot read property 'reduce' of undefined
at findPkgs (/Users/adeviankakrisnafadlil/Projects/eurecah/node_modules/react-scripts/config/paths.js:130:6)
at getMonorepoPkgPaths (/Users/adeviankakrisnafadlil/Projects/eurecah/node_modules/react-scripts/config/paths.js:143:22)
at Object.<anonymous> (/Users/adeviankakrisnafadlil/Projects/eurecah/node_modules/react-scripts/config/paths.js:155:55)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Module.require (module.js:587:17) …
```

add default value for globPatterns

---

packages/react-scripts/package.json

Update `dotenv-expand` to fix bug with environment variables that containing a `$`.
Addresses #3961 in the `1.x` branch.

Upgrade dotenv-expand to 4.2.0 in 1.x branch

---

packages/react-scripts/package.json

Fixes https://github.com/facebook/create-react-app/issues/4003.
Unpinning so that it keeps working even as new Node versions come out.
The dependency has been fairly stable and I trust that if it breaks, everyone will notice anyway.

Unpin and bump fsevents (for 1.x branch)

---

packages/react-scripts/package.json

Update `dotenv-expand` to fix bug with environment variables that contain a `$`.
Closes #3961

Upgrade dotenv-expand to 4.2.0 (#3961)

---

packages/react-scripts/package.json

Update `dotenv` to address the bug in #4002 
This should probably also be backported to `1.x`.

Update dotenv to 5.0.0

---

packages/react-dev-utils/workspaceUtils.js

With the addition of the [nohoist feature](https://github.com/yarnpkg/yarn/pull/4979), yarn has enabled a new optional format for the `workspaces` key in `package.json`:
```json
"workspaces": {
"packages": ["packages/*"],
"nohoist": ["**"]
}
```
This feature is already available in the current [yarn nightly build](https://yarnpkg.com/en/docs/nightly) and I'm successfully using it with the following setup:
`yarn@1.4.1-20180208.2355` (nightly)
`react-scripts@2.0.0-next.47d2d941` (with my patch)
`lerna@2.8.0` (with a similar [patch](https://github.com/lerna/lerna/pull/1254))
With these patches applied, everything worked out-of-the-box*, aside from needing to make use of the `nohoist` option. 
*(obviously, I also needed to configure lerna to use yarn and workspaces)
With the nightly build of …

Add support for new yarn workspaces config format

---

packages/react-scripts/template/README.md

This is the current node LTS release.

docs: use node_js 8 in example travis.yml

---

packages/react-scripts/template/README.md

Object Rest/Spread proposal is now stage 4 and accepted into the EcmaScript standard.

Docs: Update status of Object Rest/Spread proposal

---

packages/react-scripts/template/README.md

the screencast for react storybook is non-free. Remove.

Remove ref to non free resource

---

packages/react-error-overlay/src/effects/proxyConsole.js
packages/react-error-overlay/src/utils/getStackFrames.js
tasks/e2e-installs.sh
tasks/e2e-kitchensink.sh
tasks/e2e-monorepos.sh
tasks/e2e-simple.sh

This fixes some CI issue that I encountered, when trying to run CI locally (and on the CI servers).
This does not fix everything, but gets the CI closer to working correctly.
- Remove `cache clean` as it is unneeded in npm@5 and throws an error
- Fix issues with linting that fails CI

Minor fixes to CI

---

packages/react-scripts/scripts/utils/createJestConfig.js

Support for .mjs files added in #3239 did not account for npm libraries which ship native mjs files alongside js files. This accounts for this by ensuring .js files resolve before their accompanying .mjs file. Note that this is not an ideal end state since selecting a .mjs over a .js extension should be the result of whether `import` was used instead of `require()` in a node environment with native ESM support (currently via `--experimental-modules`). Instead, this change just *always* selects a .js extension before the .mjs extension if it exists.
This unbreaks support for using GraphQL (relay, apollo, etc) within create-react-app projects.

BUG MITIGATION: .mjs should not resolve before .js files

---

packages/react-scripts/template/README.md

Add troubleshooting for an issue that has to do with either 2FA, or using Windows, or both, when trying to deploy an app via gh-pages .
Proactively fixes #4196

Add troubleshooting for Github Pages

---

packages/react-dev-utils/ModuleScopePlugin.js
packages/react-dev-utils/README.md

When ejected, you can now pass in an array as the appSrc for ModuleScopPlugin.
Implement of #4079 
1. `yarn create-react-app test-app`
2. `cd test-app`
3. `yarn run eject`
4. `mkdir docs`
5. In `config/paths.js`, add `docsSrc: resolveApp('docs')`
6. In `config/webpack.config.dev.js`, modify `new ModuleScopePlugin(paths.appSrc, [paths.appPackageJson]),` to `new ModuleScopePlugin([paths.appSrc, paths.docsSrc], [paths.appPackageJson]),`
7. `yarn start`. You should be able to import stuff from both `src/` and `docs/`.

Allow ModuleScopePlugin accecpts an array as its appSrc

---

packages/eslint-config-react-app/index.js
packages/eslint-config-react-app/package.json
packages/react-error-overlay/package.json
packages/react-scripts/package.json

Update `eslint-plugin-react` to `7.7.0` and add `forbid-foreign-prop-types` check.
Closes #3840

Add ESLint check for incorrect propTypes usage (#3840)

---

packages/react-scripts/fixtures/monorepos/packages/comp1/index.js

Adds some code in shared component test that requires transpilation to ensure yarn workspace support is working correctly.

Yarn workspace transpilation verification.

---

packages/react-error-overlay/src/components/CodeBlock.js

As screenshots, notice the position of "caret" symbol.

Fix floating caret position incorrect while scrolling overlay

---

packages/react-scripts/config/webpack.config.prod.js

Building my app using the [next] version of react-scripts lead to issues when trying to open the minified results on IE11.
It's a combination of using the [commonmark.js](https://github.com/commonmark/commonmark.js) library and using the `{ecma: 8}` in the uglifyOptions. That led to unicode characters in the output that can't be parsed by IE11. Also the Google crawler bot is yelling `Unexpected token ILLEGAL` at the resulting code.
Look here for another discussion about the same issue: https://github.com/rails/webpacker/issues/1235

[next] Revert to use ecma 5 in uglifyOptions

---

packages/react-scripts/config/webpack.config.prod.js

as discussed here https://github.com/facebook/create-react-app/pull/4234#issuecomment-377996167

Fix typo in comment and be clearer about `ecma` settings in uglifyjs options

---

CHANGELOG.md

* [#4085](https://github.com/facebook/create-react-app/pull/4085) Resolve `.js` before `.mjs` files to unbreak dependencies with native ESM support. ([@leebyron](https://github.com/leebyron))
* [#4197](https://github.com/facebook/create-react-app/pull/4197) Add troubleshooting for Github Pages. ([@xnt](https://github.com/xnt))
- Lee Byron ([leebyron](https://github.com/leebyron))
- Vicente Plata ([xnt](https://github.com/xnt))
Inside any created project that has not been ejected, run:
```
npm install --save --save-exact react-scripts@1.1.2
```
or
```
yarn add --exact react-scripts@1.1.2
```

Add 1.1.2 changelog

---

packages/react-scripts/package.json
packages/react-scripts/scripts/test.js

This is a very hacky workaround for https://github.com/facebook/jest/issues/5913. I think we need this because it's actively breaking our users (https://github.com/okonet/lint-staged/issues/414) and is very tricky to debug.
cc @SimenB

Work around Jest environment resolving bug

---

packages/babel-preset-react-app/index.js

**Copying the contents of my MobX issue:**
After trying out the latest create-react-app and mobx 4's `decorate`, I found that my classes were no longer observable. At first glance, it looks like it's Babel 7's class property transform.
Here's a codesandbox: https://codesandbox.io/s/623qwprm8k
I'd expect the updated value of `FooBabel7` to trigger the `autorun`.
Differences in babel output:
Source:
```jsx
class Foo {
value = 1;
}
```
Babel 6:
```jsx
class Foo {
constructor() {
this.value = 1;
}
}
```
Babel 7:
```jsx
class Foo {
constructor() {
Object.defineProperty(this, "value", {
configurable: true,
enumerable: true,
writable: true,
value: 1
});
}
}
```
Enabling `loose` mode reverts the transform back to the Babel 6 behavior.
Simple before/after:
Current behavior:
With `loose: true`: …

Enable loose mode for `class-properties`

---

packages/react-dev-utils/README.md
packages/react-dev-utils/getCSSModuleLocalIdent.js
packages/react-dev-utils/package.json
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
packages/react-scripts/fixtures/kitchensink/src/features/webpack/CssModulesInclusion.js
packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/index.module.css
packages/react-scripts/package.json
packages/react-scripts/template/README.md

This PR updates the classname naming of CSS Modules as per the discussion in PR #3965.
**Examples**
`MyFolder/MyComponent.module.css` and class `MyClass` the output will be `MyComponent.module_MyClass__[hash]`
`MyFolder/index.module.css` and class `MyClass` the output will be `MyFolder_MyClass__[hash]`
The E2E tests have been updated, but I was unable to run them locally to ensure the tests were working correctly.
The results have been manually tested.

Update CSS Modules localIndetName

---

packages/react-scripts/template/README.md

https://github.com/facebook/create-react-app/issues/4071
Hi, in reference to issue [4071](https://github.com/facebook/create-react-app/issues/4071)
A doc issue:
And that's exactly what it looks like around the surrounding context!

Document multiple build environments via `env-cmd` #4071

---

packages/react-scripts/template/README.md

Learnstorybook is a tutorial for Storybook that both uses CRA and is at a level of introductionary detail appropriate for CRA users.

Added learnstorybook.com to Storybook links

---

packages/react-scripts/template/README.md

Fixed two typos. 
- explictly => explicitly
- overriden => overridden

Fix some typos in README.md

---

tasks/e2e-simple.sh

while reading through the tests I noticed this

Fix typo in e2e-simple.sh comment

---

packages/react-scripts/package.json

`fsevents@1.2.0` uses `node-pre-gyp@0.9.0`, which no longer uses an old version of `request`.  So the install size will be a bit smaller for Mac users.

Bump `fsevents`.

---

README.md

Added License in the README
Keep the docs consistent and informing for everyone the project License in a easiest way.
[x] adding License section on README
[x] Documentation
[ ] Tests
[x] Ready to be merged

documentation: added License to the README.md

---

packages/react-scripts/config/webpack.config.prod.js

hot fix missmatch between .dev and .prod making css modules not matched correctly when building for production. 
long term fix will be to break out common config to seperate file to avoid missmatch.

[hot]fix broken css module support in prod

---

packages/create-react-app/createReactApp.js
tasks/e2e-installs.sh

Tested via `npm link` on OSX with npm@5.8.0 and yarn@1.6.0
Closes #4348

Support package distribution tags

---

.github/ISSUE_TEMPLATE.md
packages/create-react-app/createReactApp.js
packages/create-react-app/package.json

This PR fixes a few outstanding issues, and supersedes https://github.com/facebook/create-react-app/pull/3859 and https://github.com/facebook/create-react-app/pull/3797.
There were a couple issues with envinfo, and the issue template that never got resolved - this is my attempt to fix all of that. Also, envinfo has been rewritten for size and speed since originally integrated, and a few more features have been added. The command is the same `create-react-app --info`, but now returns more info, like this:
```
System:
OS: macOS High Sierra 10.13
CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
Binaries:
Node: 8.11.0 - ~/.nvm/versions/node/v8.11.0/bin/node
Yarn: 1.5.1 - ~/.yarn/bin/yarn
npm: 5.6.0 - ~/.nvm/versions/node/v8.11.0/bin/npm
Browsers:
Chrome: 65.0.3325.181
Firefox: 59.0.2 …
```

fix: update envinfo + implementation, update issue_template

---

packages/react-dev-utils/getCSSModuleLocalIdent.js
packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
packages/react-scripts/fixtures/kitchensink/src/features/webpack/SassModulesInclusion.js
packages/react-scripts/fixtures/kitchensink/src/features/webpack/ScssModulesInclusion.js
packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/index.module.sass
packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/index.module.scss

I updated `react-dev-utils/getCSSModuleLocalIdent` to make the cases of `index.module.scss` and `index.module.sass` consistent with its behavior for `index.module.css`, meaning that all three should (approximately) output `[folder]_[localName]__[hash]` as their `localIdent`.
I also added tests to ensure this works correctly, but sadly I couldn't run them on my machine so I'll piggyback your CI.

Update getCSSModuleLocalIdent to support Sass

---

packages/react-scripts/config/paths.js

Summary:
The `hasSlash` method uses `path.substr(path, path.length - 1)` to
remove the last character from `path`. Clearly, the first parameter is
suspect; it should be `0`. The code works as written, but only very
accidentally: the first parameter is coerced by `ToNumber` to `NaN`,
which is then coerced by `ToInteger` to `+0`, per [the spec][1].
[1]: https://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.substr
Test Plan:
Reading the spec should be sufficient. To verify in the Real World:
```js
const path = "has-slash-but-does-not-need-slash/"
const a = path.substr(path, path.length - 1);
const b = path.substr(0, path.length - 1);
console.log(a === b);  // true
console.log(a);        // has-slash-but-does-not-need-slash
```
wchargin-branch: ensureslash-accidental-coercion

ensureSlash: Fix accidental string-to-NaN coercion

---

packages/react-dev-utils/formatWebpackMessages.js

The fix done in #3847 is outdated, since thread-loader updated his error message, so now this happens:
I updated the test so now it's more general.

Update the thread loader test in formatWebpackMessages

---

packages/babel-preset-react-app/package.json

Update babel-plugin-macros to 2.2.1. It fixes issue of macros not working with babel-plugin-istanbul e.g. when you run npm test --coverage in create-react-app based project
Reproducible demo of the bug https://github.com/stereobooster/babel-macro-issue
Discussion of bugfix is here https://github.com/kentcdodds/import-all.macro/issues/7

Update babel-plugin-macros to fix a bug

---

README.md

following up on https://twitter.com/iansu/status/995154881290817538

add create-react-app-parcel to Alternatives section in README

---

packages/react-scripts/scripts/utils/createJestConfig.js

Fixes https://github.com/facebook/create-react-app/issues/4345
SCSS and SASS modules currently aren't getting transformed, instead they are being resolved by the `fileTransform`. This PR instead sends them through the `identity-obj-proxy` so that:
```
<div className={style.container>...</div>
```
becomes
```
<div className="container">...</div>
```
when using `jest`.

Map (s?css|sass) modules to identity-obj-proxy in jest

---

packages/react-scripts/scripts/utils/createJestConfig.js

This has been merged to master, but I've cherrypicked it to next, so it goes into the next release. see #4317
Support for .mjs files added in #3239 did not account for npm libraries which ship native mjs files alongside js files. This accounts for this by ensuring .js files resolve before their accompanying .mjs file. Note that this is not an ideal end state since selecting a .mjs over a .js extension should be the result of whether `import` was used instead of `require()` in a node environment with native ESM support (currently via `--experimental-modules`). Instead, this change just *always* selects a .js extension before the .mjs extension if it exists.
This unbreaks support for using GraphQL (relay, apollo, etc) within create-react-app projects.

`.mjs` should not resolve before .js files (#4085) (#4317)

---

packages/react-scripts/template/README.md

There have been a couple of changes to `node-sass-chokidar` over the recent days.
The following things have been changed, [according to the `node-sass-chokidar/CHANGELOG`](https://github.com/michaelwayman/node-sass-chokidar/blob/master/CHANGELOG.md):
- `--recursive` flag removed as it doesn't do anything ([CHANGELOG v1.0.0](https://github.com/michaelwayman/node-sass-chokidar/blob/master/CHANGELOG.md#100))
- initial scss build removed on `watch-css`, as chokidar changed the behaviour ([CHANGELOG v1.0.0](https://github.com/michaelwayman/node-sass-chokidar/blob/master/CHANGELOG.md#100))
🍻

Chokidar Updates

---

packages/react-scripts/template/README.md

Small docs change to Read Me template:
https://github.com/facebook/create-react-app/issues/871 is still an issue on the latest version of react-scripts (1.1.4 at time of writing).
Rather than having people eventually find this issue and waste time, be more helpful and provide a note in the readme so people are aware this is an issue and don't waste time.
create-react-app is great for people that are learning react and this issue affects them negatively.
This note can be removed once the issue is fixed.

[Read Me template patch] Warn about #871 until it's actually fixed. 

---

packages/react-scripts/config/paths.js

This file requires the "path" module and sets it to a variable `path`. The function `ensureSlash` also has a variable `path` that then shadows the `path` module.

Update paths.js, rename shadow path variable

---

packages/react-dev-utils/browsersHelper.js

Per #4355, we should probably modernize our browser support.
Here's the new target list (you can see our old list in #4355):

Adjust browser defaults

---

packages/react-scripts/config/webpack.config.dev.js

needed this so i can query `http://localhost:3000/asset-manifest.json` for available assets to use while developing with a CMS

enable manifest plugin on dev

---

packages/react-scripts/package.json
packages/react-scripts/scripts/build.js
packages/react-scripts/template/README.md

Associated issue: #1858
To analyze Webpack bundles, a "stats" JSON is required.
This PR allows that file to be created and saved to the `build`
directory, so that users can use it with Webpack-specific insight
tools like `webpack-bundle-analyzer` without ejecting their
application.
Updated the README to include details for how to do this.
**1. check that the stats flag works**
I ran `yarn build --stats` in the root directory of the project. Once it completed, I verified that build/bundle-stats.json existed. I dragged it into Webpack Visualizer to check that the file is correct:
**2. check that it works in a created project**
I ran `yarn create-react-app test` to generate a new app.
After `cd`-ing into the directory and installing its dependencies, I followed the steps I added to the the …

Allow bundles to be analyzed with Webpack-specific tools

---

packages/react-scripts/template/README.md

We'll re-add it after 2.x is close to shipping and we've decided about https://github.com/facebook/create-react-app/issues/4563.
For now I want to avoid adding docs for 2.x features unless we keep them all in a separate branch from next. I expect that many people will accidentally find them, and be confused what 2.x is and why they don't have it.

Temporarily remove doc section on webpack analyzer

---

packages/react-scripts/config/webpack.config.dev.js

Configured the thread-loader to keeping workers alive in development mode

---

packages/react-dev-utils/printHostingInstructions.js

This PR just changes the printed output when running `yarn build` with a homepage set in the `package.json` to show `yarn build` instead of `npm run build` for the predeploy command if using yarn.
This matches the rest of the output, which also displays the yarn commands.
**Changes:**
```
// ...
"scripts": {
// ...
"predeploy": “npm run build",
"deploy": "gh-pages -d build"
}
```
**To:**
```
// ...
"scripts": {
// ...
"predeploy": “yarn build",
"deploy": "gh-pages -d build"
}
```
Tested manually to check that it is working. Screenshot below:

Use yarn build command in predeploy script if using yarn

---

tasks/e2e-installs.sh
tasks/e2e-kitchensink.sh
tasks/e2e-monorepos.sh
tasks/e2e-simple.sh
tasks/verdaccio.yaml

Replace npm-login-cli with npm-auth-to-login, which works with node 10.
Should fix https://github.com/facebook/create-react-app/pull/4383

[internal] Fix node 10 test issue

---

README.md

Added instructions for:
- `npm init react-app <name>`
- `yarn create react-app <name>`
closes https://github.com/facebook/create-react-app/issues/4478

Add instructions on alternative methods of app creation

---

packages/babel-preset-react-app/create.js
packages/babel-preset-react-app/dev.js
packages/babel-preset-react-app/index.js
packages/babel-preset-react-app/package.json
packages/babel-preset-react-app/prod.js
packages/babel-preset-react-app/test.js

This adds entry point like `react-app/dev`, `react-app/prod`, and `react-app/test`.
I need them to make https://github.com/reactjs/reactjs.org/pull/992 tolerable.

Add modes to our Babel preset (1.x)

---

packages/create-react-app/createReactApp.js

https://github.com/facebook/create-react-app/issues/4666

Support scoped package names for scripts-version option in create-react-app cli

---

packages/react-scripts/template/README.md

Rendered: https://github.com/kentcdodds/create-react-app/blob/1b3a028f0dea697322a2e85906c7642f357313c6/packages/react-scripts/template/README.md#use-react-testing-library
Considering the growing popularity of react-testing-library, it seems fitting to document and provide examples of using this library for folks looking for a testing utility that matches their preferences.

add react-testing-library documentation/examples

---

packages/react-scripts/config/webpack.config.dev.js

As discussed in: https://github.com/facebook/create-react-app/issues/4736

remove extra dot on devtool link comment

---

.travis.yml
appveyor.yml
packages/create-react-app/createReactApp.js
packages/react-scripts/fixtures/kitchensink/integration/env.test.js
packages/react-scripts/fixtures/kitchensink/integration/initDOM.js
packages/react-scripts/fixtures/kitchensink/integration/syntax.test.js
packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
tasks/e2e-kitchensink-eject.sh

See if it will make travis CI runs less flaky

[internal] Separate out kitchensink test into two

---

packages/react-scripts/package.json

No more:
```bash
warning "react-scripts > babel-loader@8.0.0-beta.0" has incorrect peer dependency "webpack@2 || 3".
```

Bump babel-loader to fix npm warning

---

packages/react-scripts/template/README.md

The website linked says that service workers are now ready 🎉
A version of #4676 that targets `next` instead of `master`.

 Update support info for service workers

---

packages/react-scripts/template/README.md

Fix link to the article about BEM

---

packages/react-scripts/package.json

This fixes the functionality of this dependency for Node 10 and above.
Refs: https://github.com/webpack/webpack-dev-server/pull/1451
Refs: https://github.com/nodejs/node/issues/21665

Update webpack-dev-server 3.1.5 → 3.1.7

---

packages/confusing-browser-globals/package.json
packages/react-dev-utils/package.json
packages/react-error-overlay/package.json
packages/react-scripts/package.json

Jest 23 adds support for `test.each` #4845

Update jest version

---

package.json
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/scripts/utils/createJestConfig.js

`.mjs` support needs to be dropped until https://github.com/facebook/jest/issues/4842 is closed and there's a path forward for `.mjs` support.

Remove `mjs` support

---

packages/react-dev-utils/InterpolateHtmlPlugin.js
packages/react-dev-utils/README.md
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/package.json

It seems that `html-webpack-plugin@3` isn't fully compatible with webpack 4 and worked by chance.

Upgrade `html-webpack-plugin` to fix tests

---

packages/babel-preset-react-app/create.js

Because of how tuned our babel configuration is we can't reliably let users target what browser's they'd like to support without everything else falling apart.
If we use just `preset-env` users are left with a suboptimal bundle or something that *requires* other configuration, so this is the best option for now.

Lock babel configuration back to IE 9 support (ES5)

---

packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

This is the best behavior so people have seamless upgrades to new React majors.
This is probably a terrible default warning from the ESLint plugin, and we need to wait for https://github.com/yannickcr/eslint-plugin-react/issues/1955 before changing this hardcoded behavior.
Closes #5034

Always lint with latest React version

---

packages/babel-preset-react-app/dependencies.js

[This proposal](https://github.com/tc39/proposal-dynamic-import) is in stage 3, is supported in Node 9.7 behind a feature flag, and shipped in Chrome 63/Safari Preview 24.
It's unlikely to change and is the basis for all modern bundler code-splitting.

Allow dynamic import proposal in node_modules

---

packages/react-dev-utils/evalSourceMapMiddleware.js
packages/react-dev-utils/package.json
packages/react-error-overlay/src/utils/mapper.js
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpackDevServer.config.js

Fixes [issue]
Switches webpack's devtool [mode] from `cheap-module-source-map` to `source-map` so that the mappings include column positions.
This enables variable and scope mappings in Firefox, which makes it easier to debug applications built with webpack and babel. This should fix the `this` mapping issue. It will also simplify the scopes pane by showing the "original" scopes and variables. It will also enable in-line code preview and console support when evaluating "original" expressions. 
The incremental build times were 25% slower for `source-map` vs `cheap-module-source-maps` (500ms vs 400ms) on a simple [app]. I believe that webpack's cache means that these numbers would not be that different on a larger app.  
Both modes had equivalent breakpoint support on page load and while …

Switch from cheap-module-source-map eval-source-map

---

packages/eslint-config-react-app/index.js

ESLint 5 dropped `experimentalObjectRestSpread`, the `generators` feature has been gone for a while, and we should support the latest JavaScript features via `ecmaVersion` 6 (2015) => 9 (2018).
`eqeqeq` also has a new `smart` mode that is a little more relaxed than `allow-null`, permitting `==` when testing a string literal against `typeof`.
Follow up to #5050.

Adjust ESLint configuration for v5

---

packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

Make sure babel caching is on *everywhere*. Also, we want to turn off Gzip compression during development to help with cold boot/rebuild speed.

Normalize babel caching across the board

---

packages/react-dev-utils/getCacheIdentifier.js
packages/react-dev-utils/package.json
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

Babel's default cache identifier isn't adequate for the way we hide configuration, this should address that.

Ensure Babel files get purged on upgrades

---

packages/react-dev-utils/README.md
packages/react-dev-utils/getCacheIdentifier.js

Add documentation for new helper and tweak the `environment` input handling.

Cache identifier follow up

---

packages/react-scripts/template/public/index.html

Chrome requests `favicon.ico` on every route change, but stops if the `<link>` for it occurs early enough in the page. [Several](https://stackoverflow.com/questions/35409588/favicon-requested-on-every-route-change) other [people](https://github.com/ctrlplusb/react-universally/issues/145) have been running into this issue since at least February 2016.

Move favicon.ico <link> to accommodate Chrome

---

packages/react-scripts/config/webpack.config.dev.js

Follow up #4930
It looks like chrome stable and safari fail to show the error overlay with `eval-source-map`. Based on that, I think we should likely switch back to `cheap-module-source-map` for the time being.

Switch back to cheap-module-source-map

---

packages/react-dev-utils/InlineChunkHtmlPlugin.js
packages/react-dev-utils/README.md
packages/react-dev-utils/package.json
packages/react-scripts/config/webpack.config.prod.js

This pull request introduces a new webpack plugin, `InlineChunkHtmlPlugin`.
`InlineChunkHtmlPlugin` taps into the new `HtmlWebpackPlugin` hook API and inlines any chunks matching (a) given regex expression(s).
It continues to delete the asset to prevent webpack from writing it to disk.
The runtime chunk should be separated from the app and vendor bundles so neither get invalidated when only the other bundle changes.
Unfortunately, the `runtime` chunk is *way too small* to warrant an additional HTTP request.
The solution? Inline it into the HTML, i.e.
```html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
<meta name="theme-color" content="#000000">
<link rel="manifest" …
```

Inline the webpack runtime chunk

---

packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/package.json

Continuation of #4799 by @kopacki.
This updates `svgr` and disables Prettier / SVGO.
Prettier is disabled because it just increases compile-time latency, there's no true benefit here.
SVGO is disabled because there's no "safe defaults" that keep it useful IMO, and we don't apply optimizations to SVGs imported as URLs.
Different optimization behavior based on how the SVG is imported would be confusing/unexpected to the user, especially during debugging.
If we go down the SVGO path, we'll probably only do it for Production and for both ReactComponents and URLs.
This PR will be a great first step.

Upgrade svgr to v2 and disable Prettier & SVGO

---

packages/react-scripts/template/README.md

this is a minor typo in troubleshooting section for github pages
someone might have run `gh-pages` with non-existing parameter 'again'

fix minor typo in troubleshooting github pages

---

packages/react-dev-utils/FileSizeReporter.js
packages/react-dev-utils/WebpackDevServerUtils.js
packages/react-scripts/scripts/build.js

Derived from https://github.com/facebook/create-react-app/issues/4492#issuecomment-421959548.
This should act on the final suggestion from @sokra, as we switched to Terser in #5026 and inlined the runtime chunk in #5058.
Thanks for the pointers, @sokra!

(Micro) Optimize webpack rebuild speed

---

packages/react-dev-utils/WebpackDevServerUtils.js

Adding the advanced proxy was a mistake, and most of the time it isn't "advanced" enough for people using it.
There needs to be a new solution.

Drop support for advanced proxy

---

packages/react-scripts/template/README.md

Mention [API Platform](https://api-platform.com), that is fully integrated with Create React App.

Integrating with an API Backend: add API Platform

---

package.json
packages/react-scripts/scripts/init.js
packages/react-scripts/scripts/test.js
packages/react-scripts/scripts/utils/createJestConfig.js
packages/react-scripts/template/README.md

This changes the default test environment to jsdom, because most people use it anyway.

Change default test environment to jsdom

---

packages/react-scripts/fixtures/kitchensink/jest.integration.config.js
packages/react-scripts/fixtures/kitchensink/jest.transform.js
tasks/e2e-kitchensink.sh
tasks/local-test.sh

https://github.com/facebook/create-react-app/issues/5095

[internal] remove babelrc dependency for kitchensink test

---

packages/babel-preset-react-app/create.js

Regenerator is already included by preset-env.
Fixes #4627

Eliminate regenerator from preset-react-app plugins

---

packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

From babel7, the `highlightCode` options defaults to true.
Related PR: https://github.com/babel/babel/pull/8546
New docs: https://babeljs.io/docs/en/next/options#highlightcode

Remove highlightCode:true because it's now the default

---

packages/babel-preset-react-app/dependencies.js
packages/babel-preset-react-app/package.json

Clean up @babel/plugin-transform-regenerator

---

packages/react-dev-utils/package.json

The `loader-utils` package is defined in `getCSSModuleLocalIdent` ([source](https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/getCSSModuleLocalIdent.js#L10)), but isn't declared in the package.json. I took the version used by `react-scripts`.

Lists loader-utils in the dependencies

---

packages/react-dev-utils/formatWebpackMessages.js

Some third party webpack plugins can generate custom single-line compiler errors without stacktrace.
For example with `html-webpack-plugin` I got following error as `formatMessage` argument:
```js
'Template execution failed: TypeError: Cannot read property \'main\' of undefined' 
```
As fast solution I propose to add empty line to avoid big changes in `formatMessage` logic.

Fix displaying third party webpack plugins errors

---

packages/babel-preset-react-app/create.js
packages/babel-preset-react-app/dependencies.js
packages/babel-preset-react-app/package.json
packages/react-error-overlay/package.json
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/package.json

Inspired by #5136, fixes https://github.com/facebook/create-react-app/issues/5116.

Remove runtime alias hack

---

packages/react-scripts/template/README.md

Resolves https://github.com/facebook/create-react-app/issues/4334#issuecomment-425175394

Mention .module.scss/sass convention

---

.eslintignore
.travis.yml
fixtures/behavior/builds-with-multiple-runtimes/package.json
fixtures/behavior/builds-with-multiple-runtimes/src/index.js
package.json
tasks/e2e-behavior.sh
tasks/test-behavior.js

I want to expand on this more in the future, e.g. load site up in headless chrome/JSDom and add output matching.
For now, this makes sure our babel runtime work-around works.
Follow up to #5142.
Example failure before addition of #5142:
https://travis-ci.org/Timer/create-react-app/builds/434316343#L1577-L1606
I'd add this to AppVeyor, but I'm thinking we should switch to Azure Pipelines and wait until then.

Add behavior e2e tests

---

fixtures/smoke/graphql-with-mjs/index.test.js
fixtures/smoke/graphql-with-mjs/package.json
fixtures/smoke/graphql-with-mjs/public/index.html
fixtures/smoke/graphql-with-mjs/src/App.js
fixtures/smoke/graphql-with-mjs/src/index.js
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

https://github.com/graphql/graphql-js/issues/1272
Wow, this new testing setup is really handy.

Toggle `mjs` files to `javascript/auto` type

---

packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

Related: #5136
This diff ensures that the process arguments (in particular `--require`) are correctly forwarded to the spawned subthreads. This is important, since preload scripts typically modify the environment in some capacity.

Forwards args through thread-loader

---

fixtures/output/webpack-message-formatting/index.test.js
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/package.json

After the cache is warm, it is possible for thread-loader to hurt speed.
thread-loader also has leaky interaction with its workers, giving us some junk output here and there.
This will hurt cold boots/builds the most, but with our cache rules it should be very seldom someone needs to clear their cache (if ever).
Per https://github.com/facebook/create-react-app/issues/5138#issuecomment-425631999, future work is to write our own worker that handles caching **and** parallelization.
---
Fixes #5138

Remove thread-loader

---

packages/react-scripts/config/webpack.config.prod.js

Requests are only made to the CDN if the user opts-in to the Service Worker via `index.js`.
The calls are not present in our default installation.

Fetch Workbox from CDN

---

README.md
packages/react-scripts/template/README.md

R: @gaearon @Timer 
This is a continuation of the fix for https://github.com/facebook/create-react-app/issues/3864, with additional changes to reflect the usage of Workbox and the fact that setting proper `Cache-Control` headers on the generated service worker file should (hopefully!) [no longer be a concern](https://developers.google.com/web/updates/2018/06/fresher-sw) for modern web browsers.
This PR depends on #4169 being merged.

Updates to README to reflect Workbox usage.

---

packages/react-dev-utils/InlineChunkHtmlPlugin.js

This emits the runtime chunk and puts it in the `asset-manifest.json`.
It is still inlined into `index.html` and is not required via `<script src="..." />`.
Fixes #5172
Fixes #5144

Still emit runtime chunk

---

packages/react-scripts/template/README.md

Replace `src/setupTests.js` with `src/setupProxy.js`.

Fix typo in 'Configuring the Proxy Manually'

---

packages/react-scripts/config/jest/fileTransform.js

Fixes the issue in https://github.com/facebook/create-react-app/pull/5147#issuecomment-425768441.
We used to just emit filename for SVG snapshots when imported as React components. But that's not super useful and we forgot to change it before the release.
This prints it as an SVG tag instead, with any props passed in. But we don't render the inside.
Before and after:
```diff
-     logo.svg
+     <svg
+       className="lol"
+     >
+       logo.svg
+     </svg>
```
Closes #5191.

Format SVG React snapshots as <svg> tag with props

---

packages/react-scripts/template/README.md

[Preview](https://github.com/mareksuscak/create-react-app/blob/update-svg-doc/packages/react-scripts/template/README.md#adding-svgs)

Document adding SVGs as React components

---

packages/react-scripts/config/webpack.config.prod.js

Fixes https://github.com/facebook/create-react-app/issues/5140. Fixes https://github.com/facebook/create-react-app/issues/5188.
While unfortunate due to concerns in https://github.com/facebook/create-react-app/issues/5188#issuecomment-425844969, I don't feel comfortable with webpack's default behavior until webpack adds a warning or an error for this (https://github.com/webpack/webpack/issues/6571#issuecomment-425897134). When webpack does, we can reconsider and go with webpack's default behavior.
I checked that this change fixes the reproducing case in https://github.com/cdaringe/will-u-load-my-styl.

Treat .css and .sass/.scss as side effectful

---

.travis.yml
appveyor.yml
packages/create-react-app/createReactApp.js
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/package.json
packages/react-scripts/scripts/init.js
packages/react-scripts/scripts/utils/createJestConfig.js
tasks/e2e-installs.sh

Fixes #5117 - there's still at least one issue with ESLint which cannot load its plugins, and as a result crashes (https://github.com/eslint/eslint/issues/10125), but at least it gets to this point 🙂

Plug'n'Play support

---

packages/react-error-overlay/src/utils/mapper.js

`String.startsWith` doesn't exist in Internet Explorer.

Fix IE 11 compatibility

---

packages/react-scripts/template/README.md

As discussed in #5154 there's an easier way to customize Bootstrap in React using Sass (starting from `react-scripts@2.0.0`). I've changed the section in the docs to make use of Sass (and tested the code of course). I'm hoping the level of detail is good here. I thought about going deeper but I felt it wasn't needed.

Adds instructions to README on how to customize Bootstrap with Sass

---

packages/react-scripts/scripts/test.js

Fixes https://github.com/facebook/create-react-app/issues/5210 with a clunky workaround.
I hope this more or less matches the Jest logic.

Don't crash npm test when hg/git are missing

---

packages/react-dev-utils/launchEditor.js

Clicking Error overlay should feed the correct line number for gvim.
Relates to https://github.com/facebook/create-react-app/issues/2636.

Feed correct line number to gvim on launch

---

packages/react-scripts/scripts/utils/createJestConfig.js

This fixes absolute paths that were introduced when ejecting in #5136.
This *does* break PnP on eject though. I asked @arcanis to look into fixing this.
The proper fix would be to actually generate a `jest.config.js` after eject, and keep them as `resolve()`.

Fix absolute paths on eject

---

packages/react-scripts/template/README.md

Fixes #5186. Adds instructions for using the babel-plugin-relay macro.

DOCS: Add Relay example

---

packages/react-scripts/config/webpack.config.prod.js

This fixes `GENERATE_SOURCEMAP` env option not being respected for css sourcemap, by checking its presence before passing sourcemap options to `OptimizeCSSAssetsPlugin`.
It can be simply tested by running `react-scripts build` with and without `GENERATE_SOURCEMAP=false`, and see if any sourcemaps are being created under `build/static/css`

Fix GENERATE_SOURCEMAP env not working for css sourcemap

---

packages/react-scripts/template/README.md

refs: https://github.com/chimurai/http-proxy-middleware#tldr

Fix usage of http-proxy-middleware

---

website/i18n/en.json
website/siteConfig.js

This commit sets the primary and secondary color of the Docusaurus page to the same as the main React site (primary = dark gray / black, secondary = bright blue).
Again, we might want to do something else later, but this sure looks more on-theme than the defaults :) 
Addresses #5238

Set the color palette to something a bit more React-y

---

packages/react-scripts/template/README.md

Revert change to http-proxy-middleware docs

---

.travis.yml
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

Fixes #5234.
Closes #5257.
Closes #5235.
Webpack was never the problem with `.mjs` support, so we probably shouldn't of removed it.
We still want to figure out a story for Jest, we're just not sure what that is yet.
---
I opted to resolve `.mjs` before `.web.js` this time, does this seem OK?

Add `.mjs` support back to webpack (it has native ESM support)

---

packages/create-react-app/createReactApp.js

This PR ensures that users of `--use-pnp` are using at least the 1.12 release, which is the first one supported by `create-react-app`.
Ref #5255

Adds a version check when using --use-pnp

---

README.md

create-react-app-parcel is failing and there is no support for that.

removed create-react-app-parcel link

---

packages/babel-preset-react-app/create.js
packages/babel-preset-react-app/dependencies.js

I think leaving it on was a mistake. It causes some issues (https://github.com/facebook/create-react-app/issues/5267), but more fundamentally, it's a leaky abstraction. It tries to make `typeof` behave to return `'symbol'` for Symbols by hijacking every single `typeof`. This leads to slowing down all code for the benefit of edge cases that likely won't work 100% correctly anyway. It *definitely* makes React slower (I've measured this before).
I considered disabling it just for `node_modules` at first. But I don't see good reasons to leave it on in application code either. Code that relies on this is inherently fragile and can break in other ways.
We're early enough in 2.x cycle that I consider this a bugfix. It definitely *will* fix bugs for some libraries in `node_modules`. And arguably …

Disable Symbol typeof transform

---

packages/react-scripts/config/webpack.config.prod.js

Disable Terser inline 3 option

---

docusaurus/website/core/Footer.js
docusaurus/website/siteConfig.js

This pull request adds some more relevant links than the boilerplate ones provided by Docusaurus by default. 
Addresses #5238

Add SoMe links to documentation

---

packages/react-scripts/template/README.md

This adds back a section documenting how to add react-testing-library, which was later lost by accident. See #4679 for the original PR. This one merely adds back that commit by cherry-pick.
* add react-testing-library documentation/examples
* make react-testing-library a heading
* fix typo

add react-testing-library documentation/examples (#4679)

---

packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

I ejected a test project to take a look at the final webpack configs for some inspiration (our app has some custom needs, but I love looking at your configs for ideas!), and noticed that there was an unused import at the top of the file after ejecting.
Below is a screenshot after I ran the following from the root of the repo:
```
yarn create-react-app my-app
cd my-app
yarn eject
```
Let me know if you need anything else from me or if there is a better way to handle this!

Remove unused require for getCacheIdentifier after ejecting

---

packages/react-scripts/template/public/index.html

It seems correct URL is https://developers.google.com/web/fundamentals/web-app-manifest/
Current URL (https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/) is redirecting to there.

Updated the URL in index.html

---

packages/react-scripts/package.json

Updated the version of `eslint-plugin-jsx-a11y` from `6.1.1` to `6.1.2`.
Properly closes #4141 
Adds clearer error messages for the `anchor-is-valid` rule as per https://github.com/evcohen/eslint-plugin-jsx-a11y/pull/486.

Update eslint-plugin-jsx-a11y version

---

packages/react-dev-utils/FileSizeReporter.js

Fixes #5333
printFileSizesAfterBuild calls canReadAsset with an object containing
the file name while measureFileSizesBeforeBuild calls it with just the
name. When canReadAsset only receives the name it returns false since
accessing the `name` property results in undefined.
This PR fixes that by having canReadAssset instead expect only the
file name and making printFileSizesAfterBuild just like
measureFileSizesBeforeBuild only provide the name as argument.

Fix file size report after build (#5333)

---

docusaurus/docs/getting-started.md

This PR adds a very short introduction (taken from this [intro blog post](https://reactjs.org/blog/2016/07/22/create-apps-with-no-configuration.html), as well as some extra headings to the "Getting started" section.

Add some headings to the getting started section

---

packages/create-react-app/createReactApp.js

/cc @arcanis
```bash
> require('semver').gte('v1.13.0-a20181006.0202', '1.1.0')
TypeError: Invalid Version: v1.13.0-a20181006.0202
at new SemVer (/Users/joe/Documents/Development/OSS/create-react-app/node_modules/semver/semver.js:305:11)
at compare (/Users/joe/Documents/Development/OSS/create-react-app/node_modules/semver/semver.js:578:10)
at Function.gte (/Users/joe/Documents/Development/OSS/create-react-app/node_modules/semver/semver.js:627:10)
> require('semver').gte('v1.13.0-a201810060202', '1.1.0')
true
> require('semver').gte('v1.13.0-a20181006+0202', '1.1.0')
true
> require('semver').gte('v1.13.0-a20181006-0202', '1.1.0')
true
```

Fix CI: non-semver compliant Yarn versions

---

README.md
docusaurus/docs/getting-started.md

Simply updating the filename displayed to match what gets generated in 2.x.x

Update path to serviceWorker.js in graphical folder structure

---

packages/eslint-config-react-app/README.md

Update peer dependency versions in README.
This pull request ensures the dependency versions in the README install instructions match the peer dependencies in `package.json.`
I’ve installed eslint-config-react-app with my updated instructions and my webpack build works fine.

Fix eslint config docs.

---

packages/react-scripts/template/README.md
packages/react-scripts/template/src/serviceWorker.js

R: @Timer 
This includes updates to both the SW registration JS file (comments and `console.log()` messages) and the "Offline-first Considerations" section of the `README`, in the hopes of clarifying the current implications of the service worker lifecycle for users who decide to opt-in to service workers.

Updates to clarify the "waiting" SW behavior

---

packages/react-scripts/template/README.md

Current instructions for running using HTTPS in a PowerShell prompt are incorrect and do not work on Windows 10 v1809

Correct instructions for HTTPS and PowerShell

---

packages/react-scripts/template/README.md

Added a note aimed at Flow users on how to get Flow to recognize the .scss imports.

Added note on update to .flowconfig for .scss imports

---

packages/react-scripts/template/src/serviceWorker.js

When trying to access the PWD link from GitHub preview the `.` in the end is included in the link.
Clicking on it leads to the following [broken path.](http://bit.ly/CRA-PWA.)
This PR fixes it for future readers that will access it from GitHub.

Remove dot from the end of the link to fix it when using from GitHub

---

docusaurus/website/static/css/custom.css

Hello,
I see that title [wraps on Safari](https://www.dropbox.com/s/m4rgpgyckevdfze/Screenshot%202018-10-21%2002.20.11.png?dl=0) so I prepared a small PR to fix this. Here is [how it looks](https://www.dropbox.com/s/uk9l66awpm9ovp0/Screenshot%202018-10-21%2002.21.16.png?dl=0) with a fix applied.
Please check and let me know if this makes sense.
Thanks 🙏

Fix title on Safari

---

docusaurus/docs/adding-typescript.md
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/package.json

Always type check TypeScript when being used

---

packages/react-dev-utils/package.json
packages/react-dev-utils/typescriptFormatter.js
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

Add TypeScript error formatting

---

docusaurus/docs/adding-typescript.md

We don't need to tell users to rename multiple files at this step, only one.
And it's not needed to add `{}` to tsconfig anymore since #5532.
_PS: At the docs, we recommend installing `typescript @types/react @types/react-dom @types/jest`, but when not looking at the docs (just renaming the file) it only recommends adding `typescript`. Maybe we should add those there too?_

Simplified TypeScript steps

---

packages/react-scripts/template/gitignore

The same as node_modules, .pnp folder should be ignored by git
NOTE:
Not sure about .pnp.js

Avoid pushing .pnp folder to git

---

packages/react-dev-utils/globby.js
packages/react-dev-utils/package.json
packages/react-scripts/config/paths.js
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
test/fixtures/typescript/package.json

This causes weird behavior that allows the user to think types are being checked when they're really not.

Automatically setup TypeScript when detected

---

docusaurus/website/siteConfig.js

Resolves part of: https://github.com/facebook/create-react-app/issues/5238
Adds search bar per [Docusaurus instructions](https://docusaurus.io/docs/en/search). 
IS:
// Some info from Algolia
- You can check your configuration in our github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/create-react-app.json). 
- Analytics available from the Algolia dashboard by selecting the application DOCSEARCH. Please select the analytics tabs. (Note: Individuals may need to email Algolia to get this access if want analytics...I have it now.)

Add Algolia search bar to Docusaurus

---

packages/react-scripts/config/react-app.d.ts

It's not a syntax babel supports inside .ts files so we better use the supported syntax here 
And it has to use `* as React` because we made `allowSyntheticDefaultImports: true` optional.

Change import syntax from typescript declaration

---

packages/eslint-config-react-app/index.js

The links provided by ESLint regarding code splitting were outdated (they pointed a still existing README file, but without the old content). You can test this by opening the old link (which no longer talks about code splitting) and new link.

Fixing the code splitting links in the ESLint output

---

packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

Don't allow user to use unsupported options
x-ref: #5585

Remove unsupported options

---

packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

Fix #5613
Sound's like another typescript bug. Opened https://github.com/Microsoft/TypeScript/issues/28202

Ignore json files from TypeScript type checking

---

docusaurus/docs/adding-typescript.md

For users coming from create-react-app-typescript, the added link provides instructions on how to port their app to Create React App.
@Timer suggested I create a PR to add this link. Not sure if this is the best place; let me know if there's a better place for links like this :)

Add link to cra-ts migration guide

---

packages/react-scripts/lib/react-app.d.ts
packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

Fix Error:
```
TS2374: Duplicate string index signature.
```

fix 'Duplicate string index signature' in ProcessEnv

---

packages/react-scripts/template-typescript/src/serviceWorker.ts

close #5650
See issue for steps to reproduce

Make serviceWorker config argument optional in typescript

---

packages/babel-preset-react-app/create.js
packages/babel-preset-react-app/package.json
test/fixtures/typescript/src/App.ts
test/fixtures/typescript/tsconfig.json

Add support for decorators

---

packages/react-error-overlay/src/index.js
packages/react-error-overlay/src/listenToRuntimeErrors.js

Enables calling `reportRuntimeError` to display a full stack trace.
* factor out crashWithFrames 
* expose reportRuntimeError
closes #4705 
My Usage:
```js
{
onError: e => reportRuntimeError(e)
}
```
Result:

Expose `reportRuntimeError`

---

docusaurus/docs/using-the-public-folder.md

This PR fixes the broken link on the "Using the Public Folder" page.

Fix public folder documentation link

---

docusaurus/docs/deployment.md

Firebase link was targeting Firebase JS SDK which is not correct for this part of the documentation. This section of the documentation is trying to outline various deployment methods, Firebase JS SDK has nothing to do with deployment. Instead, the link should be pointing to Firebase Hosting Docs.
Same as https://github.com/facebook/create-react-app/pull/5348, except with the correct file modification.

Updated the link to firebase hosting

---

README.md

[Webpack Encore](https://symfony.com/doc/current/frontend.html) is the official tool to integrate React with the Symfony framework when not building a SPA.
Note: when building a SPA, using [API Platform](https://api-platform.com), which [includes Create React App](https://api-platform.com/docs/client-generator/react), is suggested.

Suggest Encore when not building a SPA with Symfony

---

docusaurus/docs/developing-components-in-isolation.md

Executing `getstorybook` works, but emits the warning:
```shell
WARNING: getstorybook is deprecated.
The official command to install Storybook from now on is:
sb init 
```
Change `getstorybook` to `sb init`. Works the same way. No warning.

docs: Change story book command to `sb init`

---

docusaurus/docs/developing-components-in-isolation.md

Reduce the two-step install process to just one (per the latest storybook docs)
Change (i) `npm install -g @storybook/cli` and (ii) `sb init` to `npx -p @storybook/cli sb init`
| Old commands                        | New command                     |
| ----------------------------------- | ------------------------------- |
| (i) `npm install -g @storybook/cli` | `npx -p @storybook/cli sb init` |
| (ii) `sb init`                      |                                 |
Refs: https://storybook.js.org/basics/quick-start-guide/

docs: Simplify installing Storybook with npx

---

packages/react-app-polyfill/README.md

Just added the README blurb that was mentioned in #5795

extra polyfills must be included manually, fixes #5795

---

packages/babel-preset-react-app/create.js

Please see the discussion in #5452

Add allowESModules option to babel-preset-react-app

---

packages/react-error-overlay/package.json

This allows us to leave the import in the code, and webpack will still tree shake it out.
Verified by grepping for `startReportingRuntimeErrors` in the resulting bundle.
Note that this is usage outside of `react-dev-utils`.
Without this change, I need to use `require` and not `import`, and stick my `require` inside of an environment check.
Docs: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

fix: add `sideEffects: false` to react-error-overlay

---

packages/babel-preset-react-app/create.js
test/fixtures/typescript/src/App.test.ts
test/fixtures/typescript/src/App.ts

Closes #5741.
`@babel/plugin-transform-flow-strip-types` was clashing with `@babel/plugin-proposal-decorators`, which was breaking TypeScript decorator support.
/cc @metawave

Fix TypeScript decorator support

---

.travis.yml

This PR adds `node` since Node.js `11` has been released.
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.0.0
> Specifying Node.js versions #
> The easiest way to specify Node.js versions is to use one or more of the latest releases in your .travis.yml:
> 
> node latest stable Node.js release
> iojs latest stable io.js release
> lts/* latest LTS Node.js release
>

Add the latest stable node version

---

packages/react-dev-utils/typescriptFormatter.js

I use the formatter in an ejected project, and got errors after updating to the latest version of `fork-ts-checker-webpack-plugin`. The changes in this PR should make it compatible with both 0.4.x and 0.5.0.
See https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/182
I've tested by building my project using the formatter with both 0.4.15 and 0.5.0

fix: make typescriptformatter support 0.5 of fork checker

---

docusaurus/docs/getting-started.md

This commit fixes the link to read more about running tests, which previously linked to the source of a different page in Github with a non-existent anchor rather than to the published docs.

Fix link to page about running tests

---

README.md

1- For `Here's a `: The singular verb form ’s does not seem to agree with the plural subject a few common cases where you might want to try something else. Consider changing the verb form.
2- Added `A` before Reasonably : The noun phrase Reasonably good configuration seems to be missing a determiner before it. Consider adding an article. An article (a, an, or the) is a type of determiner. Possessive adjectives (my, his, our), possessive nouns (Joe’s, mother’s), and quantifiers (each, every) are also determiners. Single countable nouns usually require a determiner.

Some Grammar fixes

---

package.json
packages/react-scripts/fixtures/kitchensink/public/index.html
packages/react-scripts/template-typescript/public/index.html
packages/react-scripts/template/public/index.html
test/fixtures/__shared__/template/public/index.html

Prettier now supports HTML, Added html to `lint-statged`.
updated prettier to v1.15.2

Run prettier on HTML files

---

packages/create-react-app/createReactApp.js

Fixes an issue where npx create-react-app --info throws an exception on Windows. The exception was caused by envinfo's copy to clipboard functionality; envinfo is distributed pre-bundled, but the dependency it uses for copying to the clipboard makes use of a binary on Windows that can't be found once the bundle is made. Disabling copy to clipboard fixes the issue. Closes #5757.
Verified by running create-react-app --info, everything works just fine.

Disable copy to clipboard in cra --info

---

packages/react-scripts/template/README.md

We have four bit.ly links in our template that point to the old README. We can't change these links so this adds placeholders to the README that refer user's to the correct location in the new docs.

Add placeholders to template README for bit.ly links.

---

README.md

The link in the README links to https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app which no longer has any references to PWAs. However, this info is now available on the docusaurus site: https://facebook.github.io/create-react-app/docs/making-a-progressive-web-app

Update README.md with updated link about PWAs

---

docusaurus/docs/adding-a-sass-stylesheet.md

The docs currently indicate that to enabling sass/scss support alongside flow can be done by adding the following to your `.flowconfig`.
> [options]
> module.file_ext=.sass
> module.file_ext=.scss
Making that change is insufficient because defining values for `module.file_ext` overwrite the default values, and will prevent flow from reading from `.js` files, which prevents flow from functioning as expected.
You also need to add the following values, in order to prevent overwriting the defaults.
> module.file_ext=.js
> module.file_ext=.jsx
> module.file_ext=.mjs
> module.file_ext=.json
I would be open documenting this in another way that is less verbose, but I think that there should be some indication that adding those values will overwrite the defaults.

Add default values to `file_ext` note

---

packages/react-dev-utils/WebpackDevServerUtils.js

Corrected some comments and removed some outdated info from 1.x

Correct some comments

---

packages/react-scripts/scripts/eject.js

Add pre-eject message about new features in v2

---

packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

Advanced users can opt into this behavior, but it's generally outside the users' control to fix and comes with performance concerns

Suggest a different default for speed reasons

---

docusaurus/docs/adding-a-sass-stylesheet.md

A bunch of issues popped up with people asking how to have SASS/SCSS imports the way the would expect normally.
Turns out `node-sass` supports the SASS_PATH variable that we can use. This PR adds that to the documentation.

Add SASS_PATH instructions to Sass stylesheet docs

---

docusaurus/docs/running-tests.md

On a project running [redux-persist](https://github.com/rt2zz/redux-persist), declaring the current `localStorage` mock would yield warnings in tests, making them harder to visually grep:
Redux Persists checks for three methods to detect if `localStorage` is defined: `getItem`, `setItem` and `removeItem` ([see relevant code](https://github.com/rt2zz/redux-persist/blob/208c6b112ead87b3701dfacaae2cdbe78377775a/src/integration/getStoredStateMigrateV4.js#L31-L43)).
I suggest adding a `removeItem` mock to the docs as it fixes the warnings in tests.

Docs: update localStorage mock in “Running Tests”

---

packages/react-scripts/scripts/utils/verifyPackageTree.js

Just a small update to the wording of one of the error messages.

Improve advice in verifyPackageTree.js

---

docusaurus/docs/setting-up-your-editor.md
packages/eslint-config-react-app/README.md

References to .eslintrc now have extension (using it without extension is [deprecated](https://eslint.org/docs/user-guide/configuring#configuration-file-formats))

Updated docs re: .eslintrc

---

docusaurus/docs/adding-typescript.md

An improved version of pr #5766

Add example command to create typed project

---

packages/react-scripts/lib/react-app.d.ts

webp file support was added in #458 but the typescript declaration for webp was missing. 
webp images couldn't be used with typescript. 
This pull request fixes this by adding a webp typescript declaration.

add webp support for typescript

---

docusaurus/docs/proxying-api-requests-in-development.md

Correct markdown to avoid comment

---

docusaurus/docs/post-processing-css.md

"on" value of "autoprefixer grid" is kinda deprecated. It's better to use "autoplace" or "no-autoplace" instead.
https://github.com/postcss/autoprefixer#options
"autoplace" enables PostCss' autoplace polyfill for ie and makes prefixes, "no-autoplace" only makes prefixes
https://github.com/postcss/autoprefixer#does-autoprefixer-polyfill-grid-layout-for-ie

Fix control comment of CSS Grid prefixing

---

docusaurus/docs/setting-up-your-editor.md

My first, naive approach was just to remove that section. If we should rather modify it or leave it for older versions, let me know!
closes: #6083

Remove outdated docs for setting up eslint in editor

---

docusaurus/docs/adding-bootstrap.md

Picking a particular react bootstrap library feels like too strong of an opinion for supplementary  CRA docs. I trimmed it down to point out the two most popular options and remove library specific documentation to focus on the bits that are more CRA specific, e.g. using sass files.

Generalize the adding bootstrap documentation

---

docusaurus/docs/setting-up-your-editor.md

Replace deprecated ${workspaceRoot} variable with ${workspaceFolder} in VSCode launch.json. See https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented

Replace deprecated VSCode launch.json variable

---

packages/eslint-config-react-app/index.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json

Closes #6115.
We are able to use [`detect`](https://github.com/yannickcr/eslint-plugin-react/pull/1978) instead of the obscure `999.999.999` value for the react version of the eslint-loader config after bumping `eslint-plugin-react`.

Bump eslint-plugin-react version and update webpack config

---

packages/react-scripts/config/webpack.config.js

Follow up for #4930.
This enables `eval-source-map` for firefox browsers, which makes it possible to see mapped scopes and variables. Hopefully in a couple of months chrome will also support `eval-source-map` and we can drop the check.

Enable eval-source-map for firefox

---

packages/react-dev-utils/package.json

v8.0.2 was recently released https://github.com/sindresorhus/globby/releases to fix some pathing issues with dir-glob when v2.2.0 was published to npm this morning (https://www.npmjs.com/package/dir-glob).
Forcing to the new version locally fixes the current issues we're having with other packages not using the latest version, but it would be nice to get CRA on the same version as well.

Update react-dev-util globby dependency to v8.0.2

---

test/fixtures/relative-paths/package.json

We were missing dependencies in the `relative-paths` test fixture that yarn PnP decided to start complaining about. I imagine they must have fixed a bug that started catching our bug 😛.

Fix CI builds

---

tasks/local-test.sh

The `e2e:docker` command can run tests in a Docker container, but it always returns exit code 0 even if the tests failed. This PR resolves that and returns the exit code from the test command.

Update local-test.sh to return test exit code

---

packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
test/fixtures/issue-5947-not-typescript/index.test.js
test/fixtures/issue-5947-not-typescript/package.json

See #5947.
`verifyNoTypeScript` checks whether there are any TypeScript files in the project during the build, and this PR refines that logic by adding a [Globby](https://www.npmjs.com/package/globby) negation filter so that any `node_modules` under `./src` is excluded from this logic.
Considering that `verifyNoTypeScript` has only existed since CRA 2.1 it seems _very_ unlikely that anyone would depend on checking in a `node_modules` for TypeScript support, so this is a safe change.
Steps to reproduce this bug and to show that this PR fixes it:
1. symlink `./src/anything` to a directory outside the CRA project directory called `anything`.
2. `npm init` the `anything` with its own `package.json` that depends on `big-integer`. `big-integer` is distributed on NPM with TypeScript files which …

TypeScript detection filtering 'node_modules'.

---

docusaurus/docs/deployment.md

**Action taken:** 
Update to Documentation. Removed the the step for switching to 'gh-pages' branch as it is no longer a viable option.
**Reason:**
As per stated on GitHub, Pages for User and Organisation could only be published from 'master' branch. The option to switch to another branch is no longer a viable option.
**Extract from GitHub:**
"_If your site is a User or Organization Page that has a repository named <username>.github.io or <orgname>.github.io , you cannot publish your site's source files from different locations. User and Organization Pages that have this type of repository name are only published from the master branch._"
**GitHub reference:** 
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/
**Note:**
In the case of a user's page, users …

Changes to steps for publishing GitHub User Page

---

docusaurus/docs/updating-to-new-releases.md

I opened https://github.com/facebook/create-react-app/issues/6140 a few days ago, after experiencing two bugs which were a result of CRA global install. #6157 solves half of the problem, but programmers who already installed CRA globally, are even more likely to check "updating-to-new-releases.md".
I think part of the current version of "updating-to-new-releases.md" is a bit outdated.

Updating updating-to-new-releases.md for users who installed CRA globally

---

docusaurus/docs/deployment.md

Hi everyone! Thank for this awesome project! I enjoy this a lot and use it in my react projects! 
So, I needed to run front-end with `serve` library with my costume port, I made some reserch about all flags and docs about `serve` and noticed that frags which are on the CRA website are still working, but they are deprecated and `serve` lib recommends to use flag `-l` instead of `-p`, this discussion is in https://github.com/zeit/serve/issues/382 issue, and also you can see this in `serve` code: 
https://github.com/zeit/serve/blob/85d121e5008783395cc607089f23a5039547f952/bin/serve.js#L258
This pull request updates `serve` ports and adds example of using costume ports with `serve` lib

Update `serve` port flag and add example

---

packages/react-scripts/scripts/test.js

This is a one-line pull request for https://github.com/facebook/create-react-app/issues/6284. This allows  `react-scripts test --watch=false` to allow react-scripts to run jest without watch mode.
I tested this out by `npm link`ing my local fork to a project created with `create-react-app`.
I ran the command `npm t -- --watch=false` and jest closed right after everything was ran!
See the gif, when `--watch=false` is added, it no longer adds the `--watch`:

Allow react-scripts test --no-watch

---

packages/react-scripts/config/webpack.config.js

DNS is required by some popular node.js modules; presently a require statement for DNS will throw an error if it is not wrapped in a try catch block.
Closes #6277.

Add Node DNS module to empty mocks

---

tasks/cra.js

When running "yarn create-react-app my-app" to test local scripts changes in a CRA-fork it will fail with "You have provided more than one argument for <project-directory>". This fixes the bug by moving the project dir to the front.

fix local yarn create-react-app for local testing before publish

---

packages/react-scripts/template-typescript/public/index.html
packages/react-scripts/template/public/index.html

The template includes a comment describing the purpose of the manifest.json file. It specifically refers to add-to-home-screen functionality on Android. There's now much better cross platform support for Web App Manifests, so I thought it'd be better to make the description more generic. The language was pulled directly from the [first sentence of Google's documentation](https://developers.google.com/web/fundamentals/web-app-manifest/).

Make manifest.json description more generic

---

docusaurus/docs/deployment.md

This pull request modifies the ZEIT Now deployment instructions for Create React app to be more straight forward and to offer a guide from ZEIT directly for more in-depth instructions for deploying with more control. 
Thanks!

Update ZEIT Now deployment instructions

---

packages/react-scripts/lib/react-app.d.ts

Interface members should be [terminated with semicolons](https://www.typescriptlang.org/docs/handbook/interfaces.html). I've made this change to be consistent with other interfaces in the `create-react-app` project and also to fulfil a widely used TSLint rule [`semicolon`](https://palantir.github.io/tslint/rules/semicolon/).

Use semicolons in the ProcessEnv interface

---

packages/babel-preset-react-app/package.json

As part of the latest babel-plugin-macros [2.4.5 release](https://github.com/kentcdodds/babel-plugin-macros/releases/tag/v2.4.5), there was a small fix that went in that fixes a [bug](https://github.com/kentcdodds/babel-plugin-macros/pull/100) specifying the `babelMacros` entry in `package.json` no longer working. This patch version increase should remedy the issue and allow specifying babel macro configuration in the `package.json` file again (as stated in the [user docs](https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/user.md#config-experimental) of babel-plugin-macros)

Update babel-plugin-macros 2.4.4 -> 2.4.5

---

docusaurus/docs/adding-custom-environment-variables.md

[docs] Warn/clarify that env vars are NOT "SECRET"

---

CONTRIBUTING.md

Hi, this PR provide more information about how to modify the custom registry configuration to running E2E test. 
Refers to: #4488

Add information for usage custom registries on e2e testing #4488

---

packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

Allow for the ability to use `.d.ts` files without buying into typescript setup
Closes #6405

Allow for the ability to use `.d.ts` files without buying into typescript setup

---

packages/create-react-app/createReactApp.js

This PR supersedes https://github.com/facebook/create-react-app/pull/5745 and correctly implements @NMinhNguyen's requested changes.

Only use `yarn.lock.cached` if using the default Yarn registry

---

packages/react-dev-utils/ForkTsCheckerWebpackPlugin.js
packages/react-dev-utils/README.md
packages/react-dev-utils/WebpackDevServerUtils.js
packages/react-dev-utils/package.json
packages/react-dev-utils/typescriptFormatter.js
packages/react-dev-utils/webpackHotDevClient.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json
packages/react-scripts/scripts/start.js
test/fixtures/typescript-typecheck/index.test.js
test/fixtures/typescript-typecheck/package.json
test/fixtures/typescript-typecheck/src/App.tsx
test/fixtures/typescript-typecheck/src/index.tsx

Let's try this again shall we? 😛
This is a continuation of the work done in #5903. Ideally this time around we can try to avoid any breaking changes on the `react-dev-utils` side of things if possible.
The initial commit here is simply reverting the revert. We can then work together to improve from here.
/cc @deftomat, @johnnyreilly, @timer

Speed up TypeScript v2

---

.travis.yml

We added this a while ago and it's been causing some issues. It's nice to run our tests on the latest version of Node but it shouldn't be failing our build. This creates a lot of confusion and uncertainty.
We will look into ways to add this back in the future, separate from the main build and test suite.

Remove latest Node version from Travis config

---

packages/react-scripts/config/webpack.config.js

This changes the .js webpack file name values to use `contenthash` instead of `chunkhash` as recommended by the webpack team:
https://github.com/webpack/webpack.js.org/issues/2096
https://webpack.js.org/guides/caching/#output-filenames
This should improve long-term caching for our users by relying only on the contents of the .js file itself instead of the chunk as a whole (.js, .css, etc) to generate the filename.

Use contenthash instead of chunkhash for better long-term caching

---

docusaurus/docs/analyzing-the-bundle-size.md

The current `analyze` script only analises the `/src` code. This change leverages new version of `source-map-explorer` that is able to analyse multiple bundles at once, including the  3rd party dependencies bundle which is in my opinion even more important to analyze.

Analyse also dependencies bundle

---

CHANGELOG-0.x.md
CHANGELOG-1.x.md
CHANGELOG.md
CONTRIBUTING.md
docusaurus/docs/adding-a-sass-stylesheet.md
docusaurus/docs/adding-custom-environment-variables.md
docusaurus/docs/adding-typescript.md
docusaurus/docs/analyzing-the-bundle-size.md
docusaurus/docs/debugging-tests.md
docusaurus/docs/deployment.md
docusaurus/docs/proxying-api-requests-in-development.md
docusaurus/docs/running-tests.md
docusaurus/docs/using-https-in-development.md
docusaurus/website/README.md
packages/babel-preset-react-app/README.md
packages/confusing-browser-globals/README.md
packages/react-app-polyfill/README.md

Went through all code blocks in the markdown files are did the following:
- Added appropriate language on all plain code blocks (starting with plain ```). Added mostly sh, json and yaml.
- Changed a couple of js to json.
- Changed a couple of bash to sh for consistency.

Improved language used in markdown code blocks.

---

packages/babel-preset-react-app/README.md

The enabled by default statement made sense when the developer was supposed to disable flow in order to use ts. Both those statements in there create some confusion about it in my opinion.

removed redundant statements

---

packages/react-dev-utils/printHostingInstructions.js

At deploy instruction, the generate publicUrl link is appended with comma and while clicking the link browser opens it with comma at end in my machine. [Mac pro 2016| Chrome Version 71.0.3578.98]
For e.g: 
To publish it at http://sbimochan.github.io, run:
--
This "http://sbimochan.github.io, " gets into browser.

Fix deployInstruction: Alt+click link appends comma at end

---

packages/react-dev-utils/ForkTsCheckerWebpackPlugin.js
packages/react-dev-utils/README.md
packages/react-dev-utils/WebpackDevServerUtils.js
packages/react-dev-utils/package.json
packages/react-dev-utils/typescriptFormatter.js
packages/react-dev-utils/webpackHotDevClient.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json
packages/react-scripts/scripts/start.js
test/fixtures/typescript-typecheck/index.test.js
test/fixtures/typescript-typecheck/package.json
test/fixtures/typescript-typecheck/src/App.tsx
test/fixtures/typescript-typecheck/src/index.tsx

Reapply "Speed up TypeScript v2 (#6406)"

---

docusaurus/docs/adding-custom-environment-variables.md

An unintended change was merged in #6062

[docs] revert removal of newlines from html

---

packages/react-scripts/package.json

This PR is a simple request to upgrade the version of `webpack-dev-server`, which adds support for the IBM i platform and AIX. 
Currently, the install of `react-scripts` fails because of an old version of `internal-ip` that was not installable on these platforms. `webpack-dev-server` was updated in this PR: https://github.com/webpack/webpack-dev-server/pull/1668 which landed in 3.2.0

Update webpack-dev-server to 3.2.1

---

packages/react-scripts/template-typescript/src/App.tsx
packages/react-scripts/template/src/App.js

change class component to function component

---

packages/react-scripts/config/webpack.config.js

Closes #5619.
This adds back support for type checking of `.json` files. We had to disable previously due to a [bug in TypeScript](https://github.com/Microsoft/TypeScript/issues/28202) which was fixed a while back.
Here is an example:

Allow .json type checking

---

packages/react-scripts/scripts/build.js

compiler is not being reassigned, so we can use a const here.
I have ejected my app a long time ago and changed that to a const back then - it builds flawlessly multiple times a day.

make compiler a const not a let

---

packages/react-scripts/scripts/eject.js
tasks/e2e-simple.sh

#5953 - This adds the scripts & config folder to the git staging area after the app is ejected.

add command to add files to staging after eject

---

docusaurus/docs/adding-typescript.md

It is necessary to uninstall any version that was previously installed for the typescript flag to work when using npx.

Add note about npx caching and link to #6119

---

packages/react-scripts/config/webpack.config.js

Following suit with #2600, this PR adds `http2` as an empty module in webpack configs. ~~I don't see `http` to the list, which suggests that this empty mock should probably be replaced with a browser-side implementation sometime in the future (I can add a TODO if needed).~~
See: https://github.com/grpc/grpc-node/issues/610 (Even though it turns out the module in question seems to not be meant for the client side, I believe the lack of this mock masked the real issue)

Add empty mock for http2

---

docusaurus/docs/supported-browsers-features.md
packages/babel-preset-react-app/create.js
packages/react-dev-utils/browsersHelper.js
packages/react-scripts/package.json

This PR brings back support for configuring the build output based on `browserslist`, as well as supporting [`@babel/polyfill`](https://babeljs.io/docs/en/babel-polyfill) in the entrypoint. This provides a huge improvement to the dev experience as it allows targeting modern browsers in development which makes certain language features like async/await much nicer to debug, while still supporting a broad range of browsers in production.
Including `ie 9` in browserslist:
Modern browsers:
Closes #6198.

Support browserslist in @babel/preset-env

---

docusaurus/docs/setting-up-your-editor.md
packages/eslint-config-react-app/index.js
packages/eslint-config-react-app/package.json
packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json

Closes #5641.
This adds linting support for TypeScript via [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint). With this setup we are able to reuse the vast majority of our current ESLint rules.
TODO:

Add TypeScript linting support

---

packages/eslint-config-react-app/package.json
packages/react-scripts/package.json

Use version 1.x of the plugin.

Unpin eslint-config-react-hooks dependency

---

packages/react-dev-utils/openBrowser.js

Fixes #3113.
As far as I can see, there is no downside to adding `{ wait: false }` to the option args when invoking opn, if someone can think of one then I'm happy to test that path.
Adding `wait : false` adds `cpOpts.stdio = 'ignore';` and `cpOpts.detached = true;` to the `childProcess.spawn` [option object](https://nodejs.org/api/child_process.html#child_process_options_detached). see [the relevant opn code](https://github.com/sindresorhus/opn/blob/master/index.js#L60)
Testing on Ubuntu before the change:
- With no browser open: starting react-scripts/start.js via yarn or npm then terminating the process via `<Ctrl>c` would also terminate the browser session
After:
- With no browser open: starting react-scripts/start.js via yarn or npm then terminating the process via `<Ctrl>c` does not …

Add wait: false to options object for opn

---

packages/eslint-config-react-app/package.json

Sync the `babel-eslint` version between react-scripts (version 3) and eslint-config-react-app 
```
warning "react-scripts > eslint-config-react-app@4.0.0-next.b0cbf2ca" 
has incorrect peer dependency "babel-eslint@9.x".
```

Sync version of babel-eslint in eslint-config-react-app for react-scripts V3

---

packages/react-dev-utils/formatWebpackMessages.js

We don't need eslint comment as we no longer have an unused variable in next line inside `packages/react-dev-utils/formatWebpackMessages.js` in `formatMessage` function as that unused variable was removed in #6502

Remove unused eslint comment

---

packages/react-scripts/template-typescript/public/index.html
packages/react-scripts/template/public/index.html

I was trying to understand the needs for `shrink-to-fit=no` meta data when I saw it in `index.html` file, after some testing myself and googling I came to a conclusion that it's no longer needed.
Removed recently from twbs/bootstrap/pull/28314, h5bp/html5-boilerplate#2102 and https://github.com/joshbuchea/HEAD/commit/851bb661264edbc9a968e2d74c626198523b419a
More info in @scottaohara [blogpost](https://www.scottohara.me/blog/2018/12/11/shrink-to-fit.html)

Remove unnecessary shrink-to-fit=no meta data

---

packages/create-react-app/yarn.lock.cached
packages/react-scripts/package.json
packages/react-scripts/scripts/build.js

#6438 allows source-map-explorer to analyze bundles with multiple files, which was one of the main features that webpack-bundle-analyzer did better.  Now we have less need to have two different ways of analyzing bundle size.

remove webpack-bundle-analyzer

---

packages/react-scripts/template-typescript/src/App.tsx
packages/react-scripts/template/src/App.js

Small update to the default templates to keep them consistent with the React docs.

Change app component declaration from arrow function to regular function

---

docusaurus/website/siteConfig.js

`url` was duplicated in `siteConfig.js`, both were the same value, so stripping one of them.

Remove duplicate url key in siteConfig

---

docusaurus/docs/deployment.md

Added instructions on how to deploy a CRA app with AWS Amplify.

Add deployment instructions with AWS Amplify

---

docusaurus/docs/adding-a-sass-stylesheet.md

- Mentioned a note for windows operating system to use syntax like `SASS_PATH=./node_modules;./src`
https://github.com/facebook/create-react-app/issues/6322

Fix for #6322

---

tasks/e2e-behavior.sh
tasks/e2e-installs.sh
tasks/e2e-kitchensink-eject.sh
tasks/e2e-kitchensink.sh
tasks/e2e-simple.sh

Kill verdaccio in CI tasks cleanup

---

packages/eslint-config-react-app/index.js

The "project" property has a significant performance impact on linting,
and none our rules currently need it.
Fixes #6661.

Remove project property from @typescript-eslint/parser options

---

docusaurus/docs/loading-graphql-files.md
docusaurus/website/i18n/en.json
docusaurus/website/sidebars.json

This PR follows up #3909 and #5076 by adding documentation for the `.graphql` loading features through `babel-plugin-macros`.
Signed-off-by: petetnt <pete.a.nykanen@gmail.com>

Document .graphql and .gql file loading with graphql.macro

---

docusaurus/docs/available-scripts.md

add the reason for adding packages as dependencies

Add explanation for adding everything as dependencies to docs

---

tasks/e2e-installs.sh

This is a temporary fix to get our test suites passing so we can finish work on the 3.0 release. We still need to find and fix the root cause of this issue: #6679. This workaround should be removed once that's fixed.

Add temporary workaround for Babel dependency issues in installs test suite

---

packages/react-scripts/config/webpack.config.js

This is an optimization that will be enabled by default in webpack 5. We can opt into it now.

Enable futureEmitAssets in webpack config

---

packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

Otherwise I get i.e. such output;
```
Could not parse tsconfig.json. Please make sure it contains syntactically correct JSON.
Details: tsconfig.json(19,12): error TS1328: Property value can only be string literal, numeric literal, 'true', 'false', 'null', object literal or array literal.
```
Which is misleading - especially taking into account that info about incorrect JSON is written in bold

Suggests that tsconfig.json is incorrect only when SyntaxError is caught

---

packages/create-react-app/createReactApp.js

Just a minor oversight I think

Fix unlogged yarn pnp message

---

packages/react-scripts/lib/react-app.d.ts

```js
/**
* @deprecated as of recent React versions, function components can no
* longer be considered 'stateless'.
```

Replace deprecated SFC with FunctionComponent in react-app.d.ts

---

tasks/e2e-kitchensink-eject.sh

This is (another) temporary fix to get our test suites passing so we can finish work on the 3.0 release. We still need to find and fix the root cause of this issue: #6679. This workaround should be removed once that's fixed.

Add temporary workaround for Babel dependency issues in kitchensink-eject test suite

---

packages/react-scripts/package.json

**DESCRIPTION:**
- Resolves #6659: Updated the `workbox-webpack-plugin` from v3 to latest v4 and also tested some of the new configuration options such as `skipWaiting` and `cleanupOutdatedCaches` after ejecting the app.
- Resolves #6243: The new version automatically solves the issue where a registered service worker still tries to load an old resource, after workbox has cleaned up its old cache after an update.
**TESTS COMPLETED:**
- Change the app code to `serviceWorker.register()` and run `build`, then check if workbox caches the relevant files and if the service worker installs correctly and triggers the `onSuccess` callback.
- Add flag `skipWaiting: true` to the `webpack.config.js`, then update the app code and perhaps also the version number in `package.json`, then repeat the test …

Update to workbox-webpack-plugin v4

---

packages/react-dev-utils/package.json

Update fork-ts-checker-webpack-plugin out of alpha

---

packages/react-scripts/lib/react-app.d.ts

after change it 
```ts
process.env.NODE_ENV = 'development'
```
will throw
```
Cannot assign to 'NODE_ENV' because it is a read-only property.ts(2540)
```

change NODE_ENV and PUBLIC_URL into readonly

---

docusaurus/docs/deployment.md

Add Render deployment section

---

packages/create-react-app/createReactApp.js
packages/create-react-app/package.json

Closes #6598.
We now warn when using the `--scripts-version=react-scripts-ts` option in the CLI.

Warn when using react-scripts-ts

---

packages/babel-preset-react-app/package.json

As far as I can tell there's no reason for the webpack `babel-loader` to be a dependency of `babel-preset-react-app`. If you happen to use `babel-preset-react-app` without Webpack you get a warning like
```
warning "babel-preset-react-app > babel-loader@8.0.5" has unmet peer dependency "webpack@>=2".
```
There was another PR #6124 but it wasn't merged for some reason.

Remove unused babel-loader from babel-preset-react-app

---

docusaurus/docs/adding-images-fonts-and-files.md

Hello!
It seems like importing SVGs as components does not work with `react` versions before 16, even with up-to-date `react-scripts`. Thought this documentation should be updated to include that note.
Thanks!
**react@^15.6.2** and **react-scripts@2.1.8**
```js
import Logo from './logo.svg'
console.log(Logo) // output: /static/media/logo.5d5d9eef.svg
```

Add SVG support dependency note

---

docusaurus/docs/production-build.md

I took a stab at clarifying the vendor output wording/file names.
Closes #6698.

Clarify production build output files documentation

---

docusaurus/docs/supported-browsers-features.md
packages/babel-preset-react-app/create.js
packages/react-app-polyfill/README.md
packages/react-app-polyfill/ie11.js
packages/react-app-polyfill/ie9.js
packages/react-app-polyfill/package.json
packages/react-app-polyfill/stable.js

This is a breaking change to our 3.0 alpha that deprecates the `@babel/polyfill` feature in favor of the [recommended approach from the babel team](https://babeljs.io/blog/2019/03/19/7.4.0#core-js-3-7646-https-githubcom-babel-babel-pull-7646) as part of the babel 7.4.0 release. This adds a new `react-app-polyfill/stable` module that can be imported from `src/index.js` which will include polyfills for stable language features, and integrates nicely with `@babel/preset-env` which uses `browserslist` to only include polyfills for the target browsers.
Some more relevant info on this change: https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babel
**Outstanding questions:**
- In the [corejs@2 migration …

Update to core-js@3

---

packages/react-dev-utils/InlineChunkHtmlPlugin.js

The `InlineChunkHtmlPlugin` plugin didn't work when the `publicPath` variable is empty or unset (e.g. when I want to use relative URLs).
Before:
- If `publicPath` was unset or wasn't a string, webpack would throw an error
- If `publicPath` was an empty string, the plugin would fail to inline a chunk
Now: the plugin behaves as expected even with empty or unset `publicPath`.

InlineChunkHtmlPlugin works with empty publicPath

---

packages/react-scripts/config/webpack.config.js

Fixes #6579.
Discussion of issue and repro steps in linked issue.

Fix react-scripts peer-deps link local issue

---

packages/react-scripts/config/webpack.config.js

Initial work on improving asset manifest. This moves the current output of all files under a `files` key. This is a breaking change so we want to do this as part of 3.0. This will allow us to add additional information to the manifest under other top-level keys in the future. See #5513.

Add custom function to generate asset manifest

---

packages/react-scripts/scripts/utils/createJestConfig.js

For people who try to use Jest 24, there is a different version of `micromatch` and it behaves differently.  These changes should make it behave the same before and after changing Jest versions.
Without this change, Jest 24 will come up with no files to test.
I tested with `npm run test -- --listTests` on two projects, one with the default Jest 23 and another with the new Jest 24.  In addition to numerous normally named test files had some special case files like `src/.test.js`, `src/test.js`, and `src/somethingtest.js`.  Only the first two matched and the third one didn't; both pre-, and post- this change.

Update testMatch to also be compatible with Jest 24

---

packages/babel-plugin-named-asset-import/package.json
packages/babel-preset-react-app/package.json
packages/confusing-browser-globals/package.json
packages/create-react-app/package.json
packages/eslint-config-react-app/package.json
packages/react-app-polyfill/package.json
packages/react-dev-utils/package.json
packages/react-error-overlay/package.json
packages/react-scripts/package.json

Specifying the directory as part of the repository field in a
package.json allows third party tools to provide better support when
working with monorepos. For example, it allows them to correctly
construct a commit diff for a specific package.
This format was accepted by npm in [npm/rfcs#19](https://github.com/npm/rfcs/pull/19).

Add directory details to packages/* package.json

---

CONTRIBUTING.md
package.json
tasks/publish.sh

Upgrade from Lerna v2 to v3. Let's see what this breaks... 🎲

Upgrade to Lerna v3

---

packages/babel-plugin-named-asset-import/package.json
packages/babel-preset-react-app/package.json
packages/confusing-browser-globals/package.json
packages/create-react-app/package.json
packages/eslint-config-react-app/package.json
packages/react-app-polyfill/package.json
packages/react-dev-utils/package.json
packages/react-error-overlay/package.json
packages/react-scripts/package.json
packages/react-scripts/scripts/utils/verifyPackageTree.js

Relax ESLint version range

---

packages/react-scripts/scripts/eject.js

Change CRA version in `react-scripts` eject warning.

---

docusaurus/docs/debugging-tests.md
docusaurus/docs/running-tests.md
packages/react-scripts/scripts/test.js

`yarn test --watchAll=false` or `npm test -- --watchAll=false` is already sufficient for running tests in non-watch mode.   Both does the same thing as the current --no-watch flag.

Remove no-watch flag in favor of watchAll=false

---

docusaurus/docs/importing-a-component.md

Closes #6765.
/cc @rovansteen, @iansu, @mrmckeb

Add baseUrl documentation

---

packages/eslint-config-react-app/index.js

Fix no-useless-constructor rule in TypeScript

---

packages/react-scripts/template-typescript/src/index.css
packages/react-scripts/template/src/index.css

AFAIK reseting padding is useless since there is no padding on body in browser default styles 
https://www.w3schools.com/cssref/css_default_values.asp

Remove body padding reset from templates

---

docusaurus/docs/deployment.md

Fix typo in deployment docs

---

docusaurus/website/static/css/custom.css

Added a slight scale up on the get started button upon hover.

Call to action button now "reacts" to being hovered :)

---

packages/babel-preset-react-app/dependencies.js

Update dependencies preset in babel-preset-react-app to align it with recent changes made to the normal preset:
* Browserlist support (#6608, #6769)
* Loose mode array destructuring (#5997)

Update dependencies babel preset with recent changes

---

packages/react-scripts/config/webpack.config.js

:wave: Hello! I'm reading through react-scripts' Webpack configuration to learn a little bit more about Webpack. Thanks for the ample comments! It's super helpful.
I noticed this unneeded `Object.assign` in a `.css` loader's options, so thought I'd remove it.
* **Problem:** Using `Object.assign` in `shouldUseRelativeAssetPaths` falsey case adds a _lil bit_ of an unneeded function call
* **Solution:** Remove `Object.assign` and add `{}` to the ternary false expression
* **Testing:** _?_

Remove `Object.assign` from `MiniCssExtractPlugin` options

---

packages/react-app-polyfill/README.md

A few corrections on the graphql docs, because it doesn't work without installing the graphql package, and you need to provide real graphql in the .graphql file, not gql wrapped graphql.

Update GraphQL doc

---

docusaurus/docs/adding-typescript.md

Added block quote with warning about issues when CRA is installed globally.
Related to: #6816 & https://github.com/facebook/create-react-app/pull/6911
Updating blockquote to advise on use of CRA globally vs. npx when using --typescript flag.

Add clarifying note to TypeScript docs warning about global install of CRA

---

packages/react-dev-utils/package.json
packages/react-scripts/config/pnpTs.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json

The `fork-ts-checker-webpack-plugin` package [just released](https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/250) an update that allows to specify custom resolution schemes. This makes it possible for Create-React-App to have native PnP support even when using TypeScript.
I've tested this diff locally and it seemed to work.

Adds the configuration for PnP/Typescript

---

packages/eslint-config-react-app/index.js
packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

Fixes #6906.
I've created #6936 as a follow up for v4 to suggest the `noFallthroughCasesInSwitch` option in `tsconfig.json`.

Disable default-case lint rule for TypeScript

---

packages/react-error-overlay/package.json
packages/react-scripts/package.json

Ref: #6756.
Temporary fix to bump `babel-jest` to fix preflight check error that was a result of a new version of Jest being released. Still need to address the bigger issue as part of #6756.

Temporary fix for babel-jest preflight error

---

packages/eslint-config-react-app/index.js

Disable no-dupe-class-members rule for TypeScript

---

packages/react-error-overlay/package.json
packages/react-scripts/package.json

Ref: #6756.
We decided to unpin `babel-jest` to avoid future issues when new versions of `jest` and related packages are released.

Unpin babel-jest

---

packages/react-scripts/scripts/utils/createJestConfig.js

This PR fixes what I believe to be a very necessary fix for Jest configuration. https://github.com/facebook/create-react-app/issues/6042
What it does
- It adds 3 new keys to the allowedOverrides config
- It gracefully extends any jest config option that is an object while leaving arrays and primitive types to override
- Gracefully extending the objects made the most sense because it allows the original pieces to keep working as expected while give you the ability to fix things that would render the test framework useless for a project
We need to be able to update these keys for the following reasons
- **moduleNameMapper**: I've worked on many many jobs and projects and have yet to find one that didn't take advantage of aliasing in someway. If a project is using aliasing (despite CRAs …

Support for graceful extension of Jest config

---

docusaurus/docs/adding-relay.md

The babel macros came out in [Relay 1.7.0](https://github.com/facebook/relay/releases/tag/v1.7.0) - it's now at 4.0, so `@dev` shouldn't be needed anymore 👍

Updates the relay docs

---

docusaurus/docs/supported-browsers-features.md

I redid the spelling fix in https://github.com/facebook/create-react-app/pull/6935, which had to be reverted in https://github.com/facebook/create-react-app/pull/7016 because the CLA wasn't signed.
Thanks again @wbr2y for the original PR!

Correct spelling of browserslist

---

packages/eslint-config-react-app/index.js

The new ESLint TS rules are a little cumbersome for typedefs. We have 100s of places where we do things like the following as we like to have our types declared at the top of our files.
```ts
export type AppProps = ReturnType<typeof mapStateToProps> & typeof mapDispatchToProps;
export const mapStateToProps = (state: RootState) => ({  initialized: state.initialized });
export const mapDispatchToProps = { initialize };
```
Making the changes here in local eslint-config-react-app/index.js fixes the warnings for TS(X) files.

Adjust typescript-eslint to not warn about typedefs when used before defined

---

packages/react-dev-utils/openBrowser.js
packages/react-dev-utils/package.json

The [opn](https://npmjs.com/package/opn) package is deprecated and no longer maintained. Replaced it with [open](https://npmjs.com/package/open) to which the original package was renamed to.

fix: Replaced opn (deprecated) with open

---

CHANGELOG.md

I'm moving #6821 from enhancements to breaking changes as this causes any existing script that relies on the structure of `assest-manifest` to break.

Improve breaking changes info for CRA 3.0.0

---

packages/react-scripts/package.json

Fixes the following warning when installing:
> warning react-scripts > fsevents@2.0.6: Please update: there are crash fixes
Change applied: fsevents/fsevents#279

Update fsevents dependency version

---

docusaurus/docs/running-tests.md

Installing the latest react-testing-library will cause issues because it is now deprecated and will throw `react-testing-library has moved to @testing-library/react` when imported. [more info](https://github.com/testing-library/dom-testing-library/issues/260). This updates the document to use the new scoped package.

Update deprecated package reference

---

packages/eslint-config-react-app/index.js

This PR resolves #7167 by disabling the no-undef rule for typescript-eslint. As pointed out in https://github.com/typescript-eslint/typescript-eslint/issues/477, no-undef is handled by the Typescript compiler.
I have verified that errors are thrown by taking the example in the above issue and mangling the name of the namespace to "connect0" and verifying that compiler errors are thrown:
```
Failed to compile.
/Users/andyhopp/Projects/connect-react-example/src/connect-service.ts
TypeScript error in /Users/andyhopp/Projects/connect-react-example/src/connect-service.ts(6,9):
Cannot find name 'connect0'. Did you mean 'Connect'?  TS2552
4 | 
5 |     public initialize(ccpElement: HTMLElement, options: connect.InitCCPOptions) {
> 6 |         connect0.core.initCCP(ccpElement, options);
| …
```

Disabled Typescript no-undef rule per typescript-eslint #477

---

packages/babel-preset-react-app/dependencies.js

The `babel-plugin-transform-dynamic-import` package is not specified in babel-preset-react-app's `package.json`. It appears that it was switched out with `babel-plugin-dynamic-import-node` in `create.js` here:
https://github.com/facebook/create-react-app/commit/52fcb23b0d3b80a3d79e3863a27372e83dded1e7
This commit updates it in `dependencies.js` too.
I ran into this while working on my [SSR fork](https://github.com/facebook/create-react-app/pull/6747). The build script was failing before this commit, but is works correctly after the switch.

Use correct babel transform for dynamic import in dependencies

---

packages/eslint-config-react-app/index.js

Attempts to fix #7218 
Array format for [`overrides` key](https://github.com/facebook/create-react-app/blob/f522a0dae2/packages/eslint-config-react-app/index.js#L55) in eslint config file is now enforced to be an array in ESLint v6. Anyone who uses `eslint-config-react-app` and ESLint v6 gets a type mismatch error:
```
Error: ESLint configuration in .eslintrc.js » eslint-config-react-app is invalid:
- Property "overrides" is the wrong type (expected array but got `{"files":["**/*.ts","**/*.tsx"],"parser":"@typescript-eslint/parser","parserOptions":{"ecmaVersion":2018,"sourceType":"module","ecmaFeatures":{"jsx":true},"warnOnUnsupportedTypeScriptVersion":true},"plugins":["@typescript-eslint"],"rules":{"default-case":"off","no-dupe-class-members":"off","@typescript-eslint/no-angle-bracket-typ …
```

fix: eslintrc overrides key should be an array, not object

---

docusaurus/docs/adding-relay.md

replace in the documentation
``` yarn upgrade babel-plugin-relay@dev ```
by
``` yarn add babel-plugin-relay@dev ```
because its more meaningful that we are installing the package than upgrade it

Docs: replace the command line to install relay/macro

---

packages/eslint-config-react-app/README.md

I update the installation command to match peerDependencies in package.json
```json
"peerDependencies": {
"@typescript-eslint/eslint-plugin": "1.x",
"@typescript-eslint/parser": "1.x",
"babel-eslint": "10.x",
"eslint": "5.x",
"eslint-plugin-flowtype": "2.x",
"eslint-plugin-import": "2.x",
"eslint-plugin-jsx-a11y": "6.x",
"eslint-plugin-react": "7.x",
"eslint-plugin-react-hooks": "1.x"
},
```

Update peer dependencies

---

packages/react-error-overlay/package.json
packages/react-scripts/fixtures/kitchensink/src/App.js
packages/react-scripts/fixtures/kitchensink/src/features/webpack/DynamicImport.js
packages/react-scripts/fixtures/kitchensink/src/features/webpack/DynamicImport.test.js
packages/react-scripts/package.json

Upgrade webpack to 4.35.0 to fix dynamic import issue

---

packages/react-scripts/scripts/eject.js

closes #7288
During `eject.js`, check if `ownPackage` has `optionalDependencies` before accessing the object.
monkey patched within https://github.com/bmuenzenmeyer/test-app
```
$ npm run eject
> test-app@0.1.0 eject C:\src\tmp\test-app
> react-scripts eject
NOTE: Create React App 2+ supports TypeScript, Sass, CSS Modules and more without ejecting: https://reactjs.org/blog/2018/10/01/create-react-app-v2.html
? Are you sure you want to eject? This action is permanent. Yes
Ejecting...
Copying files into C:\src\tmp\test-app
Adding \config\env.js to the project
Adding \config\modules.js to the project
Adding \config\paths.js to the project
Adding \config\pnpTs.js to the project
Adding \config\webpack.config.js to the project
Adding \config\webpackDevServer.config.js to the project
Adding …
```

fix(eject): guard against empty key before access

---

docusaurus/docs/adding-images-fonts-and-files.md

With https://github.com/facebook/create-react-app/pull/7118 being merged, we can now pass a title prop to the SVG ReactComponent to make
our SVG component easily accessible. So we should add it to docs

docs(svg): add tip for title props accessibility

---

packages/eslint-config-react-app/index.js

jsx-no-duplicate-props ignore case fix

---

tasks/local-registry.sh

Does CI run tests right from the source? Let's find out!

Attempt at fixing CI issue on windows

---

packages/react-scripts/package.json

This closes #7359 by making IMAGE_INLINE_SIZE_LIMIT=0 actually disable image inlining.
We use url-loader's `limit` option to set the line at which images will be inlined, and we basically expose this option to our end users via the IMAGE_INLINE_SIZE_LIMIT environment variable. Most people using it want to disable inlining images all together (the major motivator for adding it at all was I think for strict CSP), and our documentation said setting the value to zero would do that. However, it did the opposite: url-loader treated zero as "no limit".
The update to 2.x fixes this; zero means nothing gets inlined. The other changes from the version bump shouldn't affect us:
- minimum node version is 8.9.x, we already require 8.10.x
- the limit was "greater than", is now "greater than or equal …

Update url-loader to 2.0.1

---

docusaurus/docs/running-tests.md

Maybe this was changed at some point in TypeScript.

Docs: remove an outdated TypeScript-related note

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/proposal.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

Add a new question issue template that directs users to Spectrum.
I also added a new `needs triage` label to the existing issue templates.

Add question issue template

---

packages/react-scripts/scripts/test.js

Resolves #7180.
All tests are currently exiting with a `0` code, regardless of failures. This causes issues in CI environment and Git hooks.

Add explicit check for --watchAll=false

---

docusaurus/docs/running-tests.md

A minor name change, `jest-dom` has also been moved to @testing-library.

Update testing-library related npm package names in README

---

packages/eslint-config-react-app/README.md

I've updated the docs as per [comment](https://github.com/facebook/create-react-app/pull/7415#pullrequestreview-267810031) from @Timer.
This was missed on #7415.

Update README for ESLint config

---

docusaurus/docs/adding-bootstrap.md

Added a missing dependency and instructions to install to use a custom SCSS for using custom themes. In this case `node-scss` is required. 
Thank you for the opportunity to contribute.

Added dependencies to bootstrap article when using custom SCSS.

---

packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

Transpilation is done by Babel, which ignores the tsconfig, so this setting (or any tsconfig setting) doesn't affect compilation, only type checking.
Setting it to `react` raises a type error if react is not imported, and gives a quick fix to import react. The linter rule does not give a quick fix.
I've set it to _suggest_ the value `react` instead of forcing it, because people might need to set it to something else in their project for whatever reason.
Verified that it works by cloning create-react-app from master, installing the local versions, and using it to compile a personal project. Setting `"jsx": "react"` does not affect the build size or content.

Typescript init: suggest `jsx: "react"` in tsconfig 

---

packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json

preprocessor will output `sourceMap` by default
then check if `sourceMap` are needed on resolve-url-loader
issue demo: https://github.com/iamandrewluca/cra-scss-relative-problem
Fixes #4653

Resolve relative paths for preprocessor styles

---

packages/react-scripts/scripts/utils/createJestConfig.js

This PR fixes #7458 by adding `roots` to Jest configuration. I wanted to add test but didn't found any for Jest configuration. Please let me know what else should I add.

Specify roots in Jest config

---

packages/react-scripts/config/modules.js

Since tsconfig files [allow comments](https://github.com/Microsoft/TypeScript/issues/4987), using `require` for a `tsonfig.json` with comments results in the following syntax error:
```bash
$ react-scripts start
internal/modules/cjs/loader.js:724
throw err;
^
SyntaxError: /Users/jack/dev/github/test/tsconfig.json: Unexpected token / in JSON at position 157
at JSON.parse (<anonymous>)
at Object.Module._extensions..json (internal/modules/cjs/loader.js:721:27)
at Module.load (internal/modules/cjs/loader.js:612:32)
at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
at Function.Module._load (internal/modules/cjs/loader.js:543:3)
at Module.require (internal/modules/cjs/loader.js:650:17)
at require (internal/modules/cjs/helpers.js:20:18)
at getModules …
```

Support comments in tsconfig.json

---

packages/react-dev-utils/WebpackDevServerUtils.js

Original issue: #6720 
Root cause: https://github.com/sockjs/sockjs-client/issues/474#issuecomment-482918785
This is a PR for naive idea how to fix it: https://github.com/facebook/create-react-app/issues/6720#issuecomment-484034646

Fix for #6720: HMR not working in Firefox if proxy option present

---

docusaurus/docs/deployment.md

Now that ZEIT has launched [zero config deployments](https://twitter.com/zeithq/status/1159145442896166912), deploying a Create React App site is now much easier:

Adjusted deployment documentation for ZEIT Now

---

packages/react-scripts/scripts/utils/createJestConfig.js

In some situations, it's much easier to create a "blacklist" than a "whitelist" so including `coveragePathIgnorePatterns` makes a lot of sense to me. I've made this change locally and it works as expected.

Support configuring coveragePathIgnorePatterns

---

packages/react-scripts/config/webpack.config.js

Hello,
This lovely RegExp was preventing my `index.html` to be served from ServiceWorker after an authentication callback; the request always hit the network…
Here is an example of this kind of "auth requests" callback:
`https://example.com/PWA/callback?code=a55b99fbe42a3a7663b344020d2407047f4eb206aded15c300568ca4ef1219ce&scope=openid%20profile%20organizations%20api1%20offline_access&state=12c7c99a9b75476545161b45302e2cd&session_state=_p1MWLryvh08qxT-gmvucCIFVsWh8rIwo_MUBjhjvyY.5f6ee222da987db8c21aa4a35f93ada`
The problem was that it was blacklisted by workbox because… it contains a `.` ! 😟 
I believe it would be just safer to remove it… I hope this will prevent fellow devs opting in for SW wasting a lot of time like I did to found out! 😅 
Thanks!

Fix RegExp from navigateFallbackBlacklist (workbox)

---

docusaurus/docs/debugging-tests.md

This fixes #5319
This PR was tested by: 
* Create `.vscode/launch.json` according to this page in the docs
* Add the changes in this PR to `.vscode/launch.json` 
* Add various tests to `src/App.test.js` in an attempt to throw off the source maps
* Set multiple break points
* Start the debugger 
* See that the debugger in VS Code hits the correct lines

Fix launch.json for #5319

---

README.md
docusaurus/website/core/Footer.js

Add links to Spectrum in README and docs

---

packages/react-scripts/template-typescript/public/robots.txt
packages/react-scripts/template/public/robots.txt

Don't block static files in robots.txt

---

packages/eslint-config-react-app/index.js

As described in [docs](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/aria-role.md), `jsx-a11y/aria-role` ESLint rule can be disabled for non-DOM elements.
I'm pretty sure that we want to check only native HTML elements as a lot of developers can struggle when we raise a warning for the `role` property in their custom React components.

Ignore "jsx-a11y/aria-role" for React components

---

docusaurus/docs/setting-up-your-editor.md
packages/react-scripts/config/webpack.config.js

Fixes #7510.
`extends` is no longer available in ESLint 6.

Fix ESLint 6 support

---

docusaurus/website/static/css/custom.css

This PR fixes issue #7517 
Create react is not being displayed in create-react-app.dev page because docusaurus by default hides the logo for mobile view. Fix here involves displaying the the logo for all the resolutions. [https://github.com/facebook/docusaurus/blob/bd72aacfe85c2e239d6d92486850b5a229cda836/packages/docusaurus-1.x/lib/static/css/main.css#L592](Info)

Show logo for mobile views in create-react-app.dev

---

docusaurus/docs/adding-flow.md

Nuclide is discontinued, so I provided some alternatives.
Also, I let the users know they need to tweak their `.flowconfig` to make the absolute imports work with Flow.

docs: update Flow documentation

---

docusaurus/docs/proxying-api-requests-in-development.md

The previous sample didn't work, revised the sample, after checking the
[documentation](https://www.npmjs.com/package/http-proxy-middleware#tldr) of the `http-proxy-middleware` package and testing it on local env.

Correcting proxy sample

---

packages/react-scripts/config/webpack.config.js

Context: #6846  - I received no feedback on it, so I figure a PR is more actionable.
Changes have been tested running on a live website since I filed the issue. Build times and their memory consumption have both decreased with no further issue arising.
----
`cacheCompression` is an enabled-by-default flag in babel-loader,
which gzips the babel-loader cache.
Most projects do not actually benefit from cache compression,
especially in production where builds often happen in a CI environment
where memory is precious and disk space is not.
Furthermore, having it disabled in dev and enabled in prod means caching
won't be shared between dev and prod.
Finally, the disk space savings are not that great. Most React projects
will have a lot of small files (one file per component). babel-loader …

Disable babel-loader's cacheCompression

---

packages/react-scripts/config/webpack.config.js

The documentation for the new EXTEND_ESLINT env variable says it applies `When set to true` but the code only checks existence of the variable.
Setting `EXTEND_ESLINT=false` still enables extending eslint since `process.env.EXTEND_ESLINT` is technically set.
This PR just checks that `process.env.EXTEND_ESLINT === 'true'`

Explicitly checking that EXTEND_ESLINT is true

---

packages/react-scripts/package.json

Hi,
This fixes issues #4002 and #5833. Fixes #7577.
Essentially if a `.env` has an override which is an empty string, it is ignored. This was fixed by https://github.com/motdotla/dotenv-expand/issues/18

Upgrade dotenv-expand to fix issues

---

packages/react-scripts/config/webpack.config.js

**Enable ESLint cache:**
We discovered that enabling the ESLint cache can reduce the time for full rebuild. In our project, the time for a warm start decreased from 20 seconds to 17 seconds.
**Disable syntactic errors check:**
According to [documentation](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#options), `fork-ts-checker` can check for syntactic errors. This is basically useless for us as Babel already report those errors.
**Remove useless `watch` option:**
According to [documentation](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#options), `fork-ts-checker` ignores the `watch` option when `useTypescriptIncrementalApi: true`.

Minor performance improvements

---

docusaurus/docs/setting-up-your-editor.md

Passing options directly to the cli is not great practice, since default editor integrations won't pick it up and many people are just going to copy paste this snippet. This change removes that customization and prettier will use its very sane defaults.
Closes #7615

Remove --single-quote from prettier examples

---

packages/react-scripts/config/env.js

The variable `dotenvFiles` is never reassigned - use const instead.
The rest of the file already makes use of const - so this change makes it more consistent.

The variable dotenvFiles is never reassigned - use const instead

---

packages/react-scripts/config/webpack.config.js

Fixes #5358.
```
npx create-react-app test-runtimechunk
cd test-runtimechunk
yarn install && yarn build
```
Then...
```
yarn link "react-scripts" # my fix yarn linked
yarn build
```

Change runtime chunk name separator from tilde to dash

---

docusaurus/docs/deployment.md

Hi there,
I recently wrote a long blog post that takes a React developer step-by-step through many features of AWS. I really think any beginner could follow the guide and have a production ready workflow. Please let me know if my addition is suitable for this page and thank you for all the awesome work you do.

Update deployment.md with another AWS example

---

docusaurus/docs/production-build.md

Updates the docs with the change introduced in #7679.

Update runtime chunk name separator in docs

---

docusaurus/docs/using-the-public-folder.md
packages/react-dev-utils/README.md
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpackDevServer.config.js
packages/react-scripts/fixtures/kitchensink/integration/env.test.js
packages/react-scripts/fixtures/kitchensink/public/index.html
packages/react-scripts/template-typescript/public/index.html
packages/react-scripts/template/public/index.html

According to [this MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types), 
> The `shortcut` link type is often seen before `icon`, but this link type is non-conforming, ignored and **web authors must not use it anymore**.
So I removed it from all files except a Changelog file, which I assume is inmutable.

Remove 'shortcut' link type before 'icon'

---

packages/react-app-polyfill/ie11.js
packages/react-app-polyfill/ie9.js

Hello!
This PR is just a small one, and ensures that window is not undefined before it invokes the polyfill.

Guard polyfills against window possibly being undefined

---

packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json

**Problem:**
We would like to generate the `index.html` file on the server. In order to get code splitting to work, we need to know which chunks are entrypoints of the React app (to be able to request these from the HTML file). Unfortunately, this currently doesn't seem to be possible (see https://github.com/facebook/create-react-app/issues/5225#issuecomment-427312764).
Ideally, `splitChunks.name` would simply be set to `true` in the Webpack config, so the entrypoints could be inferred from the file names. However, this seems to lead to caching issues (see https://github.com/facebook/create-react-app/pull/5030#issuecomment-422820779).
This PR implements @iansu's suggestion from https://github.com/facebook/create-react-app/issues/5513#issuecomment-486838664: It adds an additional …

Add "entrypoints" key to asset manifest

---

docusaurus/docs/adding-flow.md

With the currently documented regex we catch relative imports, that then get wrongly mapped.
For example, `./Foobar.js` will become `<PROJECT_ROOT>/src/./Foobar.js`, instead of `<PROJECT_ROOT>/src/the/real/file/path/Foobar.js`.
The new regex will exclude imports starting with a dot (`.`)

docs: fix module mapper regex in Flow documentation

---

packages/react-scripts/config/webpack.config.js

Closes #7741
Verified that this works locally. See #7741 for screenshots/context.

set output.globalObject to 'this'

---

docusaurus/docs/running-tests.md

There are now 14 Jest config keys that can be overriden through Create React App 
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/utils/createJestConfig.js#L72
This is just to update the list of available config overrides in the CRA site.

[Documentation] Updated list of supported Jest config overrides

---

packages/react-scripts/package.json

Speeds up the process.
* disallow cache group named test with shorthand syntax to point out a potential config error
* Improve performance of LimitChunkCountPlugin
* fix a bug that the HMR plugin affected child compilations
* improve performance of splitChunks name option by caching hashed value
* improve rebuild performance by caching module size computation

Update webpack to improve performance

---

packages/react-scripts/template-typescript/README.md
packages/react-scripts/template/README.md

Parsing create-react-app generated READMEs with a MDX parser causes an error
```sh
SyntaxError: unknown: Expected corresponding JSX closing tag for <br>
```
This fixes it without affecting previous versions.

Close <br> tags in templates' READMEs

---

packages/react-scripts/config/jest/fileTransform.js

Just a small correction of the variable name casing, to match the use in the file of filename as a single word.

Fix wrong letter casing

---

packages/react-scripts/package.json

Fixes #7753 that's affected by breaking change in https://github.com/webpack-contrib/eslint-loader/pull/294

Fix linting error when using rest props

---

packages/react-scripts/bin/react-scripts.js

In the file `react-scripts` replaces the `switch case` with a simple `if else`. Since there was only one case, it would be nice to replace it with an `if else`.

Remove switch case

---

CHANGELOG.md

I ran into weird issues with calling functions that do not exist when upgrading from `2.1.8` to `3.0.0`, the issues were resolved by simply deleting the `node_modules` folder and doing a full install.

docs: note that 2 to 3 migration may require deletion of node_modules

---

packages/react-dev-utils/formatWebpackMessages.js
test/fixtures/webpack-message-formatting/__snapshots__/index.test.js.snap

Currently, CRA's `npm start` output only reports the line number of ESLint errors but hides the column numbers. This makes it harder for IDE users to leverage the time-saving features provided by IDEs like VSCode to deal with build errors:
* devs can't one-click to navigate from the build error message to the exact spot in the code where the problem is.
* the code editor won't show the little red sqiggly line under the exact spot in the code where the problem is.
This PR removes one line of code (originally introduced in #5174 last year) that removes column numbers from ESLint errors.  Here's the current code. As you can see, it has no side effects-- it removes column numbers but doesn't do any other changes to the string.
https://github.com/facebook/create-react-app/blob/4397d069d903c2992 …

Stop hiding the column number of ESLint errors

---

packages/react-scripts/config/modules.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/scripts/utils/createJestConfig.js

This PR adds support for setting the baseUrl in `tsconfig.json`/`jsconfig.json` to the root directory (`.`).
Initially I planned to add support for aliases but that turned out to be quite difficult due to difference in implementation between webpack and TypeScript. Instead this PR aims to facility the most requested option to import files with their absolute path (as seen from root) like `src/components/Button.js`. (https://github.com/facebook/create-react-app/issues/6850)
We don't want users to import from any directory other than `src` so the implementation maps a baseUrl of `.` to an alias that transforms `src` to the absolute `appSrc` directory. This should prevent users from doing something like `import { something } from 'library/utils.js'`.

Support setting baseUrl to root directory

---

azure-pipelines-test-job.yml
azure-pipelines.yml
packages/create-react-app/createReactApp.js
packages/react-dev-utils/InlineChunkHtmlPlugin.js
packages/react-scripts/scripts/build.js

Temporarily disables the Windows stages of the CI pipeline.
I also ran `yarn format` on the repo to clean up some files.

Temporarily disable Windows in CI

---

packages/babel-preset-react-app/create.js

(Reopening due to force-push https://github.com/facebook/create-react-app/pull/7725)
By default, babel assumes babel/helpers version 7.0.0-beta.0, this PR explicitly resolves the helpers to match the provide functions.
See: https://github.com/babel/babel/issues/10261
Looking at the code in [babel-plugin-transform-runtime/src/index.js](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js) it does not seem to be enough to provide an absolute path to the runtime.

Add babel runtime version to transform-runtime plugin to reduce bundle size

---

packages/react-scripts/config/webpack.config.js

This PR fixes #6044 and fixes #6296, which are sourcemap-related problems that make the VSCode debugger unable to debug code in `node_modules` of CRA apps.  "Unable to debug" means:
* breakpoints set on `node_modules` code trigger on different code lines than where the breakpoint was set
* stepping into `node_modules` code will highlight the wrong line, and sometimes even the wrong module!
* selecting a particular frame in a call stack will highlight the wrong line in a `node_modules` file
The cause of this problem was a Babel config change in #5096 from Sept 2018:
https://github.com/facebook/create-react-app/blob/57ef103440c24e41b0d7dc82b7ad7fc1dc817eca/packages/react-scripts/config/webpack.config.js#L432-L436
The goal of that change was to force debuggers to show transpiled code instead …

Fix node_modules sourcemap config (which will fix VSCode debugging of CRA apps)

---

packages/react-scripts/template-typescript/src/serviceWorker.ts

Hi,
Please run the following commands in order to test my changes:
*  npx create-react-app my-react-app-01 --typescript
* cd my-react-app-01
* npm start
Expected result: no more compilation error appears.

Fixed process type in TypeScript template.

---

packages/react-dev-utils/browsersHelper.js

Browserslist allows for setting browserslist config using environment variables, but CRA still prompts for setting browserslist config when it is already configured for the environment.
For example, running this currently results in CRA improperly detecting that browserslist is not configured, even though it is.
```shell
BROWSERSLIST="> 5%" npm run build
```

Allow for browserslist environment variables

---

docusaurus/docs/adding-typescript.md

:wave: just gave it a run through to try make it a bit more inline with some of the changes I had made to the react native + ts docs

Tightens up the TypeScript docs

---

packages/react-scripts/config/modules.js

This PR fixes #7818, by fixing the entry added to Jest's `moduleNameMapper` that unintentionally matched with paths that did not start with `src`.

Fix absolute paths issue in Jest

---

docusaurus/docs/running-tests.md
packages/react-scripts/scripts/utils/createJestConfig.js

[`clearMocks`](https://jestjs.io/docs/en/configuration#clearmocks-boolean) is a useful feature that clears all mocks between tests.
- Kent Dodds [tweeted about it recently](https://twitter.com/kentcdodds/status/1182744387190607872?s=09).
[`displayName`](https://jestjs.io/docs/en/configuration#displayname-string-object) is really interesting, as it enables developers working in multiproject setups (and monorepos) to visually identify which suite of tests is running.

feat: add additional Jest keys to whitelist

---

docusaurus/docs/code-splitting.md

The official documentation offers a simpler way of achieving route based code splitting.

Link to React documentation for code splitting

---

docusaurus/docs/setting-up-your-editor.md

As of https://github.com/facebook/create-react-app/pull/7562 (which dropped in 3.2), `.eslintignore` files will be respected when I opt in to extending the eslintconfig. This wasn't too clear from the existing docs.

Add a note about .eslintignore files being respected

---

packages/create-react-app/createReactApp.js

This PR related to #7715 
When using the `--typescript` option with `create-react-app` with an unsupported version node.js ie. from the issue 8.9.4. It creates a React project, but completely ignores the TypeScript template. 
Whats happening is that before this fix, if you're using an unsupported version of Node.js, `createReactApp.js` falls back to using version `0.9.5`. Within `0.9.5`, the init script (or `scripts/init.js`)  there is no code paths that support the TypeScript option. This is why you can still get a react app project, but without TypeScript being configured.
Within `createReactApp.js` I just added a check and error message that tells the user they must upgrade to a supported version to continue
I tested the command using `nvm`, 8.10 fully created a TypeScript project but …

added check for typescript template and unsupported node version

---

README.md
docusaurus/docs/getting-started.md

I noticed the gifs in the readme were hosted on [https://rawgit.com/](rawgit), which is ending support soon (October 2019).
So I converted the links using [https://www.jsdelivr.com/rawgit](https://www.jsdelivr.com/rawgit)

chore: update README.md gif links

---

packages/react-scripts/config/webpack.config.js

It seems that when creating a new app with `create-react-app`, there is an unnecessary/unused `eslint` import in the generated webpack config which can be seen if you eject the project. I have now moved this import into the `@remove-on-eject` block.
Verified as working by locally running `yarn create-react-app`, ejecting and viewing the new project's webpack config, where the extra import is now gone.

Move unused eslint webpack import into @remove-on-eject block

---

packages/react-dev-utils/InterpolateHtmlPlugin.js

Edit InterpolateHtmlPlugin hook (#6448)

---

packages/react-scripts/template-typescript/src/serviceWorker.ts
packages/react-scripts/template/src/serviceWorker.js

`127.0.0.1/8` refers to only a single IPv4 address "127.0.0.1" that have the subnet mask 255.255.255.0, but doesn't to 127.0.0.2.
`127.0.0.0/8`, which is the exact definition of the loopback addresses [[1]][[2]], includes what the regex says (127.0.0.0-127.255.255.255).
[1]: https://tools.ietf.org/html/rfc1122
[2]: https://tools.ietf.org/html/rfc6890

Fix notations of loopback addresses

---

packages/react-scripts/template-typescript/src/serviceWorker.ts
packages/react-scripts/template/src/serviceWorker.js

This PR adds the http header `Service-Worker: script` to the `checkValidServiceWorker` request in both serviceWorker templates, to match the [spec](https://w3c.github.io/ServiceWorker/) on how to request a service worker.
---
See https://w3c.github.io/ServiceWorker/#update-algorithm:
> To perform the fetch given request, run the following steps:
> 1. Append `Service-Worker`/`script` to request’s header list.
And https://w3c.github.io/ServiceWorker/#service-worker-script-request:
> An HTTP request to fetch a service worker's script resource will include the following header:
> - `Service-Worker`
>   Indicates this request is a service worker's script resource request.

Add Service-Worker header to checkValidServiceWorker

---

packages/react-scripts/scripts/build.js

Fixes #6282: If build compiler error has postcssNode property, add additional information to the error message. Default compiler CSS error messages are opaque. To verify:
```
npx create-react-app css-test
cd css-test
echo "label[for=*] { margin-right: 12px; }" > ./src/App.css
yarn build
```
Outputs error:
Replace css-test/node_modules/react-scripts/build.js lines:
```
messages = formatWebpackMessages({
errors: [err.message],
warnings: [],
});
```
With :
```
let errMessage = err.message;
// Add additional information for postcss errors
if (err.hasOwnProperty('postcssNode')) {
errMessage += '\n' + path.basename(
err['postcssNode'].source.input.file
) + '\nCompileError: Begins at selector ' +
err['postcssNode'].selector +' (' +
err['postcssNode'].source.start.line + ':' + …
```

Add additional information for postcss errors (#6282)

---

package.json

Unfortunately alex doesn't seem to work nicely with lint-staged. Removing this check for the time being. It still runs on CI though.

Remove alex precommit check

---

packages/create-react-app/createReactApp.js

If template name already starts with cra-template leave it alone.

Pass through fully specified template name

---

packages/create-react-app/createReactApp.js

A small change, this doesn't require a release/update to the current beta for templates.
The `packageVersion` was already coerced on line 445. I've also added a note to remove the env variable post official release.

refactor: remove double coerce

---

packages/react-dev-utils/printHostingInstructions.js

From the build,
```
Find out more about deployment here:
https://bit.ly/CRA-deploy
Done in 64.14s.
```
The link `https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment` doesn't work anymore.
Change it to `https://create-react-app.dev/docs/deployment`.

chore: Fix broken link for CRA deployment

---

packages/react-scripts/package.json

This PR adds TypeScript as an optional peer dependency for `react-scripts`. This modification is necessary to get `react-scripts` working with Yarn v2, and will enable the TypeScript template for `create-react-app` to work with Yarn v2.
This PR uses the `peerDependenciesMeta` key, which signifies to Yarn that `typescript` is an optional dependency. npm will support the key in the future, in which case `"typescript": "*"` can be added to `peerDependencies`. Until that change is made, simply having `peerDependenciesMeta` will be enough for Yarn, and won't adversely impact users of npm.
Other relevant issues: yarnpkg/berry/pull/475
/cc @iansu

Mark TypeScript as an optional peer dependency for react-scripts

---

packages/cra-template/template/src/App.css

The `prefers-reduced-motion` CSS media feature is used to detect if the user has requested that the system minimize the amount of animation or motion it uses.
This PR detects this, and prevents the spinning React logo from spinning.
Here it is as shown with and without the "Reduce motion" setting in the Accessibility section of the macOS System Preferences.

No spinning React logo if `prefers-reduced-motion`

---

CHANGELOG.md
packages/react-scripts/fixtures/kitchensink/template/src/App.js
packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/NullishCoalescing.js
packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/NullishCoalescing.test.js
packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/OptionalChaining.js
packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/OptionalChaining.test.js

I've also started a draft changelog for 3.3 with some helpful info.

Add tests for optional chaining and null coalescing

---

packages/react-scripts/package.json

The previous version has a confusing bug - a selected pattern gets interpreted as regexp. This has been fixed in 0.4.1 and is worth bumping a dependency here.

Upgrade jest-watch-typeahead

---

docusaurus/website/src/pages/index.js
docusaurus/website/src/pages/styles.module.css

Closes #7930
Tested with the manual toggle, and with setting `prefers-color-scheme`. Not sure if there's a cleaner way to do this, but it works.

Fix light background in docusaurus night mode

---

packages/react-dev-utils/printHostingInstructions.js
packages/react-scripts/template-typescript/README.md
packages/react-scripts/template/README.md

Since there are millions of existing apps out there that link to the old template READMEs we should have a placeholder there that links to the new location.

Add placeholders where old template READMEs used to be

---

packages/create-react-app/createReactApp.js

Fixing issue #7985.
I learned a bit about some... interesting... NPM behavior while testing. With only a regex check that the package name started with `cra-template-`, it still fell back to `cra-template-@scope/package`. If `scope/package` happened to be an accessible Github project, npm would download and install some version (I'm not quite sure how it decided which version...) of that repository as the template.
The solution I came up with was adding the prefix to the package name, while leaving the scope part unchanged. Maybe not 100% intuitive, but consistent with the behaviour of non-scoped packages.
Plain, uses `cra-template`
```bash
CRA_INTERNAL_TEST=1 yarn create-react-app my-app1
#
```
Template without prefix (`typescript`), uses `cra-template-typescript`
```bash …
```

Support templates in scoped packages

---

azure-pipelines.yml
packages/create-react-app/createReactApp.js
tasks/e2e-typescript-unsupported-node.sh

Another subset of #7839 
I added some e2e tests based on the following bash script: `e2e-old-node.sh`. I tested it on my local machine and I hope it runs as apart of the changes made to `azure-pipelines.yml`
The test just installs node version 8.9.x and ensures that the code errors out

added e2e test for checking typescript template with unsupported node

---

packages/react-app-polyfill/package.json

Unpin dependencies in react-app-polyfill

---

packages/react-scripts/scripts/init.js

To test, add a "scripts" key to any `template.json` file, and use that template.
This code merges keys in, allowing template authors to add or replace the default scripts.
---
Example command below. While testing, you may need to bump the `react-scripts` version (via `package.json`) to `3.3.0`.
```
node ./create-react-app/packages/create-react-app template-test \                                                                                                                                                                                                           feat/template-scripts
--template file:./create-react-app/packages/cra-template-typescript/ \
--scripts-version file:./create-react-app/packages/react-scripts/
```

Add scripts support to templates

---

packages/eslint-config-react-app/index.js

Eslint's `no-unused-expressions` rule doesn't support the new optional chaining syntax and yields false positives. Typescript-eslints's equivalent [was recently updated](https://github.com/typescript-eslint/typescript-eslint/pull/1175) to support it, so use it instead.
This fix only affects TypeScript, so in order to make it work for plain JavaScript we'd have to wait for official Eslint support or perhaps add another plugin like [this one](https://github.com/babel/eslint-plugin-babel).

Use @typescript-eslint/no-unused-expressions to support optional chaining

---

packages/cra-template-typescript/template/public/index.html
packages/cra-template/template/public/index.html

The link for apple-touch-icon is the only URL in the templates' `index.html`s that is relative, rather than using the `%PUBLIC_URL%` prefix.
Having all URLs in `index.html` be absolute makes it possible to host the site in one URL and alias `index.html` from another.  This is helpful, for example, when proxying a site into an Azure Functions domain.

Prefix apple-touch-icon links with PUBLIC_URL

---

packages/create-react-app/yarn.lock.cached
packages/react-dev-utils/package.json
packages/react-dev-utils/webpackHotDevClient.js
packages/react-scripts/config/webpackDevServer.config.js
packages/react-scripts/fixtures/kitchensink/template/integration/initDOM.js
packages/react-scripts/package.json
tasks/e2e-kitchensink-eject.sh
tasks/e2e-kitchensink.sh

Closes #7782.
Updates `webpack-dev-server` from `3.2.1` to `3.9.0`.
I was able to resolve the previous issues i experienced when trying the upgrade before in  #7473. The error appears to be related to our usage of `sockjs-client` inside of the `webpackHotDevClient` and jsdom. Switching to using native a `WebSocket` instead made everything happy.
`yarn start` works nicely. Code changes cause page refresh, style changes causes a hot replacement of styles as expected, and error overlay works.
**I tagged as a breaking change for `react-dev-utils` only as this change could potentially affect someone out there due to the change.**

Bump webpack-dev-server

---

CHANGELOG.md
packages/eslint-config-react-app/index.js

Remove no-unexpected-multiline rule

---

packages/react-scripts/package.json

This is currently missing and will break Yarn PnP. We're requiring `^3.2.1` as this is the minimum version requirement of `@typescript/eslint`.
cc @ianschmitz @mrmckeb 
Closes #8022

Add TypeScript peer dependency to react-scripts

---

CHANGELOG.md
docusaurus/docs/custom-templates.md
docusaurus/docs/getting-started.md

Update template docs

---

packages/react-dev-utils/webpackHotDevClient.js

Fixes #8075.
**Summary**
* If https protocol is being used we should use WebSockets over SSL/TLS (WSS) protocol instead of WebSockets (WS)
**Test Plan**
Follow steps in the issue https://github.com/facebook/create-react-app/issues/8075

webpackHotDevClient now uses wss when https is used

---

packages/eslint-config-react-app/index.js
test/fixtures/typescript/src/App.ts

Fixes #7651 
Haven't tested it yet, if someone can do that then that would be great!

Remove error for @typescript-eslint/no-namespace

---

packages/react-scripts/config/webpack.config.js

Hello!
By default CSS is minified and the quotes around CSS Font-Face names are removed (to save how many bits?). This prevents custom fonts working in IE11 and presumably others too.
This just overrides the behaviour. 
Pulled from my working production build where we fixed the bug.
See issue https://github.com/facebook/create-react-app/issues/7748
Fixes #4121

Fix CSS font-face minification

---

packages/react-dev-utils/webpackHotDevClient.js

Fixes #8084 
webpackHotDevClient WebSocket constructor now adds slashes between protocol and hostname, fixes issue on some browsers like IE11.

Add slashes to WebSocket protocol URL

---

packages/babel-preset-react-app/create.js

This is just a comment fix.
Actual optional chaining operator syntax is `?.`, not `.?`.
https://github.com/tc39/proposal-optional-chaining#syntax

Fix typo in comment: `?.` is right, `.?` is not

---

docusaurus/docs/getting-started.md
docusaurus/website/docusaurus.config.js
docusaurus/website/package.json
docusaurus/website/src/css/custom.css
docusaurus/website/yarn.lock

Bump docusaurus 2 to latest version. There are lot of improvements such as smaller client bundle size, better a11y, better dark-mode, line highlighting, etc and so on. Can check full changelog here https://github.com/facebook/docusaurus/blob/master/CHANGELOG-2.x.md
I also tweaked the CSS abit.
One thing I notice too is that Algolia docsearch has never been updated from algolia side, so its appending weird `#docsNav` (legacy of v1). I sent a PR to docsearch for update
Don't merge yet until https://github.com/algolia/docsearch-configs/pull/1165 land. 
https://deploy-preview-8111--create-react-app.netlify.com/

chore: update docusaurus & tweak site

---

packages/create-react-app/createReactApp.js

Make the --info subcommand outuput the current version information and the location of the file being run. Our issue template tells users to provide the output of --info, so having the current version is incredibly helpful, especially since it doesn't necessarily match the globally installed version that envinfo outputs. Knowing the location helps us determine whether the running bin is globally installed or in the local node_modules.
New output looks like this:
```diff
Environment Info:
+  current version of create-react-app: 3.3.0
+  running from C:\Users\alex\AppData\Local\Yarn\Data\global\node_modules\create-react-app
+
System:
OS: Windows 10 10.0.18362
CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Binaries:
Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.19.1 - …
```

Add current version and bin location to --info output

---

docusaurus/docs/making-a-progressive-web-app.md

The links in the Progressive Web App docs page refer to some files in the default template, whch used to live inside `react-scripts` but now are in `cra-template` - so I've updated the links to their new locations.

update PWA docs links to point to template package

---

packages/create-react-app/createReactApp.js

Just some things I noticed going through the code last weekend. I tried to keep the commits pretty piecemeal.

Minor refactors in create-react-app

---

packages/react-scripts/scripts/init.js

close #7892
Proactively append to `.gitignore` during generation instead relying on a `try/catch`
As #7892 illustrates, relying on the `EEXISTS` error is not reliable after the `fs-extra@8.X` upgrade. This fact was [confirmed by the `fs-extra` team](https://github.com/jprichardson/node-fs-extra/issues/734) when I opened an an issue with them.
The solution is to check whether or not `.gitignore` exists in the current repo and proactively append `gitignore` to it, rather than rely on the try catch logic to sniff for `EEXISTS` / `dest already exists` errors from `fs-extra`
I attempted to test this:
1. adding a directory to the monorepo, `foo` 
1. placing a `.gitignore` into it with contents. 
1. I commit that to avoid the git status porcelain check
1. Run `yarn create-react-app foo …

fix(react-scripts): proactively append to .gitignore during generation

---

docusaurus/docs/supported-browsers-features.md

Little typo

---

docusaurus/docs/custom-templates.md
packages/create-react-app/createReactApp.js

Continue from #7991. Allow `@scope` shorthand for template package name.
The motivation comes from https://github.com/storybookjs/storybook/issues/9327#issuecomment-571972738, where when library authors want to provide cra template under their scoped name, typing `--template @storybook/cra-template` every time seems tedious. Instead, it'd be better if the users can just type `--template @storybook` to use the template `@storybook/cra-template`. Since `@` is not a valid character for npm package name, it should be backward-compatible.
To list all the possible combinations.
provided template | downloaded package
--- | ---
`--template cra-template` | `cra-template`
`--template cra-template-typescript` | `cra-template-typescript`
`--template typescript` | `cra-template-typescript`
`--template …

Support shorthand scoped templates

---

docusaurus/docs/custom-templates.md
packages/cra-template-typescript/template.json
packages/cra-template/template.json
packages/react-scripts/fixtures/kitchensink/template.json
packages/react-scripts/scripts/init.js

This PR adds support for any `package.json` keys in a `template.json` file. It uses a blacklist of specific keys that shouldn’t be touched, and explicitly lists which keys will be merged with existing config - any other keys will be replaced as discussed in #8082.
- explicit merging of `"scripts"` and `"dependencies"` kept intact
- `templatePackage` keys that aren’t blacklisted or specified as merge keys will be added to `appPackage`
- this also replaces existing entries in `appPackage` with the new values specified in `templatePackage`
- stock templates have been updated to reflect the change in `template.json`, "kitchensink" fixture also updated
- docs have been updated
- some of the names used feel a bit chunky, open to suggestions!
- I chose `"browserslist"` as the example for the …

Add template support for any package.json keys (#8082)

---

packages/cra-template-typescript/template/src/App.tsx

This removes `React.FC` from the base template for a Typescript project.
Long explanation for a small change: 
`React.FC` is unnecessary: it provides next to no benefits and has a few downsides.  (See below.)  I see a lot of beginners to TS+React using it, however, and I think that it's usage in this template is a contributing factor to that, as the prominence of this template makes it a de facto source of "best practice".  
Defining a component with `React.FC` causes it to implicitly take `children` (of type `ReactNode`).  It means that all components accept children, even if they're not supposed to, allowing code like:
```ts
const App: React.FC = () => { /*... */ };
const Example = () => {
<App><div>Unwanted children</div></App>
}
```
This isn't a run-time error, but it is a mistake and …

Remove React.FC from Typescript template

---

packages/react-dev-utils/openBrowser.js
packages/react-dev-utils/package.json

- reverted #7910
- fixes #8081
Note: The vulnerability described in #7908 affects only `open` versions `0.0.5` and lower. Readme in `open` says: 
> The original open package was previously deprecated in favor of this package, and we got the name, so this package is now named open instead of opn. If you're upgrading from the original open package (open@0.0.5 or lower), keep in mind that the API is different.
> 
> Why?
> 
> Actively maintained.
> - Supports app arguments.
> - Safer as it uses spawn instead of exec.
> - Fixes most of the open original node-open issues.
> - Includes the latest xdg-open script for Linux.
> - Supports WSL paths to Windows apps under /mnt/*.
@andriijas

Downgrade open from 7.0.0 to 6.4.0

---

packages/react-scripts/lib/react-app.d.ts

After #7118 was merged, the `react-app.d.ts` wasn't updated to reflect the new property added, this PR adds that property

Add titleProp to SVGR ReactComponent type definition

---

packages/babel-preset-react-app/dependencies.js

Our `dependencies` babel config fell behind our main config. We're bringing it up to date in this PR.

Sync dependencies babel config

---

packages/react-scripts/config/webpack.config.js

This PR fixes the importLoaders setting for sass files. I believe this was broken in #5829 when an additional loader was introduced but the `importLoaders` setting was not incremented.
I ran into this trying to upgrade react-scripts locally. Verified this change fixes it for our project.
This is the error I ran into:
```
Error: resolve-url-loader: CSS error
file:///MySassFile.module.scss:42:6: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
at runMicrotasks (<anonymous>)
```

Fix sass importLoaders

---

packages/react-error-overlay/src/containers/RuntimeErrorContainer.js

Perhaps saving another person digging through Google to find [they've missed the little 'X'](https://stackoverflow.com/questions/46589819/disable-error-overlay-in-development-mode?rq=1) that's been there all along.

Add helpful message to the footer

---

docusaurus/docs/setting-up-your-editor.md

According to `lint-staged` v10 changelog (https://github.com/okonet/lint-staged#v10):
> From `v10.0.0` onwards any new modifications to originally staged files will be automatically added to the commit. If your task previously contained a `git add` step, please remove this. The automatic behaviour ensures there are less race-conditions, since trying to run multiple git operations at the same time usually results in an error.
There's no need to specify `git add` on the config anymore. So it should be removed from the doc as well.

Update docs according to lint-staged v10

---

docusaurus/docs/troubleshooting.md

docs: Add troubleshooting documentation on ENOSPC

---

packages/react-scripts/template/README.md

Currently, the `https://bit.ly/CRA-PWA` link points to this README, which points to another document, which points to [this page](https://facebook.github.io/create-react-app/docs/making-a-progressive-web-app).
This change puts a link to [this page](https://facebook.github.io/create-react-app/docs/making-a-progressive-web-app) in the README to save folks an extra click.

Make the PWA link point to the right place

---

packages/react-dev-utils/openBrowser.js
packages/react-dev-utils/openChrome.applescript

Hey there! The Contribution Guidelines say to ask before submitting a PR, but it doesn't say how to ask. I don't have a lot of experience contributing to OSS, so please let me know if I missed something.
This PR allows for CRA to control tabs on other Chromium-based browsers besides Google Chrome. How the code works:
1. Checks if AppleScript is applicable. Logic isn't changed, but I renamed the variable to `shouldTryOpenChromiumWithAppleScript`.
2. Runs through a list of supported browsers:
* Chrome Canary (has to come before Chrome because of grep)
* Chrome
* Edge
* Brave
* Vivaldi
* Chromium
3. For each browser, it greps to see if that browser is a process
4. If it finds a match, it passes the browser name to the AppleScript
5. AppleScript uses the Google Chrome dictionary to control …

Wider Chromium support for openBrowser

---

tasks/e2e-behavior.sh

This will fix e2e-behaviour on macos
Related: https://github.com/npm/cli/issues/611#issuecomment-575287540

fix(test): force install npm in e2e-behaviour

---

docusaurus/docs/running-tests.md

__Note: `setupTestFrameworkScriptFile` is deprecated in favor of `setupFilesAfterEnv`.__
ref: https://jestjs.io/docs/en/configuration#setupfilesafterenv-array

setupTestFrameworkScriptFile is deprecated

---

docusaurus/docs/using-the-public-folder.md

Added the relevant topic linked directly, instead of saying it's just in the next section.
Adjusted the text so it sounds more like a recommendation rather than a requirement.
The topic linked is basically explainer to how you'd reference it using the global window object and ways to avoid linter errors. Thus I used 'reference' to give users a hint of what it the linked page would be for.

Update public folder usage docs to clarify globals

---

packages/react-scripts/scripts/init.js

As proposed in #8280, this PR moves initialization of git repository before installation of template dependencies.

Run git init before template dependencies are installed

---

packages/react-dev-utils/launchEditor.js

Rider is JetBrains .NET IDE, which supports the React plugin identically to other JetBrains IDEs such as Idea and WebStorm.

Support JetBrains Rider IDE as an editor

---

packages/cra-template-typescript/template/src/serviceWorker.ts
packages/cra-template/template/src/serviceWorker.js

See https://bugzilla.mozilla.org/show_bug.cgi?id=1429714 for more details.

Handle service worker error in Firefox

---

docusaurus/docs/adding-images-fonts-and-files.md
packages/cra-template-typescript/template/src/App.tsx

The JavaScript template uses a function declaration to define the App component, the TypeScript template and a page of the documentation used arrow functions. Changed it to use function declarations for consistency and readability.

Change arrow functions to function declarations

---

docusaurus/website/src/css/custom.css

Fixed a line break in navigation in safari.
The bug:
Fixed version:

Fix navbar line break in header

---

packages/react-dev-utils/printHostingInstructions.js

Fixes #8291.
Tested executing `PUBLIC_URL=http://renato-bohler.github.io/my-app yarn build` on `create-react-app` root folder before and after changes.

Fixes unchecked access to 'deploy' script on build

---

packages/create-react-app/yarn.lock.cached
packages/react-dev-utils/package.json
packages/react-error-overlay/package.json

Fixes #8405.
Downgrades `chalk` that was bumped in #8164. The newer version of `chalk` included newer dependencies that used es2015+ APIs that weren't compatible with IE 11, and were included in the webpack dev client.

Downgrade chalk for ie 11 support

---

packages/react-dev-utils/typescriptFormatter.js

This should fix broken CI
Related #8164
Related #8439

fix(typescriptFormatter): use chalk@2 constructor

---

packages/react-dev-utils/openBrowser.js
packages/react-dev-utils/package.json

reverts #8364
`open` works again with WSL in its latest version. :)
Note: I've only tested it on my machine (OS Build 18362.592), someone else should test it too and give feedback before merging. 👌
@andriijas

update open to v7.0.2

---

packages/react-scripts/package.json

Since the PnP instance was stored in a global closure, a refreshed instance (when a dependency was added or removed) wasn't being being picked up. I fixed it in the plugin, now updating the dependency 😃
Fixes https://github.com/yarnpkg/berry/issues/958

Bumps pnp-webpack-plugin

---

docusaurus/docs/custom-templates.md

The directory tree that's currently shown is the structure that a CRA template should have, but `my-app` is used earlier in this tutorial to refer to the app that's _generated_ based on that template.

Indicate that the file structure is the template's

---

packages/react-scripts/scripts/init.js

Fixes https://github.com/facebook/create-react-app/issues/8373
I'm creating a template to work with [pulumi](https://github.com/pulumi/pulumi). Pulumi programs need to have a `main` specified in the package.json in order to work ([example](https://github.com/pulumi/examples/blob/master/aws-js-s3-folder/package.json)). CRA currently blacklists/sanitizes `main` declarations which is preventing the generation of fully functional apps.
This change allows specification of the `main` field in `template.json`.
Testing was done by modifying the typescript template to include a main, and then running:
```sh
$ yarn create-react-app foo --template file:./packages/cra-template-typescript
```
which resulted in:
```sh
$ create-react-cloud evanboyle$ cat foo/package.json 
{
"name": "foo",
"version": …
```

allow specification of package.main in template.json

---

docusaurus/docs/proxying-api-requests-in-development.md

The http-proxy-middleware package has made a major version upgraded and
introduced a breaking change. This fixes the "Configuring the Proxy
Manually" docuementation to match the latest version.
Relates to #8513

Fix proxying API request docs

---

packages/cra-template-typescript/template.json

It looks like @testing-library dependency currently relies on type-only imports which conflicts with the version of Typescript used in the cra template, preventing it from building straight after starting a new project.

Bump typescript template to 3.8 

---

packages/react-scripts/scripts/utils/createJestConfig.js

Node.js added new [`.cjs` and `.mjs`](https://nodejs.org/api/esm.html#esm_enabling) file extensions for dual ESM/CJS packages.
This PR adds `.cjs` and `.mjs` files from `node_modules` support to test runner.
I have popular dual [CJS/ESM package](https://github.com/ai/nanoid/).
```json
"type": "module",
"main": "index.cjs",
"module": "index.js",
"browser": {
"./index.js": "./index.browser.js"
},
"exports": {
".": {
"require": "./index.cjs",
"import": "./index.js",
"browser": "./index.browser.js"
},
```
Everythings works in Create React App `npm start`:
```js
import { nanoid } from 'nanoid'
```
But Jest can’t load my library during `npm test`:
```
TypeError: (0 , _nanoid.nanoid) is not a function
```
Here is issue in my repo: https://github.com/ai/nanoid/issues/205
1. Create an empty CRA …

Add .cjs and .mjs files support to test runner

---

docusaurus/docs/running-tests.md

As of https://github.com/testing-library/jest-dom/pull/175, setting up `@testing-library/jest-dom` is now a bit easier, it's enough to import `@testing-library/jest-dom`.

Use simplified import of @testing-library/jest-dom

---

packages/babel-preset-react-app/README.md

Documented babel-preset-react-app absoluteRuntime option

Include absoluteRuntime in babel preset docs

---

CONTRIBUTING.md

Hello,
In CONTRIBUTING.md, adding the path of the files being served by yarn start on a bare copy (git clone) of create-react-app.

Specify what files are served form a bare local copy

---

packages/cra-template-typescript/package.json
packages/cra-template/package.json
packages/react-scripts/scripts/init.js

Some users have hit an issue when creating templates and omitting the `main` field. As `main` is not required in `package.json`, we've simplified the implementation to remove this requirement.
Solution provided by @ianschmitz. Resolves #8560.

fix: handle templates without main package field

---

docusaurus/docs/setting-up-your-editor.md

The url to see prettier in action is out-dated (returns 404). I replaced it with the url to prettier's playground.

Update url to see prettier in action

---

packages/react-scripts/config/webpack.config.js

Passing an array with a single entry is not equivalent. This causes Webpack to generate another wrapper module around the entry. This is just unnecessary overhead and bytes.
Before: 
```
...
/***/ 10:
/***/ (function(module, __webpack_exports__, __webpack_require__) {
...
/***/ }),
/***/ 5:
/***/ (function(module, exports, __webpack_require__) {
module.exports = __webpack_require__(10);
/***/ })
},[[5,1,2]]]);
```
After:
```
...
/***/ 10:
/***/ (function(module, __webpack_exports__, __webpack_require__) {
...
/***/ })
},[[10,1,2]]]);
```

Don't use webpack multi entry unnecessarily

---

packages/eslint-config-react-app/package.json

See #7790 for a previous similar PR.
I don't believe it is a breaking change to widen the peer dependency version, it merely lets people using the newer 3.x version of `eslint-plugin-react-hooks` use it with this ESLint config (e.g. if they're not using `react-scripts`). `react-scripts` will continue installing `^1.6.1` as it did before.

Widen eslint-config-react-app peer dependency versions

---

packages/react-dev-utils/printHostingInstructions.js

Currently when running `npm run build` in a create-react-app project the output has the following text
```
Find out more about deployment here:
bit.ly/CRA-deploy
```
This link leads to [https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment) which doesn't contain any information about deploying the app.
This PR changes the link to the create-react-app documentation's deployment page.

Update build script deployment URL

---

packages/react-scripts/scripts/start.js

Fixes #8688
As discussed in #8868, Docker sessions shut down the dev server before it gets a chance to use it because Docker appears to be "interactive" and then closes `stdin` immediately. The workarounds were to set `CI=true` (which worked in some cases but not others) or to configure the Docker container to maintain an open TTY.
This shouldn't be necessary and is affecting both CI deployments and other environments.
The problem is a change in #7203, which intended to close the development server when `stdin` closed because otherwise it was left hanging open. That now is closing prematurely in cases where it's used in Docker.
During development of #7203, the check for an interactive session was added to fix it crashing in CRA's CI. However that didn't resolve the issue for some uses of …

Do not check for interactive session to shut down dev server

---

packages/react-scripts/config/webpack.config.js

This should resolve #5707. A basic history of that issue as I understand it: currently, create-react-app doesn't have sourcemaps for scss on development environments. This feature was briefly added two years ago in #5713, then reverted due to a bug in an upstream dependency. The upstream bug is now fixed, so we can (I believe) re-enable this feature.

Support source maps for scss in dev environments

---

packages/react-scripts/scripts/utils/createJestConfig.js

- Add `resetMocks: true` to the template in createJestConfig
- This is a best practice (but not required) for working with RTL tests (https://github.com/facebook/create-react-app/pull/7881)
See also https://github.com/facebook/jest/issues/9047

Set resetMocks to true by default in jest config

---

docusaurus/docs/running-tests.md
package.json
packages/cra-template-typescript/template.json
packages/cra-template-typescript/template/src/setupTests.ts
packages/cra-template/template.json
packages/cra-template/template/src/setupTests.js
packages/create-react-app/yarn.lock.cached

`jest-dom`'s latest major version has its type definitions moved to DefinitelyTyped (see testing-library/jest-dom#123). This make it so the TypeScript definitions work automatically without config. This PR upgrades the version referenced in the template so that newly generated projects get the newest version right from the start.
The newest `jest-dom` version also makes it so that the main module takes care of extending `expect`, so this PR includes the following change where appropriate (though the usual way still works):
```diff
-import '@testing-library/jest-dom/extend-expect';
+import '@testing-library/jest-dom';
```
This PR also takes the liberty to upgrade the actual dev dependency of `create-react-app` itself. Ran the tests and it all worked. Hope that's ok too.

Upgrade testing-library packages

---

packages/react-scripts/package.json

Previously #8378 we rollback `style-loader` to v0.23.1 because CSS hot reload not worked with newer versions. Today it was fixed https://github.com/webpack-contrib/style-loader/pull/466 and we can safely upgrade it back and close #7665

Bump style-loader to 1.2.1

---

docusaurus/docs/custom-templates.md
packages/react-scripts/scripts/init.js

This PR adds support for templates to defined `devDependencies` alongside `dependencies`.
It also adds a deprecation warning for templates using the previous syntax.

Support devDependencies in templates

---

packages/react-scripts/config/webpack.config.js

@charrondev  @ianschmitz
The `react-refresh/babel` plugin got added as the option of `babel-plugin-named-asset-import`  🙈😂

fix react-refresh babel plugin not applied

---

docusaurus/docs/adding-css-reset.md

A warning kept popping up in my editor. Narrowed it down to https://github.com/Microsoft/vscode/issues/53175. Adding the suggestion as a tip.

Add a VSCode tip in the CSS reset section

---

packages/react-scripts/package.json
packages/react-scripts/scripts/build.js

This commit is a manual revert of the following commits:
https://github.com/facebook/create-react-app/commit/e7a427ad161b7b58868409d99307d8b68fad1335
https://github.com/facebook/create-react-app/commit/140e182e7d7fbeb8d507b6be4813a4ce0bf9b6d8
And a re-introduction of
https://github.com/facebook/create-react-app/commit/7c8593845830c585a780f4e40268e7b4f442c7a4
Fixes: https://github.com/facebook/create-react-app/issues/8789
Fixes: https://github.com/facebook/create-react-app/issues/6904
Tested:
Manually ran yarn link and then ran yarn build from a 3.x version of CRA
with react-scripts linked in from this patch.
Verification:
Saw that a bundle-stats.json file was written out where as before in the
pre-linked version it was not.

Add back in --stats output from webpack.

---

packages/create-react-app/createReactApp.js

The `--use-pnp` flag will break Yarn 2 because PnP has been enabled by default and the flag has been removed. This improves user experience by automatically ignoring the flag for Yarn 2, and explaining that it won't be needed in the future.
I've tested this with Yarn 1 and it works normally, though Yarn 2 has a different installation linking system that I couldn't get to work with create-react-app locally.

Fix --use-pnp for Yarn 2

---

packages/react-dev-utils/__tests__/getCSSModuleLocalIdent.test.js
packages/react-dev-utils/getCSSModuleLocalIdent.js

Fixes #8491
- Replaces periods `.` with underscores `_` in CSS modules class names generated from filenames.
- Added test cases using a stripped down mock context.
Screenshot of the issue (more info in issue #8491)

Replace period in CSS Module classnames

---

docusaurus/docs/making-a-progressive-web-app.md
packages/cra-template-typescript/template/src/index.tsx
packages/cra-template-typescript/template/src/serviceWorker.ts
packages/cra-template/template/src/index.js
packages/cra-template/template/src/serviceWorker.js
packages/react-dev-utils/printBuildError.js
packages/react-dev-utils/printHostingInstructions.js
packages/react-scripts/scripts/init.js
packages/react-scripts/scripts/start.js
packages/react-scripts/template/README.md

Replace outdated bitly links with our own updated links.

Move shortlinks to cra.link

---

packages/babel-preset-react-app/create.js

Remove outdated comment

---

packages/react-scripts/package.json

Resolves `yargs-parser` vulnerability mentioned in https://github.com/facebook/create-react-app/issues/8529

bump webpack-dev-server to 3.11.0

---

packages/react-scripts/scripts/utils/createJestConfig.js

Resolves #8637. 
Tested locally with these steps:
1. `cd packages/react-scripts`
2. `yarn link`
3. In another project: `yarn link "react-scripts"`
4. Running `SKIP_PREFLIGHT_CHECKS=true yarn test`
5. Verifying that nothing changed from before symlinking modules
6. Add `testMatch` key to `package.json` Jest config
7. Running `SKIP_PREFLIGHT_CHECKS=true yarn test` again
8. Verifying that only filed matching specified pattern are being included for testing
For further reasoning as to why this option should be added please refer to #8637.

Allow testMatch for jest config

---

docusaurus/docs/deployment.md

Just an update to the Azure docs for deployment for the new Azure Static Web Apps.

Update deployment docs for Azure Static Web Apps

---

packages/react-dev-utils/openBrowser.js
packages/react-scripts/bin/react-scripts.js

Instead of requiring Node to be on the system PATH.
Currently, `react-scripts` spawns scripts such as `test`, `build` by specifying an executable name, `node`. This requires `node` to be on the system PATH. Some users (like me) may not have it on the system PATH and normally don't have problems since an IDE like Webstorm configured with a node interpreter mostly runs tests and builds without any problem. However, this doesn't work with `create-react-app` because it expects `node` on the PATH.
Luckily, there is an easy way of getting an absolute path to the current interpreter binary so we can use it and remove the requirement that `node` is on the system PATH.
I have verified that before this change, running tests in Webstorm failed with this
```
'node' is not recognized as an internal or …
```

Use process.execPath to spawn node subprocess

---

docusaurus/docs/running-tests.md

The root domain, chaijs.com, does not serve a valid certificate
and gives a browser warning.
chaijs.com:
www.chaijs.com:

Fix chai URL

---

README.md
docusaurus/docs/adding-typescript.md
docusaurus/docs/getting-started.md
packages/react-scripts/scripts/init.js

I've noticed a few times that users will read the error about having to uninstall create-react-app, not know how to do that, and then get stuck and have to ask for help. This adds uninstallation advice (similar to what's in the readme) at the bottom of the error messages, and also includes yarn.

Explain how to uninstall create-react-app globally

---

packages/react-dev-utils/refreshOverlayInterop.js
packages/react-error-overlay/src/index.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json

I've just released `0.4.x` stable for the fast refresh plugin, and didn't want CRA to release 4.0 depending on a beta version, so I decided to PR the related changes 😺 
- Bumped `@pmmmwh/react-refresh-webpack-plugin` from `0.4.0-beta.8` to `0.4.1` (latest stable)
- Added interop to enable the plugin to use `react-error-overlay` instead of the bundled overlay, unifying the error experience for CRA users
- This is needed because only the plugin will be able to catch module initialization errors (during HMR);
- I think keeping a cohesive experience throughout the usage of CRA is a good thing;
- This would save a few kilobytes since the plugin will not inject the bundled stuff ([overlay files](https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/main/overlay) and [socket …

feat: better refresh plugin integration

---

packages/create-react-app/createReactApp.js

Unfortunately this is a tricky problem. As @Timer pointed out, a global install catch would be triggered on `npx` and `yarn create` runs. 
I couldn't find a way to determine if the user had initialised `create-react-app` with `npx` or `yarn create` specifically (although I was able to find out if they used `yarn` or `npm`) - but there may be a method I missed.
An alternative option is to use the command `npm view create-react-app version` - which returns the latest version as a string. This solution, however, is slow.
---
This PR:
- Resolves #7422
- Closes #7452

feat: exit on outdated create-react-app version

---

packages/cra-template-typescript/template/README.md
packages/cra-template/template/README.md

Updated README.md in both templates (JS/TS) to adhere to the following Markdown ESLint rules. This isn't a big change to how create-react-app works, but I'm submitting this as my eslint plugin in VS Code complains about these rules every time I open the README.md file locally.
- [MD041 - First line in file should be a top level heading](https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md#md041)
- [MD033 - Inline HTML](https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md#md033)
- [MD034 - Bare URL used](https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md#md034)
Screenshots below show the markdown changes applied _(Left)_ and original version _(right)_. Note that the only visible change is the top level heading `Getting Started with Create …

Updated README.md Templates to Follow ESLint Markdown Rules

---

docusaurus/docs/running-tests.md

The React Testing Library has been modified to use the screen api in [v9.4.0](https://github.com/testing-library/react-testing-library/releases/tag/v9.4.0).
I think the documentation should also be changed to the recommended api.

[Doc] fix React Testing Library example

---

packages/react-dev-utils/package.json

Getting errors when trying out fast refresh with the react-scripts **next** release as refreshOverlayInterop.js was not included with react-dev-utils.

Publish refreshOverlayInterop with react-dev-utils 

---

packages/eslint-config-react-app/README.md
packages/eslint-config-react-app/index.js

`jsx-a11y/accessible-emoji` has been deprecated, see #9239

fix: remove deprecated rule

---

packages/react-dev-utils/formatWebpackMessages.js

[`formatMessage` function](https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/formatWebpackMessages.js#L18) accepts only one argument. This pull request cleans up the extra argument passed to it.

clean formatMessage usage

---

packages/babel-preset-react-app/create.js
packages/babel-preset-react-app/dependencies.js

This PR removes `modules: false` option and resorts to the defaults of `@babel/preset-env`: `{ modules: "auto" }`.
See https://github.com/babel/website/pull/2301 for the differences between `{ modules: "auto" }` and `{ modules: false }`.
Since Babel 7.11 (https://github.com/babel/babel/pull/11849), `{ modules: false }` could result to unwanted behaviour when `export * as ns` is used in test environment on Node 14, where Babel will skip `proposal-export-ns-from` because Node 14 has native `export * as ns` support but Webpack 4 will throw because it does not support `export * as ns`.
When `{ modules: "auto" }` is specified, Babel will determine whether it should be transformed from the caller data passed by `babel-loader`.
This change is not breaking change given that `webpack 4 + …

fix: use default modules option from `preset-env`

---

packages/react-app-polyfill/package.json

Updates the polyfill for whatwg-fetch to include https://github.com/github/fetch/commit/ff32363d6e136dd4878b7ce28a424e69a415922b which will allow fetch-mock to work in IE11. Prevents the need for a user to have two versions of the polyfill in their in package.lock aswell

Upgrade whatwg-fetch

---

packages/react-dev-utils/README.md

Some sentences were off, suggested corrections made with this PR

Fixes in the /packages/react-devs-utils/README.md file

---

docusaurus/docs/deployment.md

This pull request updates the Vercel deployment documentation section with the recommended deployment method from Vercel for the greatest chances of user success.

Update Vercel deployment documentation

---

docusaurus/docs/making-a-progressive-web-app.md

This pull request fixes insensitive language in the Docusaurus documentation page for "making a progressive web app".
Removes "just" from a recommendation.

Fix insensitive language in Docusaurus docs

---

README.md

This emphasises that Next.js is capable of static site generation. A lot of comparisons between the most popular React frameworks seem to go like this:
- CRA is good for client-side SPAs
- Gatsby is good for static sites
- Next.js is good for server-rendered applications
So people who need static sites will typically always choose Gatsby. However, Next.js now supports [static site generation](https://nextjs.org/docs/advanced-features/static-html-export) - since earlier this year I think. So I feel this comparison should include that.

Emphasise that Next.js is capable of SSG

---

packages/babel-preset-react-app/create.js
packages/react-scripts/config/webpack.config.js

Use new JSX transform with React 17

---

packages/eslint-config-react-app/base.js
packages/eslint-config-react-app/index.js
packages/react-scripts/config/webpack.config.js

This resolves an issue where the ESLint config is not resolved from the project root correctly.
It also moves a rule to the new `base` config, to prevent potential user errors.

fix: resolve ESLint config from appPath

---

packages/react-scripts/config/webpack.config.js
packages/react-scripts/lib/react-app.d.ts

Add AVIF image support.
Closes #9610

Add AVIF image support

---

packages/babel-preset-react-app/create.js
packages/eslint-config-react-app/base.js
packages/react-scripts/config/webpack.config.js

This PR resolves two issues with CRAv4 and React's [new JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) - originally implemented in #9645.
- The configuration has been moved to the Babel config, which means it will now work with Jest.
- Conflicting ESLint rules are now automatically disabled.
I made the decision not to share the small helper as I didn't want to add another dependency to `babel-preset-react-app` and `eslint-config-react-app`,  but that's of course open to discussion/ideas.
Resolves #9772, resolves #9782.

fix: resolve new JSX transform issues

---

docusaurus/docs/deployment.md
docusaurus/website/docusaurus.config.js
docusaurus/website/package.json
docusaurus/website/src/pages/index.js
docusaurus/website/yarn.lock

I'm a Docusaurus maintainer, and I noticed that CPA website uses very old version of Docusaurus (.39), so it's best to upgrade to the latest one (.64). There are many improvements and fixes in the newest versions of Docusaurus.
You can go to the demo website (https://competent-knuth-32330e.netlify.app/) to make sure that nothing was broken after upgrading Docusaurus.
P.S. New versions of Docusaurus have a built-in broken links checker that found two invalid links which I fixed. Also, instead of `classnames` we use `clsx` now.
Friendly ping @ianschmitz

Upgrade Docusaurus to latest version

---

packages/react-scripts/package.json

Currently, `npm audit` fails because of `react-scripts > resolve-url-loader > adjust-sourcemap-loader  > object-path`.
See https://github.com/facebook/create-react-app/issues/9840 for details.
This PR bumps the `resolve-url-loader` version from 3.1.1 to 3.1.2

Bump resolve-url-loader version

---

packages/react-scripts/config/webpack.config.js

`ModuleScopePlugin` was getting upset about `react-dev-utils/refreshOverlayInterop` being injected by the react refresh plugin. This PR adds that module to the ignore list.

Fix refreshOverlayInterop module scope error

---

packages/cra-template/template/src/App.js
packages/cra-template/template/src/App.test.js

I'm not sure if this change should go out in 4.0, but any new installations will have the required support for this - and it might be good to lead by example.
Anyone scaffolding a new project should have no issues with this, unless they were using an old `react-scripts` version - but I feel we can consider that edge-case, and they could also specify an old template version if they really need it.
The TypeScript template is blocked by #9734, which is waiting on TypeScript 4.1 to be released.

feat: remove unused React imports

---

packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

Use new JSX setting with TypeScript 4.1.0

---

packages/react-scripts/config/webpack.config.js

fixes #9886
This is the commit that removed the cache flag:
https://github.com/FezVrasta/create-react-app/commit/d07b7d025f5933710fcb01718617dbdf4bc54c33#r43578777

fix: slow recompile time

---

.prettierrc

`es5` is the default value for `trailingComma` since `prettier@2.x`

chore: Update .prettierrc

---

packages/react-dev-utils/webpackHotDevClient.js

Page doesn't get refreshed when disabling `FAST_REFRESH`. This is because the `process.env.FAST_REFRESH` in `webpackHotDevClient` is a boolean value, comparing `!== 'false'` will always return `true`.
- `yarn create-react-app my-app`
- `yarn start`
- Modify `App.js` content
- The app gets updated through Fast Refresh
`FAST_REFRESH=false`
- Start the app by using `FAST_REFRESH=false yarn start`
- Modify `App.js`
- The app should do a full reload

fix: page doesn't get refreshed when FAST_REFRESH=false

---

packages/react-scripts/config/webpack.config.js

fix #9882
Eject the app will cause `React is not defined`, This is due to the Babel's configuration for JSX runtime gets removed during ejecting.
- Keep `runtime` configuration on ejection
- `yarn create-react-app test-ejecting-app`
- `cd test-eject-app`
- `yarn eject`
- `yarn start` and app should gets compiled successfully

fix: `React is not defined` compilation error after ejected

---

packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

Fixed an issue that prevented TypeScript apps from starting #9868 9868

Fix react-jsx error

---

packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

Relative Issues https://github.com/facebook/create-react-app/issues/9868 https://github.com/facebook/create-react-app/issues/9429
I fixed broken `yarn start` that cause react-scripts can't handle correctly `noFallthroughCasesInSwitch` and `jsx` compileOptions.
Thank you for your decent review 😀

Fix noFallthroughCasesInSwitch/jsx object is not extensible

---

docusaurus/docs/running-tests.md

As the *React Testing library* requires a dom to execute their assertions, I'm adding it to the list of libraries requiring it on the documentation.
here's a screenshot of a test failing by using the node environment.

docs: add React Testing Library as a library requiring jsdom

---

packages/react-scripts/config/webpack.config.js

By default, any asset that is larger than 2mb won't be precached when using Workbox in your service worker with the PWA template. This will bump up that limit to 5mb.
There's a tradeoff here—you can easily end up accidentally precaching, e.g., very large media files by mistake if this limit is too high—but based on https://github.com/cra-template/pwa/issues/13#issuecomment-722667270, it's fairly easy to hit the 2mb limit on lazy-loaded JavaScript chunks. 5mb seems like a decent compromise.

Increase Workbox's maximumFileSizeToCacheInBytes

---

package.json
packages/cra-template-typescript/template.json
packages/cra-template/template.json

web-vitals package has upgraded its version to 1.0.1 This PR is just a routine task to upgrade the dependency. The core functionality of web-vitals is working after the upgrade. I created a sample project and hit `reportWebVitals(console.log);` Following is the result that proves the successful of web-vitals functionality.

chore: bump web-vital dependency version

---

packages/cra-template-typescript/template.json

As react version is 17.0.1, @types/react and @types/react-dom should be updated too.
Also, typescript version should be 4.1.2.
(I'm not sure what causes this, but when I create typescript project with CRA 4.0.1, installed node_modules/typescript version is 4.1.2, but root package.json describes it as "^4.0.3".)

chore: bump typescript version

---

packages/react-scripts/package.json

CRA is supposed to officially support TypeScript 4 as of [4.0.0](https://github.com/facebook/create-react-app/releases/tag/v4.0.0) but `react-scripts` is still set at only allowing TypeScript as `^3.2.1`. As the CRA TypeScript template comes with TypeScript 4 I think this is causing an install error for users on npm 7 as it now attempts to install peerDependencies by default but the TypeScript versions conflict.
If CRA now supports TypeScript 4 I think this is the correct change to make things right.
Closes #9892 
Closes #9764 (not really related to this but it can close after this)
Closes #9995

Add TypeScript 4.x as peerDependency to react-scripts

---

packages/react-dev-utils/formatWebpackMessages.js

Part of https://github.com/facebook/create-react-app/issues/9994 Webpack 5 series
`formatWebpackMessages.js` gets pulled into the browser and potentially runs there. 
This causes `Chalk` to try and run which eventually fails. 
The failure is because Webpack 5 no longer polyfills node built-ins. And Chalk uses `process`.
The best option is to not run chalk in formatWebpackMessages.js. The text will still show in the terminal just not have a grey background, I think this is a feature worth losing compared to the errors it causes in the browser, or the large amount of refactoring everyone using this would need to do.

remove chalk from formatWebpackMessages

---

packages/react-scripts/config/webpack.config.js

Out of the box today, CRA produces [numbered vendor chunks](https://create-react-app.dev/docs/production-build). They look like this in production:
```
File sizes after gzip:
146.17 KB       build/static/js/7.f5a20c19.chunk.js
39.39 KB        build/static/js/8.5cf7927d.chunk.js
```
And like this in development:
This is a good default for production, following [webpack's guidance](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunksname) (`splitChunks.name: false`) to create stable, cacheable names.
In development, though, when I'm trying to understand exactly what code is delivered when, I'd like to know more about what goes in to those chunks.
This PR sets `splitChunks.name` to `true` in development, producing vendor chunk names like this:
Is this something others would be …

Improve vendor chunk names in development

---

packages/react-scripts/package.json

Fix #9986 
With the current `node-sass` version (v5), `react-script` won't survive.
**TEST PLAN**
With the `sass-loader` version upgrade and new version of `node-sass`:
1. `npx create-react-app sass-error-compilation`
1. `cd sass-error-compilation`
1. `yarn add node-sass@5.0.0`
1. Modify App.css to App.scss. Change extension in App.js as well.
1. change the sass-loader version in `node_modules/react-scripts/package.json` to `^10.0.5`
1. `yarn add sass-loader@10.0.5`
1. `yarn start`
1. Should work successfully
With the `sass-loader` version upgrade and old version of `node-sass`:
1. `npx create-react-app sass-error-compilation`
1. `cd sass-error-compilation`
1. `yarn add node-sass@4.14.1`
1. Modify App.css to App.scss. Change extension in App.js as well.
1. change the sass-loader version …

Upgrade sass-loader

---

packages/react-scripts/config/paths.js
packages/react-scripts/config/webpack.config.js

Fix #9970
Fix #10161
As mentioned in https://github.com/facebook/create-react-app/pull/9977#discussion_r515618643, likewise `eslint-loader`, we need to support non-existing OR inaccessible path fallback for cache folder into `os.tempdir`, as current(new) eslint plugin doesn't support the fallback.
**TEST PLAN:**
To test how **permission issue** folder fallback works:
1. under the `node_module`
- Remove the `.cache` folder content, if folder exists.
- Or, create `.cache` folder
2. run `chmod u=r--,g=r--,o=r-- node_modules/.cache`
3. run `npm start`
4. `ls node_modules/.cache` should not show the `.eslintcache` file
To test how **non-existent** folder fallback works:
1. under the `node_module`
- Remove the `.cache` folder content, if folder exists
2. run `npm start`
3. `ls …

Move ESLint cache file into node_modules

---

README.md
docusaurus/docs/debugging-tests.md

There were a couple dangling references to Node 8 from the last major.

Remove references to Node 8

---

docusaurus/docs/running-tests.md

Hi 👋
I've noticed that the [documentation for overriding CRA's default Jest configuration](https://create-react-app.dev/docs/running-tests/#configuration) has gone out of sync with the actual implementation:
https://github.com/facebook/create-react-app/blob/5e703a568a687dacdc45f1211355ce4b1b586625/packages/react-scripts/scripts/utils/createJestConfig.js#L75-L94
This PR fixes that!

docs: add missing override options for Jest config

---

packages/react-scripts/package.json

Resolves #10084 security vulnerability in websocket-driver library version 0.5.6, imported transitively by sockjs

Bump webpack-dev-server 3.11.0 -> 3.11.1

---

packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json

An update to `eslint-webpack-plugin` broke behaviour of the new flag (`ESLINT_NO_DEV_ERRORS`) that allowed users to opt-out of ESLint errors during development.
Since that time, another change was made that allows us to have similar behaviour to before.
- https://github.com/webpack-contrib/eslint-webpack-plugin/pull/72#issuecomment-773706538
- https://github.com/webpack-contrib/eslint-webpack-plugin/pull/85
With this new version of the plugin, we can now show errors in the terminal as errors - but as we've just rolled out the previous change, it made more sense to just fix the behaviour today. We can look at how to improve this further in future iterations.
Closes #9887.

Upgrade eslint-webpack-plugin to fix opt-out flag

---

packages/react-dev-utils/package.json

Resolves #10411
Bumps immer version to 8.0.1 to address the prototype pollution
vulnerability with the current 7.0.9 version.

update immer to 8.0.1 to address vulnerability

---

packages/react-dev-utils/getProcessForPort.js

@zpbrent (https://huntr.dev/users/zpbrent) has fixed a potential Command Injection vulnerability in your repository 🔨. For more information, visit our website (https://huntr.dev/) or click the bounty URL below...
Q | A
Version Affected | *
Bug Fix | YES
Original Pull Request | https://github.com/418sec/create-react-app/pull/2
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/npm/react-dev-utils/1/README.md
react-dev-utils includes some utilities used by Create React App.
The function getProcessForPort in react-dev-utils is vulnerable to command injection.
Used child_process.execFileSync() instead of child_process.execSync().
The use of the child_process function execSync() is highly discouraged if you accept user input and don't sanitize/escape them. This PR …

Security Fix for Command Injection - huntr.dev

---

packages/react-dev-utils/ModuleNotFoundPlugin.js

Support both "SingleEntryPlugin" and "EntryPlugin"
ref: https://webpack.js.org/blog/2020-10-10-webpack-5-release/#minor-changes
Part of making way for Webpack 5 #9994 
`yarn docker:e2e --test-suite simple` not tested - but done manual QA*

Update ModuleNotFoundPlugin to support Webpack 5

---

packages/react-scripts/config/webpack.config.js

After upgrading Create React App to `v4`, the exported SASS variables did not work anymore in my project. [This was a known issue for CRA@v4](https://github.com/facebook/create-react-app/issues/10047).
In CRA@v4, `css-loader` was upgraded from v3 to v4. In `css-loader` v4 there [was a bug](https://github.com/webpack-contrib/css-loader/issues/1134) that did not handle ICSS (the syntax within CSS modules used to `:import` and `:export`) imports properly. This has been resolved by adding the `compileType` property in v4.2.0.
In the README of `css-loader`, there is a whole section about how to configure your setup to support ICSS properly when used together with CSS modules ([see here](https://github.com/webpack-contrib/css-loader#separating-interoperable-css-only-and-css-module-features)).
* …

Fix ICSS syntax in stylesheets

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG-0.x.md
CHANGELOG-1.x.md
docusaurus/docs/adding-css-reset.md
docusaurus/docs/code-splitting.md
docusaurus/docs/deployment.md
docusaurus/docs/importing-a-component.md
packages/babel-preset-react-app/README.md
packages/eslint-config-react-app/README.md

Upgraded all `http` links to `https` that support the `https` protocol.
<details>
<summary>All upgraded links</summary>
Links
---
https://exploringjs.com/es6/ch_modules.html
https://yarnpkg.com/
https://i.imgur.com/1FLa9Tg.gif
https://facebook.github.io/jest/docs/getting-started.html
https://facebook.github.io/jest/blog/2016/10/03/jest-16.html
https://github.com/gaearon
https://facebook.github.io/jest/blog/2017/05/06/jest-20-delightful-testing-multi-project-runner.html#breaking-changes
https://browserl.ist/
https://2ality.com/2017/01/import-operator.html#loading-code-on-demand
https://console.amplify.aws
https://babeljs.io/docs/plugins/transform-object-rest-spread
https://eslint.org/docs/user-guide/configuring
https://babeljs.io/docs/plugins/transform-react-jsx
</details>

Upgrade docs http links to https

---

docusaurus/docs/adding-a-sass-stylesheet.md
docusaurus/docs/adding-bootstrap.md
packages/react-dev-utils/formatWebpackMessages.js
test/fixtures/webpack-message-formatting/index.test.js

In addition to updating the docs to reference `sass` and its latest features, I've also updated the docs to [reflect the fact](https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules) that we don't need the '~' prefix to resolve modules from `node_modules` anymore.
Closes #10045, closes #10771

Suggest sass instead of node-sass package

---

packages/react-scripts/config/env.js

Related Issue: https://github.com/facebook/create-react-app/issues/9984#
Without `FAST_REFRESH=false`, auto reload on `src/index.js` does not work. 
According to comment, `react-refresh` should be disabled by default.
This commit changes default value of `process.env.FAST_REFRESH`.
For testing
`$ yarn create-react-app path/to/app`.
Edit `path/to/app/src/index.js`.

Remove outdated comments on react-refresh

---

docusaurus/docs/using-the-public-folder.md

Replace the Github home link with a link to the repo's main page or a link to the source (https://github.com/CodeByZach/pace/blob/master/pace.js)

Fix link address

---

packages/react-dev-utils/package.json

Bump immer minor version to fix `Prototype Pollution` Security issue.

Bump immer version for fixing security issue

---

packages/react-scripts/scripts/utils/verifyPackageTree.js

This PR follows #10170 and ensures that we no longer "verify" `eslint` and `babel-eslint` versions if the user has opted out of the plugin completely.
Related comment: https://github.com/facebook/create-react-app/pull/10170#issuecomment-767080023

Remove ESLint verification when opting-out

---

packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json
packages/react-scripts/scripts/build.js

This PR is the next step to improve debugging of dependency (node_modules) code when running CRA apps in a debugger like Chrome or VSCode. This PR continues my previous PR, #7022, that changed babel config to ensure that sourcemaps would be generated properly for dependency libraries, including react itself.
However, what's still broken is the case where node_modules libraries include sourcemaps. This is increasingly common as more libraries are written in typescript and/or use features like async/await that make it very difficult to debug transpiled code.  When debugging current CRA apps, you can't step into or set breakpoints in original (ES6, typescript, etc.) library source code.  You can only debug transpiled code which can be very challenging for async-heavy or TS code.
To enable …

Add source-map-loader for debugging into original source of node_modules libraries that contain sourcemaps

---

packages/create-react-app/createReactApp.js

Coerces Node versions with metadata, to support `-nightly`, `-rc`, etc.
Closes #9614.

Coerce Node versions with metadata

---

packages/create-react-app/createReactApp.js
packages/react-scripts/scripts/init.js

This should improve the situation with https://github.com/facebook/create-react-app/issues/11174 somewhat.
These "audits" are pretty much always misleading for build tooling and get people into a hopeless rabbit hole of trying to work around issues that aren't real problems. Let's suppress the audit on the first run. The user can always do it themselves if they want to, but it's pretty much always misleading and harmful.

Run npm with --no-audit

---

packages/react-dev-utils/webpackHotDevClient.js

Fast Refresh requires the HMR runtime to support bail out behaviour (we do not do so within the core runtime as it has to be platform agnostic) - and currently webpackHotDevClient does not do so properly as it circumvents the logic for forced reloads completely when using Fast Refresh.
The changes done here ensures that:
- If Fast Refresh is not enabled, we would always bail out to a forced reload;
- If Fast Refresh is enabled and there are updated modules, it indicates the update has at least partially executed, and we can rely on Fast Refresh being resilient to errors and skip the forced reload;
- If Fast Refresh is enabled and there are none updated modules, check for the status of the hot update. If it is `abort` or `failed`, it indicates the update cannot be executed without being …

fix: fast refresh stops on needed bail outs

---

packages/react-scripts/package.json

The latest release of `workbox-build` is not being pulled by `react-scripts` due to an explicit dependency on `workbox-webpack-plugin@6.1.5`.
Since there are no breaking changes mentioned in the Workbox [releases notes](https://github.com/GoogleChrome/workbox/releases/tag/v6.2.0), this PR updated the version to `6.2.0`

fix: dependency issue after workbox-webpack-plugin 6.2 release

---

packages/react-scripts/config/webpackDevServer.config.js

working with module federation locally in development mode requires CORS. This PR enables that.

allow CORS on webpack-dev-server

---

packages/confusing-browser-globals/README.md
packages/cra-template-typescript/template.json
packages/cra-template/template.json
packages/create-react-app/createReactApp.js
packages/create-react-app/index.js

Bump template dependency version

---

docusaurus/docs/deployment.md

As you can see [here](https://github.com/vercel/serve/releases/tag/13.0.0), the default port of `serve` has changed with its latest release, in response to Apple having claimed `5000` with the macOS Monterey update.

The default port used by `serve` has changed

---

.github/workflows/build.yml
.github/workflows/integration.yml
.github/workflows/lint.yml
azure-pipelines-test-job.yml
tasks/e2e-behavior.sh
tasks/e2e-installs.sh
tasks/e2e-kitchensink-eject.sh
tasks/e2e-kitchensink.sh
tasks/e2e-simple.sh
tasks/local-test.sh
tasks/publish.sh

Previously, individual tests were updating `npm` and running `npm install`, which was redundant with the config in the test runner.
This also updates all test runners to `npm@8` and fixes the local Docker test runner, which wasn't working previously.

chore(test): make all tests install with `npm ci`

---

package-lock.json
packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json
tasks/cra.js

Load the Tailwind PostCSS plugin if the project includes a `tailwind.config.js` file

Add support for Tailwind

---

docusaurus/docs/adding-typescript.md

This change isolates npm command and yarn command because if it is in the same shell code then both gets copied at the same time when copy button is clicked.

prevent both npm and yarn commands from being copied

---

packages/react-dev-utils/noopServiceWorkerMiddleware.js
packages/react-dev-utils/redirectServedPathMiddleware.js

This avoids issues encountered on non-posix compliant systems.
The issue was first identified from a Windows system attempting to utilize noopServiceWorkerMiddleware. The platform-specific separator implemented by path.join would render a mismatch in any non-empty path provided and thus would not result in the service-worker.js file being provided through the middleware.
Further investigation of the react-dev-utils found a similar scenario in redirectServedPathMiddleware. Both path.join calls were adjusted to path.posix.join to ensure that posix compliance is preserved in urls for both of these middleware, in their comparison or redirection.
At present there are several open issues which may be impacted by this pull request. If needed I can do sufficient investigation to compile a list of …

Ensure posix compliant joins for urls in middleware

---

docusaurus/website/package.json
tasks/publish.sh

Docs package was causing errors when running Lerna to publish packages.

Ignore docs when publishing

---

packages/create-react-app/createReactApp.js

Make the latest version check a bit less aggressive and let the process continue. Fixes #11772 and #11754.

Warn when not using the latest version of create-react-app but do not exit

---

docusaurus/website/docusaurus.config.js

https://github.com/facebook/create-react-app/pull/12113 introduced a change in the Algolia credentials, which made the search throw an error. As the credentials were still the one of our legacy infrastructure, this PR updates them to use the [new infrastructure](https://docsearch.algolia.com/docs/migrating-from-legacy) ones.
Maintainers of the previous application should have receive invites, if it's not the case, please let me know I'll send new ones!
fixes https://github.com/facebook/create-react-app/issues/12164

docs: update Algolia credentials

---

packages/cra-template-typescript/template.json
packages/cra-template/template.json

RTL version 13 was released to support React 18.
Thanks @eps1lon for the hard work on version 13 :)

chore: upgrade rtl version to support react 18

---

package-lock.json
packages/cra-template-typescript/template.json
packages/cra-template-typescript/template/src/index.tsx
packages/cra-template/template/src/index.js
packages/react-scripts/package.json

Fixes #12219 
Since CRA installs React 18 by default now, we should update the template to use the new `createRoot`

Update templates to use React 18 `createRoot`

---

packages/react-scripts/config/webpack.config.js

This is a proposed fix for issue https://github.com/facebook/create-react-app/issues/12229. Following the webpack documentation, `stats` is set such that only errors or warnings are printed by webpack. This was tested by running `npm start` locally.

fix: webpack noise printed only if error or warning

---

docusaurus/docs/setting-up-your-editor.md

Here's a screenshot of the page with the current CRA link. 
I updated it to lead to that debugger, so that readers don't get confused..

update a debugger for VS Code

---

README.md

Quick PR to update two links to `www.reactjs.org` in the `README`.

Update links in `README`

---

docusaurus/docs/deployment.md

GitHub now uses the name `main` instead of `master` for the default branch.  This PR updates the documentation to reflect those changes so users can cut and paste sample code.  https://github.com/github/renaming

Chore:  Update document to GitHub default branch

---

docusaurus/docs/developing-components-in-isolation.md

With this small pull request, the Storybook documentation is updated to include a more recent video/gif, and also some of the links were updated as well to redirect to their proper places. 
What was done:
- Updated the location of the gif to Storybook's own repo. 
- Fixed the links currently used to their respective place
The change to the way the gif was being added is intentional, and hope it's fine with all of you. The intention behind this is to avoid having to rely on an external provider and subsequent pull requests. If by any chance the Storybook UI changes, said gif will be updated and with that automatically propagate here.
Feel free to provide feedback

Chore: (Docs) Updates for the Storybook docs

---

docusaurus/docs/pre-rendering-into-static-html-files.md

Since there are references to both `react-snapshot` and `react-snap`. I think they should be in the same format for consistency. Both links to npm packages or both GitHub links.

docs: Make hyperlink consistent

---

packages/react-dev-utils/FileSizeReporter.js

I noticed the code splitting link when doing a production build could be pointing directly to the documentation instead of taking the user through some non-optimal redirects and clicks.

fix code splitting link

---

docusaurus/docs/adding-typescript.md

When adding typescript to an existing Create React App project you have to have tsconfig.json in the project, I believe this change should clarify it for beginners getting stuck on this step. Not sure if providing an example would be too much so I have added a link to the tsconfig.json instead.

Add missing instruction if you are adding typescript

---

package-lock.json
packages/babel-preset-react-app/package.json

In #11318 a change was made to `babel-preset-react-app` to require `@babel/plugin-proposal-private-property-in-object`, but no such dependency was added to `package.json`. This fixes that by adding the dependency.

fix(babel-preset-react-app): add missing dependency

---

README.md
packages/create-react-app/createReactApp.js
packages/create-react-app/package.json

It's probably time to make this project document its status as being deprecated and not recommended for production usage.
To change it:
- I opted to add a header to the README saying its over and you should go look at https://react.dev/learn/start-a-new-react-project
- I left a note saying that if you are following, it is maybe worth carrying on. While I hear react 19 doesn't work with CRA, I wouldn't be surprised that a good chunk of tutorials would still work. Open to being a bit more hard-lined there but there was a lot of great resources for learning react in that era and it seems like a waste to be making people stop early?
- I added a message inside the CLI, it shows once and says "don't use this, use the stuff in https://react.dev/learn/start-a-new-react-project"

Deprecate Create React App officially by changing the README, and adding a message on init

---

packages/create-react-app/createReactApp.js

Updates to a shortlink that we can redirect as needed for old versions. Currently 404

Update deprecation link

---

docusaurus/website/docusaurus.config.js
docusaurus/website/src/pages/index.js

- Adds a banner with deprecation notice
- Adds a noindex meta tag to home page to remove from search
- Add og meta info for when noindex is ignored

Add deprecation to website
