facebook/create-react-app

README.md
Sagui is the single development dependency that provides the tooling required to build, test and develop modern JavaScript applications.
https://github.com/saguijs/sagui
=> Add Sagui to the list of alternatives

.gitignore
The Contributing instructions in the README give my-app as the sample
app name when running `npm run create-react-app my-app`. This just adds
those directories to the .gitignore so they don't accidentally get
committed.
=> Ignores my-app* directories

scripts/init.js, template/gitignore
Might be nice to give the users a .gitignore file to start with ala rails, ember, etc.
=> Adds .gitignore file to default template

template/gitignore
I think it's a good practice to exclude production files (ones created on `npm run build`) by default.
Related to https://github.com/facebookincubator/create-react-app/pull/79
=> Add build directory to gitignore

config/webpack.config.dev.js, config/webpack.config.prod.js
=> Resolve imported CSS files from anywhere

global-cli/index.js, package.json
closes https://github.com/facebookincubator/create-react-app/issues/82
cc @gaearon
=> add node engine to package.json and call checkNodeVersion function in cli

config/eslint.js
Closes #156
Not sure if we can simply delete the line and that'll disable it, so I
went with setting it to 0. Let me know!
=> Disable jsx-handler-name eslint rule

CONTRIBUTING.md
This adds a first CONTRIBUTING.md.
Still missing is something about the release process, and also I think we should add something about how to submit bug reports, similar to the [html5boilerplate CONTRIBUTING.md](https://github.com/h5bp/html5-boilerplate/blob/master/CONTRIBUTING.md)!
Ref #92
=> Add first CONTRIBUTING.md

CONTRIBUTING.md, README.md
- Moved setup instructions to CONTRIBUTING.md, referencing that from the README
- Slightly reworded the setup instructions
=> Contributing instructions step two

scripts/eject.js, scripts/init.js
Fixes #124. Notice that we need to change the path in `package.json` while ejecting since the config folder gets moved.
Tested with Atom (Nuclide) and Visual Studio Code and it works both before and after ejection. ~~I'm not sure about Sublime Text -- seems like `SublimeLinter-eslint` only recognizes `.eslintrc` config. However, it could be fixed by [configuring](https://github.com/roadhump/SublimeLinter-eslint#i-want-not-to-lint-files-if-there-is-no-eslintrc-file-in-project-folder-for-eslint-100) the linter plugin itself. Or even better, could someone who uses Sublime Text send a PR to let it recognize the `eslintConfig` field in `package.json`? :)~~
Edit: @kevinastone confirmed that Sublime Text works fine too.
=> Explicitly specify ESLint config path for editor plugins in package.json

config/webpack.config.prod.js, scripts/build.js, template/package.json
* Require package.json in webpack.config.prod.js and use homepage if set; otherwise use '/'
Fixes #21
=> Don't assume the project is hosted at the root

global-cli/index.js, scripts/init.js
Fixes the instructions printed by the script so that if you create a new app with `create-react-app foo`, it will suggest getting there with `cd foo` rather than `cd /some/big/long/path/foo`.
This will require a new global-cli deploy to work, but it's backward compatible so that the new init script works with the old global-cli (and just is buggy in the same way the current one is).
=> fix cdpath bug

bin/react-scripts.js
No change in functionality, just thought it was easier to understand using `require.resolve` rather than `path.resolve` for resolving the location of a JavaScript file.
=> Simplify path resolving for react-scripts

config/eslint.js, package.json
This project is a really good use case to apply some accessibility rules to the lint config. For beginners getting started with React and/or web in general, we can also teach & enforce basic accessibility rules in the web at author time.
For now, I’ve just applied to the rules that are listed in `eslint-config-airbnb` because these are most real-world tested, and we can continue to add as you see fit.
I know from Twitter that you're wary about adding more dependencies, but very happy to help if there are any questions/issues/concerns about the plugin!
=> Add select eslint-plugin-jsx-a11y rules to lint config.

config/paths.js, config/webpack.config.dev.js, config/webpack.config.prod.js, scripts/build.js, scripts/eject.js, scripts/init.js, scripts/start.js
This makes path calculation explicit so it’s easier to maintain.
In the future we can put `paths.before-eject.js` and `paths.after-eject.js` into separate files so we don’t need to ship dev-only or dep-only code.
I haven’t actually tested this yet.
=> Unroll indirection in paths

template/src/App.css
=> Avoid CSS Globals

config/polyfills.js, config/webpack.config.dev.js, config/webpack.config.prod.js, package.json, scripts/eject.js
I used [promise](https://github.com/then/promise) (maintained by @ForbesLindesay and widely used at Facebook) and [fetch](https://github.com/github/fetch) (pretty much standard in the community).
These will be included for everyone. In terms of size, it adds about 4kB min+gzip, and I think it’s a fair tradeoff for getting these features as baseline since they’re so commonly used in the React tutorials.
Promise rejection tracking is on in all environments. If it truly causes performance issues, we can disable it in production. However I wouldn’t expect it to: front-end code isn’t usually as Promise-heavy as Node. There’s a difference between using a Promise here and there, and creating thousands of Promises in tight loops or whatever it is that most benchmarks measure.
=> Add Promise and fetch polyfills

config/babel.dev.js, config/babel.prod.js
Here is how I verified.
1. cloned create-react-app
2. created .babelrc in the parent directory as specified in #233 
3. ran npm start in create-react-app and got the error message
With the fix in place, I'm no longer getting the "Failed to compile" message.
=> Turn off .babelrc usage (fixes #233)

template/README.md
=> Document how to install a dependency

package.json, tasks/e2e.sh
`trap` provides more robust error handling than `set -e`.  (http://mywiki.wooledge.org/BashFAQ/105)
This may actually fix #163. I was seeing a trapped error when I tried to replicate the state described in that issue, but it'd be helpful to have someone else confirm this.
I also point the npm test command to e2e.sh for convenience. Could go either way on that one. It's unimportant.
Error messages look like:
=> Improve error handling within e2e.sh

bin/react-scripts.js
=> Return proper exit code in bin/react-scripts via spawnSync (#252)

package.json
The `LICENSE` file is being included regardless of what's specified in `package.json/files`.
=> Remove LICENSE from package.json/files

config/eslint.js, package.json, template/README.md
This fixes annoying false positives like `ReactClass` is not defined when using Flow.
=> Tweak ESLint to better understand Flow

config/webpack.config.dev.js, config/webpack.config.prod.js
This enables us to ship them now, and find a way to resolve runtime path without webpack later.
See https://github.com/facebookincubator/create-react-app/issues/255
=> Add a temporary fix for generators

config/webpack.config.prod.js
https://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin
=> Rename compressor field to compress in UglifyJsPlugin settings

CHANGELOG.md
* You can now enable deployment to GitHub Pages by adding `homepage` field to `package.json` ([@dhruska](https://github.com/dhruska) in [#94](https://github.com/facebookincubator/create-react-app/pull/94))
* Development server now runs on `0.0.0.0` and works with VirtualBox ([@JWo1F](https://github.com/JWo1F) in [#128](https://github.com/facebookincubator/create-react-app/pull/128))
* Cloud9 and Nitrous online IDEs are now supported ([@gaearon](http://github.com/gaearon) in [2fe84e](https://github.com/facebookincubator/create-react-app/commit/2fe84ecded55f1d5258d91f9c2c07698ae0d2fb4))
* When `3000` port is taken, we offer to use another port ([@chocnut](https://github.com/chocnut) in [#101](https://github.com/facebookincubator/create-react-app/pull/101), …
=> Changelog for 0.2.0

README.md
https://github.com/kriasoft/react-app - a tool  similar to `create-react-app` with built-in support of CSS Modules, PostCSS, Redux, Browsersync, code splitting, async chunk loading, HMR, React Hot Loader and more awesomeness ;)
[![image](https://cloud.githubusercontent.com/assets/197134/17200248/5022e728-548c-11e6-9c2d-220261c162e8.png)](https://github.com/kriasoft/react-app)
Another difference, is that it suggest a proposes the following project structure in its [default template](https://github.com/kriasoft/react-app/tree/master/template):
```shell
.
├── /actions/                   # Redux actions
├── /components/                # Shared or generic UI components
│   ├── /Button/                # Button component
│   ├── /Layout/                # Website layout component
│   ├── /Link  / …
```
=> Add react-app to Alternatives section in README.md

config/paths.js
I was having difficulties using a local copy of `react-scripts` and `npm link`ing it into a real world project. This change resolves paths relative to the current working directory (that is, most likely the directory of the app) rather than assuming a certain directory structure.
I've tested the "happy path" (that is, the use case I was trying to solve) locally and solved the problem, both by just running `npm start` and `npm run eject`ing and then running the app again. I was unable to test the other case of installing from npm - I'm actually not quite sure how to verify that. I imagine that's pretty important though, so I'd be very open to suggestions and guidance! I did run `npm test` which seems to cover a lot of cases though.
=> Symlink-friendly path resolution

config/webpack.config.dev.js, config/webpack.config.prod.js, scripts/build.js, tasks/e2e.sh
This changes JS/CSS/image paths from flat to being in specific directories:
* `static/js` for JS files
* `static/css` for styles
* `static/media` for everything else
This works both for development and production.
There are a few benefits:
* It’s easier for users to enable CDN caching just for `static` assets (but not for `index.html` in the root).
* It’s easier for us to address #147.
I tweaked the post-build output as well so long paths don’t obscure the sizes:
This partly addresses #246 (except the socket part).
=> Use /static paths for assets

config/webpack.config.dev.js, package.json
Addresses #240.
Plugin works as advertised, both with requires and imports.
I was not sure if we need this in prod, so only included in dev for now. Also, pinned the version as with other dependencies.
=> Webpack plugin to detect case mismatch in requires

scripts/build.js
We need to better educate our users about support for this since it’s implicit.
I keep it dim so it’s less annoying.
Also, this notice will go away once you fill `homepage`.
=> Make GH Pages support more discoverable

scripts/start.js
As discussed in #293, Webpack is watching the `node_modules` directory, which causes high CPU usage in some situations. This PR adds sets the `ignored` watchOption to prevent this.
=> Prevent Webpack from watching node_modules dir

config/webpack.config.dev.js, config/webpack.config.prod.js
Fixes #295. The version is optional so I didn't extract font extensions into a separate loader.
=> Accept version when loading fonts e.g. font-awesome

README.md
Adds the [`dev-toolkit` npm package](https://github.com/stoikerty/dev-toolkit) to the list of Alternatives.
After some suggestions in my last PR https://github.com/facebookincubator/create-react-app/pull/292, I've changed my project to provide better command-line utilities for initializing an app. Managed to get rid of babel's dev-dependencies as well, so this is now a dependency-free project just like `create-react-app` :smiley:
=> Add `dev-toolkit` Alternative

package.json, scripts/eject.js, scripts/start.js, scripts/utils/detectPort.js
This fixes #302 by temporarily forking `detect-port`.
Hopefully this fix will be merged into the original project, and we can refer to it again.
=> Fix port detection lag on OS X with Firewall enabled

CHANGELOG.md
* Fixes an issue with `npm start` taking a very long time on OS X with Firewall enabled ([@gaearon](https://github.com/gaearon) in [#319](https://github.com/facebookincubator/create-react-app/pull/319))
* Fixes an issue with Webpack eating a lot of CPU in some cases ([@dceddia](https://github.com/dceddia) in [#294](https://github.com/facebookincubator/create-react-app/pull/294))
* We now warn if you import a file with mismatched casing because this breaks the watcher ([@alexzherdev](https://github.com/alexzherdev) in [#266](https://github.com/facebookincubator/create-react-app/pull/266))
* CSS files specifying `?v=` after asset filenames, such as Font Awesome, now works correctly ([@alexzherdev](https://github.com/alexzherdev) in …
=> Add 0.2.1 changelog

config/babel.dev.js, config/babel.prod.js, package.json
Test plan: 
```js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
class App extends Component {
async componentDidMount() {
try {
await fetch('http://google.com');
} catch (lol) {
alert('oh noes')
}
}
render() {
return (
<div className="App">
<div className="App-header">
<h2>Welcome to React</h2>
</div>
<p className="App-intro">
To get started, edit <code>src/App.js</code> and save to reload.
</p>
</div>
);
}
}
export default App;
```
It worked.
=> Support async/await

config/webpack.config.dev.js, scripts/eject.js, scripts/utils/WatchMissingNodeModulesPlugin.js
=> Force rebuild after npm install

template/README.md
I've installed both Sublime Text and Visual Studio Code in order to see if I needed to add any extra configuration to make eslint work. 
Since the only editor that I found the issue was Atom, I added
just the instruction for the _linter-eslint_ plugin.
Below is the instruction that I added:
>Note: if you are using the `linter-eslint` plugin on Atom, make sure that **Use global ESLint installation** option is checked.
=> Added a note with instructions on eslint plugin configuration

config/env.js, config/webpack.config.dev.js, config/webpack.config.prod.js, scripts/eject.js, template/README.md
This enables users to specify custom environment variables under a `REACT_APP_*` namespace. To verify it works, I ran the start script via:
```bash
REACT_APP_TITLE="Env-enabled React" npm start
```
And changed the `<h2>` in src/App.js:
```jsx
<h2>Welcome to {process.env.REACT_APP_TITLE}</h2>
```
Which rendered:
=> Adding namespaced environment variables to DefinePlugin under REACT_APP_

package.json, scripts/build.js
This PR closes #326 
1. Run `npm run build` without a `build` folder
* Should not show any difference
2. Run `npm run build` with a `build` folder with no changes
* Should show a green positive difference of zero
* example: `(+0 B)`
3. Run `npm run build` with a `build` folder after adding new code
* Should show a red positive difference of some number
* example: `(+3 B)`
4. Run `npm run build` with a `build` folder after removing old code.
* Should show green negative difference of some number
* example: `(-3 B)`
=> Display Build Size Difference

config/babel.dev.js, config/babel.prod.js, config/env.js, config/polyfills.js, config/webpack.config.dev.js, config/webpack.config.prod.js, scripts/build.js, scripts/start.js
This seems like a nice thing to do since the user will have to deal with this after ejection.
Also serves as a good reminder for us in the future for why we made certain choices.
=> Document configuration and build process

tasks/e2e.sh, tasks/release.sh
`tasks/e2e.sh` and `tasks/release.sh` expect to be run with Bash (`function` etc) but fail in Dash (default Ubuntu `/bin/sh`) or Zsh (my default shell). Add shebangs so they run with the right shell.
=> add shebang to tasks scripts

config/jest/environment.js, scripts/eject.js, scripts/utils/createJestConfig.js
Disable timer mocking and enable verbose output.
This makes my Mocha tests from another projects pass, and makes the output more obvious.
=> Tweak Jest default settings

global-cli/index.js, global-cli/package.json, package.json, scripts/init.js
=> Creating a new app in the current directory

config/polyfills.js, package.json
=> Add Object.assign() polyfill

scripts/utils/createJestConfig.js
Allow three popular conventions:
```sh
**/__tests__/*.js
**/*.test.js
**/*.spec.js
```
=> Allow popular test path conventions

config/webpack.config.dev.js, config/webpack.config.prod.js
=> Fix #316 Add React Native Web support

package.json, scripts/start.js
Ref #387 
Verified by running `npm start` and opening `localhost:3000/page/test.com` in the browser as specified in the initial issue.
=> Disable dot rule of connect-history-api-fallback

config/webpack.config.dev.js
This will work correctly when there are duplicate filenames in different paths.
Fixes: #445
=> Add a hash to media files even in the devmode.

config/eslint.js, config/webpack.config.dev.js, config/webpack.config.prod.js, scripts/utils/createJestConfig.js, template/README.md
Add ability to load `otf` font format in application
=> add otf font format to loaders

config/eslint.js
This rule is considered dangerous in certain situations. This is especially true for Immutable.js users. See the discussion at issue #465 for more information about this.
Fixes #465
=> Deactivate the `new-cap` rule in ESLint

CHANGELOG.md
* `npm install`ing a missing dependency now forces a rebuild. ([@gaearon](https://github.com/gaearon) in [#349](https://github.com/facebookincubator/create-react-app/pull/349))
* Autoprefixer config now includes more commonly supported browsers. ([@kripod](https://github.com/kripod) in [#345](https://github.com/facebookincubator/create-react-app/pull/345))
* All the configuration is now documented inline so ejecting doesn’t leave you in the dark. ([@gaearon](https://github.com/gaearon) in [#362](https://github.com/facebookincubator/create-react-app/pull/362))
* `Object.assign()` polyfill is now bundled by default. ([@gaearon](https://github.com/gaearon) in [#399](https://github.com/facebookincubator/create-react-app/pull/399))
* [React Native …
=> Add 0.2.2 changelog

config/eslint.js, config/webpack.config.dev.js, config/webpack.config.prod.js, scripts/utils/createJestConfig.js, template/README.md
Heres a .webp [file](http://magentafilms.net/img/logos/logo-hero.webp) for testing.
I tested locally by adding the image via ES6 `import `and as a `background-image` property on css.
=> Webp images

global-cli/index.js
According to the official SemVer FAQ, versioning should start at 0.1.0 (http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)
=> Fix default package version added by global CLI

scripts/init.js
Fixes #473. I thought the best approach would be calling `npm view react[-dom] version` and then using the output. If it fails, it falls back to the old method of getting the version. The other alternative I considered was just doing a separate install of react and react-dom, but then you'd end up with more extra npm installs.
Test plan: I ran `init` and the new app had version `^15.3.1` in the package.json, instead of `^15.3.0`, which is how it is in the `create-react-app` repo and when creating a new app off of master.
=> Use most recent React version

CHANGELOG.md
* You can now [proxy requests to an API server](https://github.com/facebookincubator/create-react-app/blob/ef94b0561d5afb9b50b905fa5cd3f94e965c69c0/template/README.md#proxying-api-requests-in-development) without worrying about CORS. ([@gaearon](https://github.com/gaearon) in [#282](https://github.com/facebookincubator/create-react-app/pull/282))
* You can now [pass custom environment variables](https://github.com/facebookincubator/create-react-app/blob/ef94b0561d5afb9b50b905fa5cd3f94e965c69c0/template/README.md#adding-custom-environment-variables) to your application. ([@eliperelman](https://github.com/eliperelman) in [#342](https://github.com/facebookincubator/create-react-app/pull/342))
* You can now [use `async` and `await`](https://ponyfoo.com/articles/understanding-javascript-async-a …
=> Add changelog for 0.2.3

config/webpack.config.dev.js, config/webpack.config.prod.js
Remove the `include` setting from webpack loaders for CSS, JSON and other static assets.
This way it's possible to import files from a separate config folder, a parent directory etc.
Fixes #497.
**Test plan:**
Created a `test-config.json` with contents `{}` in the root folder of `create-react-app` and added `import '../../test-config.json';` to `template/src/App.js`. The app started and was built successfully.
=> Allow importing static files outside src and node_modules folders

README.md
As a contributor, I know where to find the documentation/guide since know the codebase, but I've seen people miss the link to it in the README, because it's not very prominent. Let's try to make it more discoverable by including a link to it right on top of the page.
=> Add a more prominent link to the guide

config/eslint.js
Discussion here: https://github.com/facebookincubator/create-react-app/issues/528
=> removing no-return-assign lint rule

package.json, scripts/eject.js, scripts/init.js, scripts/test.js, tasks/e2e.sh
Fixes #532.
By default project won’t have `--watch`.
We will always assume that `react-scripts test` launches the watcher.
However we offer an escape hatch. If `process.env.CI` is defined, we disable watching. This should satisfy most use cases, and people who really insist on not using a watcher can always `CI=true npm test`. However our intention is to keep improving the watcher and we will push for it to become the default workflow.
=> Enable watch implicitly unless on CI

config/babel.prod.js
Disabled because of issues:
* https://github.com/facebookincubator/create-react-app/issues/525
* https://phabricator.babeljs.io/search/query/pCNlnC2xzwzx/
TODO: Enable again when these issues are resolved.
=> Disable react-constant-elements because of bugs

config/babel.dev.js, config/babel.prod.js, config/webpack.config.dev.js, config/webpack.config.prod.js, package.json
This makes generators work with Jest.
Fixes #255.
Replaces #262.
=> Resolve babel-runtime relative to the config

README.md, template/README.md
=> Document testing

CHANGELOG.md
* Testing is [now supported](https://github.com/facebookincubator/create-react-app/blob/master/template/README.md#running-tests)! ([Jest project contributors](https://github.com/facebook/jest/pulls?q=is%3Apr+is%3Aclosed), [@cpojer](https://github.com/cpojer) in [#250](https://github.com/facebookincubator/create-react-app/pull/250), [@gaearon](https://github.com/gaearon) in [#378](https://github.com/facebookincubator/create-react-app/pull/378), [#530](https://github.com/facebookincubator/create-react-app/pull/530), [#533](https://github.com/facebookincubator/create-react-app/pull/533))
* Static files such as CSS, images, and fonts, can now exist outside `src` directory. ([@fson](https://github.com/fson) in [#504](https://github.com/facebookincubator/create-react-app/pull/504))
* Local …
=> Add 0.3.0 changelog

template/gitignore
Thank you for create-react-app. Really amazing tools greatly packaged up.
I always run my tests with coverage to maintain 100% code coverage so I tried create-react-app 0.3.0 but noticed the coverage folder was not getting ignored by git.
So, this simply ignores the coverage folder since I don't think it belongs in source control.
=> Ignore coverage folder generated by jest

CONTRIBUTING.md
Fixed two typos I found while reading through the updated doc :smile:
=> Fix some typos

config/babel.dev.js, config/babel.prod.js, config/env.js, config/eslint.js, config/jest/CSSStub.js, config/jest/FileStub.js, config/jest/transform.js, config/paths.js, config/polyfills.js, config/webpack.config.dev.js, config/webpack.config.prod.js, global-cli/index.js, package.json, scripts/build.js, scripts/eject.js, scripts/start.js, scripts/utils/WatchMissingNodeModulesPlugin.js, scripts/utils/chrome.applescript, scripts/utils/createJestConfig.js, scripts/utils/prompt.js, tasks/clean_pack.sh, tasks/e2e.sh, tasks/release.sh
- part of #191 
- same as in #206 , can close 206 if this PR is accepted.
- as discussed in #206, the `--smoke-test` tag is kept in production code for now
- in the node_module installed at users side, there will be no `--debug-template` flag
Disscussion 1:  add parameter `stage` to pack.sh so that
- pack.sh prod only ship prod configurations
- pack.sh dev only ship dev configurations
- pack.sh test only ship test configurations
- etc.
This can be done by removing `files` in package.json, and creating a few versions of .npmignore files (e.g. .npmignore.prod).
Disscussion 2: further split paths.prod.js to 2 files, paths.beforeEject.js and paths.afterEject.js; remove the `// Dead code on eject:start/end` block.
Question:
[start.js](https://github.com/facebookincubator/create-react-app/blob/g …
=> Clean publish and eject

template/README.md
Add documentation for Modulus deployment option.
=> Add Modulus to list of deployment options

config/paths.js, scripts/utils/createJestConfig.js, template/README.md
Fix #545 
Run `npm run create-react-app my-app` and in the generated `App.js`, add something like `localStorage.getItem('test');`. Run `npm test`, it should fail because `localStorage` is undefined. Add a `setupTests.js` in `src` that looks like this:
```js
const localStorageMock = {
getItem: jest.fn(),
setItem: jest.fn(),
clear: jest.fn()
};
global.localStorage = localStorageMock
```
Then run `npm test` again (you need to re-run the command in order to have the `setupTests.js` added to Jest config) and it should pass.
You can also simply add a `setupTests.js` that does a `console.log('Hello world')` to check it's properly executed before the tests.
=> Add src/setupTests.js to specify environment setup for Jest (#545)

package.json, scripts/start.js, scripts/test.js
#257 was awesome, let’s reap the benefits (and also clean up some old cruft).
=> Remove code that is unused after publish

scripts/start.js, template/README.md
Fixes #503 (it was never intentionally supported).
Supersedes #226 (I think there is not enough proof that this feature is necessary after #428).
Documents #428.
I understand this will be somewhat controversial because people might rely on this, but if they do, their production builds are already broken right now. This brings our features to consistency and documents the escape hatch that I believe removes the need for #226.
Justification in the comment:
```diff
+    // By default WebpackDevServer also serves files from the current directory.
+    // This might be useful in legacy apps. However we already encourage people
+    // to use Webpack for importing assets in the code, so we don't need to
+    // additionally serve files by their filenames. Otherwise, even if it
+    // works in …
```
=> Disable implicit serving of the source files

template/README.md
Update instructions for `proxy` feature added in #282 to clarify that requests with text/html accept header will not be proxied.
Related to #523.
=> Clarify proxy instructions in generated app README

CHANGELOG.md
For the 0.4.0 CHANGELOG entry, the npm install command should be:
```
npm install --save-dev --save-exact react-scripts@0.4.0
```
Not:
```
npm install --save-dev --save-exact react-scripts@0.3.1
```
=> Fix version in CHANGELOG npm install command

CHANGELOG.md
We missed this one, sorry!
----
Now `favicon.ico` is not treated specially anymore.  
If you use it, move it to `src` and add the following line to `<head>` in your HTML:
```html
<link rel="shortcut icon" href="./src/favicon.ico">
```
=> Add missing breaking change description from 0.3.0

config/webpack.config.dev.js, config/webpack.config.prod.js, scripts/utils/createJestConfig.js
Adds JSX file support.
Connects to #290
=> Adds JSX extension support

package.json, tasks/cra.sh, tasks/e2e.sh, tasks/release.sh
This should fix the problem mentioned in https://github.com/facebookincubator/create-react-app/issues/462#issuecomment-244550135.
=> Fix local end-to-end testing flow

template/README.md
Flow has recently changed its defaults to better fit Create React App.
The only remaining issue is the one with `fbjs` so I left it in the workaround doc.
Great work Flow team!
=> Update Flow instructions

global-cli/package.json, package.json
Add the `engines` field to package.json so users of old Node.js versions
will at least get a warning when trying to install create-react-app:
```
npm WARN engine react-scripts@0.4.1: wanted: {"node":">=4"} (current: {"node":"2.5.0","npm":"2.13.2"})
```
Fixes the issue raised in #570.
=> Warn about unsupported Node.js versions

scripts/utils/createJestConfig.js
The regexes in the Jest `moduleNameMapper` configs were a bit too strict,
causing them to not pick up files with special characters like `@` in the
file path. Change them to match anything with the correct file extension.
Fixes #579.
Test plan:
* Created a file named `template/src/logo@2x.png`.
* Added `import './logo@2x.png';` to `App.js`.
* Ran `npm test`. Tests pass.
=> Fix mocking assets with special characters in the file path

config/babel.dev.js, package.json
=> Avoid tons of *.json.gzip-files created in project root when running with docker node 

package.json
Resolves an issue that can occur in certain situations that causes a build error when user has CDed into an incorrectly cased directory.
=> Bump case-sensitive-paths-webpack-plugin version

scripts/init.js
@fson Ran into major problems with git trying to merge this pull-request:
https://github.com/facebookincubator/create-react-app/pull/363
=> Improve the output of scripts/init.js

global-cli/index.js
=> Check the app name before proceeding.

scripts/start.js
In `scripts/start.js` I removed a double "won't"
=> Fixed typo in code comment

README.md
Following https://twitter.com/MoOx/status/776008513252392960
=> Readme: add Travis-CI badge so people can easily see there is tests

scripts/init.js, template/README.md
**tl;dr** The `eslintConfig` setting is used to make editor plugins such as `linter` use our ESLint configuration, but at the moment this requires additional packages and configuration to work, and we should not create the project with broken configuration. The configuration can still be added manually.
At the moment, when you create an app, the `eslintConfig` setting gets added to package.json. If you have an ESLint package (e.g. [linter](https://atom.io/packages/linter) with [linter-eslint](https://atom.io/packages/linter-eslint)) installed in your editor, you'll get a big error:
This error is shown every time you save a file, so you're forced to figure out what to do, even if you were just starting out and didn't want to configure the integrations yet.
After a little digging you'll …
=> Remove eslintConfig from package.json

package.json
Tested it locally with HTTPS=true (and without). The "WDS Disconnected" message no longer appears, and both HTTP and HTTPS reload correctly when changes are made.
=> Bump webpack-dev-server to version 1.15.2 to fix #574

config/paths.js
This makes all paths returned from `resolveApp()` begin with the `realpath` of the app root, resolving any symlinks etc.
Note: `realpathSync` throws when its argument is a non-existing path, so this change only assumes that `process.cwd()` exists and does a plain `resolve` from there.
@guivho Can you try this in your newly created project? `npm install motiz88/create-react-app#resolve-symlink-cwd && npm start` (later you can do `npm install react-scripts` to restore things to normal).
=> Resolve app paths from realpath of CWD, fix #637

config/eslint.js
This is useful when e.g. using object spread operator to remove only a
certain field from the object.
For example, this can be used to ignore a property from React
component's `this.props`:
```js
class OpinionatedDebugger extends React.Component {
render() {
const { justIgnoreMe: _unused, ...rest } = this.props;
return <pre>{ JSON.stringify(rest) }</pre>;
}
}
```
This PR was asked by Dan via Twitter when he replied to [my tweet about ignoring unused variables with underscore prefix](https://twitter.com/valscion/status/775754615933501440): https://twitter.com/dan_abramov/status/775764929894809602
Write this to any JS file in the project and observe no warnings are shown:
```js
var obj = { a: 1, b: 2 };
var { a: _unused, ...rest } = obj;
console.log(rest);
```
Then try to change it to this …
=> Exempt variables prefixed with underscore from no-unused-vars rule

README.md, template/README.md
Move favicon.ico into src folder.
=> Update file structure in README

ISSUE_TEMPLATE.md
Collecting all the relevant details early on means less back and forth between the poster and project contributors. Asking to create a small reproducible demo means less time wasted trying to repro the bug.
Brunch has been doing this for a while and it has really helped. There are people who deleted the template and went free-form in their bug reports but for the most part, people have actually been filling that in:
https://github.com/brunch/brunch/issues?q=is%3Aissue+is%3Aclosed
A lesser percentage of the people were creating the demos, but a few definitely were. The details, and the demos especially, led to faster resolution times, which a win for everyone.
---
I do see bugs account for about 13% of issues so there might be a bit less value of this than for Brunch, but the first few bug …
=> Add the GitHub issue template

global-cli/index.js
=> Make --scripts-version work with forked react-scripts

config/webpack.config.dev.js, config/webpack.config.prod.js
This is occasionally requested, e.g. for https://github.com/facebookincubator/create-react-app/issues/495. I checked, and `request()` works if I add these mocks.
The mocks are empty objects.
They don’t increase size normally because they are added lazily only if you import them.
=> Provide empty Node mocks for fs, net, tls

CHANGELOG.md
=> Add 0.4.2 changelog

tasks/e2e.sh
I published a `react-scripts-fork` package to npm for testing.
=> Add test for special scripts versions

packages/create-react-app/index.js, packages/create-react-app/package.json, packages/react-scripts/package.json
https://github.com/sindresorhus/path-exists/pull/4#issuecomment-216041493
=> Use pre node@4 compatible `path-exists`

package.json, packages/eslint-config-react-app/index.js, packages/eslint-config-react-app/package.json, packages/react-scripts/package.json
Some new rules had been added that are a good fit for this project. All of these are either already runtime warnings in React (no-danger-with-children, style-prop-object) or React features that are going to be deprecated in the future (no-find-dom-node). The new rules:
* [`react/no-danger-with-children`](https://github.com/yannickcr/eslint-plugin-react/blob/v6.3.0/docs/rules/no-danger-with-children.md) (yannickcr/eslint-plugin-react#710)
* [`react/no-find-dom-node`](https://github.com/yannickcr/eslint-plugin-react/blob/v6.3.0/docs/rules/no-find-dom-node.md) (yannickcr/eslint-plugin-react#678)
* [`react/style-prop-object`](https://github.com/yannickcr/eslint-plugin-react/blob/v6.3.0/docs/rules/style-prop-object.md) (yannickcr/eslint-plugin-react#715)
=> Update eslint-plugin-react and enable new rules

tasks/e2e.sh
In the end-to-end test, we want to test all the latest packages from
the monorepo instead of the versions from npm.
To do this we will now:
* run `lerna bootstrap` in the repo root folder before packaging react-scripts
* bundle the deps like we do for releases, so the e2e test uses those packages
=> Fix the e2e test

tasks/bundle-own-deps.js, tasks/e2e.sh
Only copy our own packages to bundledDependencies in the e2e test.
We previously (#699) added bundling all the dependencies to the e2e test, but this can crash Travis ([#701](https://github.com/facebookincubator/create-react-app/pull/701#issuecomment-248985286)), when it runs out of memory trying to bundle them.
=> Attempt to fix the e2e test

packages/react-scripts/scripts/start.js
=> openBrowser() causes docker-compose set ups to fail because of spawn EACCESS 

packages/react-scripts/package.json, packages/react-scripts/scripts/build.js, packages/react-scripts/scripts/start.js, packages/react-scripts/scripts/test.js, packages/react-scripts/template/README.md, packages/react-scripts/template/gitignore
Adds support to load environment variables via a .env file for development using the very stable and battle tested ⚔ npm package [dotenv](https://github.com/motdotla/dotenv). For more context see https://github.com/facebookincubator/create-react-app/issues/687.
I've tested this out by doing the following:
```sh
npm run create-react-app my-app
cd my-app
echo "NODE_PATH=." >> .env
npm start
```
In `my-app/src/index.js` I changed `import App from './App';` to `import App from 'src/App';` and verified all still works (including tests)
=> Load environment file in development

packages/react-scripts/template/README.md
As promised in #365 , adding notes on enabling Travis CI for a generated app.
- [Demo Repo](https://github.com/Jiansen/CRA-Travis-Demo)
- [Travis Build](https://travis-ci.org/Jiansen/CRA-Travis-Demo)
In the generated app, users will see the note under the **Continuous Integration** section.
In a development branch, run `npm run create-react-app my-app` and check the README.md in the generated app (my-app).
[Build 3](https://travis-ci.org/Jiansen/CRA-Travis-Demo/builds/160884798) encounters the following error on the Node 4 test.  As the Node 6 build succeeds, the failure shall not be related to CRA.
```
> CRA-Travis-Demo@0.1.0 test /home/travis/build/Jiansen/CRA-Travis-Demo
> react-scripts test --env=jsdom
module.js:327
throw err;
^
Error: Cannot find module 'lru-cache'
at …
```
=> Add notes on enabling Travis CI for created repo

packages/react-scripts/scripts/eject.js, packages/react-scripts/scripts/test.js
Fixes #702.
Fixes inconsistencies introduced on eject (e.g. lack of handling of `CI` variable or `dotenv`).
=> Preserve scripts/test.js after ejecting

packages/react-scripts/scripts/start.js
eg: `HOST=test.dev.local npm start` or `npm start`
I tried with and without the env `HOST` and it works as expected.
=> Add host as adjustable parameter through env variables

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json
Fixes #700.
Read about it here: https://twitter.com/dan_abramov/status/779308833399332864.
Test plan:
A. It shows up with `npm start`:
B. `npm run build` output doesn’t include `__source`.
C. It shows up with `npm test`:
=> Add JSX source transform for better warnings

packages/react-scripts/scripts/eject.js, packages/react-scripts/scripts/init.js
Fixes issue described in https://github.com/facebookincubator/create-react-app/issues/682#issuecomment-248781486.
=> Don't hardcode react-scripts package name

packages/react-dev-utils/InterpolateHtmlPlugin.js, packages/react-dev-utils/package.json
Fixes https://github.com/facebookincubator/create-react-app/issues/625#issuecomment-249320724.
=> Fix InterpolateHtmlPlugin only replacing the first occurrence

packages/react-dev-utils/README.md, packages/react-dev-utils/formatWebpackMessages.js, packages/react-dev-utils/package.json, packages/react-dev-utils/webpackHotDevClient.js, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/scripts/start.js
Fixes #89.
Fixes #569.
Fully fixes #263 (we don’t log anything now, and don’t try to reconnect).
Some screenshots:
=> Add syntax error overlay in development

packages/react-dev-utils/webpackHotDevClient.js
Turns out, loading empty iframes is sync in some browsers, and async in others.
Fixes #747.
I also added some code to print errors to the console and clear outdated ones so they don’t distract in the console.
=> Fix error overlay in Firefox

packages/react-scripts/scripts/eject.js, packages/react-scripts/scripts/init.js
=> Forked react-scripts should retain the binary name

packages/react-scripts/package.json
Removes a deprecation warning:
```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
See: https://github.com/jergason/recursive-readdir/pull/39
=> Bump recursive-readdir

packages/react-scripts/scripts/init.js
Otherwise it makes it an invalid path :(
=> Remove the `.` at the end of the init message

packages/react-dev-utils/webpackHotDevClient.js
Minor CSS tweak to the error overlay: fix the right and bottom padding by adding `box-sizing: border-box`.
Before:
After:
=> Fix the right and bottom padding of the error overlay

packages/react-scripts/scripts/eject.js
Implements https://github.com/facebookincubator/create-react-app/issues/766
E2E test ran successfully on my computer.
While running it I discovered that https://github.com/facebookincubator/create-react-app/blob/master/tasks/e2e.sh#L187 does not work, the test ran in `watch` mode anyway.
=> Moved Babel and ESLint config to package.json after ejecting

packages/eslint-config-react-app/index.js
Now allows the use of short circuit and ternary expressions.
Resolves #722.
=> Relaxed eslint rule no-unused-expressions

packages/react-scripts/config/env.js, packages/react-scripts/config/webpack.config.prod.js
Issue: https://github.com/facebookincubator/create-react-app/issues/795
=> Define process.env as object

packages/react-scripts/template/README.md
They accidentally got edited away in #809.
Since Markdown "two spaces" thing is confusing, and short paragraphs look ugly on GitHub, I'm adding explicit line breaks.
=> Add explicit linebreaks

packages/eslint-config-react-app/README.md
I've changed [README.md](https://github.com/facebookincubator/create-react-app/tree/master/packages/eslint-config-react-app#usage-outside-of-create-react-app) of `eslint-config-react-app` package.
It seems #696 doesn't applied to file yet.
Thanks.
=> docs(readme): eslint-plugin-react peer dependencies applied

packages/react-dev-utils/openBrowser.js
A previous commit renamed the apple script to open chrome from
`chrome.applescript` to `openChrome.applescript`. That created
a minor bug. Even when chrome was open with the client app,
`npm start` would open the client app in a new Safari tab on
macOS instead of re-using the open tab in chrome.
=> Fix script name to open chrome

packages/eslint-config-react-app/index.js
I think this is better to surface early because it’s a common mistake and will lead to broken code in 100% cases.
Test plan:
1. Remove `React` from imports in `App.js`
2. See the overlay:
The error is googleable and leads [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md).
=> Promote "React must be in scope" to be an error

packages/react-dev-utils/webpackHotDevClient.js
Support webpack 2 by `webpackHotDevClient`.
Closes #839
=> Make webpackHotDevClient support webpack 2 too

packages/react-scripts/scripts/build.js, packages/react-scripts/template/README.md
fixes https://github.com/facebookincubator/create-react-app/issues/501 https://github.com/facebookincubator/create-react-app/issues/654
=> Update instructions on publishing to GitHub pages

packages/react-scripts/utils/createJestConfig.js
fixes facebookincubator/create-react-app#824
* `setupFiles` now contains only polyfills
* if `src/setupTests.js` file exists, it will be called after test framework initialization
=> Load setupTests file at setupTestFramework stage

packages/babel-preset-react-app/package.json
It looks like `babel-plugin-transform-regenerator` is already a dependency of ` babel-preset-es2015`  in a different version : 
```
$npm ls babel-plugin-transform-regenerator 
babel-preset-react-app@0.2.1 
├── babel-plugin-transform-regenerator@6.14.0
└─┬ babel-preset-latest@6.14.0
└─┬ babel-preset-es2015@6.16.0
└── babel-plugin-transform-regenerator@6.16.1
```
This can causes some trouble when using regeneratorRuntime but to ensure the older npm compatibility we have to keep this dependency. 
So I just updated its version to the same version found from babel-preset-es2015@6.16.0.
=> Remove duplicate transform-regenerator dependency

packages/react-scripts/config/paths.js, tasks/cra.sh, tasks/release.sh
Hi! Was poking around the repo and saw this https://github.com/facebookincubator/create-react-app/issues/765 and thought I'd give it a shot.
I think this mostly works, but I've noticed a bit of destructive package.json touching during the process. Would love to get some feedback at this point and see if this is heading in the right direction.
Thanks!
=> #765 - Work on removing publish feature flags

tasks/cra.sh, tasks/e2e.sh
This continues after #861 and should fully fix #765.
Also fixes #698.
=> Clean up e2e script

packages/react-scripts/scripts/build.js
Until https://github.com/webpack/webpack/issues/2390 is addressed and all errors trigger the `--bail` switch, would be helpful to manually surface them from the production build stats passed in the callback.
Sample output
```
> react-scripts build
Creating an optimized production build...
Error(s) occurred during the production build:
static/js/main.9a6b731a.js from UglifyJs
SyntaxError: Unexpected token: name .....
```
=> Exit production build if any errors are in build stats

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json
=> Disable ES2015 transforms based on node version using babel-preset-env

packages/create-react-app/index.js
`create-react-app myApp --scripts-version=@myscope/react-scripts` fails since `getPackageName` currently assumes a match of "@" at any index denotes version and strips it from the str.
Minor change to fix.
=> Support passing scoped package names to --scripts-version arg

packages/react-dev-utils/webpackHotDevClient.js
Remove error overlay when linting errors have been corrected and the next webpack linting is successful / contains only warnings.
=> Dispose error overlay when linting errors have been corrected

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/package.json
To resolve #600
I use [webpack-manifest-plugin](https://www.npmjs.com/package/webpack-manifest-plugin) on Webpack production configuration to create a file named `asset-manifest.json` which contain a mapping of all asset filenames to their corresponding output file. `asset-manifest.json` will be located at the root of output folder.
Here's the example from a newly created project.
```json
{
"main.css": "static/css/main.9a0fe4f1.css",
"main.css.map": "static/css/main.9a0fe4f1.css.map",
"main.js": "static/js/main.c9af8c27.js",
"main.js.map": "static/js/main.c9af8c27.js.map",
"static/media/logo.svg": "static/media/logo.5d5d9eef.svg"
}
```
You can see that it doesn't map those files from `public/`. What do you think?
=> Create asset filenames mapping on the build output

packages/create-react-app/index.js
For example, react-scripts version`0.2.0-alpha.1` with tarball url didn't works:
```sh
$ create-react-app --scripts-version=https://registry.npmjs.org/react-scripts/-/react-scripts-0.2.0-alpha.1.tgz test-app-tarball-url
Creating a new React app in /Users/archie/Repos/test-app-tarball-url.
Installing packages. This might take a couple minutes.
Installing react-scripts from npm...
> fsevents@1.0.14 install /Users/archie/Repos/test-app-tarball-url/node_modules/fsevents
> node-pre-gyp install --fallback-to-build
...
module.js:457
throw err;
^
Error: Cannot find module '/Users/archie/Repos/test-app-tarball-url/node_modules/react-scripts-0.2.0/package.json'
at Function.Module._resolveFilename (module.js:455:15)
at Function.Module._load (module.js:403:25)
at Module.require (module.js:483:17)
at …
```
=> Fix using pre-release tags with a tarball url in `--scripts-version`

packages/react-scripts/template/README.md
As discussed in [#870](https://github.com/facebookincubator/create-react-app/issues/870)
=> Added note about env server restart

packages/react-scripts/template/README.md
1. Added `:` after `script`.
2. Added extra indent as per the example [here](https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies).
The config now passes YAML validation (was broken before) and I'm using it on Travis CI myself.
=> Fix Travis CI config in template README.md

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json
Should fix #904. This is my first commit to this project- let me know if this is missing anything!
=> Enable babel parameters/destructuring for all versions of Node

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Looks like PostCSS isn't running on stylesheets included via `@import` within another stylesheet. The [postcss-loader docs use `?importLoaders=1` in there configuration](https://github.com/postcss/postcss-loader). Adding it fixed the issue.
**Steps to reproduce:**
1. Create a new app with `create-react-app`
2. Import `App.css` from `src/index.css`
3. Remove `import './App.css'` from `src/App.js`
The `-webkit-` prefix for the `animation` style rule is gone! I've pushed up an example here:
https://github.com/nhunzaker/no-autoprefixer-issue
=> PostCSS should run on @import statements.

packages/eslint-config-react-app/index.js
Enable the [`no-webpack-loader-syntax`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-webpack-loader-syntax.md), (https://github.com/benmosher/eslint-plugin-import/pull/586) rule in eslint-config-react-app.
Fixes #733.
Test plan:
Add this to `App.js`:
```
import 'css!./App.css';
```
=> Forbid Webpack loader syntax in imports

packages/react-scripts/scripts/start.js
This enables compression of generated assets over webpack-dev-server. Especially useful if you're developing on a remote machine with subpar connection speed.
I couldn't think of any test cases but I'm open to suggestions.
=> Enable compression on webpack-dev-server (#966)

packages/react-scripts/template/README.md
gh-pages supports https. It's important for prominent help files to encourage best practices.
=> Gently nudge users towards https by default

packages/react-dev-utils/openBrowser.js
Running `create-react-app` in a Docker container causes an unhandled rejection error in nodejs > 6.5 because the `opn` module tries to open a web browser in a system that doesn't have one. I figured this error could be safely ignored.
=> Catch and noop call to open web browser.

packages/react-scripts/utils/createJestConfig.js
Adding collectCoverageFrom option to the config to cover files that have no tests. This is set to look for any file under the `src/` directory. 
Below is the coverage report prior to the change:
And here is the coverage after the change with the same tests:
It's worth noting this can currently be achieved by passing the arguments through 
`npm test -- --coverage --collectCoverageFrom='src/**/*.{js,jsx}'`. 
This change would make this the default behaviour. If a different path is required then passing it as an argument overrides the default. 
For example if I only cared about the actions folder I could run:
`npm test -- --coverage --collectCoverageFrom='src/actions/*.{js,jsx}'`
A similar PR was already submitted #905 but the author hasn't responded in a while. This is also without the …
=> Add collectCoverageFrom option to collect coverage on files without any tests

packages/react-scripts/template/README.md
Pretty simple docs change:
Recommendations for `package.json` `scripts` for deploying to Github Pages:
```diff
+"deploy": "npm run build && gh-pages -d build"
-"deploy": "gh-pages -d build"
```
It seems very unlikely the user would want to deploy without rebuilding and can be confusing since the dev server automatically rebuilds.
This also adds a line to these deploy docs instructing where to put the `CNAME` file:
```diff
+You can configure a custom domain with GitHub pages, by adding a `CNAME` file to the `public/` folder.
```
This fixes https://github.com/facebookincubator/create-react-app/issues/654
=> Always build before deploying to gh-pages

packages/react-scripts/scripts/eject.js
Verifies that the folders created during an eject (not just the files) do not exist. Exits with error if they do exist.
I tested this by creating `scripts` and `config/jest` folders in the app, then running `npm run eject`. The script failed early on both `scripts` and `config`, as expected. Removing these directories allowed the script to continue running and successfully create the required directories and copy the files over to them.
Closes #939.
=> Check for presence of folders before continuing eject.

packages/react-dev-utils/package.json
Now that [webpackHotDevClient support webpack 2](https://github.com/facebookincubator/create-react-app/pull/840), react-dev-utils should allow the most recent beta release to 🐱.
=> Allow webpack 2 as peerDependency in react-dev-utils

packages/react-scripts/template/README.md
It seems
```js
export default function Header;
```
should read
```js
export default Header;
```
=> Remove redundant `function` from export statement

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json
This replaces the hand-rolled node version setup with a new feature that was introduced in `babel-preset-env@v0.0.7`: https://github.com/babel/babel-preset-env/blob/v0.0.7/CHANGELOG.md
Changes between 0.0.6 and 0.0.8 should be backwards compatible.
https://github.com/babel/babel-preset-env/blob/master/CHANGELOG.md
=> Update babel-present-env and use node: 'current' as target

packages/babel-preset-react-app/index.js
Hi,
This clears the usage of why we have added two plugins separately, rather than not using it via options in babel-preset-react.
=> Explain the usage of react-jsx-source & react-jsx-self

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json
The `babel-plugin-transform-object-rest-spread ` v6.19.0 update made the other two plugins unnecessary as it contains the fixes done in https://github.com/babel/babel/pull/4755
https://github.com/babel/babel/blob/v6.19.0/CHANGELOG.md
Ref https://github.com/facebookincubator/create-react-app/issues/904#issuecomment-261077538 and #927
If you use [`nvm`](https://github.com/creationix/nvm), this is how:
```
nvm install v6.7.0
nvm use v6.7.0
```
```
npm install -g npm@2.x
```
Modify `packages/react-scripts/template/src/App.test.js` to look like this:
```js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
it('renders without crashing', () => {
const fn = ({ a, ...otherProps }) => otherProps;
fn({ a: 1, b: 2 });
console.log(fn({ a: 1, b: 2 }));
const div = …
```
=> Remove unnecessary transform plugins for object spread to work

packages/react-dev-utils/openChrome.applescript
When you start the development server it open a tab with your preferred browser with the site your developing. [The docs for `react-dev-utils/openBrowser` states](https://github.com/facebookincubator/create-react-app/tree/master/packages/react-dev-utils):
> Attempts to open the browser with a given URL.
On Mac OS X, attempts to reuse an existing Chrome tab via AppleScript.
Otherwise, falls back to opn behavior.
The reuse of tabs in Chrome does not work correctly because of a bug in the applescript which this PR provides a fix for. Additionally it now supports tab reuse even if you've navigated in your app with history API, and brings Chrome to the foreground focused after tab reuse.
=> Fix chrome tab reuse

.travis.yml, packages/create-react-app/index.js, packages/react-scripts/config/paths.js, packages/react-scripts/scripts/build.js, packages/react-scripts/scripts/eject.js, packages/react-scripts/scripts/init.js, packages/react-scripts/scripts/start.js, tasks/e2e.sh
[Yarn](https://yarnpkg.com/) is a new fast, reliable and secure alternative to the npm client.
This pull request adds support for Yarn in Create React App. See discussion in #896.
In the `create-react-app` command, we try to install packages using Yarn. If Yarn is not installed, we use npm instead. In `react-scripts`, we detect if the project is using Yarn by checking if a `yarn.lock` file exists. If the project is using Yarn, all the instructions are displayed with Yarn commands and Yarn is used to install packages in `init` and `eject` scripts.
=> Support Yarn

packages/react-scripts/scripts/build.js
Add `--dev` argument to the `yarn add gh-pages` message to match the npm one.
=> Add missing dev argument in build script message

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/package.json
Update css-loader which disables its use of autoprefixer.
<https://github.com/webpack/css-loader/releases/tag/v0.26.0>
=> Update css loader

packages/react-scripts/config/jest/transform.js
=> Don't look for babelrc file during test

packages/react-scripts/config/webpack.config.dev.js
see: https://github.com/facebookincubator/create-react-app/issues/920
=> Enable sourcemaps in development

packages/react-scripts/template/README.md
Add instructions on how to add Storybook to the User Guide.
I also mentioned a bit of information about benefits of using Storybook.
Related to: https://github.com/facebookincubator/create-react-app/issues/297#issuecomment-249055979
=> Add Storybook to the user guide

packages/react-scripts/template/README.md
=> Added info on using global variables.

README.md
This rule seems to be limiting development of this package. While it's certainly better to provide ready-to-use module that one doesn't need to configure, preventing configuration all together is constraining developers, forcing them to develop workarounds.
Besides this rule is already broken with `NODE_ENV` and `proxy` configuration and will be with plugins and `PUBLIC_URL`, `BROWSER`, `browsers` in package.json, and many others.
=> No Configuration -> Convention over Configuration

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, tasks/e2e.sh
Loads all files in appSrc not already handled by other loaders.
Also, switch image loading from file loader to url-loader.
Fixes #667.
=> Use url-loader with limit 10k as a default loader.

packages/react-scripts/template/README.md
Adds documentation for deploying to AWS S3 and CloudFront.
Just a link to a blog post I wrote on the subject. This change was requested by @gaearon in issue #997.
=> Adds to docs - deployment with S3/CloudFront

CONTRIBUTING.md, packages/react-scripts/package.json, tasks/cra.sh, tasks/e2e.sh, tasks/release.sh, tasks/replace-own-deps.js
* Remove bundledDependencies
* Change the e2e scripts to use local file dependencies instead of bundledDependencies to test the packages
=> Remove bundledDependencies

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
=> exclude html from default loader.

packages/react-scripts/package.json, packages/react-scripts/scripts/build.js, packages/react-scripts/scripts/eject.js
Saves a dep since we already bring in `fs-extra`
=> Replace rimraf with fs-extra functions

packages/eslint-config-react-app/index.js, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/utils/createJestConfig.js
=> Fix wp loaders

packages/babel-preset-react-app/README.md, packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json
Addresses https://github.com/facebookincubator/create-react-app/issues/899
=> Enable useBuiltIns option on object-rest-spread

packages/react-dev-utils/README.md, packages/react-dev-utils/getProcessForPort.js, packages/react-dev-utils/package.json, packages/react-scripts/scripts/start.js
Hello awesome contributors,
In #441, there are was a request to guess the name of the existing process running on the default port when starting CRA. So, building on the incomplete yet solid work done in #454, this PR aims to complete that feature.
It shows the app's name and directory.
Note: `my-test-app` is the name of a CRA app in `~/dev/test2`
It shows the command name and directory.
It shows the original, generic message.
=> add logging of existing default port process on start

packages/react-scripts/template/README.md
Minor additional information on how to solve watchman problems reported in #713 and #1767
=> Add a note for OSX users about watchman and jest

packages/react-scripts/scripts/start.js
Added `ws: true` to the httpProxyMiddleware options, and also listen
for the "upgrade" event so that websockets can be proxied immediately,
rather than waiting for an initial HTTP request.
I modified the template `App.js` and added a `componentDidMount` that creates a websocket. It tries to connect to localhost:3000, the webpack dev server.
```javascript
componentDidMount() {
let s = new WebSocket("ws://localhost:3000/");
s.addEventListener('message', m => console.log(m.data));
s.addEventListener('error', m => console.log(m));
s.addEventListener('open', m => {
console.log(m);
s.send("hey there!");
});
}
```
Then, in `packages/react-scripts/package.json`, added the `proxy` option:
```
"proxy": "http://localhost:4000"
```
(it works with `http` and with `ws` -- no need for `ws` though …
=> Enable proxying of websockets

packages/react-scripts/scripts/start.js
=> Add support for non-interactive terminal

packages/react-scripts/template/README.md
Adds a note about VS Code Jest, didn't try to pitch too hard, given that at this stage of the doc you don't know too much about Jest other than the watcher.
@cpojer your call on the "Similar support for Nuclide is in the works" otherwise I'm happy to remove it.
Screenshot looks like:
=> Add a note about vscode-jest

packages/react-scripts/scripts/build.js, packages/react-scripts/template/README.md
Fixes issue #906.
Whenever someone runs the build script with the environmental variable `CI` set to true then it will crash when any linter warnings are encountered.
``` sh
CI=true npm run build
```
I have tested this locally by generating an app using `create-react-app` and the updated `react-scripts`. Is this enough or should there be an automated way of testing this functionality? If so, can anyone give some advice on how to go about testing this?
I am also struggling to find the best location to document this feature. I considered updating the   `npm run build` section of the README with this information however, I am afraid that explaining this feature in that location will only detract from the clarity to the reader. Perhaps I should create a new section in the user guide where …
=> Crash the build during CI whenever linter warnings are encountered

.gitignore, CHANGELOG.md, lerna.json, package.json
[Lerna Changelog](https://github.com/lerna/lerna-changelog) allows us to generate a scaffold for the changelog, a list of changes with all the PR and contributor links in place, from labeled GitHub pull requests.
I added the following labels (inspired by [Babel's change log](https://github.com/babel/babel/blob/v6.19.0/CHANGELOG.md#changelog) which is also made with Lerna Changelog).
* `tag: new feature`: :rocket: New Feature – Features added in this release.
* `tag: breaking change`: :boom: Breaking Change – Breaking changes should be accompanied with a migration guide for users in the change log.
* `tag: bug fix`: :bug: Bug Fix
* `tag: enhancement`: :nail_care: Enhancement – Changes to existing features.
* `tag: documentation`: :memo: Documentation –  Contributions to docs can also be …
=> Update changelog for 0.8.0 and add Lerna Changelog

packages/react-scripts/utils/createJestConfig.js
Jest matches moduleNameMapper regexes with module names, not the full file path, so the negative lookahead doesn’t work for filtering out JS files, because they can be imported without the extension. So paths like `lodash.assign` and `../utils/range` were mislabeled as resources with unknown file extensions because they have a dot in the name.
As a stopgap measure, revert the moduleNameMapper regex added in #1077.
This will fix issues #1145 and #1147. However, since the behaviour will now differ for obscure file extensions not listed in the whitelist, we should try to find a way to support the same behaviour as we have for webpack loaders (map any unknown file type mapped to a stub).
=> Revert Jest moduleNameMapper regex back to a whitelist

packages/eslint-config-react-app/index.js
Fixes https://github.com/facebookincubator/create-react-app/issues/1158
=> Make jsx-no-undef rule an error

packages/react-scripts/utils/createJestConfig.js
In my tests, jsdom was throwing a "SecurityError" at HistoryImpl._sharedPushAndReplaceState (node_modules/react-scripts/node_modules/jsdom/lib/jsdom/living/window/History-impl.js:87:15)
This happens because document.URL defaults to "about:blank". Unfortunately, if you interact with the History object it tries and fails to parse the URL, causing a "SecurityError" to be thrown. Setting the default URL to "http://localhost" fixes this issue.
=> Add testURL to jest config

packages/react-scripts/template/README.md
Based on info in https://github.com/facebookincubator/create-react-app/issues/1133#issuecomment-264612171.
=> Add "npm run build silently fails" to Troubleshooting

packages/react-scripts/template/README.md
The User Guide does not actually document what `npm run build` does. The docs also don't describe how exactly to "deploy" the resulting `build` directory. 
This PR describes what `npm run build` does and what it means to deploy the build in the Users Guide. 
Additionally, it describes the `pushState` gotcha which was previously only described in reference to specific servers (eg github pages).
=> Document what npm build does and pushState

tasks/e2e.sh
Should fix https://github.com/facebookincubator/create-react-app/issues/1166.
Root cause is https://github.com/yarnpkg/yarn/issues/2142.
=> Fix end-to-end test on Yarn

packages/react-scripts/template/README.md
A step by step guide to deploying a recent created react app (with create-react-app) to the Firebase CDN.
=> Add deploy to Firebase CDN on template's README (Closes #374)

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
=> Remove path module from webpack config on eject.

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/package.json
This pull request will add to `create-react-app` the ability to inject into the final html page the integrity hashes required to take advantage of [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) (when the browser supports it)
=> Add Subresource Integrity support

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json
As said in #1156 and #1160 it seems that `babel-plugin-transform-regenerator` needs some additional plugins to work, and `babel-preset-env` is unable to detect it.
=> [babel-preset-react-app] Temporary fix missing babel plugins

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json
This is a followup to #1177 with a less aggressive fix.
For context, read threads #1156 and #1160.
Why this works:
* Babel has a bug where object/spread depends on parameters transform: https://github.com/babel/babel/issues/4851. So we have to enable parameters.
* Including regenerator transform in `test` environment was incorrect. Its `async: false` option only made sense for `development` and `production` configuration where we use `babel-preset-latest`, and so async functions are already being handled. But for `test` environment we use `babel-preset-env` instead of `babel-preset-latest`, and so including regenerator second time is redundant (and somehow breaks things—@hzoo could you clarify why this happened?)
I am remove `destructuring` and `arrow-functions` because they were added as …
=> Fix Babel issues in tests by applying the right transforms

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, tasks/e2e.sh
This pull request closes issue #1153 .
The problem with base64 inlining svgs is that it breaks [fragment identifiers](https://css-tricks.com/svg-fragment-identifiers-work/) which are used in [sprite systems](http://una.im/svg-icons/) .
If the user wants to inline an svg they could put it directly into components like @gaearon [said](https://github.com/facebookincubator/create-react-app/issues/1153#issuecomment-264739469)
=> Use file-loader for svgs

packages/react-dev-utils/openChrome.applescript
> ~~Still WIP: need to clean up duplicated code and found some unexpected behavior (both in master and this branch)~~
on `start`script - If there're no debugging tab (localhost:3000) open, we will try to use empty tab instead of create new one. (fixes #1157)
**Test plan**
To invoke script, We can use both `npm/yarn start` or run `osascript openChrome.applescript localhost:3000` inside `/packages/react-dev-utils` folder .
- **No open chrome window**: When chrome open with an empty tab, use the empty tab instead of create new one.
- **Chrome window with debugging tab**: Reuse debugging tab.
- **Chrome window w/o debugging tab**: Create new tab with url.
- **Chrome window w/o debugging tab, but have an empty tab**: Use empty tab. 
```bash
npm run create-react-app my-app
cd my-app
yarn start …
```
=> Chrome 'open tab' reuse an empty tab when possible

packages/react-scripts/config/webpack.config.prod.js
@gaearon This is a follow up to #1176 - I discovered a small issue while making intensive tests till I landed here: https://github.com/waysact/webpack-subresource-integrity/issues/20
=> Set crossOriginLoading to anonymous in output

packages/react-scripts/package.json
Should fix #1186.
The fix works because Webpack dependency bumps `webpack-core` which bumps `source-list-map` which includes https://github.com/webpack/source-list-map/pull/2.
That fix was necessary because Babel started adding variable names to source maps in https://github.com/babel/babel/pull/3658 but Webpack didn't add support for this format.
=> Update Webpack to fix source map issues

packages/eslint-config-react-app/package.json
Fixes #1110.
We still pin them in `react-scripts` itself but this should help people using the preset directly.
=> Relax peerDependencies for ESLint preset

packages/react-scripts/config/paths.js
We used to honor `NODE_PATH` because it provides a relatively convenient way to allow absolute imports for people who need them: `NODE_PATH=src npm start`.
However this backfired with #1023 and #815.
The best analysis is in https://github.com/facebookincubator/create-react-app/issues/1023#issuecomment-265344421.
Sometimes, a module (which may be inside a dependency) may depend on Node core modules like `events`. In this case Webpack attempts to shim it with [node-libs-browser](https://github.com/webpack/node-libs-browser). However it only attempts to shim it if it can't resolve the module name using the regular mechanism. The problem is that [some Linux distributions include Node sources into `NODE_PATH`](https://github.com/facebookincubator/create-react-app/issues/1023#issuecomment-264064 …
=> Only honor relative NODE_PATH

CHANGELOG.md
* [#1176](https://github.com/facebookincubator/create-react-app/pull/1176) Add Subresource Integrity support. ([@XVincentX](https://github.com/XVincentX))
The generated HTML now includes [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) attributes ensuring that your users aren't served malicious code if your CDN gets compromised.
* [#1197](https://github.com/facebookincubator/create-react-app/pull/1197) Let Jest handle all file types. ([@gaearon](https://github.com/gaearon))
Since 0.8.0, we started treating imports of any unknown file extensions as URLs. However, we had to revert this change for the test configuration in 0.8.1 because of a bug causing false positives. In 0.8.2, we are fixing this and …
=> Add changelog for 0.8.2

packages/react-scripts/utils/createJestConfig.js
This small change fixes #1085. Basically it includes @gaearon's suggested fix.
=> Instruct Jest to load native components from RNW instead of RN

packages/create-react-app/index.js
Maybe fixes #1200.
Apparently `spawn` sometimes fails synchronously and sometimes fails in an event emitter.
I restructured the code a tiny bit.
=> Catch synchronous errors from spawning yarn

CHANGELOG.md
* [#1204](https://github.com/facebookincubator/create-react-app/pull/1204) Catch synchronous errors from spawning yarn. ([@gaearon](https://github.com/gaearon))
Fixes a crash when running `create-react-app` in some cases.
* [#1203](https://github.com/facebookincubator/create-react-app/pull/1203) Update webpack-subresource-integrity to fix Windows builds. ([@gaearon](https://github.com/gaearon))
Fixes a crash when running `npm run build` on Windows.
* [#1201](https://github.com/facebookincubator/create-react-app/pull/1201) Instruct Jest to load native components from RNW instead of RN. ([@remon-georgy](https://github.com/remon-georgy))
Fixes tests for users of React Native Web.
* …
=> Add 0.8.3 changelog

packages/react-dev-utils/openChrome.applescript
fixes #1213
I accidentally changed "Chrome" to "Google Chrome" in #1165. It forces to open Chrome Stable instead of default browser in system-wide (eg. Chrome Canary).
- Use “Chrome” instead of "Google Chrome", It will try to use current active browser. otherwise, use default.
- If no “Chrome” aren’t running, will fallback to opn(url)
=> Fix - openChrome won't open default browser (using Canary)

packages/react-scripts/template/README.md
Adding this section to the troubleshooting documentation:
[Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) digests are added to the build output files. For a particular scenario, these checks may fail when deployed. The files are built using `LF` characters, but if your deployment uses a Git repository for deployment (like Azure web sites) and the Git repository is set up to translate `LF` characters into `CR/LF` characters, then the checked out files will be different and the digests will be invalid.
To fix this, just add a `.gitattributes` file to your deployment repository that will ensure the build files are not modified when checked out:
```
*.css text eol=lf
*.js text eol=lf
```
=> Adding troubleshooting information about Subresource Integrity digests.

packages/react-scripts/scripts/build.js
resolve #1221 
Disable github page setup instruction if `scripts.deploy` has been added to `package.json`
**No deploy script**
```bash
> yarn run build
The build folder is ready to be deployed.
To publish it at http://myname.github.io/myapp, run:
yarn add --dev gh-pages
Add the following script in your package.json.
// ...
"scripts": {
// ...
"deploy": "npm run build&&gh-pages -d build"
}
Then run:
yarn run deploy
✨  Done in 7.45s.
```
**after added deploy**
```bash
The project was built assuming it is hosted at /myapp/.
You can control this with the homepage field in your package.json.
The build folder is ready to be deployed.
To publish it at http://myname.github.io/myapp, run:
yarn run deploy
✨  Done in 7.08s.
```
=> Disable gh-page setup instruction if scripts.deploy has been added

packages/create-react-app/index.js
* Remove the `'yarn' is not recognized as an internal or external command, ...` message on Windows.
* Simplify the detection code: just run `yarn --version` – if it succeeds use `yarn`, if it fails use `npm`.
* Pass the `--verbose` option to Yarn if given, Yarn supports it now.
Tested on macOS and Windows 10.
=> Clean up Yarn detection and install code

packages/create-react-app/index.js
Previously create-react-app exited with 0 after an installation error.
=> Exit with an error code when npm/yarn install fails

packages/react-dev-utils/formatWebpackMessages.js
fixes #1218 
Since I can't reproduce it by myself, I use https://github.com/dtinth/pixelpaint to reproduce and verify. 
**Result**
```
Compiled with warnings.
Warning in ./src/App.js
/Users/n3tr/Code/js/pixelpaint/src/App.js
45:49  warning  Unexpected mix of '&&' and '||'  no-mixed-operators
46:44  warning  Unexpected mix of '&&' and '||'  no-mixed-operators
✖ 2 problems (0 errors, 2 warnings)
Warning in ./src/ReduxCanvasV3.js
/Users/n3tr/Code/js/pixelpaint/src/ReduxCanvasV3.js
25:5  warning  Expected a default case  default-case
✖ 1 problem (0 errors, 1 warning)
You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```
=> Fix weird lint output 

packages/react-dev-utils/README.md
...since the old url links to a `404` page
=> [documentation] fix html-dev-plugin link in react-dev-utils doc

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/package.json, packages/react-scripts/template/README.md
We need to disable subresource integrity for now due to discussion in https://github.com/facebookincubator/create-react-app/issues/1231.
SRI causes problems for users who don't serve their apps over HTTPS, and we need to disable this until we incorporate a work-around or make the behavior opt-in.
=> Disable subresource integrity temporarily

packages/react-scripts/package.json
=> Bump babel-eslint version

packages/react-scripts/scripts/start.js
The new proxy option introduced in #282 works well for GET requests but many browsers send Origin headers with same-origin POST/PUT/DELETE requests.
This pull request makes the http-proxy-middleware to overwrite the original Origin header (if set) to match the target server URL.
=> Proxy rewrites Origin header to match the target server URL

.travis.yml, packages/create-react-app/index.js, packages/create-react-app/package.json, tasks/e2e.sh
[`commander`](https://www.npmjs.com/package/commander) is more easily configurable than the previous tool, and gives some output out-of-the-box.
Also I've bumped the comment on the minimal node version as per #575.
=> Use "commander" for  cli argv handling

packages/react-scripts/scripts/test.js
This PR adds the enhancement described in #1207.
I just added this condition to the addition of the '--watch' flag in the test script. I tested this on my computer and it seems to do the trick, i'm guessing the rest is handled by Jest (make all the tests run when not in watch mode, versus only run tests modified since last commit when watch mode is active).
If there's something I forgot, please let me know.
Also I ran the tasks/e2e.sh script, and it hangs on line 181
```npm run test -- --watch=no``` because it does, in fact, run in watch mode. You have to press 'q' for the script to continue. Is this normal or a regression I introduced ? This seems to be true even on master...
Finally, is there something to add to test the new behavior?
=> Disable jest watch mode when --coverage flag is present [#1207]

packages/react-dev-utils/clearConsole.js
Found this in https://github.com/facebook/jest/pull/2230.
I tried many different options before but this one seems to work most consistently and removes the annoying scrollback both on OS X and Windows.
=> Use a better clear console sequence

packages/create-react-app/index.js, tasks/e2e.sh
Follow-up to #1195 to make the messages prettier.
=> Tweak console messages

packages/react-scripts/scripts/test.js
Jest will release https://github.com/facebook/jest/pull/2230 in Jest 18 but I’d like to fix this asap so I’m monkeypatching this. We’ll remove it when Jest 18 is out and stable.
=> Clear scrollback in test mode

CHANGELOG.md
* [#1233](https://github.com/facebookincubator/create-react-app/pull/1233) Disable subresource integrity temporarily. ([@Timer](https://github.com/Timer))
We added [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) checks to the build output in 0.8.2 but it turns out that they may fail in browsers using special compression proxies, such as Chrome on Android, when served over HTTP. We disabled the checks until we can find a safe way to add them.
* [#1226](https://github.com/facebookincubator/create-react-app/pull/1226) Fix weird lint output. ([@n3tr](https://github.com/n3tr))
Fixes a strange lint message formatting in some edge cases.
* [#1215](https://github.com/facebookincubator/create-react-app/pull/1 …
=> Add 0.8.4 changelog

packages/react-dev-utils/openBrowser.js
Use a 'BROWSER' environment variable with npm start to specify which
browser to open. if the value of 'BROWSER' is not valid executable file,
don't open any browser.
=> Configure which browser to open in npm start (#873)

README.md, packages/react-scripts/template/README.md
=> Add "Changing the Page Title" to User Guide

packages/react-scripts/template/README.md
- helps users resolve 'file/module not found' error encountered while attempting to deploy an app to Heroku using [Heroku Buildpack for create-react-app](https://github.com/mars/create-react-app-buildpack/)
@gaearon
=> Heroku Deployment: Adds a note on how to resolve "File/Module Not Found Errors" 

packages/react-scripts/scripts/start.js
Browser launch can still be suppressed using BROWSER=none
Closes https://github.com/facebookincubator/create-react-app/issues/1263
=> Remove interactive shell check when opening browser on start

packages/react-scripts/template/gitignore
hehe I spent far too long trying to figure out why my build would only work on my computer but not in CI, it was because we had a directory in src literally named `build` that silently not being included in source control (and some red herring errors mislead me into not realizing why). The current generated gitignore excludes all directories named `build | coverage | node_modules`, even ones that aren't in the root.
This changes it to only exclude those which I imagine was intended, only those in the root.
=> Only gitignore dirs in root, not deep

packages/create-react-app/index.js, packages/create-react-app/package.json, tasks/e2e.sh
=> gh-1269: Enabling nested folder paths for project name

packages/react-scripts/package.json, packages/react-scripts/scripts/build.js, packages/react-scripts/scripts/eject.js, packages/react-scripts/scripts/init.js, packages/react-scripts/scripts/start.js, packages/react-scripts/utils/createJestConfig.js
[path-exists](https://www.npmjs.com/package/path-exists) was originally created to support the semantics of deprecated [fs.exists](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) which is used to check if given path exists in the file system asynchronously.
> Because fs.exists() is being deprecated, but there's still a genuine use-case of being able to check if a path exists for other purposes than doing IO with it.
In Create React App [all of the uses](https://github.com/facebookincubator/create-react-app/search?utf8=%E2%9C%93&q=pathExists) of [path-exists](https://www.npmjs.com/package/path-exists) are synchronuous.
The original [fs.existsSync](https://nodejs.org/api/fs.html#fs_fs_existssync_path) is not deprecated, which makes …
=> Remove path-exists from dependencies and replace it with fs.existsSync

packages/react-dev-utils/package.json
As discussed on #1268 there are two incompatible versions of SockJS-Client being used which prevents hot reloads when websocket connections are unavailable (e.g. when a browser doesn't support websockets, or when a CRA app is being proxied by a server that doesn't support them -- the later being my use case).
Normally SockJS can recover from this because it can use AJAX etc., but with two different versions of SockJS-Client it gives up, and throws this error:
Incompatibile SockJS! Main site uses: "1.0.3", the iframe: "1.0.1"
Specifically SockJS-Client 1.0.3 ([`packages/react-dev-tools/package.json`](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/package.json#L31) is incompatible with SockJS-Client 1.0.1 (`react-scripts@0.8.4` depends on …
=> Downgrading to compatible version of SockJS-Client

packages/react-scripts/template/README.md
Removes the duplicate "is" from [the react scripts template README](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md), from when the [Changing the Page title](https://github.com/facebookincubator/create-react-app/commit/587b2f8b590b0854080b25ffc316eafd945f3417#diff-4e6ec56f74ee42069aac401a4fe448adR204) section was added.
=> Fixes duplicate "is" typo

packages/react-scripts/scripts/build.js, packages/react-scripts/template/README.md
Lifecycle hooks on npm scripts are fun, you can `pre` and `post` anything. This avoids using `&&` in a script which can be a bit harder to debug (not really a cross-platform concern since `&&` should work on Windows). FWIW, I'm using this and can confirm that it works.
=> Use npm script hooks to avoid && in deploy script

packages/create-react-app/index.js, packages/react-scripts/scripts/eject.js, packages/react-scripts/scripts/init.js
There’s a common tool included in Hadoop that also has a `yarn` command, which created issues for users who had Hadoop installed:
* #1257
* #1363
Yarn also installs the command under `yarnpkg` alias (added in https://github.com/yarnpkg/yarn/commit/cefa9a368dd3df1a1f1ecd9e50de9c5fabefbc92) so we can use `yarnpkg` instead of `yarn` to make it more reliable.
This has no effect on users who don't have Hadoop installed, but those who have won't see errors from falsely detecting Hadoop Yarn as Yarn the package manager, and they can now also install Yarn to make use of our Yarn support without the Hadoop Yarn interfering.
=> Use yarnpkg alias to run Yarn

packages/react-dev-utils/README.md
It's just a typo in the [README](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/README.md) of `react-dev-utils` package 👍
=> Add missing import in react-dev-utils README.md

packages/react-dev-utils/README.md
Array.forEach is passed the following parameters:
currentValue
The current element being processed in the array.
index
The index of the current element being processed in the array.
array
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
console.log takes multiple arguments. We only want to print the first one, the actual message.
=> Change console.log for errors and warnings

packages/react-dev-utils/webpackHotDevClient.js
handleSuccess function in react-dev-utils/webpackHotDevClient.js does not run for message.type of 'still-ok'. added 'still-ok' to the switch statement so in can reload the window and appropriately clear error messages.
=> webpack-dev-server patch for 'still-ok' success status

README.md
Projects created by Create React App use the `babel-preset-react` which includes
Flow babel plugins which introduces new syntax. This is important for users to know
as it causes what used to be syntax errors to be silently suppressed because they're
valid type annotations in Flow. For example if a user accidentally has `[foo: 'bar']`,
Babel will silently convert it to `[foo]`.
=> Document Flow support

README.md
I found this while doing my own translation in Korean.
super-trivial, but for consistency :)
=> replace two space syntax with <br> tag

packages/react-scripts/template/README.md
Added a summary of causes of `npm start` not detecting changes to Troubleshooting chapter of User Guide. Collected from #659 and #1374
=> Add causes of dev server not detecting changes

packages/react-scripts/package.json
By adding `babel-runtime` as a top level dependency (even though it is not directly depended on) forces yarn to hoist the version to the top which reduces the resultant `node_modules` directory size significantly. The npm install is unaffected.
**npm baseline:**
```
114.7 MiB [##########] /node_modules
64.0 KiB [          ]  README.md
32.0 KiB [          ] /public
24.0 KiB [          ] /src
4.0 KiB [          ]  package.json
4.0 KiB [          ]  .gitignore
```
**npm with patch:**
```
114.7 MiB [##########] /node_modules
64.0 KiB [          ]  README.md
32.0 KiB [          ] /public
24.0 KiB [          ] /src
4.0 KiB [          ]  package.json
4.0 KiB [          ]  .gitignore
```
**yarn baseline:**
```
560.0 MiB [##########] /node_modules
216.0 KiB [          ]  yarn.lock
64.0 KiB [ …
```
=> Added babel-runtime dependency to deduplicate dependencies when using yarn

packages/react-scripts/template/README.md
Per final comment in #372
> Snapshot rendering should actually be pretty stable / useable after React 15.4.1.
> See this post for more info.
=> Readme: Removes experimental from Jest snapshot

packages/react-scripts/scripts/eject.js
ATM if react-scripts is (erroneously) declared in `dependencies` instead of `devDependencies` or isn't declared at all, the `eject` script will fail half-way. This change makes it more robust, react-scripts will be removed from either, if present.
=> eject: Additionally remove `react-scripts` from dependencies

packages/react-scripts/fixtures/kitchensink/.template.dependencies.json, packages/react-scripts/fixtures/kitchensink/integration/initDOM.js, packages/react-scripts/fixtures/kitchensink/src/App.js, packages/react-scripts/fixtures/kitchensink/src/features/env/NodePath.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ArrayDestructuring.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ArraySpread.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/AsyncAwait.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ComputedProperties.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/CustomInterpolation.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/DefaultParameters.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/DestructuringAndAwait.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/Generators.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ObjectDestructuring.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ObjectSpread.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/Promises.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/RestAndDefault.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/RestParameters.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/TemplateInterpolation.js, tasks/e2e-installs.sh, tasks/e2e-kitchensink.sh
@Timer @tuchk4
The trick was probably to add the event listener earlier, and to gain control on when to close `document`.
Now we don't have event differences between `E2E_FILE` and `E2E_URL` in this regard, and don't have to wait/poll for when the feature is fully loaded.
---
@gaearon any insight on why calling
```javascript
this.setState({ users }, () => this.done())
```
works, but
```javascript
this.setState({ users }, this.done)
```
doesn't ([**@here**](https://github.com/EnoahNetzach/create-react-app/blob/e2e-jsdom-fix/packages/react-scripts/fixtures/kitchensink/src/features/env/NodePath.js#L18))?
=> E2e jsdom fix

packages/react-scripts/fixtures/kitchensink/integration/initDOM.js, packages/react-scripts/fixtures/kitchensink/src/App.js
There is wrong expect function:
- it is called but not imported
- it is called as jest expect but `chai` is used for e2e tests
btw. Maybe there should be `throw Error` instead of `it => expect`
=> Minor code style and wrong expect

packages/react-scripts/template/README.md
=> Reflect websocket proxy support on README (#1013)

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
As per issue #1208 this PR updates the comments explaining that after ejecting and trying to add new loaders, the user must also add add the extension that loader is handling to the exclude list for the `url loader`.
I have made the original comment stand out more, and given a more practical example and have added a new comment to the edit of the `loaders` array where a person would usually add a new loader to warn them to update the exclude list.
Happy to hear feedback if this is over the top / not obvious enough.
=> Update comments for loaders webpack to clarify excluding file extensions

packages/react-scripts/template/README.md
Updated README.md to refer to the current rebranding.
=> Change "OS X" references to "macOS"

packages/react-scripts/template/README.md
Thanks for  making this awesome tool!  This tripped me up a little as to why you couldnt add regular environment variables, so i thought to clarify in the docs.  Happy to reword
=> clarifying the use of custom environment variables

packages/react-scripts/config/env.js, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
This PR try to fixed #1438.
Expose all vars from `getClientEnvironment` and put it into `InterpolateHtmlPlugin`.
=> Make all vars accessiable in index.html

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/template/README.md
The goal is to be able to set `homepage` in the `package.json` to `./` (or just `.`) to be able to deploy the app anywhere. This topic has already been mentioned in #1094, #931 and #165.
This PR will obviously not make this `homepage` "trick" works with client-side routing without hash but not everybody needs this feature anyway.
The only problem I saw when setting the `homepage` to `./` is #1480. This issue is caused by ExtractTextPlugin not supporting non-flat build output by default. To fix it, we can use the `publicPath` option of this plugin and go back to the build folder when needed.
=> Support setting "homepage" to "." to generate relative asset paths

README.md, packages/react-scripts/template/README.md
This may be missing some options, but I included the most obvious ones to start.
=> readme: Advanced Configuration

packages/react-scripts/bin/react-scripts.js, packages/react-scripts/scripts/build.js
This addresses issue #1493 
Current behavior is that `npm run build` exits code 0 without creating a bundle when interrupted. This change makes the build script catch catchable interruptions and exit with the appropriate error code.
=> Make build exit with error code when interrupted

tasks/e2e-simple.sh
This should make sure the new homepage and `PUBLIC_URL` features are functioning correctly (primitively).
=> Add test cases for PUBLIC_URL and relative path

.travis.yml
It's out of maintenance and we already broke it by updating Lerna version which is incompatible.
So might as well stop testing that we gracefully crash in it.
=> Don't run CI on Node 0.10

packages/react-scripts/template/README.md
Add [`jest-enzyme`](https://github.com/blainekasten/enzyme-matchers) to documentation for simpler tests when using enzyme.
=> Suggest jest-enzyme for simplifying test matchers

packages/react-scripts/template/README.md
As pointed out in https://github.com/facebookincubator/create-react-app/issues/1007, adding a specific section about SASS in documentation could help users avoid ejecting in order to use `sass-loader`.
This is simpler in my opinion and more aligned to this project's way of thinking.
=> Add SASS support documentation #1007

tasks/e2e-installs.sh, tasks/e2e-kitchensink.sh, tasks/e2e-simple.sh
The `test` command fails with multiple arguments when given a unary operator such as '-e'. Add a function that can test one or more files by looping over all files.
Specifically, if I add another template asset (i.e. 404.html) the e2e scripts fail with "binary operator expected" because the glob expands to `test -e build/404.html build/index.html`.
=> Fix `test -e` with wildcard arguments.

README.md
In the first time, I use create-react-app the instruction tell me to use yarn command. I saw the command README.md still use npm command. I already change it to yarn command.
=> Correctly Command in README.md

packages/react-scripts/template/README.md
I'd like to avoid using "ES2017" as the baseline because nobody knows what it means.
Seriously, there's so much confusion that it's just not a good way of framing the doc IMO.
Instead, I propose using ES6 as the baseline (since that's the big update that's well-known), and add individual syntax features in a list (both stable and proposed). At some point we can reset the baseline but I think for now it's nice to be explicit.
=> Tweak syntax doc

tasks/e2e-simple.sh
I noticed that when running `./tasks/e2e.sh`, the node version check was failing to execute properly due to bash complaining (version `3.2.57(1)-release` on my Mac OSX machine). Once I changed the test syntax to use `[[`, I found that sed wasn't stripping the node version correctly. I verified this with:
nvm use 0.10
./tasks/e2e.sh
...which bombed out on a 'const' declaration'. It's probably down to some platform peculiarities, but good to fix them nonetheless.
=> Make node version check more robust in e2e.sh

packages/react-scripts/template/README.md
- Windows shell users should note that running two programs simultaneously is not supported.
=> update CSS preprocessor instructions

package.json, packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/fixtures/kitchensink/src/App.js
This PR enables babel syntax support for `import()` and disables require.ensure support within webpack.
It also updates the required internal files.
=> Add support for dynamic import & disable require.ensure

packages/react-dev-utils/webpackHotDevClient.js, packages/react-scripts/scripts/start.js
This makes files in the `public/` folder reload the page when they change.
Test plan:
- create a project;
- start the project with `npm start`;
- modify something in `public/index.html`, for example the `<title>`;
- hit save;
- verify that the page has reloaded and the title has changed.
Fixes #656, fixes #1508
=> Enable page reloading for files in `public/`

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json, packages/react-scripts/package.json
=> Bump babel deps and re-enable transform-react-constant-elements

packages/react-scripts/template/README.md
Added the `--recursive` flag to the npm watch-css script in order to behave properly with SCSS files in nested directories.
=> add --recursive to sass watch script

README.md
We've moved away from active Neo development, instead transitioning to a more generic approach by coupling our Webpack wrapper Neutrino with a preset for building React apps: [neutrino-preset-react](https://www.npmjs.com/package/neutrino-preset-react).
=> Switch from Neo to Neutrino

packages/react-scripts/scripts/start.js
This PR makes sure the PORT env variable is always read as integer, #1584.
=> fixes #1584 PORT env variable not always an integer

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json
https://github.com/babel/babel/issues/4851 is now closed 🎉
=> babel-preset: remove babel-plugin-transform-es2015-parameters

CHANGELOG.md, CONTRIBUTING.md, README.md, packages/babel-preset-react-app/README.md, packages/create-react-app/README.md, packages/eslint-config-react-app/README.md, packages/react-dev-utils/README.md, packages/react-scripts/README.md, packages/react-scripts/template/README.md, template/README.md
Happy to remove whitespace changes and resubmit PR.
=> Add note for using CHOKIDAR_USEPOLLING in virtual machines to enable HMR

packages/create-react-app/index.js
We maintain a psuedo-fork of react-scripts at https://github.com/firstlookmedia/react-scripts (it only matches the general structure). It seems desirable from #682 to be able to use git repos as the argument to `--scripts-version` -- if some company wants to keep its fork private, this avoids requiring a private npm account. This PR makes that possible:
(https)
```shell
create-react-app --scripts-version=git+https://github.com/firstlookmedia/react-scripts.git#init myapp
```
or (ssh)
```shell
create-react-app --scripts-version=git+ssh://git@github.com/firstlookmedia/react-scripts.git myapp
```
---
Note that this requires the `react-scripts` package being hoisted to its own git repo.
---
Note also we haven't yet implemented the `init.js` script (the `init` branch above will work with this …
=> Allow --scripts-version git urls

packages/react-scripts/template/README.md
The documentation was missing creating the .flowconfig file
=> Update flow configuration documentation

packages/react-scripts/template/README.md
Resolves https://github.com/facebookincubator/create-react-app/issues/1611
=> Add note about when to import bootstrap CSS.

packages/react-scripts/config/paths.js, packages/react-scripts/scripts/eject.js, packages/react-scripts/utils/isReactScriptsLinked.js
It is very useful to use [npm-link](https://docs.npmjs.com/cli/link)  for `react-scripts` package when want to test new (local) developed features on existing application.
```
$ cd create-react-app/packages/react-scripts
$ npm link
$ cd ~/any-existing-app
$ npm link react-scripts
$ npm start
``` 
Related to #1107
=> Fix workflow if react-scripts package is linked via npm-link

packages/react-scripts/scripts/build.js, packages/react-scripts/scripts/start.js
Webpack validates the configuration during setup. If there are problems detected, it will throw a validation error. The problem is, that the build and start scripts don't print the messages.
Main cause for this particular problem is when users eject and modify the webpack config.
Only valid for webpack2 builds.
fixes https://github.com/facebookincubator/create-react-app/issues/1595
Error logging before this change: 
```
$ npm run build
> combined@1.0.0 build C:\Projects\combined
> node scripts/build.js
Creating an optimized production build...
C:\Projects\combined\node_modules\webpack\lib\webpack.js:19
throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
^
Error
at webpack (C:\Projects\combined\node_modules\webpack\lib\webpack.js:19:9)
at build …
```
=> (feat): add webpack validation error logging

packages/eslint-config-react-app/index.js
Fixes #1524
Also, disallow `System.import` as it has been deprecated in webpack 2.
=> Add lint rule to disallow require.ensure and System.import

packages/react-scripts/template/README.md
As requested via https://twitter.com/dan_abramov/status/803712995280830466
=> Add documentation for customizing Bootstrap theme

packages/create-react-app/index.js
To avoid file conflict issue with IJ static web projects.
This is related to issue #368. 
IJ static web project creates the file web.iml which also triggers the conflict file issue, as the .idea dir did.
=> Fix conflict file issue in IJ static web projects by adding web.iml to the exclusion list

packages/react-scripts/scripts/eject.js
Remove .bin files defined at react-scripts/package.json after eject
https://github.com/facebookincubator/create-react-app/pull/1356#issuecomment-280047793
```js
Object.keys(ownPackage.bin).forEach(function(binKey) {
fs.removeSync(path.join(appPath, 'node_modules', '.bin', binKey));
});
```
=> Remove .bin files defined at react-scripts/package.json after eject 

packages/react-scripts/package.json
`recurisve-readir` released a patch bump to bump `minimatch` to a version that dedupes with the common `minimatch@3.0.3`.  Checks off an item on #1183.
It'll be like 80% less significant after #1490, but this way I can at least pretend to be useful.
=> Bump `recursive-readdir`.

packages/eslint-config-react-app/index.js
=> Disallow event global variable with no-restricted-globals rule (#1530)

README.md, packages/react-scripts/template/README.md
Added a short description and link to a tutorial on zero-configuration snapshotting / pre-rendering with react-snapshot, and a link to it in the section on changing the page `<title>`.
=> Added a how-to on react-snapshot

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/package.json
POC for https://github.com/facebookincubator/create-react-app/issues/740. Haven't found any problem, build times improved about 1s on my project and machine.
=> Enable eslint caching in development

packages/react-scripts/scripts/build.js
Use the configured appBuild value in paths.js instead of hard-coding it to 'build'.  This is helpful for the ejected case where the appBuild path is changed to another folder name.
=> Use real build path name in build output

packages/react-scripts/scripts/eject.js, packages/react-scripts/scripts/test.js
Aims to resolve #1417 and #1498.
=> Retain posix paths in Jest config

packages/create-react-app/index.js, tasks/e2e-installs.sh
As per #1505 
> Currently, when npm fails for the first time, you end up with an empty project that doesn't work.
> We should delete the broken files we added (or the whole folder if we created it), and print a message explaining the problem is with npm, as well as the underlying message.
* Print out message when problem occurs
* Delete project folder on errors
=> Gracefully handle initial installation error (#1505)

packages/react-scripts/scripts/test.js
Should fix https://github.com/facebookincubator/create-react-app/issues/1645.
I haven't tested it but I won't have access to Windows until Monday so going to ninja-land it.
The reason I believe this is a fix is because #1635 should only have fixed a problem for ejecting. So I'm just rolling back the part that isn't relevant for ejecting (and that worked well before).
=> Fix npm test on Windows

packages/react-scripts/template/README.md
Addendum to #1540. Keeping `userDataDir` under `.vscode` folder honors common gitignore rules for VSCode.
=> Set Chrome userDataDir to be under .vscode folder

appveyor.yml, tasks/e2e-installs.sh, tasks/e2e-kitchensink.sh
This leverages the fact that appveyor uses cygwin. It might be worthwhile to investigate switching our e2e to a node script instead of bash.
=> Add appveyor.yml

packages/create-react-app/index.js
Possible fix for #1663
This change will patch the package.json dependencies for `react` and `react-dom` after the successfull installation. A caret will be prepanded and afterwards validated if a valid semver version range is the result.
=> fix react dependency versions during initial install

packages/create-react-app/index.js, packages/create-react-app/package.json
Could be a potential fix for #1649
The main idea is to validate the project name to meet the npm specification. If the validation fails detailed error information is provided to resolve the issue.
``` 
$ node ./create-react-app/packages/create-react-app/index.js "   asdf:asdf asdfasdf asdföjk asdlöfj alösdfjk aölsdfkjalö sdfjkalösdkfj öalsdkfjalös dfdklö jasdlöfj asödlfjasl
ö dfkjaslödfkj asdlöfjkaslöd fkjasdlöfjaslö dfjasöldfjasöldfjk aösdlfj aölsdfjasdf asdf SAD asdfasdfasdf asdfasdfa sdfasdäfk äasdfjklö asdfjlö aksdjfölasjd fölaksdfjölasj dfö
laksdfj  DSD~"
The project name    asdf:asdf asdfasdf asdföjk asdlöfj alösdfjk aölsdfkjalö sdfjkalösdkfj öalsdkfjalös dfdklö jasdlöfj asödlfjaslö dfkjaslödfkj asdlöfjkaslöd fkjasdlöfjaslö dfjasöldfjasöldfjk aösdlfj aölsdfjasdf asdf SAD …
```
=> add project name validation

packages/create-react-app/index.js
possible fix for #1671
please test on linux/mac machines
=> fix project cleanup on windows

packages/react-scripts/config/webpack.config.dev.js
Reverts facebookincubator/create-react-app#1578.
As I mentioned in https://github.com/facebookincubator/create-react-app/issues/1656#issuecomment-282608398, `eslint-loader` caching code does not have proper error handling, causing failures when used together with Yarn.
=> Revert "Enable eslint caching in development"

packages/react-scripts/scripts/start.js
fix for #1676
The change will configure the proxy middleware to send X-FORWARDED-* headers.
=> add X-FORWARDED headers for proxy requests

packages/create-react-app/index.js, packages/react-scripts/scripts/init.js
This pull request enables offline support from the next version of yarn. With the 0.19 version there are some issues. The related issue is #1235!
Right now we prefer offline over online with --prefer-offline flag. Maybe in the future yarn wil have a --prefer-online flag and we can change it with that ;)
Let me know if it's ok!
cheers,
Simon
=> Use offline cached version with yarn when it's possible

CHANGELOG.md
* [#1423](https://github.com/facebookincubator/create-react-app/pull/1423) **Fall back to Yarn offline cache when creating a new project.** ([@voxsim](https://github.com/voxsim))
If you are using Yarn, and you have created at least one app previously, Create React App now works offline.
* [#1665](https://github.com/facebookincubator/create-react-app/pull/1665) Temporarily disable ESLint caching because of a bug. ([@gaearon](https://github.com/gaearon))
* [#1675](https://github.com/facebookincubator/create-react-app/pull/1675) Delete project folder on failed installation on Windows. ([@johann-sonntagbauer](https://github.com/johann-sonntagbauer))
* [#1662](https://github.com/facebookincubator/create-react-app/pull/1662) Validate …
=> Add 0.9.3 changelog

packages/react-scripts/template/README.md
The first `package.json` change doesn't have the `--recursive` flag that is included in the later example where it updates the `start, `build`, and `start-js` commands. This pr would update it so it matches this [line](https://github.com/facebookincubator/create-react-app/compare/master...mklemme:patch-1#diff-4e6ec56f74ee42069aac401a4fe448adR456).
=> Fixed missing --recursive flag in first `npm run watch-css` command

packages/react-scripts/package.json
https://github.com/webpack-contrib/extract-text-webpack-plugin/releases/tag/v2.0.0
=> Update extract-text-webpack-plugin to stable

packages/react-dev-utils/getProcessForPort.js
=> fixing things for people with the username `cwd`

lerna.json, package.json
Lerna just released a new version here https://github.com/lerna/lerna/releases/tag/v2.0.0-beta.38
But I encountered this error after deleting yarn.lock and node_modules and tried to install again.
```
yarn
yarn install v0.21.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
$ lerna bootstrap
Lerna v2.0.0-beta.38
Independent Versioning Mode
Lerna version mismatch: The current version of lerna is 2.0.0-beta.38, but the Lerna version in `lerna.json` is 2.0.0-beta.37. You can either run `lerna init` again or install `lerna@2.0.0-beta.37`.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. …
```
=> pin and upgrade lerna version

packages/react-scripts/template/README.md
Incorporates changes announced at https://zeit.co/blog/now-static that streamline Now deployments from CRA projects.
=> Update now.sh deployment instructions.

package.json, packages/eslint-config-react-app/README.md, packages/eslint-config-react-app/index.js, packages/eslint-config-react-app/package.json, packages/react-scripts/package.json
=> Add support for ignoreRestSiblings in no-unused-vars

tasks/cra.sh, tasks/e2e-installs.sh, tasks/e2e-kitchensink.sh, tasks/e2e-simple.sh, tasks/release.sh
Plans to fix https://github.com/facebookincubator/create-react-app/issues/1652
This happens when you clone create-react-app to a path where it has spaces in any of the parent foldes.
To test it, just rename your parent folder to something with spaces and run `npm run e2e`
=> add double quotes to escape spaces in paths in e2e

packages/react-dev-utils/openBrowser.js
On OS X, the `BROWSER` environment variable can be set to `open` to open the default browser.
In this case, the value should not be passed to `opn()` as a `browser` option. Doing so would pass it to the `open` command using the `-a` parameter and not do anything:
This change passes an empty string in this situation. I added `isBrowserValid` to make it clearer and to make it easy to add other cases in the future.
=> Fix openBrowser() when BROWSER=open on macOS

packages/react-scripts/config/webpack.config.dev.js
Fixes https://github.com/facebookincubator/create-react-app/issues/1713.
Sending this directly to 0.9.x because the hack is irrelevant for Webpack 2.
=> Fix hot reloading for WebpackDevServer after eject

tasks/e2e-simple.sh
Create empty package.json in e2e test while installing packaged CLI to prevent installation issues. Related to #1401.
=> Create empty package.json in e2e test (#1401)

packages/react-dev-utils/openBrowser.js
Fixes a failure I introduced merging https://github.com/facebookincubator/create-react-app/pull/1690.
=> Don't use ES6 in a file that should run on Node 4

.eslintrc, package.json, packages/eslint-config-react-app/index.js, packages/react-dev-utils/checkRequiredFiles.js, packages/react-dev-utils/clearConsole.js, packages/react-dev-utils/formatWebpackMessages.js, packages/react-dev-utils/getProcessForPort.js, packages/react-dev-utils/openBrowser.js, packages/react-dev-utils/prompt.js, packages/react-dev-utils/webpackHotDevClient.js, packages/react-scripts/bin/react-scripts.js, packages/react-scripts/fixtures/kitchensink/integration/initDOM.js, tasks/e2e-simple.sh
It didn't make a lot of sense to use CRA's own linting setup because we're in a different environment (Node). It was also a pain to do this with our monorepo setup because we'd always trail a version behind. This seems much simpler and will hopefully unbreak master.
=> Lint internal scripts with eslint:recommended

packages/react-scripts/config/paths.js, packages/react-scripts/scripts/eject.js
I think this should fix #1722.
=> Fix ejecting from a scoped fork

packages/create-react-app/index.js, packages/create-react-app/package.json, tasks/e2e-installs.sh
Will add test[s] + extract logic to a function if we consider this a decent solution.
Aims to resolve #1414.
=> Properly extract package name for installing tgz of scoped packages

packages/eslint-config-react-app/package.json
I'm not sure what's going on but it seems like Lerna breaks somewhere on Windows because `peerDependencies` are being checked too early or something.
Maybe this will help.
=> Relax ESLint config peerDependency

packages/react-scripts/config/paths.js, packages/react-scripts/scripts/eject.js
=> Fix eject for linked react-scripts

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json, packages/react-scripts/package.json
Disables webpack modules (enables babel modules) to resolve #1638
=> Switch to preset-env

packages/react-scripts/template/README.md
`yarn` is mentioned for a lot of steps, but not for `flow`, this fixes that.
=> Add yarn steps for adding flow

PULL_REQUEST_TEMPLATE.md, package.json
As [promised](https://twitter.com/kentcdodds/status/839240469515141120)
Here's a quick gif demo:
This uses [husky](https://npmjs.com/package/husky) (by @typicode) for the commit hooks and [lint-staged](https://www.npmjs.com/package/lint-staged) (by @okonet) for running stuff on the staged files. Pretty neat!
=> Add lint-staged + husky for prettier auto-formatting on commit

packages/react-scripts/scripts/build.js, packages/react-scripts/template/README.md
This PR introduces [serve](https://github.com/zeit/serve) as the new suggested way of handling `create-react-app` projects in production.
However, it also ensures that the docs clearly state that this is only a good idea inside Node.js environments. For all other platforms (or servers that aren't static-only), we still provide the user with a clear explanation of what to do in theses cases.
This closes https://github.com/facebookincubator/create-react-app/issues/1757.
How it looks:
=> Suggest `serve` for running in production

packages/eslint-config-react-app/index.js
Iterating over an object's keys using `for/in` is idiomatic and it's safe (in all modern browsers) to not check hasOwnProperty as long as the object is a plain object. Can we remove this lint rule?
=> Remove 'guard-for-in' lint rule

.travis.yml, appveyor.yml, packages/react-scripts/package.json
Should fix UnhandledPromiseRejectionWarning on Node 7.7.2 (#1776)
=> Run CI on Node 7; Bump detect-port: 1.0.1 -> 1.1.0 (#1776)

CHANGELOG.md
* [#1783](https://github.com/facebookincubator/create-react-app/pull/1783) **Work around Node 7.7.2 bug that crashes `npm start`.** ([@ryanwalters](https://github.com/ryanwalters))
* `eslint-config-react-app`
* [#1773](https://github.com/facebookincubator/create-react-app/pull/1773) Remove `guard-for-in` lint rule. ([@spicyj](https://github.com/spicyj))
* [#1760](https://github.com/facebookincubator/create-react-app/pull/1760) Suggest `serve` for running in production. ([@leo](https://github.com/leo))
* [#1747](https://github.com/facebookincubator/create-react-app/pull/1747) Display `yarn` instead of `yarnpkg` when creating a new app. ([@lpalmes](https://github.com/lpalmes))
* …
=> Add 0.9.5 changelog

packages/react-scripts/babelrc, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/eslintrc, packages/react-scripts/package.json, packages/react-scripts/scripts/eject.js
This only affects master, not any stable releases.
It should fix the main problem in #1806 although we still shouldn't close the issue until we fix the end-to-end tests and make eject crash on error.
I'd appreciate the review because I haven't really tested it. We can look at Travis logs to verify it worked.
I want to merge this sooner than other issues in #1806 so that less forkers who track master are affected.
=> Fixes a silent crash when ejecting

packages/react-scripts/scripts/build.js, packages/react-scripts/scripts/eject.js, packages/react-scripts/scripts/init.js, packages/react-scripts/scripts/start.js, packages/react-scripts/scripts/test.js
This makes sure that end-to-end-testing crash when `scripts/*.js` run into an unhandled promise rejection as explained here https://github.com/facebookincubator/create-react-app/issues/1806#issuecomment-286146425.
This code has been added at the beginning of each script:
```javascript
process.on('unhandledRejection', err => {
throw err;
});
```
Faulty `eject.js` fails silently.
Faulty `eject.js` makes end-to-end testing crash.
Note that the bug outlined above should be fixed by #1810.
=> Makes end-to-end testing crash on unhandled rejections

packages/create-react-app/createReactApp.js
Currently create-react-app fails on newly created mercurial repos. This change fixes that.
=> Allow creation of apps in empty mercurial repos

packages/create-react-app/createReactApp.js
Solves #1796 by always showing `create-react-app` as a command name in help messaging.
Immediate consequence is that even if I explicitly run the job as `node packages/create-react-app/index.js`, it's going to show me `create-react-app` and not `index`, as before. Which in my opinion makes more sense, but might seem confusing to some experienced contributors.
=> Pull command name from package.json instead of letting commander to figure it out on its own

packages/create-react-app/createReactApp.js, packages/react-scripts/template/public/index.html
Adding _shirink-to-fit=no_ to ensure proper responsive behavior in iOS 9+
For more about why this is needed read _[The Problem with iOS Safari and shrink-to-fit](https://bitsofco.de/ios-safari-and-shrink-to-fit/)_
=> Fix responsive behavior in iOS 9+

packages/create-react-app/createReactApp.js
As discussed in issue https://github.com/facebookincubator/create-react-app/issues/1818
When we ran `yarn run create-react-app foo`, it failed because it said it was in offline-mode.
Now, after this change it actually creates a new react-app.
=> Changed resolve into lookup

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Looking through the `npm link` issues, I see two use cases:
1. (#1356) using `npm link` to test `react-scripts`
2. using `npm link` for libraries your app depends on.
This PR solves the 2nd case. Webpack's official solution for `npm link` is to [add your project's node_modules to `resolve.fallback` on the config](https://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-don-t-find-their-dependencies).
To verify the issue and fix create a small library to link:
```
cd /tmp
git clone https://gist.github.com/f40e1bad454626691097b4cc4651208c.git link-example
cd link-example
npm link
```
Then create your app and link the library.
```
create-react-app my-app
cd my-app
npm link link-example
echo 'import "link-example"' > src/index.js
npm run build
```
With the current published …
=> Fix importing npm linked libraries

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Resolves #1661 and backports #1359
=> Fix importing linked packages

tasks/e2e-installs.sh
Fixes #1720 
It just checks package.json and check if includes `react, react-dom, react-scripts`, if other is found it will fail the test.
=> Added test to check for accidental extraneous dependencies

packages/babel-preset-react-app/index.js, packages/react-scripts/package.json
An updated version of webpack was just released which fixes cheap source maps (line numbers) when using harmony module imports.
The babel feature can now be disabled and reliance shifted back onto webpack@2 to handle modules.
Validated by making crash overlay throw an error and having the correct line number appear.
**This PR also upgrades other deps in spirit of trying newer versions in alpha releases.** I did check the upgrades and most seemed to be bug fixes, which is good. Autoprefixer is one we should always try to keep up to date.
=> Re-disable babel modules transform

README.md
https://github.com/seek-oss/sku
We've built our own open-source tooling similar to create-react-app, designed for our existing front-end tech stack, but with an added focus on static pre-rendering as a first-class citizen. Even though it's designed to make building internal products easier, it's decoupled from our infrastructure and can be used by anyone.
=> Add sku to the list of alternatives

packages/react-scripts/scripts/utils/addWebpackMiddleware.js
#800 
Added check that if proxy string is provided in package.json then it should start with either http:// or https://
=> Ensure proxy url starts with `http://` or `https://`

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/fixtures/kitchensink/.template.dependencies.json, packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js, packages/react-scripts/fixtures/kitchensink/src/App.js, packages/react-scripts/fixtures/kitchensink/src/features/webpack/LinkedModules.js, packages/react-scripts/fixtures/kitchensink/src/features/webpack/LinkedModules.test.js, tasks/e2e-kitchensink.sh
This adds tests which verify linked modules are working.
Also adds a fallback when ejected because `enhanced-resolve` isn't so enhanced.
This is resolved in webpack 2 (which uses a newer `enhanced-resolved`), but is not backported.
=> Add linked modules test (0.9.x)

packages/react-scripts/scripts/start.js
While writing docs for #1300 I found a bug with the `HOST` environment variable. When I set this variable, it uses the value I passed to print the link to the app in the console, but it doesn't actually use it.
Execute `npm start`.  The  console displays this message: 
```
Compiled successfully!
The app is running at:
http://localhost:3000/
```
The app is can be viewed from your browser, and also from all the devices connected to your local network such as your mobile phone. Once you find your computer's IP address, you can open your phone's browser at something like `192.168.0.9:3000` to see the app. The `localhost` url is a bit misleading since the server is actually listening at `0.0.0.0` since that's the value that binds to all interfaces, not just the local loopback interface …
=> Fix host environment variable bug

CONTRIBUTING.md
It helps in resolving issues by providing brief description of each package and its purpose. Fixes #850
=> Adding folder structure to help people navigate through project while contributing

packages/react-scripts/template/README.md
It’s safer to use the absolute path of the directory that you want to serve, in case you run the express app from another directory.
=> Node.js serving with absolute path

packages/react-scripts/config/webpack.config.prod.js
Snooping around UglifyJS docs I discovered that as of version v2.8.5, the version which webpack uses, the option `screw_ie8` is enabled by default:
>  --screw-ie8                   
Use this flag if you don't wish to support Internet Explorer 6/7/8.
By default UglifyJS will not try to be IE-proof.
That might look a bit vague, but looking in the code I found the default values, `screw_ie8` defaults to `true` and `output.comments` defaults to `false`
https://github.com/mishoo/UglifyJS2/blob/e5cb9275df257751b7322f34bca5e76cc519b974/lib/output.js#L81
https://github.com/mishoo/UglifyJS2/blob/e5cb9275df257751b7322f34bca5e76cc519b974/lib/compress.js#L79
https://github.com/mishoo/UglifyJS2/blob/e5cb9275df257751b7322f34bca5e76cc519b974/lib/output.js#L78
The commit I'm browsing in is the v2.8.5 one …
=> removed options in UglifyJsPlugin which are equal to the defaults

packages/react-scripts/scripts/start.js, packages/react-scripts/scripts/utils/addWebpackMiddleware.js
Node on windows has issue which effects proxy to localhost when there is no internet. #1116 
Added a check for windows host and changed localhost to 127.0.0.1 as discussed.
=> Resolve localhost when offline on Windows

packages/react-scripts/template/README.md
Updates Readme --> CSS Preprocessor to include information on node-sass-chokidar alternative to node-sass.
I originally brought this up in this [#1986](https://github.com/facebookincubator/create-react-app/issues/1986)
16GB RAM
2.7 GHz i7
___
`node-sass --watch` in docker for mac
___
`node-sass-chokidar --watch` in docker for mac
=> Update README.md CSS Preprocessor --> node-sass-chokidar alternative

packages/react-dev-utils/crashOverlay.js, packages/react-dev-utils/package.json
This PR includes a highly refactored version of `crashOverlay` that was typed via flow and then compiled back down to ES5.
This refactor enabled rendering into a desired document & element, which made for an easy transition to an iframe (removing some global side-effects and global scoped vars in the process 👍).
The overlay was switched to an iframe so that app styles do not have an effect on the overlay.
~~Besides the refactor, this PR also welcomes showing React warnings (#1746, captured via `console.error`) and fixes #1853.~~
~~React warnings still need to be displayed differently to show that they're not errors.~~
=> Modularize and extract crashOverlay to iframe

packages/react-scripts/fixtures/kitchensink/.template.dependencies.json, packages/react-scripts/fixtures/kitchensink/src/App.js, packages/react-scripts/fixtures/kitchensink/src/features/env/NodePath.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ArrayDestructuring.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ArraySpread.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/AsyncAwait.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ClassProperties.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ComputedProperties.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/CustomInterpolation.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/DefaultParameters.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/DestructuringAndAwait.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/Generators.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ObjectDestructuring.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/ObjectSpread.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/Promises.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/RestAndDefault.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/RestParameters.js, packages/react-scripts/fixtures/kitchensink/src/features/syntax/TemplateInterpolation.js
=> Updates for React 15.5

packages/react-scripts/template/README.md
I have not verified this works, but I *think* this should fix https://github.com/facebookincubator/create-react-app/issues/1955.
=> Suggest to create .eslintrc for IDE lint plugins

packages/eslint-config-react-app/index.js, packages/react-scripts/fixtures/kitchensink/src/App.js, packages/react-scripts/fixtures/kitchensink/src/features/webpack/NoExtInclusion.js, packages/react-scripts/fixtures/kitchensink/src/features/webpack/UnknownExtInclusion.js
All the properties of window object such as `name`, `self`, and `status` are considered to be global variables because of having `browser` env in eslint config.
As a result this variables are ignored by eslint for errors such as `no-unused-vars` when someone uses this variables in their code without the intent of using them as a global variable.
To solve this we'd have to remove `browser` env  from eslint config and add a list of global variables that are more commonly used. Other window properties are not considered global and requires `window.` qualifier.
I have added a list of all variables that I think are commonly used as globals in browser env.
Please guide if I have missed something.
***How did I test this?***
I created a new app with 
`npm run create-react-app test-app`
`npm …
=> Forbid using window properties as global variables

packages/react-scripts/scripts/utils/createJestConfig.js
Fixes #2043 
Test Plan:
```
❯ create-react-app cra-test
❯ cd cra-test
// simulate a failing test in a yarn cache
❯ mkdir -p .cache/yarn/v1
❯ echo "it('fails', () => throw new Error());" > .cache/yarn/v1/Foo.test.js
```
Then test that it fails:
Then link the updated version of `react-scripts` and re-run the test:
=> Ignore the yarn cache directory

packages/eslint-config-react-app/index.js, packages/react-scripts/fixtures/kitchensink/src/App.js, packages/react-scripts/fixtures/kitchensink/src/features/webpack/NoExtInclusion.js, packages/react-scripts/fixtures/kitchensink/src/features/webpack/UnknownExtInclusion.js
Reverts facebookincubator/create-react-app#1840.
See the discussion https://github.com/facebookincubator/create-react-app/pull/1840#issuecomment-299933160 for reasons why:
* We probably aren’t going to implement server side rendering any time soon.
* Beginners are genuinely confused why copy-pasting valid examples produces errors.
=> Revert "Forbid using window properties as global variables"

packages/react-dev-utils/crashOverlay.js
* Remove some junk code
* Remove iframe border (which is unnecessary and a bit confusing)
=> Minor tweaks for crash overlay

packages/react-dev-utils/formatWebpackMessages.js, packages/react-dev-utils/webpackHotDevClient.js
Should fix https://github.com/facebookincubator/create-react-app/issues/2109.
Test plan: different combinations of JS and CSS syntax and lint errors and warnings.
=> Prettify errors and warnings for Webpack 2

packages/react-scripts/config/webpack.config.dev.js
While playing with #2113 I noticed ESLint only works for a scaffolded application, and not in our monorepo.
It's because our [`.eslintignore`](https://github.com/facebookincubator/create-react-app/blob/master/.eslintignore) says to ignore these files.
Just like `.eslintrc`, we should not respect `.eslintignore` files since webpack is managing the globbing (and only linting `src/**/*.js` files).
=> Do not respect eslintignore

packages/react-scripts/scripts/start.js
Let's default to `0.0.0.0` which binds to all available IPv4 addresses.
We might want to bind to `0:0:0:0:0:0:0:0` if we can.
We also might want to open the browser to `localhost` instead of `0.0.0.0` when we detect that you're binding to all interfaces.
=> Bind to all IPv4 addresses

packages/react-dev-utils/formatWebpackMessages.js
This fixes https://github.com/facebookincubator/create-react-app/issues/2056.
It's not really maintainable—I'll file another issue to rewrite this to a custom ESLint formatter.
Just warnings:
Now I make an error:
(Before, they would all be displayed together.)
After fixing the error:
=> Omit ESLint warnings when there are ESLint errors

packages/eslint-config-react-app/index.js
* Provide us with clear instructions on how you verified your changes work. Bonus points for screenshots!
In App.js file created an unused variable _x, eslint shows no-unused-vars error as expected
=> disable ignoring unused vars prefixed with _

packages/react-error-overlay/src/components/frame.js, packages/react-error-overlay/src/components/overlay.js, packages/react-error-overlay/src/styles.js
* Break `Check the render method` onto the next line (I think we already do this in React but haven't cherry-picked to 15.x). This is important because otherwise stack takes too much precious attention even when it's not actionable.
* Hide "Invariant Violation" completely. (This is college speak.)
* Add a hacky workaround for https://github.com/facebookincubator/create-react-app/issues/2097.
Before:
After:
=> Make error box messages friendlier

packages/react-dev-utils/formatWebpackMessages.js
Addresses https://github.com/facebookincubator/create-react-app/pull/1755#issuecomment-285179758.
Since I removed the duplicate filtering hack, this came up again.
Now I'm just showing the first compilation error.
This makes sense because in most cases it's the one you want to fix first anyway. And showing a list is not useful if it's repopulated on every change as you can't easily keep track of it.
=> Only show the first compilation error

packages/react-scripts/template/README.md
updating readme with comment from #1939 . works with latest `node-sass@4.5.2`
🎉
=> update readme with fix from #1939

CONTRIBUTING.md
Based on [this](https://github.com/facebookincubator/create-react-app/pull/2014#issuecomment-300811661) thread.
=> Add note about yarn.lock in CONTRIBUTING.md

packages/react-error-overlay/src/utils/warnings.js
A cruder, but simple alternative to https://github.com/facebookincubator/create-react-app/pull/2142.
We can revisit https://github.com/facebookincubator/create-react-app/pull/2142 after https://github.com/facebookincubator/create-react-app/issues/2100.
=> Skip React frames that are too close

packages/react-error-overlay/src/components/code.js, packages/react-error-overlay/src/components/frame.js, packages/react-error-overlay/src/components/frames.js, packages/react-error-overlay/src/components/overlay.js, packages/react-error-overlay/src/utils/isInternalFile.js
This should fix https://github.com/facebookincubator/create-react-app/issues/2144.
If the error is one of the built-in ones, we don't collapse, and show all the internal frames up to the first instance of user code. Then collapsing logic works as before.
I found the variable overwriting confusing and hard to deal with, so I tried to separate variables. Let me know if I missed some case.
=> Don't collapse unintentional top-level errors

packages/react-dev-utils/launchEditor.js
Fully fixes https://github.com/facebookincubator/create-react-app/issues/2110.
=> Print error messages for editor integration

packages/react-dev-utils/README.md, packages/react-dev-utils/eslintFormatter.js, packages/react-dev-utils/formatWebpackMessages.js, packages/react-dev-utils/formatter.js, packages/react-dev-utils/package.json, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/scripts/utils/createWebpackCompiler.js
Replaces hacky code to format eslint errors by using custom loader.
I built this formatter on top of the default `stylish` formatter. 
It omits warnings if there are any eslint errors as required in #2120 and errors and warnings looks the same as earlier.
Closes #2121
=> Add custom eslint formatter

packages/react-dev-utils/eslintFormatter.js, packages/react-dev-utils/formatWebpackMessages.js, packages/react-scripts/scripts/utils/createWebpackCompiler.js
I think this looks a bit better.
=> Tweak error and warning output

packages/react-dev-utils/prepareProxy.js, packages/react-scripts/scripts/start.js
Using a custom `${protocol}://${HOST}:${port}/` URL formatter breaks IPv6, which requires brackets around the host. We should use the internal formatter.
=> Add support for IPv6 hosts

packages/react-scripts/scripts/start.js
Windows doesn't let you use `0.0.0.0` as a valid URL in the browser, unlike macOS.
When using the unspecified address (which binds to everything), we should switch to `localhost`. It's a saner default anyway and something people recognize.
=> Prefer localhost as an address

packages/react-dev-utils/eslintFormatter.js, packages/react-dev-utils/formatWebpackMessages.js, packages/react-scripts/scripts/utils/createWebpackCompiler.js
Hopefully the last one for now.
I removed dimming, and instead I make the filenames inverse and line numbers bold.
=> Make error/warning output more useful

packages/react-error-overlay/src/effects/proxyConsole.js, packages/react-error-overlay/src/utils/warnings.js
Matches what we did in https://github.com/facebook/react/pull/9679
=> Put console.stack() behind a react vendor prefix

tasks/e2e-simple.sh
Just checking if their bug was fixed.
=> Unpin Yarn

packages/eslint-config-react-app/README.md, packages/eslint-config-react-app/index.js, packages/eslint-config-react-app/package.json, packages/react-error-overlay/package.json, packages/react-scripts/package.json
As discussed in #1708 
After this PR the included rules from `eslint-plugin-jsx-a11y` will be:
```
'jsx-a11y/accessible-emoji': 'warn',
'jsx-a11y/alt-text': 'warn',
'jsx-a11y/anchor-has-content': 'warn',
'jsx-a11y/aria-activedescendant-has-tabindex': 'warn',
'jsx-a11y/aria-props': 'warn',
'jsx-a11y/aria-proptypes': 'warn',
'jsx-a11y/aria-role': 'warn',
'jsx-a11y/aria-unsupported-elements': 'warn',
'jsx-a11y/heading-has-content': 'warn',
'jsx-a11y/href-no-hash': 'warn',
'jsx-a11y/html-has-lang': 'warn',
'jsx-a11y/iframe-has-title': 'warn',
'jsx-a11y/img-redundant-alt': 'warn',
'jsx-a11y/no-access-key': 'warn',
'jsx-a11y/no-distracting-elements': 'warn',
'jsx-a11y/no-redundant-roles': 'warn',
'jsx-a11y/role-has-required-aria-props': 'warn',
'jsx-a11y/role-supports-aria-props': 'warn', …
```
=> ESLint Config: Upgrade eslint-plugin-jsx-a11y and activate more rules.

packages/eslint-config-react-app/index.js
This removes `eslint` rules which are syle choices.
With rule that's being removed.
```
<div visible ={false} />
// or 
<div visible= {false} />
// or 
<div visible={false} />
//  or 
<div visible = {false} />
```
Are all allowed!
Fixes #2057
=> Removing a stylistic lint rule

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Our `resolveLoader` config is the only thing I found causing https://github.com/facebookincubator/create-react-app/issues/556 to fail.
We probably already fixed the other issues.
I don't think we need it anyway because it was mostly necessary for npm 2 which we’re dropping.
As a followup I decided to add `require.resolve()` to all loaders and configs. We already do this in a bunch of places, and it seems to make sense given that *the config is the one that knows their versions*. Webpacks resolves them relatively to the source, but I don’t think this is what makes sense in most cases.
I hope this doesn’t break some obscure linking scenario. In fact I think it might fix some of the more obscure ones. But I’m not 100% sure.
=> Support hoisting react-scripts and add require.resolve() to loaders

packages/react-scripts/config/webpack.config.prod.js
Fixes https://github.com/facebookincubator/create-react-app/issues/2026.
From my understanding, caveats from https://github.com/facebookincubator/create-react-app/pull/591 apply to development only.
If this is buggy we can disable it in a patch.
=> Enable CSS sourcemaps in production

packages/react-dev-utils/openBrowser.js
Tiny improvement to fix #2047.
=> react-dev-utils/openBrowser now supports urls with 2+ params

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
This removes a hack that caused an absolute path to be embedded in the modules after being processed by our Babel preset. This hack doesn’t matter for apps that are bundled, but it breaks libraries.
The hack was in the wrong place. We can’t really get around the fact that regenerator runtime is resolved from the consuming application. So instead we should embrace it, and redirect at the webpack config level instead. Additionally the preset should make it clear `babel-runtime` is meant to be installed by the app, so I moved it to the peer dependencies.
=> Resolve regenerator runtime relative to react-scripts

packages/react-scripts/package.json, packages/react-scripts/scripts/start.js
Fixes https://github.com/facebookincubator/create-react-app/issues/2179.
=> Handle errors from port detector

packages/eslint-config-react-app/index.js, packages/react-dev-utils/eslintFormatter.js
* Adds an explanatory message to the bottom of the lint error output
* Adds a rule forbidding AMD syntax
* Adds a rule forcing you to hoist `import`s manually since people often trip on this thinking they can put statements between them
=> Tweak lint rules

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/template/README.md
We don’t often make special cases like this but Moment.js is extremely popular, and there is no end to this problem in sight. I’m okay just doing this as a “best practice” already popular in the community.
=> Ignore Moment.js locales by default

packages/react-dev-utils/ModuleScopePlugin.js, packages/react-dev-utils/README.md, packages/react-dev-utils/package.json, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Sorry, short on time. Should be self explanatory.
=> Add module scope plugin

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Hi,
I was just reading the config and I saw a typo that could come from old comments.
=> Webpack config typo

packages/react-dev-utils/formatWebpackMessages.js, packages/react-scripts/config/webpack.config.prod.js
* Hides `[CaseSensitivePathsPlugin]` prefix for errors from `case-sensitive-paths-webpack-plugin` since the messages are descriptive enough.
* Hides the `Total precache size is [...]` message from `sw-precache` which is noisy on every build. I let the other messages pass through as ejected users might misconfigure it and will likely want to see them in this case.
=> Tidy up some build logs

packages/react-dev-utils/README.md, tasks/e2e-simple.sh
This adds a test to make sure we don't unwittingly regress (since we're relying on webpack internals).
It also fixes the usage README.
=> Follow up PR for module scoping

packages/react-scripts/config/webpack.config.prod.js
A temporary workaround to fix https://github.com/facebookincubator/create-react-app/issues/2199.
We can revisit when https://github.com/mishoo/UglifyJS2/issues/1964 is solved.
=> Disable Uglify reduce_vars

packages/react-dev-utils/README.md, packages/react-dev-utils/eslintFormatter.js, packages/react-dev-utils/package.json, packages/react-dev-utils/printHostingInstructions.js, packages/react-scripts/scripts/build.js
This moves a bunch of code into `react-dev-utils`, applies our `start` formatting to the `build`, and fixes https://github.com/facebookincubator/create-react-app/issues/2190.
Please test.
=> Refactor and improve build output

packages/react-dev-utils/webpackHotDevClient.js, packages/react-error-overlay/src/components/code.js, packages/react-error-overlay/src/components/frame.js, packages/react-error-overlay/src/components/overlay.js, packages/react-error-overlay/src/styles.js
Follow up from PR #2201
I think I addressed the critical things and some of the nits, including:
Did not address:
=> Tweaked error overlay styles (pt2)

packages/create-react-app/createReactApp.js, packages/create-react-app/index.js, packages/create-react-app/package.json
Dropping support for Node 6 is breaking for CLI, so we'll bump it to 2.x.
But then even people with CLI 1.x would get `react-scripts@1.0` which isn't Node 4 compatible.
To solve this, we will release the last CLI 1.x which falls back to `react-scripts@0.9.x` on old environments.
Then we'll bump CLI to 2.x and remove support for Node 4 in it.
=> Add temporary support for Node 4.x to global CLI

packages/react-scripts/bin/react-scripts.js, packages/react-scripts/config/env.js, packages/react-scripts/config/paths.js
=> ES6 syntax

packages/react-dev-utils/README.md, packages/react-error-overlay/middleware.js, packages/react-error-overlay/package.json, packages/react-error-overlay/src/components/frame.js, packages/react-scripts/config/webpackDevServer.config.js
It makes sense because they know about each other.
=> Move error overlay middleware into react-error-overlay

packages/react-dev-utils/webpackHotDevClient.js, packages/react-error-overlay/src/styles.js
Last thing I wanted to fix before cutting 1.0.
This changes `z-index` to the actual max possible value (and one below for runtime overlay).
It also changes the logic to prevent dismissing the syntax overlay right before the page reloads. Now we only dismiss it when the page is guaranteed to stay (which is when? I’m not sure but maybe it’ll make more sense in the future). Anyway, the point is that compile overlay should no longer disappear in flicker, just to be refreshed a few milliseconds later.
=> Improve interaction between compile and runtime overlays

README.md, packages/react-scripts/template/README.md
Also will need to merge https://github.com/facebookincubator/create-react-app/pull/1801.
=> Enable 1.0 docs

packages/react-error-overlay/src/overlay.js
In regard to #2231, I tried to write a quick fix for the error, by not handling shortcuts if the error list is empty.
Tested by rebuilding `react-error-overlay`, and testing shortcuts.
If you think they're is a better way to do this, i'm completely open for suggestions, as I am new to create-react-app codebase !
Thanks 😄
=> Fix shortcut handling in react-error-overlay

packages/react-scripts/scripts/start.js
Inspired by #787 as suggested in https://github.com/facebookincubator/create-react-app/issues/1753#issuecomment-285882292.
I think this fixes https://github.com/facebookincubator/create-react-app/issues/1753 and https://github.com/facebookincubator/create-react-app/issues/932.
I have not verified, but I’ll just go ahead and close them, and if it doesn’t work we can reopen.
=> Gracefully shut down the server on signals

README.md, packages/react-scripts/template/README.md
Between issues like https://github.com/facebookincubator/create-react-app/issues/2225, and the general switch to Webpack (and update of our preset) I am temporarily hiding React Storybook integration because it doesn't work. Will be happy to add it back once it's compatible with `react-scripts@1.0.0`.
=> Hide React Storybook from the User Guide while it's incompatible

packages/react-scripts/config/env.js
This matches both what https://github.com/bkeepers/dotenv does, and what we claim we do in the docs. Fixes https://github.com/facebookincubator/create-react-app/issues/2249.
=> Ignore .env.local in test environment

packages/eslint-config-react-app/index.js
It's just a style rule.
Fixes https://github.com/facebookincubator/create-react-app/issues/2245.
=> Turn off operator-assignment stylistic rule

packages/react-scripts/template/README.md
https://github.com/facebookincubator/create-react-app/issues/2156
=> update readme with example of include path

packages/react-scripts/template/README.md
s/adding-images-and-fonts/adding-images-fonts-and-files/
=> update reference adding-images-fonts-and-files

packages/react-scripts/config/webpack.config.prod.js
As mentioned in https://github.com/facebookincubator/create-react-app/issues/2235#issuecomment-302760351.
=> Additional fix to service worker config for "homepage" field

packages/react-scripts/config/env.js, packages/react-scripts/config/paths.js, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
This fixes https://github.com/facebookincubator/create-react-app/issues/2230#issuecomment-302673174 specifically (note: not the same as main issue in #2230 which was fixed in #2242).
Reproducing code was in https://github.com/ingro/cra-test-bug.
The underlying cause is https://github.com/facebook/jest/pull/3616. However I want to make sure any other tools we use in the future don't have the same problem, and consolidate our cleanup of `NODE_PATH` (since we already do it for Webpack anyway).
=> Always resolve NODE_PATH

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Fixes an issue I introduced in https://github.com/facebookincubator/create-react-app/pull/2261.
Travis didn't catch it because of https://github.com/facebookincubator/create-react-app/issues/2263.
In particular, if it is empty, `''.split()` gives us `['']` and then webpack complains about empty value at the end when validating the config. Which is neat!
=> Fix a bug on empty NODE_PATH

packages/react-dev-utils/package.json
On npm 2.15.11 I'm getting an "Error: Cannot find module 'text-table'", from react-dev-utils/eslintFormatter.js:4:15). This fixes that error.
=> Fix missing dependency on npm 2

packages/react-dev-utils/launchEditor.js
In WSL (Bash on Ubuntu on Windows), Windows executables can be launched from within the shell, however setting `EDITOR` or `REACT_EDITOR` to a Windows editor and feeding `launchEditor()` an absolute path currently results in it trying to open a file at e.g. `C:\mnt\c\...\foo.js` (usually resulting in a new file with that save path), rather than just opening `C:\...\foo.js` like it should do. Thankfully, the interop functionality can actually translate between the WSL and Windows version of a path (when it's located on the Windows file system), as long as it's provided as a relative path, which is what this change does.
Just to make it clear, these are the possibilities when using this utility under WSL after this change:
<table>
<tr><td></td><th>Linux-based editor<br>(e.g. …
=> Add WSL support to launchEditor utility / error overlay functionality

packages/react-scripts/config/webpackDevServer.config.js, packages/react-scripts/template/README.md
The newly added host check (https://github.com/webpack/webpack-dev-server/issues/887, [explanation](https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a)) is significantly disruptive to people’s workflows (https://github.com/facebookincubator/create-react-app/issues/2271, https://github.com/facebookincubator/create-react-app/issues/2233), especially in legit use cases like cloud editors (https://github.com/facebookincubator/create-react-app/issues/2271#issuecomment-302872631).
I think **only enabling the host check for `proxy` users** is a reasonable compromise because unlike WDS, we only serve files in `public` folder by default which the user has consented to... being public. Of course, with `proxy` enabled this is still dangerous, so we enable the host …
=> Only enable host check if you use proxy, and add a way to opt out of it

packages/react-scripts/scripts/eject.js
[#2090](https://github.com/facebookincubator/create-react-app/pull/2090)
sorry about last PR, I had accidentally pushed commit to build.js and couldn't solve merge conflict.
so I made another branch.
=> Ejecting should ensure you have clean git status

packages/react-dev-utils/README.md, packages/react-dev-utils/noopServiceWorkerMiddleware.js, packages/react-dev-utils/package.json, packages/react-scripts/config/webpackDevServer.config.js, packages/react-scripts/template/public/service-worker.js
R: @gaearon @Timer 
This adds in a "no-op" `service-worker.js` at the root of the dev environment's web server.
It works around the issue of someone serving their dev and prod environments from the same port and ending up with a production service worker that controls their dev environment.
If a user finds themselves in that situation, then the next time the browser checks for an updated service worker, the "no-op" version will be installed instead, and immediately force any open pages to reload, so that they're once again talking directly to the dev server.
(The caveat here is that, as with all things service worker-y, this assumes that `build/service-worker.js` was served [using reasonable cache headers](https://github.com/facebookincubator/create-react-app/tree/master/packages/react-scr …
=> Provide a no-op SW that will be served by the dev environment.

CHANGELOG.md
* `react-dev-utils`, `react-scripts`
* [#2276](https://github.com/facebookincubator/create-react-app/pull/2276) Serve a no-op service worker in development to ensure it doesn't cache the production build even if it was served on the same port. ([@jeffposnick](https://github.com/jeffposnick))
* `react-dev-utils`, `react-error-overlay`
* [#2290](https://github.com/facebookincubator/create-react-app/pull/2290) Wrap console calls into a check for IE9. ([@gaearon](https://github.com/gaearon))
* [#2282](https://github.com/facebookincubator/create-react-app/pull/2282) Add Windows Subsystem for Linux support to the error overlay. ([@noinkling](https://github.com/noinkling))
* [#2269](https://github.com/facebookincubator/create-react-app/pull/2269) Fix a missing package …
=> Add changelog for 1.0.2

packages/react-scripts/package.json
This works around https://github.com/facebookincubator/create-react-app/issues/2302.
=> Roll back to an older version of case-sensitive-paths-webpack-plugin

packages/react-dev-utils/webpackHotDevClient.js, packages/react-error-overlay/src/effects/proxyConsole.js
An improvement of what we did in https://github.com/facebookincubator/create-react-app/pull/2290/files
Same way as https://github.com/facebookincubator/create-react-app/pull/2290/files
=> Wrap console calls into a check

packages/eslint-config-react-app/index.js
Until this issue (https://github.com/gajus/eslint-plugin-flowtype/issues/165) is fixed we're disabling `flowtype/require-valid-file-annotation`.
(For future tracking this came out of a twitter thread: https://twitter.com/robdel12/status/866073982801502209)
=> Remove `flowtype/require-valid-file-annotation` temporarily.

packages/react-dev-utils/WebpackDevServerUtils.js
=> Ensure address is private

README.md
I no longer support this package.
Create-react-app is so great I can no longer call tarec a credible alternative :smile:
=> Remove tarec from README

packages/react-dev-utils/crossSpawn.js, packages/react-dev-utils/package.json, packages/react-scripts/bin/react-scripts.js, packages/react-scripts/package.json, packages/react-scripts/scripts/eject.js, packages/react-scripts/scripts/init.js
Unused dependency `connect-history-api-fallback` was removed from `react-scripts`. Next I removed `cross-spawn` dependency from `react-scripts` and use re-exported version from `react-dev-utils` instead as we discussed in my last PR (#2283).
But one think I observed is that after ejecting an app all the dependencies from react-dev-scripts remain in the yarn.lock. Is it ok?
=> Remove connect-history-api-fallback and cross-spawn dependencies (#751)

packages/eslint-config-react-app/index.js
Addresses the use case described in https://github.com/facebookincubator/create-react-app/issues/2157#issuecomment-303106812.
We still catch the mistakes in the same scope.
=> Allow declaring variables before use in a scope above

packages/react-dev-utils/webpackHotDevClient.js
As discussed in https://github.com/facebookincubator/create-react-app/issues/2157#issuecomment-303131618.
You can still see them all in the terminal, but there's no use littering the browser console.
=> Limit console warnings to 5 files at most

packages/react-dev-utils/WebpackDevServerUtils.js
=> Don't resolve localhost if on network

packages/eslint-config-react-app/package.json, packages/react-error-overlay/.flowconfig, packages/react-error-overlay/package.json, packages/react-scripts/package.json
Background
------------
After upgrading my app to `create-react-app` 1.0.0, I started seeing flow errors, coming from `eslint-plugin-jsx-a11y` that's bundled with `create-react-app`. I've been able to reproduce in [a simple test app](https://github.com/iainbeeston/eslint-plugin-jsx-a11y-241), and you can see the flow errors raised in [the circleci build for it](https://circleci.com/gh/iainbeeston/eslint-plugin-jsx-a11y-241).
What went wrong?
-------------------
`create-react-app` currently uses `eslint-plugin-jsx-a11y` locked to version 5.0.1, which has [a bug](https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/241) with it's flow types. This issue was fixed in version [5.0.2](https://github.com/evcohen/eslint-plugin-jsx-a11y/commit/d70ac7d7975819e7a52b85465ec67a0d93eb962a).
How …
=> Resolve flow errors in eslint JSX a11y

packages/react-scripts/config/webpack.config.prod.js
Adds `navigateFallbackWhitelist` to service worker precache config options in Webpack config for production builds. This solves an issue with [Firebase reserved URLs](https://firebase.google.com/docs/hosting/reserved-urls) not working due to the PWA service worker serving the `navigateFallback` URL (/index.html) when non-cached URLs are requested.
Fixes part of https://github.com/facebookincubator/create-react-app/issues/2237, specifically https://github.com/facebookincubator/create-react-app/issues/2237#issuecomment-302693219.
=> Add navigateFallbackWhitelist /__* to SW Precache config

CHANGELOG.md
* `eslint-config-react-app`, `react-error-overlay`, `react-scripts`
* [#2346](https://github.com/facebookincubator/create-react-app/pull/2346) Resolve Flow errors in an ESLint plugin. ([@iainbeeston](https://github.com/iainbeeston))
* [#2332](https://github.com/facebookincubator/create-react-app/pull/2332) Fix proxying issues with backends that don't support IPv6. ([@Timer](https://github.com/Timer))
* [#2347](https://github.com/facebookincubator/create-react-app/pull/2347) Don't precache `/__*` URLs to fix Firebase hosting. ([@ryansully](https://github.com/ryansully))
* README
* [#2334](https://github.com/facebookincubator/create-react-app/pull/2334) Add missing files to the list. ([@jesselpalmer](https://github.com/jesselpalmer))
- Iain Beeston …
=> Add changelog for 1.0.6

packages/react-scripts/package.json
This [update](https://github.com/webpack/webpack/releases/tag/v2.6.0) of webpack unlocks some new features to better handle dynamic imports. 
Not sure what should do to test it, I've ran `npm test` with no errors but `npm run e2e` fails both on windows and on WSL.
=> Update webpack to v2.6.0 in react-scripts

packages/react-scripts/template/README.md
Simplified steps for deploying app to `now` as a static site. No need to `serve` script in `package.json` file. As of May 15, 2017, all static deployments on `now` are free and unlimited.
=> Update README.md for `now` deployments

packages/react-scripts/config/webpack.config.prod.js
This is a fix for #2293 
[Webpack v2.6.0](https://github.com/webpack/webpack/releases/tag/v2.6.0) included the [fix](https://github.com/webpack/webpack/pull/4902) of `Uglify` so we removed `reduce_vars: false` to restore the default back to `true`.
=> Removed the overriding of reduce_vars since webpack v2.6.0 included fix of Uglify

packages/react-scripts/config/webpack.config.prod.js
Testing: I created an equivalent repo to the repo described in https://github.com/facebookincubator/create-react-app/issues/2376 but using this version of create-react-app, and its production build doesn't exhibit the bug mentioned in that bug.
=> Disable comparisons feature in uglify compression in production

packages/react-scripts/scripts/build.js, packages/react-scripts/scripts/start.js, packages/react-scripts/scripts/test.js
This ensures we set both `BABEL_ENV` and `NODE_ENV` in case the preset reads `BABEL_ENV` instead.
This probably fixes https://github.com/facebookincubator/create-react-app/issues/2377 although I still don’t understand why `BABEL_ENV=undefined` (visible in the message) was preferred to an existing `NODE_ENV`. Perhaps it only fixes it for some cases.
=> Consistently set environment variables

CHANGELOG.md
* [#2382](https://github.com/facebookincubator/create-react-app/pull/2382) Consistently set environment variables. ([@gaearon](https://github.com/gaearon))
* [#2379](https://github.com/facebookincubator/create-react-app/pull/2379) Temporarily disable `comparisons` feature in uglify compression. ([@davidascher](https://github.com/davidascher))
* [#2383](https://github.com/facebookincubator/create-react-app/pull/2383) Update webpack to 2.6.1. ([@gaearon](https://github.com/gaearon))
* [#2349](https://github.com/facebookincubator/create-react-app/pull/2349) Update webpack to v2.6.0. ([@ingro](https://github.com/ingro))
* [#2351](https://github.com/facebookincubator/create-react-app/pull/2351) Removed the overriding of `reduce_vars` since webpack v2.6.0 …
=> Add changelog for 1.0.7

tasks/e2e-kitchensink.sh
As noted in #2285, [appveyor tests are failing](https://ci.appveyor.com/project/gaearon/create-react-app-a3khu/build/1.0.811/job/iyhmu4pwoa9leiu2#L1415).
This PR is intended as a patch to cover this case, while the kitchensink CI tests are fixed.
=> Catch "No tests found" during CI

packages/react-dev-utils/WebpackDevServerUtils.js
AFAIK yarn doesn't need the "run" prefix.
=> Suggest just "yarn build"

tasks/e2e-kitchensink.sh
I don't know if it'll help (probably not).
Trying to figure out why AppVeyor turns
```
npm test -- --no-cache --testPathPattern=/src/
``` 
into
```
node scripts/test.js --env=jsdom "--no-cache" "--testPathPattern=C:/Program Files/Git/src/"
```
even though the script itself has quotes around `testPathPattern`.
=> Fix wrong path expansion in end-to-end test

tasks/e2e-kitchensink.sh
Reverts facebookincubator/create-react-app#2387
It seems like actually fixing the issue causes a test failure with a weird message.
Let's just remove this for now.
=> Revert "Catch "No tests found" during CI"

tasks/e2e-kitchensink.sh
This fixes #1672, the cleanup command for the kitchensink e2e tests.
The command should be either be `xargs kill -s SIGKILL` or `xargs kill -9`.
I believe this was causing issues with running e2e test locally where clean ups were partially failing and causing re-running of the tests to include old files/data.
=> Fix kill command in e2e-kitchensink.sh cleanup

tasks/e2e-installs.sh, tasks/e2e-kitchensink.sh, tasks/e2e-simple.sh
Fixes #2399 
Yarn is caching old react-scripts when running the e2e tests, which means old versions are being used during the build process. Fine for CI where each build is on a clean machine but breaks e2e in unforeseen ways on local machines.
This might be related to yarnpkg/yarn#2165
The fix is to run `yarn clean cache` before running the e2e tests.
=> Added cache clear to e2e scripts

packages/react-dev-utils/ModuleScopePlugin.js
This PR fixes [#2404](https://github.com/facebookincubator/create-react-app/issues/2404).
=> Fix detection of parent directory in ModuleScopePlugin

packages/react-scripts/template/README.md
since CRA now uses the latest version of Jest under the hood,
`jest-enzyme` v3.2.0 is now also working perfectly fine
I've made a PR to update their docs too
https://github.com/blainekasten/enzyme-matchers/pull/99
`package.json`
`.test.js file`
*note: I intentionally make the test failed (string vs number)*
=> docs: update `jest-enzyme` section

packages/react-dev-utils/launchEditor.js
WebStorm changed the format to open files from the command line in the latest versions.
Relates to #2406.
https://www.jetbrains.com/help/webstorm/2017.1/opening-files-from-command-line.html
Tested manually on my windows machine.
=> Add WebStorm >2017 launchEditor Support

packages/react-scripts/template/README.md
Removed Node v4 (CRA only supports Node >= 6)
=> Update Travis CI Node versions in User Guide

packages/react-scripts/template/README.md
I re-enabled the storybook section, and updated the documentation and links.
Can you please review **but not yet merge**?
This is because our `3.0.0` release is not yet released. Though this is about to happen (expected to be this week).
If you have any comments or question, just let me know!
=> re-add storybook && update the documentation and links

packages/react-scripts/template/src/index.js
Hi. I'm under the assumption that `index.css` is used for global styles not associated with any component. This is where I import 3rd party css libraries as well. However, I noticed that it would override the styles in `App.css`.
=> Prioritize index.css over the implicit App.css

packages/react-scripts/config/webpack.config.dev.js
Added `webpack.NamedModulesPlugin()` according to #2448 
Profiler now look like this instead of anonymous:
=> Added NamedModulesPlugin in webpack.config.dev.js

README.md
* Update README.md to make links to webpack point to webpack.js.org instead
insteade of webpack 1 webpack.githup.io
=> Update webpack links to point to webpack 2

packages/react-scripts/template/README.md
- Call `npm run flow --init` won't create a .flowconfig file, it should be `npm run flow init`
=> Flow init to run as command not flag

packages/react-scripts/package.json
This eliminates a `yarn` warning on OSX machines running Node.js 8. See
here for details: https://github.com/strongloop/fsevents/issues/170
You can see an example of the warning in the second screenshot in
https://github.com/facebookincubator/create-react-app/issues/2422#issuecomment-305218252
I verified this by running:
```bash
npm run create-react-app my-app
cd my-app
yarn
```
=> Upgrade fsevents to 1.1.2

packages/react-scripts/template/README.md
It should be `baz` instead of `bar` on last example.
```
// Matches /bar/abc.html and /bar/sub/def.html <- wrong
"/baz/**/*.html": {
"target": "<url_4>"
// ...
}
```
=> Fix wrong comment on Proxy guide

packages/react-dev-utils/WebpackDevServerUtils.js, packages/react-dev-utils/package.json
On Linux/macOS (and WSL too) it requires admin permissions to run a server on a port below 1024.
I'm shifting my development stuff to WSL on Windows at the moment and didn't know that so it would be nice to show another message in this case.
ref #2512
=> Show warning when trying to run on port below 1024 without admin permissions under Linux/macOS

packages/react-scripts/scripts/build.js
In the rare case that the environment variable has been defined as a non-string, we don't want to cause an error.
=> Fix a potential issue

packages/react-dev-utils/launchEditor.js
https://www.jetbrains.com/help/webstorm/opening-files-from-command-line.html
https://www.jetbrains.com/help/phpstorm/opening-files-from-command-line.html
Both editors have the same signature `<editor> <projectPath> --line <number> <filePath>` to open file from the command line.
It seems to work even if `<projectPath>` is omitted (commit 02f88ba15701f70e613137dd5a3d81caba9d9eb8).
Tested on `Win10`+`PhpStorm2016` and `macOS 10.12`+`PhpStorm2017`.
=> Support PhpStorm in launchEditor

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/package.json
Updating sw-precache-webpack-plugin to `v0.11.3` will fix the following related issues:
Windows path: https://github.com/facebookincubator/create-react-app/issues/2235
Duplicate builds: https://github.com/facebookincubator/create-react-app/pull/1728#issuecomment-301998584
I have tested by running `/bin/react-scripts.js build` and asserting that the build log message is not emitted twice. The problem was discovered in this https://github.com/goldhand/sw-precache-webpack-plugin/pull/78 we were calling the webpack `done` callback twice.
I do not have a windows machine to test the windows fix but the fix is exactly the same as in this configuration. The fix is [here](https://github.com/goldhand/sw-precache-webpack-plugin/blob/ea47cec497ed2fbed1dee962df325b3fdbf785ee/src/index.js#L114) and has …
=> Update sw-precache-webpack-plugin to lastest version

packages/react-scripts/template/src/registerServiceWorker.js
R: @Timer @gaearon 
FYI: @addyosmani
This is a bit more explicit than trying to use a regular expression. It uses the `URL` object inside of a block that first checks to see if `navigator.serviceWorker` is defined; `URL` should always exist in browsers that support service workers.
From testing locally, I saw scenarios in which `process.env.PUBLIC_URL` wasn't set at all (which contradicts what @Timer [suggested in the issue](https://github.com/facebookincubator/create-react-app/issues/2374#issuecomment-304362666)).
The code in this PR should behave properly regardless of whether it's unset, whether it's set to a local path, or whether it's set to a full URL.
Fixes #2374
=> Determines whether PUBLIC_URL is same-origin before registering SW.

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Since `v2.2.1` of Webpack, the need for `ident` for complex options is no longer required. See
https://webpack.js.org/guides/migrating/#complex-options
Steps ran to check if `postcss-loader` and its plugins still work.
- `npm start`. 
- Add to `App.css`. 
```
display: flex;
user-select: none;
flex: 1 0 calc(1vw - 1px);
```
- Check chrome dev tools and select element too see if `postcss-flexbugs-fixes` & `autoprefixer` work. See screenshot.
Then checked build version
- `npm run build`
- `serve -s build`
- Check chrome dev tools and select element. See screenshot
=> webpack no need for `ident` if using complex options anymore

CONTRIBUTING.md, package.json, packages/react-scripts/fixtures/kitchensink/README.md, tasks/local-test.sh
=> E2E testing enhancements

packages/react-scripts/config/webpack.config.prod.js
This doesn't really make any difference AFAIK but prevents an annoying warning when the result file is too large and Babel switches this mode on automatically.
=> Use Babel compact mode in production

packages/react-scripts/config/webpack.config.prod.js
Fixing https://github.com/facebookincubator/create-react-app/issues/2488
Verified the changes by cloning https://github.com/crabicode/create-react-app-emoji and manually editing react-scripts/config/webpack.config.prod.js
Before:
After:
=> turn on ascii_only for issue with emoji and regex

packages/react-scripts/scripts/eject.js
Hi :) I've a spotted a small bug in eject command output.
Steps to reproduce:
Given the `package.json` file:
```json
"start": "react-scripts start",
"build": "react-scripts build",
"test": "react-scripts test --env=jsdom",
"eject": "react-scripts eject",
"stylelint": "node ./node_modules/stylelint/bin/stylelint.js src/**/*.scss",
"eslint": "node ./node_modules/eslint/bin/eslint.js src/**/*.js"
```
As you can see there are two custom scripts that were added after the project was created.
The output of `npm run eject` is:
```
Replacing "react-scripts start" with "node scripts/start.js"
Replacing "react-scripts build" with "node scripts/build.js"
Replacing "react-scripts test" with "node scripts/test.js"
Replacing "react-scripts stylelint" with "node scripts/stylelint.js"
Replacing …
```
=> Fix eject command updating scripts output

packages/react-scripts/scripts/eject.js
This should fix https://github.com/facebookincubator/create-react-app/issues/2624 and work around https://github.com/facebookincubator/create-react-app/issues/2030.
Obviously it's not a very good workaround, but I'm running out of options and we need the CI to be working. The reason I'm okay with this solution is because current behavior is broken anyway. Re-running `yarn` makes no difference since we didn't change the lockfile, so it might as well be a no-op.
See https://github.com/facebookincubator/create-react-app/issues/2627 for discussion of the proper fix.
=> Don't run yarn after ejecting

packages/create-react-app/createReactApp.js, packages/react-scripts/scripts/eject.js
This should hide useless warnings like https://github.com/facebookincubator/create-react-app/issues/2613#issuecomment-311315516.
npm discussion https://github.com/npm/npm/issues/11632.
Yarn doesn't support this yet AFAIK but I filed https://github.com/yarnpkg/yarn/issues/3738.
=> Set npm loglevel to 'error'

packages/react-dev-utils/launchEditor.js
I decided to go with an a bit different approach for Windows than on macOS. This resolves the first two issues mentioned below.
The new approach detects only by the file name and re-uses the whole path found in the process list to launch the editor. On macOS this was not possible because some executables did not match the command needed to run (if I understood that right).
Regarding the third one:
We could improve that by launching a PowerShell at the beginning in the background and just pipe the commands in then. This would require to switch to a Promise/callback-based implementation of the whole feature. I would pick that up in a second PR later on if you're okay with it 🙂 
Tested on Windows 10 with latest VS Code, Atom and Sublime Text 3.
_The original content of this PR:_
> So, this …
=> Auto-detect running editor on Windows for error overlay

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Chrome devtools doesn't recognize Windows file paths with backslashes. This is a naive fix, replacing backslashes with forward slashes. I tried looking for a more generalized `path` function that did this, but didn't find any.
Before:
After:
Fixes #2456.
=> Fix sourcemap directory organizing on Windows (#2456)

packages/react-scripts/template/src/registerServiceWorker.js
Adds invalidation of service workers based on by attempting to `fetch` `service-worker.js` and if its receives a 404, or if its the wrong content type (e.g. all not found urls are being redirected to index.html or serving a 404 page without a 404 code) it unregistered the current service worker and reloads the page.
This issues the issue where sites hosted on the same `url:port` (e.g. `localhost:5000`) are incorrectly displaying`create-react-app` instead of the hosted page.
This was addressed in a more complex manner in #2438. However, this is a simplified version based on the feedback of @jeffposnick.
Note: I created a new PR/Branch because I believe #2438 addresses more cases, however it also adds complexity. This PR should fix most use cases when combined with #2426.
=> Add simplified service worker invalidation

packages/react-scripts/template/README.md
Due to many of the other examples in the README showing both `npm` and `yarn` commands.
I have added an example of how to install a dependency using `yarn`.
=> Add yarn example under "Installing a Dependency"

packages/react-scripts/template/README.md
Provides some information on setting up a WebSocket Proxy to avoid confusion. #2260
=> Update docs with WebSocket proxy information

packages/react-scripts/template/README.md
In the section about npm run build fails in troubleshooting added more
info about memory usage of the build script and a link to a tutorial for
adding more swap space as a viable solution.
Today I tried to create a build in my cheap 512MB Digital Ocean 
Ubuntu server and I ran into issues similar to #1026 and #1493. 
After running the command while having the system monitor open, I
noticed that it uses hundreds of megabytes of memory. The 
docs do mention this issue, but what really helped me was a tutorial
that I found online for adding more swap space to the server. It is for 
Ubuntu 14.04 but it does work on newer versions and it should be still
useful for any other Linux distro that uses systemd. I think that it would
be good to add it to the docs.
Also, since #1496 it no longer fails …
=> Add more info about OOM build failiure [docs]

README.md, packages/react-scripts/template/README.md
=> Added instruction on how to install Prettier

packages/react-dev-utils/launchEditor.js
Hello from the https://github.com/adobe/brackets/ team! 👋 
Tested on MacOS, should work on WIN too!
=> Add Brackets to launchEditor.js

README.md, packages/react-scripts/template/README.md
This is a second try to add React Styleguidist to CRA docs after #921, where we’ve decided that CRA integration in Styleguidist wasn’t good enough. Since then we’ve greatly improved first time experience and out-of-the-box CRA support.
=> Add React Styleguidist

packages/react-scripts/config/webpack.config.prod.js
For some reason it comes up as false positive on Uglify errors which is bad: https://github.com/facebookincubator/create-react-app/issues/2433.
It is also not very meaningful to most users (skipping what? why?)
For now I'm muting it, but we can consider adding our own warnings for large bundles in the future.
=> Ignore "Skipping static resource" message from SW precache

packages/react-dev-utils/FileSizeReporter.js, packages/react-scripts/scripts/build.js
We now have docs both about code splitting and about analyzing bundles so seems like a good time.
The limits are *very* liberal IMO. For the vast majority of apps it's possible to fit the main bundle into 512k gzipped, and 1M gzipped for individual chunks. If that doesn't fit you, you might as well need to eject for other reasons (e.g. too slow builds that need fine tuning with HappyPack or similar).
The warning looks like this:
**In the screenshot I hardcoded it to show the message (to test it), but in practice it will only appear for main bundles > 512k gzipped, and for chunks > 1m gzipped.**
This partially alleviates the problem https://github.com/facebookincubator/create-react-app/pull/2645 is hiding. Perf sensitive users will probably notice this. We still don't address the issue in …
=> Warn about large bundle sizes

packages/create-react-app/createReactApp.js, packages/react-scripts/scripts/eject.js, packages/react-scripts/scripts/init.js, tasks/e2e-installs.sh
The distinction doesn't fully make sense in React world because you need both types to bundle the app, and neither on the server. It also created problems for folks who run build on deployment. It is also inconsistent (for example promise polyfill is technically a runtime dependency but was treated as a build one). Fixes https://github.com/facebookincubator/create-react-app/issues/2655 as well.
=> Put react-scripts in dependencies, not devDependencies

packages/react-scripts/template/README.md
Trying to be more consistent and show diffs.
=> Minor code style edits to user guide

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/scripts/utils/createJestConfig.js
This PR will be fixing a pain point I've been experiencing in code reuse of React Native projects with Create React App projects. The React Native bundler will allow Android specific code to resolve with a prefixed `.android` on the default `.js`/`.jsx` extension. This PR is allowing that same functionality but with web specific code.
While React Native Web support has been added in in the past, the addition did not follow 
_https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md_ exactly, missing the added extensions options to the webpack config.
Something I may have missed in the PR is making any additional changes to the file `/create-react-app/packages/react-scripts/scripts/utils/createJestConfig.js`. Will there need to be any additional extension …
=> Better React Native Web support

CONTRIBUTING.md, packages/react-scripts/fixtures/kitchensink/README.md
I've added a link to **Docker**'s installation docs, as requested in https://github.com/facebookincubator/create-react-app/pull/2408#issuecomment-311672317.
=> Local testing docker links

CHANGELOG.md
* [#2550](https://github.com/facebookincubator/create-react-app/pull/2550) Fix Node 8 compatibility. ([@josephfrazier](https://github.com/josephfrazier))
* [#2610](https://github.com/facebookincubator/create-react-app/pull/2610) Fix sourcemap directory organization on Windows. ([@plusCubed](https://github.com/plusCubed))
* [#2596](https://github.com/facebookincubator/create-react-app/pull/2596) Fix an issue with minifying emojis. ([@viankakrisna](https://github.com/viankakrisna))
* [#2501](https://github.com/facebookincubator/create-react-app/pull/2501) Fix incorrect check if `CI` variable is set to true. ([@varnav](https://github.com/varnav))
* [#2432](https://github.com/facebookincubator/create-react-app/pull/2432) In new projects, don't register service worker for …
=> Changelog for 1.0.8

packages/react-scripts/template/README.md
This changes the proposed way about using prettier inside the README.md, because prettier supports css since the 1.4.0 release and json since the 1.5.0 release. 
Was not sure if it was a good idea to add different regexes for json and css inside the README.md don't have a real opinion about it myself, could maybe easier for starters to do so if they wan't to add things like `eslint` or `stylelint` the the commit hooks.
=> Add json and css to lint-staged in template README

.travis.yml, tasks/e2e-installs.sh, tasks/e2e-kitchensink.sh, tasks/e2e-simple.sh
We still test Node 7 on AppVeyor
=> Test Node 8 on Travis

bootstrap.js, lerna.json, package.json, tasks/e2e-installs.sh, tasks/e2e-kitchensink.sh, tasks/e2e-simple.sh
`lerna bootstrap` uses `npm` unless otherwise specified.
It also doesn't understand when it should or should not apply concurrency.
This PR polishes contributor workflow and addresses above issues (long time nit I've had but too lazy to do anything about).
=> Bootstrap with Yarn

CHANGELOG.md
* [#2680](https://github.com/facebookincubator/create-react-app/pull/2680) Fix external CSS imports. ([@gaearon](https://github.com/gaearon))
* [#2679](https://github.com/facebookincubator/create-react-app/pull/2679) Fix minor typo. ([@dbanck](https://github.com/dbanck))
* [#2666](https://github.com/facebookincubator/create-react-app/pull/2666) Add more info about Apache client side routing. ([@viankakrisna](https://github.com/viankakrisna))
* [#2671](https://github.com/facebookincubator/create-react-app/pull/2671) Add JSON and CSS to Prettier instructions. ([@jbovenschen](https://github.com/jbovenschen))
* Other
* [#2673](https://github.com/facebookincubator/create-react-app/pull/2673) Bootstrap with Yarn. ([@Timer](https://github.com/Timer))
* …
=> Changelog for 1.0.9

packages/react-dev-utils/package.json
This should fix #2691.
`strip-ansi` v4.0.0 (used by `react-dev-utils`) updates `ansi-regex` to v3.0.0, which exports an arrow function instead of a regular function. Internet Explorer 11 doesn't support arrow functions, so in development the app throws a syntax error and won't load. Downgrading to the previous version of `strip-ansi` (v3.0.1) also downgrades `ansi-regex` and should resolve the issue.
=> Downgrade `strip-ansi` package

README.md
**Documentation: ReadMe update**
Gluestick is a notable alternative actively used and maintained by TrueCar
https://github.com/TrueCar/gluestick
=> Added `gluestick` to the alternatives section

CHANGELOG.md
* [#2692](https://github.com/facebookincubator/create-react-app/pull/2692) Fix IE11 crash in development. ([@pdhoopr](https://github.com/pdhoopr))
* [#2683](https://github.com/facebookincubator/create-react-app/pull/2683) Fix a typo. ([@BenBrostoff](https://github.com/BenBrostoff))
* README
* [#2402](https://github.com/facebookincubator/create-react-app/pull/2402) Added `gluestick` to the alternatives section. ([@JoeCortopassi](https://github.com/JoeCortopassi))
- Ben Brostoff ([BenBrostoff](https://github.com/BenBrostoff))
- Forbes Lindesay ([ForbesLindesay](https://github.com/ForbesLindesay))
- Joe Haddad ([Timer](https://github.com/Timer))
- Patrick Hooper ([pdhoopr](https://github.com/pdhoopr))
- …
=> Changelog for 1.0.10

packages/eslint-config-react-app/index.js
This PR should address #2647 by allowing tagged templates. This avoids ESLint warning about `styled-components`'s `injectGlobal`.
=> ESLint: set allowTaggedTemplates to true

packages/react-scripts/template/README.md
Glob support has been added in source-map-explorer@1.4+
=> Remove Windows note for source-map-explorer

packages/react-dev-utils/launchEditor.js
This allows you to set REACT_EDITOR to 'vim --remote', so the file can
be opened in an already running vim process. When using vim without
remote, it works in the same way as before.
When launching vim without --remote, the order of the line and path
arguments doesn't matter. However, when using --remote the line argument
has to precede the path. This happens to be the same as joe and emacs
uses, so the vim cases were just moved there.
I haven't tested this with mvim, but the documentation says the same as
the vim documentation, so I assume it works the same.
=> Reorder vim arguments in launchEditor so --remote works

packages/react-dev-utils/launchEditor.js
PyCharm has the same signature as WebStorm and PhpStorm `<editor> <projectPath> --line <number> <filePath>` so it can reuse the logic from those.
https://www.jetbrains.com/help/pycharm/opening-files-from-command-line.html
Tested with PyCharm Pro 2017.1.4 on MacOS 10.12
=> Support PyCharm in launchEditor

packages/react-scripts/scripts/utils/createJestConfig.js
Jest’s default value for its [`moduleFileExtensions`](https://facebook.github.io/jest/docs/en/configuration.html#modulefileextensions-array-string) option is `["js", "json", "jsx", "node"]`. CRA was not using this option before version 1.0.8, so this default list was used.
PR #2511 (merged in version 1.0.8) sets this option to `["web.js", "js", "json", "web.jsx", "jsx"]`. The PR is about adding `.web` extensions, but it is also removing `.node` because it is not included like other default extensions.
Packages using native code through `node-gyp` import files with `.node` extension. Using those packages fails the tests with a `Cannot find module …` error.
This used to work with version 1.0.7.
[This repo](https://github.com/mostafah/cra-jest-extensions-bug) is a minimal reproduction of …
=> Add “node” to Jest's moduleFileExtensions

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
This PR uses the oneOf rule to resolve loaders in `webpack.config.prod.js`. This will use the first loader that matches in the list of loaders provided by `oneOf` and enables us to remove the big exclusion list of the `file-loader`. The file loader will only be used if the module falls through all other loaders.
https://webpack.js.org/configuration/module/#rule-oneof
For some reason though I had to still preserve the `js(x)` exclusion in the file loader. Otherwise the build would break. This happens with or without the `eslint` preloader. Will have to investigate further why exactly this happens and why these unknown `js(x)` modules fall through to the `file-loader`.
The `resolve` now looks something like this (pseudocode):
```javascript
[
{ 'eslint-loader', enforce: 'pre', test: …
```
=> Use Rule.oneOf to resolve correct loader

packages/react-dev-utils/launchEditor.js
Autodetect PyCharm (Pro and CE), WebStorm, PhpStorm, IntelliJ IDEA, RubyMine, CLion, and AppCode
Added IntelliJ IDEA, RubyMine, CLion, and AppCode to list of IDEs. They have the same signature as WebStorm and PhpStorm `<editor> <projectPath> --line <number> <filePath>` so they can reuse the logic from those.
Removed older integrations of PyCharm, WebStorm, AppCode, IntelliJ IDEA
https://www.jetbrains.com/help/idea/opening-files-from-command-line.html
https://www.jetbrains.com/help/pycharm/opening-files-from-command-line.html
https://www.jetbrains.com/help/phpstorm/opening-files-from-command-line.html
https://www.jetbrains.com/help/ruby/opening-files-from-command-line.html
https://www.jetbrains.com/help/webstorm/opening-files-from-command-line.html
Tested with Appcode 2017.1.3, CLion …
=> Autodetect JetBrains IDEs

packages/react-dev-utils/package.json, packages/react-dev-utils/printHostingInstructions.js
This PR (#2750) removes the line prompting to install `serve` if the user already has it installed globally. Tested on Mac OS with and without serve installed.
=> Don't prompt to install serve if already installed

packages/react-scripts/template/README.md
Fix https://github.com/facebookincubator/create-react-app/issues/2593
=> Docs for react-router v4 basename feature

packages/react-scripts/package.json
This resolves another iteration of #1268 which was resolved in https://github.com/webpack/webpack-dev-server/pull/975. The current error is:
> Uncaught Error: Incompatible SockJS! Main site uses: "1.1.4", the iframe: "1.1.2".
=> Upgrade webpack-dev-server

packages/react-scripts/template/README.md
=> Add explicit "Opting Out of Caching" header

packages/react-scripts/package.json
As discussed, bumping to Webpack 3.4. Damn they're fast.
=> Bump Webpack 3.4

packages/create-react-app/createReactApp.js
When specifying a --scripts-version, the first `@` in a scoped package prevents the `packageName` from being trimmed of its version tag, if it has one. Hence, an uncaught error is thrown when the full, pinned package name is used in the path to read `package.json`:
I added the .match() to yield a truthy value if the `installPackage` contains an @ symbol at char `0` and at char `1+`. To test that this works, run `create-react-app --scripts-version=@organization/my-react-scripts@0.0.1` and see that create-react-app completed successfully and that the correct package version was installed:
=> Allow use of scoped packages with a pinned version

packages/react-scripts/bin/react-scripts.js
The create-react-app need node >= 6, and node version 6 support a lot of ES6, and let's switch using '+' to concat string with template string.
=> use the template string

packages/react-dev-utils/README.md
It must work in webpack 2 since create-react-app is still using it and is using webpack 2 now.
It would be great if you could add some kind of note about how it differs from the default webpack hot reloaders.
=> Remove note about webpackHotDevClient being webpack 1.0 only

packages/react-dev-utils/ansiHTML.js, packages/react-dev-utils/webpackHotDevClient.js
This should fixed #2789.
Just replaces all the angle brackets to `&lt;` and `&gt;` to avoid parsing them as real HTML elements.
Here is the screenshot of the example that mentioned in origin issue, the checkbox is not showing and it displays its source code.
=> Fix parsing HTML/JSX tags to real elements

package.json
Since `yarn.lock` shouldn't be added to the repo, nor excluded via
`.gitignore`, lets take advantage of `lint-staged` to unstage any staged
`yarn.lock` files before they can even be committed.
=> Unstage yarn.lock pre-commit

packages/react-scripts/bin/react-scripts.js
Need to be able to pass Node args into the spawned Node process:
```bash
$ npx react-scripts --inspect build
```
=> Fix the order of arguments in spawned child proc

packages/react-dev-utils/WebpackDevServerUtils.js, packages/react-dev-utils/formatWebpackMessages.js, packages/react-scripts/scripts/build.js
Hi,
I propose this change to `formatWebpackMessages` that currently removes all errors but one to the places in which it is used.
I propose this change because it's really surprising that when you call a function that is supposed to format messages that actually formats and removes messages.
I moved the removal of messages where they're displayed. That makes it clearer why you see only one single error and not all the errors that occured.
=> fix formatWebpackMessages to return all formatted messages instead of just one error.

packages/react-scripts/config/webpack.config.prod.js
escape hatch for https://github.com/facebookincubator/create-react-app/issues/2555 and various request for disabling source maps on production.
verified the changes using this command
```
REACT_APP_DISABLE_SOURCE_MAP=1 npm run build
```
and check build folder for the existence of source maps
<hr />
Use this one for the latest changes
```
SOURCE_MAP=false npm run build
```
=> use env variable to disable source maps

packages/react-dev-utils/printBuildError.js
=> Remove superfluous lodash usage

packages/react-scripts/template/README.md
The service was rebranded to xervo.io and was completely shut down in April 2017
=> Remove Modulus from user guide

packages/react-dev-utils/README.md
Closes https://github.com/facebookincubator/create-react-app/issues/2357
=> Fix docs for `printFileSizesAfterBuild`

packages/react-scripts/template/README.md
Hi!
I've added the steps for debugging the app in WebStorm (similar to VS Code).
Please let me know if you have any questions or I can improve something.
Thanks!
=> Docs: debugging in WebStorm

packages/react-error-overlay/src/components/frame.js
Since https://github.com/facebookincubator/create-react-app/pull/2458, we've been showing a weird name in the error overlay for top-level module errors: `Object.<module path>`. 
This fixes it to just omit `Object.` because it's always useless.
=> Fix module function name in error overlay

CHANGELOG.md
* `react-error-overlay`
* [#3012](https://github.com/facebookincubator/create-react-app/pull/3012) Fix module function name in error overlay. ([@gaearon](https://github.com/gaearon))
* [#2938](https://github.com/facebookincubator/create-react-app/pull/2938) Remove superfluous lodash usage. ([@Timer](https://github.com/Timer))
* [#2917](https://github.com/facebookincubator/create-react-app/pull/2917) Optimize the size of default favicon. ([@sylvainbaronnet](https://github.com/sylvainbaronnet))
* [#2986](https://github.com/facebookincubator/create-react-app/pull/2986) Docs: debugging in WebStorm. ([@prigara](https://github.com/prigara))
* [#2948](https://github.com/facebookincubator/create-react-app/pull/2948) Remove Modulus from user …
=> Changelog for 1.0.12

packages/react-scripts/config/webpack.config.dev.js
=> Fix error overlay 'Object.assign' issue in IE by including polyfills before webpack client

packages/react-dev-utils/FileSizeReporter.js
This fixes bug #3048 and strips hashes from chunks correctly.
1. `npm run create-react-app test-fix`
2. `cd test-fix`
3. Copied `src/App.js` and `src/content.js` from [cra-chunk-bundle-diff-bug repo](https://github.com/esturcke/cra-chunk-bundle-diff-bug)
4. `yarn build`
```
...
File sizes after gzip:
48.61 KB  build/static/js/main.b6cc0832.js
288 B     build/static/css/main.cacbacc7.css
177 B     build/static/js/content.4f2061bf.chunk.js
...
```
5. Edit `src/content.js`
6. `yarn build`
```
...
File sizes after gzip:
48.61 KB (-1 B)  build/static/js/main.b3f3c0af.js
288 B            build/static/css/main.cacbacc7.css
180 B (+3 B)     build/static/js/content.c58cbe0c.chunk.js
...
```
=> Strip hash from chunk file name

packages/react-error-overlay/src/components/ErrorOverlay.js, packages/react-error-overlay/src/containers/CompileErrorContainer.js, packages/react-error-overlay/src/containers/RuntimeErrorContainer.js
=> Rename Overlay to ErrorOvelay

packages/react-dev-utils/webpackHotDevClient.js, packages/react-error-overlay/src/index.js, packages/react-error-overlay/src/listenToRuntimeErrors.js
Related to #2515 .
This makes the filename that `react-error-overlay` listens to configurable making it more modular and easy to integrate outside of CRA.
=> Make error overlay filename configurable

packages/eslint-config-react-app/README.md
The `npm install` script for outside usage instructions is outdated. Updated to match the package's current peer dependencies.
=> Update eslint-config npm install command

packages/react-error-overlay/src/utils/unmapper.js
Turns out that the `path` module stubbed into a web environment does not support Windows, nor contains the `posix` / `win32` variants of path (it's fixed `posix`, so `path.sep` returns `/` in a win32 environment).
Effectively, what happened here is that the `fileName` was `C:\foo\bar` and upon normalizing, remained `C:\foo\bar` (it should've switched to `/`, or more specifically, `path.sep`).
This aligns the behavior with the other path normalization process as seen here: https://github.com/facebookincubator/create-react-app/blob/b17fa4123e2d098d943f4b33ae9c5c2ac311fab6/packages/react-error-overlay/src/utils/unmapper.js#L67
Fixes #3078.
=> Switch to unix path separators before normalizing path for Windows compatibility

tasks/e2e-installs.sh, tasks/e2e-kitchensink.sh, tasks/e2e-simple.sh
in response to https://github.com/facebookincubator/create-react-app/pull/2792#issuecomment-325726021
=> run npm 5.4.0 in CI

packages/react-dev-utils/webpackHotDevClient.js
=> Reload the page when an error has occurred

packages/react-error-overlay/package.json
We may inadvertently release old source files (or ones under different case on certain file systems) if we do not clean the target compile directory first.
=> Clean target directory before compiling overlay

packages/react-dev-utils/launchEditor.js
Basic support of auto detecting running editor for #2636.
Tested on Ubuntu 16.04.
It detects few editors. JetBrains products should start by wrapper like /usr/local/bin/webstorm. Otherwise it takes a lot of time to open editor.
=> Auto-detect running editor on Linux for error overlay

tasks/e2e-installs.sh, tasks/e2e-kitchensink.sh, tasks/e2e-simple.sh
This reverts commit fcb6dc55578e089e9f62f6e6c12cb9b60a57fee5.
https://github.com/npm/npm/issues/16970 made the e2e in CI failed for changes containing the top level packages like https://github.com/facebookincubator/create-react-app/pull/3105 and https://github.com/facebookincubator/create-react-app/pull/3100.
I think we need to wait a little more to run npm 5++ in CI
=> Revert "run npm 5.4.0 in CI (#3026)"

packages/react-scripts/template/src/App.css, packages/react-scripts/template/src/App.js
- Changed h2 to h1 in template to adhere to accessibility guidelines.
- Added h1 styles to maintain same font size.
- Changed div tag to the semantically correct header tag for header in template.
Verification of changes:
1. Created new React app using the modified branch.
2. Checked code to ensure the h2 tag has been replaced with the h1 tag.
3. Ran `npm start` and verified the font size of new h1 tag matches the former h2 tag in browser.
=> Resolved issue #2971

tasks/e2e-kitchensink.sh
In #2515, we removed react-error-overlay from the dependency list of react-scripts, and now it's only included via react-dev-utils. This causes kitchensink test to download and use published react-error-overlay package from NPM instead of using the local package since [`replace-own-deps.js`](https://github.com/facebookincubator/create-react-app/blob/v1.0.13/tasks/e2e-kitchensink.sh#L133) can't handle it anymore. As a result, the test fails when there are changes that need sync in the local react-error-overlay and react-dev-utils packages (#3100).
This PR fixes the issue by linking the local package with `npm link`.
=> Link local react-error-overlay package in kitchensink test

packages/react-dev-utils/getProcessForPort.js
A few days late but here it is. Simply added the pid to the output allowing the process to be easily killed if that's your fancy.
=> Display pid in already running message (#3106)

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Update `This loader don't uses a "test"` to `This loader doesn't use a "test"` to make it more clear.
Thank you to everyone for the fantastic documentation that is well worth reading! 👏
=> Update unclear wording in webpack config docs (file loader section)

packages/react-scripts/template/README.md
Per 2017.07.27 TC39
https://github.com/tc39/proposals/commit/0bbbb08c3cdcc986d59b21782b70633329546042
=> Class fields to stage 3

packages/react-scripts/package.json
It doesn't look like there is any backwards incompatibility:
https://github.com/webpack/webpack-dev-server/releases
=> Update webpack-dev-server to 2.8.2

packages/react-scripts/template/README.md
Fixes #3184. 
My observation was that the configuration uses regexps for the proxy paths instead of globs.
=> Correct manual proxy documentation

packages/react-scripts/template/README.md
This formats the text better so it's clearer that `Accept` is a header
=> Minor docs change to highlight dev proxy behaviour

packages/react-scripts/template/public/index.html
Changed
`<!doctype html>`
to
`<!DOCTYPE html>`
According to the spec it should be uppercase (but parsing is case insensitive).
Spec link (see then `8.1.1 The DOCTYPE` chapter): https://www.w3.org/TR/html5/syntax.html#the-doctype
=> <!doctype html> -> <!DOCTYPE html>

packages/react-dev-utils/getProcessForPort.js, packages/react-scripts/config/webpackDevServer.config.js
Building off #2760, this will allow dev server to watch for changes in the `src/node_modules` directory.
Fix #3223
=> Allow the dev server to watch for changes in src/node_modules

README.md
=> Fix package management link in README for issue #3218

packages/react-error-overlay/build.js, packages/react-error-overlay/package.json, packages/react-error-overlay/src/iframeScript.js, packages/react-error-overlay/src/index.js, packages/react-error-overlay/src/utils/pollyfills.js, packages/react-error-overlay/webpack.config.iframe.js, packages/react-error-overlay/webpack.config.js
This attempts to implement the idea proposed in #3120.
In this implementation, the script(`iframeScript.js`) that needs to be executed in the context of the iframe is bundled in a separate webpack build step. Then this script is imported as a text using webpack raw-loader in the main overlay script(`index.js`) and inject to the iframe with a script tag. After the injected script is executed, it starts to communicate with the main script via some global hooks and continue to update overlay until there are no errors to show. 
Based on #2961, #1944, [using inline webpack raw-loader](https://github.com/facebookincubator/create-react-app/pull/3142/files#diff-66b69a1c0b15ace46390921b87d6621dR17) might not be a good idea. Any suggestions on that?
=> Make error overlay to run in the context of the iframe

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/package.json
[`style-loader` v0.19.0](https://github.com/webpack-contrib/style-loader/blob/master/CHANGELOG.md#0190-2017-10-03) adds an [`hmr` option](https://github.com/webpack-contrib/style-loader#hmr) which can be used to disable inclusion of its HMR code block in production builds.
=> Update style-loader and disable inclusion of its HMR code in builds

packages/react-dev-utils/webpackHotDevClient.js, packages/react-error-overlay/src/containers/CompileErrorContainer.js, packages/react-error-overlay/src/containers/RuntimeError.js, packages/react-error-overlay/src/containers/RuntimeErrorContainer.js, packages/react-error-overlay/src/containers/StackFrame.js, packages/react-error-overlay/src/containers/StackTrace.js, packages/react-error-overlay/src/iframeScript.js, packages/react-error-overlay/src/index.js, packages/react-error-overlay/src/utils/parseCompileError.js
This a basic implementation of "click to open in editor" feature for build(compile time) errors and We can improve it based on the feedback coming from the community.
Currently, it only supports Babel syntax errors and ESLint errors. What are the other common or known error types that we can consider here?
Also, please note that this includes a refactoring to the programming interface of the error overlay and it will break any project that uses the package separately without CRA.
=> Add click-to-open support for build errors

packages/react-error-overlay/package.json
=> `react-error-overlay` has no dependencies now (it's bundled)

packages/react-scripts/template/README.md
In the User Guide, it would be helpful to have links to the deployment services in each section title since most people will want to compare them before picking one.
=> Add external links to deployment services

packages/react-error-overlay/src/index.js
This logs a warning when the overlay is included in an envified production build or strictly minified build.
=> Add warning when using `react-error-overlay` in production

packages/react-error-overlay/package.json, packages/react-error-overlay/webpack.config.iframe.js, packages/react-error-overlay/webpack.config.js
=> Use production React version for bundled overlay

packages/react-scripts/template/README.md
=> Fix dead link to Jest "expect" docs

packages/react-scripts/template/README.md
The existing link lands on a 'this page has moved' placeholder that
doesn't redirect to the correct location. This PR replaces it with the
currently working URL.
Side note: this project is amazing 💕
=> Update link to Jest Expect docs

packages/react-scripts/template/README.md
=> Add jest coverage configuration docs

packages/react-scripts/package.json
After trying out to interop reasonml bindings for react, [reason-react](https://github.com/reasonml/reason-react) @chenglou found out that eslint was causing this practicular [problem](https://github.com/yannickcr/eslint-plugin-react/issues/921).
It is fixed in the newer version of eslint-plugin-react@7.3.0, this will allow to interop components in reason and plain js.
I have this [repo](https://github.com/lpalmes/reason-react-test) that displays the error found out when running it (in one session `yarn start`,  in another `yarn bsb-watch`), and a [branch](https://github.com/lpalmes/reason-react-test/tree/eject) fixing the problem by upgrading the dependency.
I'm sure this will be helpful for a lot of people looking to chime into the future of react.
Thanks!
=> Support reason-react

packages/react-scripts/template/README.md
=> recommend react-snap; react-snapshot isn't upgraded for React 16

packages/react-scripts/config/webpack.config.prod.js
Implement settings as suggested here:
https://github.com/mishoo/UglifyJS2/tree/harmony#mangle-options
To solve this Safari bug:
https://bugs.webkit.org/show_bug.cgi?id=171041
=> Make uglify work in Safari 10.0 - fixes #3280

packages/react-scripts/template/README.md
=> Add documentation for Enzyme 3 integration

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/scripts/utils/createJestConfig.js
Resolves #3237 by following https://github.com/facebookincubator/create-react-app/pull/2511.
`.mjs` is the specification the Node ecosystem has chosen for files containing ES Modules; we should support it!
=> Add `.mjs` support

packages/react-scripts/config/webpack.config.dev.js
According to this parameter's comment, it's unused but webpack-dev-server crashes without it. However, webpack-dev-server is running fine for me without this parameter.
=> Remove output.path from dev webpack config

packages/react-scripts/template/src/registerServiceWorker.js
A very minor update in the generated code to make it easier to read and avoid an useless `if (!x) {} else {}` expression.
=> Remove an useless negation in registerServiceWorker.js

packages/react-scripts/template/README.md
It looks like things have changed in opting out of service workers in the documentation. Most importantly, registerServiceWorker.js is returning different variables thus it's unclear how to call `unregister()`.
=> Updating the Service Worker opt-out documentation

packages/react-scripts/template/README.md
Instead of using `&&` to run multiple commands in `package.json`, guide users to use `npm-run-all`.
=> start using npm-run-all to build scss and js

packages/react-error-overlay/.gitattributes
Added .gitattributes file react-error-overlay which forces all *.js files to be checked out with LF line feeds.
=> Fix for add .gitattributes file #3080

appveyor.yml, packages/react-scripts/scripts/eject.js, tasks/e2e-kitchensink.sh, tasks/e2e-simple.sh
`npm link` is super unreliable and causes our tests to fail; this replaces `npm link` with a much more predictable behavior.
This doesn't work on AppVeyor yet because the version of `rsync` is complaining about a local copy; any ideas?
=> Stop using `npm link` in tests

packages/create-react-app/createReactApp.js
This is the only reliable way I could find to detect https://github.com/facebookincubator/create-react-app/issues/3326 and show a nice message.
Yarn is also affected by this issue, but running it with explicit `--cwd` flag fixes it. So we'll just let Yarn-powered installs run normally.
=> Add preflight CWD check for npm

CHANGELOG.md
* [#3287](https://github.com/facebookincubator/create-react-app/pull/3287) Fix favicon sizes value in the project manifest. ([@ryansully](https://github.com/ryansully))
* `react-dev-utils`, `react-scripts`
* [#3230](https://github.com/facebookincubator/create-react-app/pull/3230) Fix watching for changes in `src/node_modules`. ([@xjlim](https://github.com/xjlim))
* [#3239](https://github.com/facebookincubator/create-react-app/pull/3239) Allow importing `.mjs` files. ([@Timer](https://github.com/Timer))
* [#3340](https://github.com/facebookincubator/create-react-app/pull/3340) Polyfill `requestAnimationFrame` in test environment. ([@gaearon](https://github.com/gaearon))
* `babel-preset-react-app`, `react-dev-utils`, `react-error-overlay`, `react-scripts` …
=> Changelog for 1.0.15

packages/react-dev-utils/webpackHotDevClient.js
To test, I ran the following:
yarn run create-react-app ie11test
cd ie11test/
yarn start
Then I opened localhost:3000 in IE11 and verified that the sample app runs without errors.
=> Replace template literal; fixes #3367

packages/react-scripts/template/public/manifest.json
- changed favicon sizes description to an array `64x64 32x32 24x24 16x16` as file contains multiple sizes. See [w3c](https://w3c.github.io/manifest/#sizes-member), [mdc](https://developer.mozilla.org/en-US/docs/Web/Manifest#icons)
- changed favicon mime type from `image/png` to `image/x-icon`, as per [this](https://stackoverflow.com/a/28300054/1012616) SO answer
=> Update favicon props in manifest.json

CHANGELOG.md
* [#3374](https://github.com/facebookincubator/create-react-app/pull/3374) Set correct image type and sizes in `manifest.json`. ([@piotr-cz](https://github.com/piotr-cz))
* [#3368](https://github.com/facebookincubator/create-react-app/pull/3368) Fix a crash in development mode in older browsers. ([@felthy](https://github.com/felthy))
- Dan Abramov ([gaearon](https://github.com/gaearon))
- Piotr ([piotr-cz](https://github.com/piotr-cz))
Inside any created project that has not been ejected, run:
```
npm install --save --save-exact react-scripts@1.0.16
```
or
```
yarn add --exact react-scripts@1.0.16
```
=> Changelog for 1.0.16

CHANGELOG.md
* [#3401](https://github.com/facebookincubator/create-react-app/pull/3401) Stop using a deprecated option. ([@gaearon](https://github.com/gaearon))
* [#3399](https://github.com/facebookincubator/create-react-app/pull/3399) Add link to VS Code troubleshooting guide. ([@auchenberg](https://github.com/auchenberg))
* [#3400](https://github.com/facebookincubator/create-react-app/pull/3400) Update VS Code debug configuration. ([@auchenberg](https://github.com/auchenberg))
- Dan Abramov ([gaearon](https://github.com/gaearon))
- Kenneth Auchenberg ([auchenberg](https://github.com/auchenberg))
- Loren Sands-Ramshaw ([lorensr](https://github.com/lorensr))
Inside any created project that has not been ejected, run:
```
npm install --save --save-exact …
```
=> Add 1.0.17 changelog

appveyor.yml, tasks/e2e-kitchensink.sh
Fix #1654
Removed [fixed](https://github.com/appveyor/ci/issues/1431) `TODO`
=> one-line waiting for app start

packages/react-error-overlay/src/index.js
Context from https://github.com/react-cosmos/react-cosmos/pull/484#issuecomment-341589413
> @skidding thinking of programmatically closing runtime error overlay in some cases. I noticed there's a `dismissRuntimeErrors` function but [it isn't exported](https://github.com/facebookincubator/create-react-app/blob/9ce144ed90c37f116b8457821d36dba2ceb0490a/packages/react-error-overlay/src/index.js#L90). Do you see any reasons why it shouldn't be called? Otherwise I'd like to submit a PR for exporting it.
> @Timer Mainly because in our use case it doesn't make sense to dismiss. Happy to accept a pull request exporting it.
=> Export dismissRuntimeErrors function

packages/react-scripts/scripts/eject.js
=> Improve eject message

packages/create-react-app/createReactApp.js, tasks/e2e-installs.sh
Allow user to choose npm over yarn. This should close #3385.
=> add —use-npm flag to bypass yarn

packages/react-scripts/template/README.md
This updates the docs to include a “Debugging Tests” section. 
I included how to use debug Jest tests with Chrome/Node Inspector and the new `—inspect` flag.  
I also included the configuration file for debugging tests directly in VS Code.
I _think_ this mostly closes #594. I know @prigara wanted to additionally add a section about debugging Webstorm too, which would really finish this off!
=> Docs: How to Debug Unit Tests

packages/react-scripts/config/jest/cssTransform.js, packages/react-scripts/config/jest/fileTransform.js
Some of the links within the jest config file comments point to an article that has since been moved.
=> Fix dead links

packages/react-scripts/template/src/registerServiceWorker.js
R: @gaearon @Timer 
This adds in an additional log message pointing folks to https://goo.gl/SC7cgQ (I could use a different URL shortener or just include the full URL if you'd prefer.)
It's displayed every time `registerServiceWorker()` is called and there's a service worker active on `localhost`. Displaying it on each load should give it higher visibility vs. the other logging messages which are only displayed when content is initially cached or content is updated.
I hope it will help with the type of questions that come up at, e.g., https://github.com/facebookincubator/create-react-app/issues/2398#issuecomment-344510011
=> Add a localhost-only log message pointing folks to the PWA docs

packages/eslint-config-react-app/README.md
This fixes the broken link to removed `href-no-hash.md` file, which is no longer available in the [eslint-plugin-jsx-a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y) plugin (since [6.0.0](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/a14617528cda23c6c88902ace1d083e4e13ac271/CHANGELOG.md)).
=> Fix broken link to href-no-hash eslint rule

packages/react-error-overlay/src/index.js
Seems we forgot to set the unregister function.
=> Allow error overlay to be unregistered

packages/react-scripts/template/README.md
Updated link in documentation.
=> Update Prettier editor integration link

packages/react-scripts/template/README.md
Added details to the User Guide specifying how to deploy to a GitHub user page, instead of a project page.
Tested here: https://github.com/aaronlna/aaronlna.github.io
Issue: https://github.com/facebookincubator/create-react-app/issues/3456
=> Update User Guide with deploying to GitHub User pages

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
Closes #3520 
See issue for steps to reproduce/test.
=> Add mjs and jsx filename extensions to file-loader exclude pattern

packages/react-scripts/scripts/start.js
the code got updated from `detect()` to `choosePort()` while the comment did not.
=> updates comment to reflect codebase

packages/react-scripts/template/README.md
The launch configuration code provided is not compatible with VSCode since version 1.19.
The proposed documentation change is based on the response by a VSCode team member.
References:
https://github.com/facebookincubator/create-react-app/issues/3602#issuecomment-352075571
https://github.com/Microsoft/vscode/issues/40293#issuecomment-352017028
=> Updated Debugging Tests for VSCode

packages/react-scripts/template/README.md
(Cleaned up version of https://github.com/facebookincubator/create-react-app/pull/3530)
Documentation update to fix a [maddeningly easy oversite](https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows#comment48615249_9250168) for Windows users.  The `SET` command allows for [wrapping the variable assignment expression with double quotes](https://ss64.com/nt/set.html). Using this method negates the need to smash two commands together with the `&&` operator as currently documented.
=> use safer/more aesthetic syntax for setting environment variables on Windows

packages/react-dev-utils/ignoredFiles.js
This change prevents Regex expression errors from being thrown when the paths passed to the function have a `++` in them.
Taking a path like `some/dummy/path/with++/`
the function transforms it to `some\/dummy\/path\/with++\/` the second  `+` is not ignored by the regex engine and hence throws an `Invalid Regular Expression Error`
This pull request changes the path to `some\/dummy\/path\/with\+\+\/` with all `+` escaped.  
I noticed the bug when i tried to run `npm start`  in a directory containing a `+` in it's name.
npm version 5.5.1
node version 8.9.3
```
$ npm start
> demoreact@0.1.0 start C:\Users\Norris\Desktop\C_C++\JS\NodeJs\demoreact
> react-scripts start
Invalid regular expression: /^(?!C:\\Users\\Norris\\Desktop\\C_C++\\JS\\NodeJs\\demoreact\\src\\).+[\\/]node_modules[\\/]/: …
```
=> Fix path regex match bug

packages/react-scripts/template/README.md
=> Document adding a router

packages/react-scripts/template/README.md
Fixes https://github.com/facebookincubator/create-react-app/issues/682.
=> Link to an explanation for forking react-scripts

packages/react-dev-utils/launchEditor.js
Adds support for the error overlay to detect and open the file with the error in MacVim.
Relates to #2636.
=> Autodetect MacVim editor

packages/react-dev-utils/clearConsole.js
#1914
I've tested it with Windows 10 and 7, node versions from ~5.0.0 up to 7.7.0.
Didn't managed to test it on 8 but it should work to.
Before   
After
=> Update the string that clears the console.

packages/react-dev-utils/launchEditor.js
Adapting the code for usage elsewhere and noticed it doesn't support the dev channels of some editors.
=> Add editor support for Sublime Dev & VSCode Insiders

packages/react-dev-utils/FileSizeReporter.js
FileSizeReporter would fail if create-react-app project is ejected and webpack configuration is
modified to multi build setup. This could be reproduced with webpack configuration which returns array of configuration objects.
Real world use case for that kind of setup could be implementing localization with separate builds for each language.
In those situations `webpackStats` parameter would contain stats array
for each build. This fix will try to access stats and then fallback to using plaing webpackStats object.
If stats array is found it is mapped through and flattened. Assets are handled like before.
=> Fix FileSizeReporter for multi build Webpack setups

packages/react-scripts/template/README.md
When running `npm run eject` before creating `src/setupTests.js`, the resulting `package.json` file, won't contain any entry for it - and this is correct in my opinion, since otherwise Jest will crash - but it's useful to have it documented and avoid pointless waste of time.
=> Better documentation for setupTests.js when ejecting

packages/react-dev-utils/launchEditor.js
This PR helps auto detect [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/)
I have tested this on 
- macOS High Sierra v10.13.2
- windows 10 Pro v1703
**NOTE** :  not tested on linux
=> added code-insiders to the editor list

packages/react-dev-utils/errorOverlayMiddleware.js, packages/react-dev-utils/launchEditor.js, packages/react-dev-utils/webpackHotDevClient.js, packages/react-error-overlay/src/utils/parseCompileError.js
Fixes #3358 
Only support babel syntax errors with Atom, Sublime, Notepad++, Emacs, and VSCode. Welcome support for other editors.
@gaearon Any particular reason to [ignore the column number from eslint errors](https://github.com/facebookincubator/create-react-app/commit/5e35645b95af92b8b45cbb5e703e0bd8f38fd605)? If not we can change the message format and support eslint errors as well.
=> Open editor to exact column from build error overlay

packages/create-react-app/createReactApp.js
This change is useful for testing local changes to scripts packages before committing them.
e. g.
```
create-react-app my-app --scripts-version=file:./create-react-app/packages/react-scripts
create-react-app my-app --scripts-version=file:./path/to/custom/scripts-package
```
I verified these changes by running `npm link` inside the create-react-app package and then running `create-react-app my-app --scripts-version=file:./create-react-app/packages/react-scripts`.
=> Allowing "file:<path>" --scripts-version values

.travis.yml
It appears Travis CI trusty version has Yarn v1.3.2 now.
So (#3054) shouldn’t be an issue changing to trusty. As Travis CI [precise support](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status) will be dropped in March 2018 .
=> Travis CI use trusty instead precise

packages/react-scripts/template/README.md
The Windows commands shown in the README.md file target only cmd.exe, and not Powershell. Since Powershell is increasingly popular, I consider it useful to add the corresponding commands. 
Example:
=> Add Powershell commands to README.md

packages/create-react-app/createReactApp.js, packages/create-react-app/package.json
I realize the file says not to modify the createReactApp.js, but a better way to do this did not occur to me. If there is a better way, I am certainly open to it. 
To help the issue process and better narrow down environment and version issues, I have added `create-react-app --info` which should print the following:
```
Environment:
OS: macOS High Sierra 10.13
Node: 8.6.0
Yarn: 1.2.1
npm: 5.5.1
Watchman: 4.9.0
Packages: (wanted => installed)
react: ^16.0.0 => 16.0.0
react-dom: ^16.0.0 => 16.0.0
react-scripts: 1.0.17 => 1.0.17
```
=> add envinfo package, —info flag

packages/react-dev-utils/getProcessForPort.js
awk splits lines based on spaces, which causes directory names with spaces to end up in other fields. Using a for loop allows us to print from the 9th field onwards instead of just the 9th field.
Fixes #3439.
=> Print full directory name from lsof

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/scripts/init.js
Hi. I moved browsers from Autoprefixer’s inner option to `browserslist` in `package.json`.
* Autoprefixer team recommends only `package.browserslist` as a way to set target browsers.
* `package.browserslist` is used in many different tools. It is used by `autoprefixer`, `stylelint-no-unsupported-browser-features`, `eslint-plugin-compat`, `postcss-cssnext`, `postcss-preset-env`, `postcss-normalize`. The most important, this config will be used in next `babel-preset-env` 7.0.
* It is used by `autoprefixer-info` CLI tool. This CLI tool is part of `autoprefixer` package, but didn’t work correctly without Browserslist config.
* This config is useful not only for tools. The new developer will have the single place to check target browsers in a new project.
* CSS-Tricks …
=> Move browsers to cross-tool config

packages/babel-preset-react-app/index.js, packages/babel-preset-react-app/package.json
closes #2730
This will remain undocumented until the brave have tried it in the wild.
**Test Plan:**
There's currently no established way to test changes to
`babel-preset-react-app`. But I did create [`unmaintained-react-scripts-babel-macros`](https://www.npmjs.com/package/unmaintained-react-scripts-babel-macros) [a while back](https://github.com/facebookincubator/create-react-app/issues/2730#issuecomment-328153982) and it worked well.
=> add experimental babel-plugin-macros support
