facebook/create-react-app

- README.md
Roc is a tool that assists with creating JavaScript applications and minimise the amount of configuration and setup that needs to be done before starting a new project, making it easy to build, test and develop. 
Through its flexible ecosystem it support a number of different features and types of applications, like for example server side rendered React applications with no configuration needed.
https://github.com/rocjs/roc
> Add roc to the list of alternatives

- README.md
Quik is a tool to prototype and build apps with React and Babel with zero-setup. It also supports HMR, CSS modules, Sass etc.
https://github.com/satya164/quik
> Add quik to alternatives

- template/README.md
> Update README to correct typo

- global-cli/index.js
Tested and verified by `npm link`ing my local CLI to my global installation and running `create-react-app --version`:
Closes #151
> Fix --version

- template/README.md
It helps to maintain consistency with React docs
> Use double quotes for JSX properties

- README.md
Add aik as possible alternative for create-react-app
> Add one more alternative

- scripts/build.js
> Make filesize stats prettier

- README.md
hi all, just a small documentation update to the README to keep it in sync with the latest release. this is an awesome project btw! 😄
> generated project now includes .gitignore

- template/README.md
> Fix typo in template README

- template/README.md
Updated README.md with instructions to deploy on surge.sh
> Add Surge.sh to deploy instructions

- README.md
Shameless plug of course.
If you want hot reloading and the best DX experience (friendly errors, desktop notifications, decorators, very fast reload times with dlls...) you should really check out [The Awsesom REact Cli](https://github.com/geowarin/tarec) (tarec).
I have used it in numerous projects that now run in production and I continue to make it better day after day with a lot of love :smile:
Typescript and SSR are on the roadmap!
Thanks for create-react-app, it's an awesome project and a great source of inspiration :heart:
> Add tarec to the alternatives

- config/eslint.js
- config/webpack.config.dev.js
- config/webpack.config.prod.js
- scripts/utils/createJestConfig.js
> Add support for *.jpeg file extension.

- config/eslint.js
> Promote no-undef to be treated as an error

- tasks/cra.sh
> Use bundled local packages in the end-to-end flow

- packages/react-scripts/template/README.md
Fix link to recent version of this guide
> Docs: Fix link to recent version of this guide

- packages/react-scripts/scripts/start.js
> added link to better visualizing tool

- packages/react-scripts/config/webpack.config.prod.js
> Correct a comment mistype in webpack production config

- packages/eslint-config-react-app/index.js
- packages/react-scripts/utils/createJestConfig.js
Fixes https://github.com/facebookincubator/create-react-app/issues/952
> Fixes https://github.com/facebookincubator/create-react-app/issues/952

- packages/react-scripts/config/paths.js
solves https://github.com/facebookincubator/create-react-app/issues/973
> Move the remove-on-eject-end tag at the end of the file

- packages/react-scripts/package.json
> Update webpack-subresource-integrity to fix Windows builds

- packages/react-dev-utils/openBrowser.js
> Only open Chrome tab if BROWSER is missing or is Chrome

- packages/react-scripts/package.json
Fixes #1009 which was merged in `babel-loader@6.2.10` by @danez.
> Bump babel-loader version (#1009)

- packages/react-scripts/package.json
> Bump Jest version

- .gitignore
- packages/react-scripts/template/gitignore
Adds gitignores for Yarn to the root project and to the react-scripts template.
> fix: add yarn gitignores

- .travis.yml
- tasks/e2e-simple.sh
Reverts facebookincubator/create-react-app#1521
> Revert "Don't run CI on Node 0.10"

- tasks/e2e-installs.sh
- tasks/e2e-kitchensink.sh
- tasks/e2e-simple.sh
Just rolling back the pin I did before.
> Use Yarn latest in e2e

- packages/babel-preset-react-app/index.js
- packages/babel-preset-react-app/package.json
- packages/react-scripts/package.json
Reverts facebookincubator/create-react-app#1552
See https://github.com/facebookincubator/create-react-app/issues/553#issuecomment-280358039.
> Revert "Bump babel deps and re-enable transform-react-constant-elements"

- packages/react-scripts/template/README.md
https://github.com/facebookincubator/create-react-app/issues/790#issuecomment-281986264
> add a comment about NODE_ENV value set to 'production' during build step

- packages/react-scripts/template/README.md
> Document debugging in the browser.

- packages/react-scripts/template/README.md
Seems simpler.
Not sure it works though.
> Suggest to use .env for enabling polling mode

- packages/create-react-app/index.js
Adding diagnostic code as requested by @gaearon in https://github.com/facebookincubator/create-react-app/issues/1693
> Diagnostic code

- appveyor.yml
Fixes https://github.com/facebookincubator/create-react-app/issues/1701
> Skip AppVeyor CI builds for Markdown changes

- README.md
I don't want to put words on your mouth, but I think the philosophy of this project is "Zero configuration", similar to that of `standard`. 
[Convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration) is about providing sane defaults, but with the ability to override them if they don't match your needs. That is a different thing, IMO.
> Clarify philosophy about configuration

- packages/babel-preset-react-app/index.js
One more thing about switching to preset-env
> docs(babel-preset): Update information about babel-preset-env.

- packages/react-scripts/template/README.md
Fixes the wrong render of the code block
> User Guide: Removed blockquote from code section, due to markdown conflict

- appveyor.yml
Fix #1865 due to https://github.com/appveyor/ci/issues/1426
> Fix AppVeyor CI

- packages/react-scripts/template/public/index.html
> Suggest Yarn in HTML template

- packages/react-scripts/template/README.md
> Update information in User Guide for Enzyme dependency

- packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
- packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
- packages/react-scripts/fixtures/kitchensink/src/App.js
- packages/react-scripts/fixtures/kitchensink/src/features/webpack/LinkedModules.js
- packages/react-scripts/fixtures/kitchensink/src/features/webpack/LinkedModules.test.js
- tasks/e2e-kitchensink.sh
This adds tests which verify linked modules are working.
> Add linked modules test (0.10.x)

- CONTRIBUTING.md
This is a new version of https://github.com/facebookincubator/create-react-app/pull/1933 with new commit base. Now it is targeted at `0.9.x` branch
> Add note about installing watchman

- packages/eslint-config-react-app/index.js
Pull request fixes #1835 by allowing exempting for loop label statements.
Verified:
I applied same rules in a project created by create-react-app and supplied code entered with the issue. It didn't throw any warnings 👍
> Relax anti label rules. Fixes #1835

- packages/react-scripts/config/webpack.config.prod.js
Fixes https://github.com/facebookincubator/create-react-app/issues/1934
before:
after:
> Minify and map css

- packages/react-scripts/template/README.md
There's not a lot more to say...
> Fix Netlify heading level.

- packages/react-scripts/config/webpack.config.dev.js
> Define dev chunk names

- packages/react-scripts/template/README.md
Not sure if new, but the `--single` flag is now important.
> Fix instructions for serving with now

- packages/react-scripts/template/README.md
Simple documentation fix for the storybook documentation link which returns a not found page
> Fixed documentation link for storybook in README.md

- packages/react-scripts/package.json
Not important really, just need for some things I am testing.
> Bump React in development

- packages/react-scripts/template/README.md
> Remove live-editing since isn't accurate.

- packages/react-dev-utils/ansiHTML.js
> Add a missing mapping

- packages/eslint-config-react-app/index.js
Temporarily plugs https://github.com/facebookincubator/create-react-app/issues/2176 as suggested in https://github.com/facebookincubator/create-react-app/issues/2172#issuecomment-301780284.
> Disable require.ensure() warning

- packages/react-dev-utils/eslintFormatter.js
- packages/react-scripts/scripts/start.js
- packages/react-scripts/scripts/utils/createWebpackCompiler.js
This seems a bit better overall.
> Tweak colors for better contrast on Windows

- packages/react-dev-utils/webpackHotDevClient.js
- packages/react-error-overlay/src/styles.js
Other than this, everything seems to work well.
> Replace text-align: start with left to fix Edge and IE

- CHANGELOG-0.x.md
- CHANGELOG-1.x.md
- CHANGELOG.md
> Swap changelogs

- packages/react-dev-utils/package.json
- packages/react-error-overlay/package.json
Closes #2232
Package hoisting bites again!
> Add explicit package dependence

- packages/react-scripts/config/env.js
> Fix reading of .env variables

- packages/react-dev-utils/printHostingInstructions.js
1. npm link `react-dev-utils` globally
2. create new `create-react-app`
3. `npm link react-dev-utils`
4. `npm run eject`
5. Modify `config/paths.js`, change `appBuild`
6. `npm run build`
7. Verify output
```
The dist folder is ready to be deployed.
You may serve it with a static server:
npm install -g serve
serve -s dist
```
> Show customized build path for serve instruction

- packages/react-scripts/template/public/index.html
Now that we support Progressive Web App, i think it's nice to improve out of the box [Lighthouse](
https://developers.google.com/web/tools/lighthouse/) score. Added `<noscript></noscript>` to index.html.
> add noscript to template's index.html

- packages/react-scripts/config/webpack.config.prod.js
A bandaid to fix https://github.com/facebookincubator/create-react-app/issues/2235.
> Work around Windows path issue in SWPrecacheWebpackPlugin

- packages/react-dev-utils/webpackHotDevClient.js
- packages/react-error-overlay/src/effects/proxyConsole.js
Fixes https://github.com/facebookincubator/create-react-app/issues/2289.
> Wrap console calls into a check

- packages/react-scripts/template/README.md
> Fix broken links

- packages/react-dev-utils/FileSizeReporter.js
- packages/react-scripts/scripts/build.js
> Print file sizes with correct build folder path.

- packages/react-scripts/package.json
This includes a few bugfixes.
https://github.com/webpack/webpack/releases/tag/v2.6.1
> Update webpack to 2.6.1

- packages/react-scripts/template/README.md
``` diff
-This is an optimization designed to make your tests runs fast regardless of how many tests you have.
+This is an optimization designed to make your tests run fast regardless of how many tests you have.
```
> Fix minor typo

- packages/react-scripts/template/README.md
> Fix broken link to Storybook docs

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Hope this will be a bit more effective.
> Update issue & PR templates

- packages/react-scripts/config/webpack.config.dev.js
- packages/react-scripts/config/webpack.config.prod.js
* Provide us with clear instructions on how you verified your changes work. Bonus points for screenshots!
Created a new project using CRA, added `import 'dgram';` to the App.js. Verified that it fails before this commit, and works after this commit.
Relates to issue #2584
> Add empty mock for dgram

- packages/react-scripts/template/README.md
Link to tutorial on Code Splitting with React Router
> Docs: Added link to tutorial on code splitting

- packages/react-scripts/template/README.md
> add docs for setting up CircleCI for CRA

- README.md
https://github.com/jaredpalmer/razzle
> Add Razzle to the alternatives

- packages/react-scripts/template/README.md
See discussion in https://github.com/facebookincubator/create-react-app/pull/2044#discussion_r124516065.
@sapegin Looks good to you? I need to get this in before cutting a release today.
> Don't ask to install webpack for using Styleguidist

- package.json
Update to Prettier v1.
Here's a quick run down on what changed for the 1.0 release: http://jlongster.com/prettier-1.0
Here's the changelog since 1.0: https://github.com/prettier/prettier/blob/master/CHANGELOG.md
> Update Prettier to v1

- packages/react-scripts/template/README.md
After a revelation in https://github.com/facebookincubator/create-react-app/issues/2593#issuecomment-311729534
> Add more info about apache client side routing

- packages/react-scripts/config/webpack.config.dev.js
- packages/react-scripts/config/webpack.config.prod.js
- packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
- packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
- packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/style.css
Fixes https://github.com/facebookincubator/create-react-app/issues/2677.
Not sure why.
Would be nice to follow up with someone to figure it out.
cc @andykenward
> Fix external CSS imports

- .github/ISSUE_TEMPLATE.md
> Fix typo in README link

- packages/react-error-overlay/package.json
> Upgrade flow

- .github/ISSUE_TEMPLATE.md
> Issue template: fix env list ordering

- packages/babel-preset-react-app/index.js
> Update link to issue blocking JSX hoisting

- packages/react-scripts/template/README.md
moved npm run build before npm test in .travis.yml
> #2713 - react-scripts - fixed typo in Documentation 

- README.md
They moved it to pundle monorepo 2 months ago
> Update link for motion

- README.md
The electrode framework: https://github.com/electrode-io/electrode
> Add Electrode to alternatives

- CHANGELOG.md
> Prepare for 1.0.11 release

- packages/react-scripts/config/webpack.config.dev.js
- packages/react-scripts/config/webpack.config.prod.js
> add empty mock for child_process in webpack config

- .travis.yml
> Set travis config to use 'precise' ci environment

- packages/react-scripts/config/webpackDevServer.config.js
> Fix Windows compatibility

- packages/react-scripts/package.json
- Changelog: https://github.com/webpack-contrib/url-loader/blob/master/CHANGELOG.md
- Reference issue:  https://nodesecurity.io/advisories/535
> Update url-loader to 0.6.2 for mime ReDoS vuln

- packages/react-scripts/config/polyfills.js
- packages/react-scripts/package.json
Fixes https://github.com/facebookincubator/create-react-app/issues/3199.
> Polyfill rAF in test environment

- packages/react-scripts/template/public/manifest.json
> Fix favicon sizes value in manifest

- packages/react-scripts/template/README.md
Update VS Code debug configuration to reflect new default values in the VS Code Chrome debugger.
> Update VS Code debug configuration

- packages/react-scripts/template/README.md
> Add link to VS Code troubleshooting guide

- packages/react-scripts/template/README.md
"subway" by itself is not a proper noun
> Fix grammar in README

- packages/react-scripts/config/webpackDevServer.config.js
- packages/react-scripts/package.json
Fixes https://github.com/facebookincubator/create-react-app/issues/3390.
> Use new WebpackDevServer option

- packages/react-scripts/template/README.md
Fixed misspelling favourite -> favorite 'Deployment' Chapter in 'packages/react-scripts/template/README.md'
> Fix misspelling

- README.md
It's great to see love for Windows users elsewhere in the docs, thought I'd add it here too.
> Add link to nvm-windows

- packages/react-scripts/template/src/App.test.js
Partially solves https://github.com/facebookincubator/create-react-app/issues/3482#issuecomment-347347454.
> Unmount the App in the default test

- packages/react-scripts/config/webpack.config.dev.js
> Fixed typo in webpack.config.dev.js

- packages/eslint-config-react-app/index.js
> Relax no-cond-assign rule

- packages/babel-preset-react-app/README.md
Added some more documentation to install the babel-preset-react-app making it more clear on how to get started with this preset outside of create-react-app.
> Updated babel-preset-react-app README.md

- packages/react-dev-utils/printHostingInstructions.js
the diff is big, i think someone has an old prettier on their node_modules?. see here for a more readable https://github.com/facebookincubator/create-react-app/compare/master...viankakrisna:deployment-instructions?expand=1&w=1
> move the link for deployment to the bottom

- packages/react-error-overlay/package.json
Haven't verified this works yet..
> Try updating Flow

- packages/react-scripts/config/webpack.config.dev.js
- packages/react-scripts/config/webpack.config.prod.js
- packages/react-scripts/package.json
Eases https://github.com/facebookincubator/create-react-app/pull/3776
> Compile code in parallel

- packages/react-scripts/fixtures/kitchensink/src/features/syntax/AsyncAwait.js
Just to make sure this doesn't break again.
> Add regression test for #3055

- packages/react-scripts/template/README.md
>  Remove CSS modules docs

- packages/react-scripts/config/webpack.config.dev.js
- packages/react-scripts/config/webpack.config.prod.js
Just a small grammatical update in a webpack config.
> fix small grammatical typo in webpack config documentation

- packages/eslint-config-react-app/index.js
> remove radix eslint rule

- packages/react-dev-utils/formatWebpackMessages.js
> Remove duplicated stack from `thread-loader`

- packages/react-scripts/config/webpack.config.dev.js
- packages/react-scripts/config/webpack.config.prod.js
I added this here instead of our babel preset just because. 🤷‍♀️
> Babel 7 disabled code highlighting by default :cry:

- packages/create-react-app/package.json
> pin envinfo version to 3.4.2

- packages/react-scripts/scripts/init.js
Noticed there was a race condition that caused us to commit `node_modules` into the repo.
This fixes it.
> Fix git init race condition

- README.md
> Fix prefix format

- packages/react-scripts/template/README.md
Just removed a trailing space in the instructions.
> Removed trailing space

- packages/react-scripts/template/README.md
`s/allows to easily makes/allows you to easily make/`
> Fix a typo in packages/react-scripts/template/README.md

- CONTRIBUTING.md
Fixed some minor typos in `CONTRIBUTING.md` 😄
> fix: Minor typos

- packages/react-scripts/template/README.md
Update example package.json snippets to be correct.
> Fix typos in example monorepo documentation.

- packages/react-error-overlay/src/effects/proxyConsole.js
- packages/react-error-overlay/src/utils/getStackFrames.js
See https://github.com/facebook/create-react-app/pull/4187#issuecomment-376007887
> Revert lint-related changes made in #4193

- packages/react-scripts/template/gitignore
> use the lastest url of gitignore file

- packages/react-dev-utils/package.json
> hotfix/update detect-port-alt

- packages/react-scripts/template/README.md
> Fixed link to document describing CSS import

- packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
- packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/scss-styles.scss
- packages/react-scripts/package.json
> Update sass-loader (#4363)

- tasks/cra.js
> Remove trailing spaces from copyright

- README.md
> Update file tree view

- packages/react-scripts/config/webpack.config.dev.js
> Added thread-loader tweak for application code entry-point

- packages/react-scripts/template/README.md
Swapping out a paid Storybook video link for free text tutorials!
> Remove paywalled tutorial link for Storybook

- packages/babel-preset-react-app/dependencies.js
https://github.com/facebook/create-react-app/pull/5046#issuecomment-423501823
> Add Babel config sourceType: 'unambiguous' for dependencies

- packages/react-scripts/template/README.md
> small typo fix

- packages/react-scripts/template/README.md
Husky had an overhaul of the API, see https://github.com/typicode/husky
Therefore the usage advice here has been adjusted.
> Update usage advice of husky to 1.0

- CONTRIBUTING.md
> Update targeted IE version in documentation

- packages/react-error-overlay/webpack.config.iframe.js
- packages/react-scripts/config/jest/babelTransform.js
- packages/react-scripts/config/webpack.config.dev.js
- packages/react-scripts/config/webpack.config.prod.js
> Prevent Babel config overridden

- packages/babel-preset-react-app/dependencies.js
> Add dynamic import transformer for dependencies in test env

- README.md
https://github.com/facebook/create-react-app/pull/5097
> Fix Troubleshooting link

- packages/react-scripts/config/webpack.config.prod.js
Fixes https://github.com/facebook/create-react-app/issues/5120
> Output CSS sourcemaps in separate file

- packages/react-scripts/template/README.md
Properly solves #5038 
The `gh-pages` error message is misleading because my git `user.email` was already set.
I needed to set my git `user.name` as well to solve the issue.
> Add additional troubleshooting for Github Pages

- packages/babel-plugin-named-asset-import/LICENSE
- packages/babel-preset-react-app/LICENSE
- packages/confusing-browser-globals/LICENSE
- packages/create-react-app/LICENSE
- packages/eslint-config-react-app/LICENSE
- packages/react-app-polyfill/LICENSE
- packages/react-dev-utils/LICENSE
- packages/react-error-overlay/LICENSE
- packages/react-scripts/LICENSE
> Add license file to all packages

- packages/eslint-config-react-app/index.js
> Disable react/no-deprecated rule

- packages/react-scripts/scripts/utils/createJestConfig.js
Fixes https://github.com/facebook/create-react-app/issues/4393.
> Support globalSetup and globalTeardown Jest options

- CHANGELOG-1.x.md
- CHANGELOG.md
Moved all of v1 into separate changelog
> Add changelog for v2-final

- packages/react-scripts/template/README.md
> Adding documentation about git init

- packages/react-scripts/template/src/serviceWorker.js
Fixes #5299
I have no idea how to unit test this. Just trying to get the ball rolling.
> avoid TypeError on when registering service workers without config

- README.md
Simple change: copied the heading link from the user guide in `packages/react-scripts/template/README.md` to the root README
> Add the new SVGs feature from the template README to the root README

- packages/eslint-config-react-app/README.md
This PR updates the README to instruct users to install the updated dependency versions according to the `package.json`.
> Update eslint-config-react-app/README to reflect new dependency versions

- docusaurus/docs/getting-started.md
> Fixed typo in getting-started

- docusaurus/website/siteConfig.js
Adds "edit" button on the page, making it easy to contribute to docs. See: https://docusaurus.io/docs/en/site-config#editurl-string
IS:
> Add "edit" feature to Docusaurus pages

- packages/react-scripts/template-typescript/src/App.tsx
> Update TypeScript template

- README.md
eslint requires node 8.10 or higher.
> Update minimum node version to 8.10 in README

- packages/create-react-app/package.json
This should fix the environment error from #5679.
> update envinfo to 5.11.1

- packages/react-scripts/package.json
Updates postcss-preset-env to include the root fix for #5426.
Closes #5426
> Version bump postcss-preset-env to latest

- README.md
Add PR welcoming badge to the ``` README ``` file
> Add PR welcoming badge 

- packages/react-app-polyfill/ie11.js
- packages/react-app-polyfill/ie9.js
> Don't polyfill fetch for Node -- additional files

- README.md
Create React Native App (https://github.com/react-community/create-react-native-app ) has been archived by the owner. It is now read-only.
> React native repository updated in README.md

- netlify.toml
this one file will help CRA deploy to netlify - as discussed in #5807, please see more details there
> Add netlify.toml to prepare for deploy to netlify #5807

- .github/ISSUE_TEMPLATE.md
- README.md
- packages/babel-preset-react-app/README.md
- packages/create-react-app/README.md
- packages/eslint-config-react-app/README.md
- packages/react-dev-utils/README.md
- packages/react-scripts/README.md
- packages/react-scripts/bin/react-scripts.js
There are also a lot of links to the old README in the CHANGELOGs but I don't know if we want to update those.
> Update links to docs in all package README files

- packages/react-scripts/config/webpack.config.js
This PR fixes the following typo:
- seperated -> separated
> Fix comment typo

- docusaurus/docs/adding-a-css-modules-stylesheet.md
> Correct an error for documentation

- docusaurus/docs/supported-browsers-features.md
seems the page which the old link points to has removed the related information.
> update link for difference between proposal stages

- docusaurus/docs/getting-started.md
> Add note for global install of CLI

- README.md
> Minor issue in README.md

- docusaurus/website/package.json
- docusaurus/website/siteConfig.js
- docusaurus/website/yarn.lock
Docusaurus maintainer here 👋
Docusaurus has released a number of versions and many new features have been added. This PR updates the docs to the latest version of Docusaurus and enables the useful new features, namely:
- Last update author and time for a doc
- Collapsible side navigation (useful for websites with a large number of pages like CRA)
- Scroll to top button
These features are captured nicely within this screenshot:
Have a go at the Netlify preview to test it more in-depth.
If you don't want to enable certain features, I can omit them from the PR.
> Upgrade Docusaurus and enable new features

- packages/react-scripts/config/webpack.config.js
Fixes #6433.
Unfortunately it looked like the change made in #5060 caused some line number inconsistencies.
> Revert "Switch to eval-source-map (#5060)"

- docusaurus/docs/running-tests.md
"Collocation" insead of "Colocation".
> Fix typo in doc

- docusaurus/docs/making-a-progressive-web-app.md
- packages/react-dev-utils/printBuildError.js
- packages/react-dev-utils/printHostingInstructions.js
- packages/react-scripts/scripts/start.js
- packages/react-scripts/template-typescript/src/index.tsx
- packages/react-scripts/template-typescript/src/serviceWorker.ts
- packages/react-scripts/template/src/index.js
- packages/react-scripts/template/src/serviceWorker.js
This change converts all bit.ly links from http to https :)
> Convert all bit.ly links from http to https

- packages/react-scripts/config/webpack.config.js
> revert css sourcemaps in development

- packages/react-dev-utils/openBrowser.js
> minor typo fix in openBrowser

- packages/create-react-app/createReactApp.js
> Fix a typo

- packages/react-scripts/package.json
> Updating html-webpack-plugin dep

- packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Addresses #6566 - intended to operate as discussed
> Convert JSON.stringify \n to os.EOL

- packages/react-scripts/template-typescript/src/App.tsx
see https://github.com/facebook/create-react-app/pull/6623#issuecomment-471971346
> change named import into default import

- docusaurus/docs/running-tests.md
> Update link to React Testing Library docs

- packages/react-scripts/scripts/start.js
> Fix code comment typo

- docusaurus/docs/getting-started.md
This also updates our min version of Node that we ask for
> Add link to TypeScript page in Getting Started

- docusaurus/docs/adding-images-fonts-and-files.md
> Fix docs about minimum React version for SVG component support

- packages/react-scripts/package.json
Fixes #6852.
I update the dependency version of fsevents because old versions was vulnerable (CWE-59). Vulnerability found with snyk.io report
> Update fsevents dependency version

- docusaurus/docs/adding-custom-environment-variables.md
> Add note to restart the dev server after changing .env file

- docusaurus/docs/supported-browsers-features.md
Reverts facebook/create-react-app#6935
> Revert PR #6935 because CLA was not signed

- docusaurus/docs/deployment.md
> docs: fix env-cmd example in deployment section

- packages/react-scripts/package.json
> Upgrade svgr to 4.2.0

- packages/create-react-app/index.js
Fixes: https://github.com/facebook/create-react-app/issues/6940
> Fix compatibility of create-react-app to Node.js v0.10+

- packages/react-scripts/package.json
> Update @typescript-eslint package versions

- docusaurus/docs/getting-started.md
This PR is related to https://github.com/facebook/create-react-app/issues/7234
documented `--use-npm` & `--use-script` flag in CRA
> Documented --use-npm & --use-script

- README.md
> Fix issue #7181

- docusaurus/docs/code-splitting.md
see https://github.com/tc39/proposal-dynamic-import#import
see https://github.com/tc39/proposal-dynamic-import/pull/78
> proposal dynamic import are stage 4

- packages/react-scripts/package.json
> bump sass-loader

- packages/react-scripts/lib/react-app.d.ts
> add readonly modifier for css module

- docusaurus/website/i18n/en.json
- netlify.toml
> Update Netlify config

- CHANGELOG.md
> add a migration step to remove static from robots.txt

- packages/react-scripts/template-typescript/public/manifest.json
- packages/react-scripts/template/public/manifest.json
> remove trailing spaces

- docusaurus/docs/running-tests.md
> cleanup-after-each is no longer necessary!

- CODE_OF_CONDUCT.md
- docusaurus/website/core/Footer.js
React (and many other open source projects) have recently adopted the [Contributor Covenant](https://www.contributor-covenant.org/). This PR does the same for Create React App.
> Adopt Contributor Covenant

- docusaurus/docs/supported-browsers-features.md
[proposal dynamic import](https://github.com/tc39/proposal-dynamic-import) is currently stage 4.
This file is missed in https://github.com/facebook/create-react-app/pull/7372
> Clarify dynamic import stage in docs

- docusaurus/docs/using-https-in-development.md
> Document how to use the .env file to enforce HTTPS

- docusaurus/docs/troubleshooting.md
> Fix grammar error in troubleshooting.md

- docusaurus/docs/integrating-with-an-api-backend.md
ASP.NET Core has a pretty nice Create React App integration. Let's link to its docs.
> Link to ASP.NET Core docs

- README.md
📖 IMPROVEMENT: A little description of npx added in the documentation.
> 📖 DOC: Improvement

- .github/workflows/build.yml
This is a just a quick experiment with GitHub Actions.
I realize that this particular action is not useful at all. See #7852.
> Add a GitHub Action that runs the build script

- packages/react-scripts/scripts/build.js
> Fix eslint complaints in build.js

- docusaurus/website/package.json
- docusaurus/website/src/pages/index.js
- docusaurus/website/yarn.lock
* Update docusaurus 
* Fix backwards incompatible changes accordingly
> Bump docusaurus 🦖

- CONTRIBUTING.md
`https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/fixtures/kitchensink/README.md`
`https://github.com/facebook/create-react-app/blob/master/test/README.md`
> chore: Fix broken link for e2e README

- packages/react-scripts/scripts/utils/createJestConfig.js
> Add restoreMocks to supported jest config keys

- packages/babel-preset-react-app/create.js
fixes a typo in a comment. I am a master OSS contributor! 😂
> fix seperators typo

- packages/cra-template-typescript/template/src/App.css
- packages/cra-template-typescript/template/src/App.test.tsx
Adding changes to the TypeScript template to be consistent with the base JavaScript template.
> Make base and TypeScript templates consistent

- README.md
> Add contributors section to readme

- docusaurus/website/sidebars.json
> Add custom-templates to docs sidebar

- packages/react-dev-utils/browsersHelper.js
- packages/react-dev-utils/package.json
Update pkgUp and adapt to new config format. ( https://github.com/sindresorhus/pkg-up/commit/7b8d9cfc5d9f7bb47cb3e38359a0cfa0e92caedd )
> Bump pkgUp

- packages/create-react-app/package.json
- packages/react-dev-utils/README.md
- packages/react-dev-utils/package.json
- packages/react-dev-utils/typescriptFormatter.js
- packages/react-error-overlay/package.json
Bump chalk to utilize it's new performance boosts and adapt to new api's, 
https://github.com/chalk/chalk/releases/tag/v3.0.0
> Bump chalk

- packages/babel-plugin-named-asset-import/index.test.js
- packages/babel-plugin-named-asset-import/package.json
Bump babel-plugin-tester and adapt to new api 
https://github.com/babel-utils/babel-plugin-tester/releases
> Bump babel-plugin-tester and fix breaking changes

- docusaurus/docs/supported-browsers-features.md
> Minor grammatical edit

- packages/cra-template/template/public/robots.txt
The default robots.txt is incorrect, so I set it valid.
> Add "Disallow:" to robots.txt

- packages/react-scripts/scripts/init.js
Why:
* As per best practice:
https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches#n135
See also:
https://chris.beams.io/posts/git-commit/#imperative
> Update commit message to use imperative mood

- packages/cra-template-typescript/template/public/robots.txt
> Fix robots.txt for TS

- packages/cra-template-typescript/template/src/App.test.tsx
- packages/cra-template/template/src/App.test.js
Closes #8699.
As requested by @kentcdodds in #8699, I've update the template tests.
I didn't update the dependencies, since that would require Node 10+.
> Update template tests

- README.md
> Add setupTests.js to the list of generated files

- docusaurus/docs/setting-up-your-editor.md
> Simplify wording in setting-up-your-editor.md

- packages/react-scripts/scripts/start.js
Fix #8685, introduced by https://github.com/facebook/create-react-app/pull/7203
Refer same issue with rollup https://github.com/rollup/rollup/pull/2410#issuecomment-413492131
> Skip stdin resuming to support lerna parallel

- packages/react-scripts/package.json
> Upgrade refresh plugin

- docusaurus/docs/adding-typescript.md
It wasn’t clear to me on first reading whether the npm/yarn installs below this paragraph were part of creating a new project or adding TypeScript to an existing one, I think this clarifies it!
> Clarify wording in adding TypeScript to existing project

- docusaurus/website/src/pages/index.js
> fix: add alt tag to improve accessibility of docusaurus website

- packages/react-error-overlay/package.json
- packages/react-scripts/package.json
Update to latest React version.
> Upgrade to React 17

- README.md
Add a link to our Open Collective in the README.
> Add link to Open Collective

- packages/cra-template-typescript/template/src/reportWebVitals.ts
I found a trailing space in `reportWebVitals.ts`, so I removed it
> Remove trailing space in reportWebVitals.ts

- packages/create-react-app/yarn.lock.cached
- tasks/e2e-simple.sh
> Fix CI tests

- packages/create-react-app/__tests__/getTemplateInstallPackage.test.js
> tests: update test case to match the description

- packages/cra-template/template/README.md
Including `%s/’/'/g` to avoid https://www.fileformat.info/info/unicode/char/2019/index.htm
> Trivial English fixes

- packages/eslint-config-react-app/README.md
This just fixes a shell snippet in the readme file for this plugin
> eslint-config-react-app typo fix

- packages/react-scripts/package.json
As far as I can tell, there should be no issues with this:
https://github.com/postcss/postcss/blob/main/CHANGELOG.md
See related advisory:
https://www.npmjs.com/advisories/1693
Closes #9664
> Update PostCSS version

- package-lock.json
- packages/react-scripts/package.json
This should fix the test suite issues for now
> Update webpack and dev server

- packages/react-scripts/config/webpackDevServer.config.js
> fix(webpackDevServer): disable overlay for warnings

- CHANGELOG-4.x.md
- CHANGELOG.md
- Copy release notes 5.0.0  into Changelog.md.
- Rename existing changelog to 4.x
resolves #11783
> docs: Changelog 5.0.0

- docusaurus/docs/deployment.md
> Fix a typo in deployment.md

- packages/react-dev-utils/openBrowser.js
> fix: Reuse opening tab in Chrome Dev and Chrome Beta

- docusaurus/docs/running-tests.md
> docs: update jest links

- docusaurus/docs/adding-a-router.md
Add a link to React Router docs specific to adding routes.
> docs: Add Link to Adding Routes Docs

- docusaurus/docs/deployment.md
updating the heroku buildpack link to its official as the previous buildpack is deprecated and will no longer support
> update the heroku buildpack link
